library module_chimesdkmediapipelines_media_insights_pipeline_configuration_real_time_alert_configuration_rule_sentiment_configuration;

export 'media_insights_pipeline_configuration_real_time_alert_configuration_rule_sentiment_configuration/media_insights_pipeline_configuration_real_time_alert_configuration_rule_sentiment_configuration.dart';
