library module_chimesdkmediapipelines_media_insights_pipeline_configuration_element_sns_topic_sink_configuration;

export 'media_insights_pipeline_configuration_element_sns_topic_sink_configuration/media_insights_pipeline_configuration_element_sns_topic_sink_configuration.dart';
