library module_iam_workforce_pool_provider_extra_attributes_oauth2_client_query_parameters;

export 'workforce_pool_provider_extra_attributes_oauth2_client_query_parameters/workforce_pool_provider_extra_attributes_oauth2_client_query_parameters.dart';
