library module_iam_workload_identity_pool_inline_trust_config_additional_trust_bundle_trust_anchor;

export 'workload_identity_pool_inline_trust_config_additional_trust_bundle_trust_anchor/workload_identity_pool_inline_trust_config_additional_trust_bundle_trust_anchor.dart';
