library module_ecs_capacity_provider_managed_instances_provider_instance_launch_template_instance_requirements_total_local_storage_gb;

export 'capacity_provider_managed_instances_provider_instance_launch_template_instance_requirements_total_local_storage_gb.dart';
