import 'package:pulumi/pulumi.dart' as pulumi;
import 'app_cookie_stickiness_policy_args.dart';
import 'app_cookie_stickiness_policy_state.dart';

/// Provides an application cookie stickiness policy, which allows an ELB to wed its sticky cookie's expiration to a cookie generated by your application.
///
/// ## Example Usage
///
///
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
///
/// const lb = new aws.elb.LoadBalancer("lb", {
///     name: "test-lb",
///     availabilityZones: ["us-east-1a"],
///     listeners: [{
///         instancePort: 8000,
///         instanceProtocol: "http",
///         lbPort: 80,
///         lbProtocol: "http",
///     }],
/// });
/// const foo = new aws.elb.AppCookieStickinessPolicy("foo", {
///     name: "foo_policy",
///     loadBalancer: lb.name,
///     lbPort: 80,
///     cookieName: "MyAppCookie",
/// });
/// ```
/// ```python
/// import pulumi
/// import pulumi_aws as aws
///
/// lb = aws.elb.LoadBalancer("lb",
///     name="test-lb",
///     availability_zones=["us-east-1a"],
///     listeners=[{
///         "instance_port": 8000,
///         "instance_protocol": "http",
///         "lb_port": 80,
///         "lb_protocol": "http",
///     }])
/// foo = aws.elb.AppCookieStickinessPolicy("foo",
///     name="foo_policy",
///     load_balancer=lb.name,
///     lb_port=80,
///     cookie_name="MyAppCookie")
/// ```
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var lb = new Aws.Elb.LoadBalancer("lb", new()
///     {
///         Name = "test-lb",
///         AvailabilityZones = new[]
///         {
///             "us-east-1a",
///         },
///         Listeners = new[]
///         {
///             new Aws.Elb.Inputs.LoadBalancerListenerArgs
///             {
///                 InstancePort = 8000,
///                 InstanceProtocol = "http",
///                 LbPort = 80,
///                 LbProtocol = "http",
///             },
///         },
///     });
///
///     var foo = new Aws.Elb.AppCookieStickinessPolicy("foo", new()
///     {
///         Name = "foo_policy",
///         LoadBalancer = lb.Name,
///         LbPort = 80,
///         CookieName = "MyAppCookie",
///     });
///
/// });
/// ```
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-aws/sdk/v7/go/aws/elb"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		lb, err := elb.NewLoadBalancer(ctx, "lb", &elb.LoadBalancerArgs{
/// 			Name: pulumi.String("test-lb"),
/// 			AvailabilityZones: pulumi.StringArray{
/// 				pulumi.String("us-east-1a"),
/// 			},
/// 			Listeners: elb.LoadBalancerListenerArray{
/// 				&elb.LoadBalancerListenerArgs{
/// 					InstancePort:     pulumi.Int(8000),
/// 					InstanceProtocol: pulumi.String("http"),
/// 					LbPort:           pulumi.Int(80),
/// 					LbProtocol:       pulumi.String("http"),
/// 				},
/// 			},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		_, err = elb.NewAppCookieStickinessPolicy(ctx, "foo", &elb.AppCookieStickinessPolicyArgs{
/// 			Name:         pulumi.String("foo_policy"),
/// 			LoadBalancer: lb.Name,
/// 			LbPort:       pulumi.Int(80),
/// 			CookieName:   pulumi.String("MyAppCookie"),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.aws.elb.LoadBalancer;
/// import com.pulumi.aws.elb.LoadBalancerArgs;
/// import com.pulumi.aws.elb.inputs.LoadBalancerListenerArgs;
/// import com.pulumi.aws.elb.AppCookieStickinessPolicy;
/// import com.pulumi.aws.elb.AppCookieStickinessPolicyArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var lb = new LoadBalancer("lb", LoadBalancerArgs.builder()
///             .name("test-lb")
///             .availabilityZones("us-east-1a")
///             .listeners(LoadBalancerListenerArgs.builder()
///                 .instancePort(8000)
///                 .instanceProtocol("http")
///                 .lbPort(80)
///                 .lbProtocol("http")
///                 .build())
///             .build());
///
///         var foo = new AppCookieStickinessPolicy("foo", AppCookieStickinessPolicyArgs.builder()
///             .name("foo_policy")
///             .loadBalancer(lb.name())
///             .lbPort(80)
///             .cookieName("MyAppCookie")
///             .build());
///
///     }
/// }
/// ```
/// ```yaml
/// resources:
///   lb:
///     type: aws:elb:LoadBalancer
///     properties:
///       name: test-lb
///       availabilityZones:
///         - us-east-1a
///       listeners:
///         - instancePort: 8000
///           instanceProtocol: http
///           lbPort: 80
///           lbProtocol: http
///   foo:
///     type: aws:elb:AppCookieStickinessPolicy
///     properties:
///       name: foo_policy
///       loadBalancer: ${lb.name}
///       lbPort: 80
///       cookieName: MyAppCookie
/// ```
///
///
/// ## Import
///
/// Using `pulumi import`, import application cookie stickiness policies using the ELB name, port, and policy name separated by colons (`:`). For example:
///
/// ```sh
/// $ pulumi import aws:elb/appCookieStickinessPolicy:AppCookieStickinessPolicy example my-elb:80:my-policy
/// ```
class AppCookieStickinessPolicy extends pulumi.CustomResource {
  /// Application cookie whose lifetime the ELB's cookie should follow.
  late final pulumi.Output<String> cookieName;
  /// Load balancer port to which the policy
  /// should be applied. This must be an active listener on the load
  /// balancer.
  late final pulumi.Output<int> lbPort;
  /// Name of load balancer to which the policy
  /// should be attached.
  late final pulumi.Output<String> loadBalancer;
  /// Name of the stickiness policy.
  late final pulumi.Output<String> name;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final pulumi.Output<String> region;

  /// Creates a new [AppCookieStickinessPolicy].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [AppCookieStickinessPolicy]. {@macro pulumi_elb_app_cookie_stickiness_policy_app_cookie_stickiness_policy_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  AppCookieStickinessPolicy(
    String name, {
    AppCookieStickinessPolicyArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:elb/appCookieStickinessPolicy:AppCookieStickinessPolicy',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.cookieName = registerOutput<String>('cookieName');
    this.lbPort = registerOutput<int>('lbPort');
    this.loadBalancer = registerOutput<String>('loadBalancer');
    this.name = registerOutput<String>('name');
    this.region = registerOutput<String>('region');
  }

  /// Gets an existing [AppCookieStickinessPolicy] resource's state with the given [name] and [id].
  static AppCookieStickinessPolicy get(
    String name,
    pulumi.Input<String> id, {
    AppCookieStickinessPolicyState? state,
  }) {
    return AppCookieStickinessPolicy._get(
      name,
      state: state?.toMap(),
      options: pulumi.CustomResourceOptions(id: id),
    );
  }

  AppCookieStickinessPolicy._get(
    String name, {
    Map<String, dynamic>? state,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:elb/appCookieStickinessPolicy:AppCookieStickinessPolicy',
          name,
          pulumi.Input.mapToInputs(state ?? const <String, dynamic>{}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.cookieName = registerOutput<String>('cookieName');
    this.lbPort = registerOutput<int>('lbPort');
    this.loadBalancer = registerOutput<String>('loadBalancer');
    this.name = registerOutput<String>('name');
    this.region = registerOutput<String>('region');
  }
}
