name: pulumi_docker
description: A Pulumi package for interacting with Docker in Pulumi programs
version: 4.11.0
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-docker
topics:
    - pulumi
    - docker
environment:
    sdk: ^3.10.0
dependencies:
    pulumi: ^1.0.0
