library module_sagemaker_domain_default_user_settings_jupyter_lab_app_settings_emr_settings;

export 'domain_default_user_settings_jupyter_lab_app_settings_emr_settings/domain_default_user_settings_jupyter_lab_app_settings_emr_settings.dart';
