library module_sagemaker_domain_default_user_settings_canvas_app_settings_model_register_settings;

export 'domain_default_user_settings_canvas_app_settings_model_register_settings/domain_default_user_settings_canvas_app_settings_model_register_settings.dart';
