library module_sagemaker_domain_default_user_settings_canvas_app_settings_direct_deploy_settings;

export 'domain_default_user_settings_canvas_app_settings_direct_deploy_settings/domain_default_user_settings_canvas_app_settings_direct_deploy_settings.dart';
