library module_sagemaker_domain_default_user_settings_canvas_app_settings_identity_provider_oauth_setting;

export 'domain_default_user_settings_canvas_app_settings_identity_provider_oauth_setting/domain_default_user_settings_canvas_app_settings_identity_provider_oauth_setting.dart';
