library module_sagemaker_domain_domain_settings_rstudio_server_pro_domain_settings_default_resource_spec;

export 'domain_domain_settings_rstudio_server_pro_domain_settings_default_resource_spec/domain_domain_settings_rstudio_server_pro_domain_settings_default_resource_spec.dart';
