library module_sagemaker_domain_default_space_settings_space_storage_settings_default_ebs_storage_settings;

export 'domain_default_space_settings_space_storage_settings_default_ebs_storage_settings/domain_default_space_settings_space_storage_settings_default_ebs_storage_settings.dart';
