library module_sagemaker_endpoint_configuration_shadow_production_variant_managed_instance_scaling;

export 'endpoint_configuration_shadow_production_variant_managed_instance_scaling/endpoint_configuration_shadow_production_variant_managed_instance_scaling.dart';
