library module_sagemaker_monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_network_config_vpc_config;

export 'monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_network_config_vpc_config/monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_network_config_vpc_config.dart';
