library module_sagemaker_monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_baseline_statistics_resource;

export 'monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_baseline_statistics_resource/monitoring_schedule_monitoring_schedule_config_monitoring_job_definition_baseline_statistics_resource.dart';
