library module_sagemaker_user_profile_user_settings_canvas_app_settings_identity_provider_oauth_setting;

export 'user_profile_user_settings_canvas_app_settings_identity_provider_oauth_setting/user_profile_user_settings_canvas_app_settings_identity_provider_oauth_setting.dart';
