library module_wafv2_rule_group_rule_statement_rate_based_statement_custom_key_query_argument_text_transformation;

export 'rule_group_rule_statement_rate_based_statement_custom_key_query_argument_text_transformation.dart';
