library module_kinesisanalyticsv2_application_application_configuration_flink_application_configuration_parallelism_configuration;

export 'application_application_configuration_flink_application_configuration_parallelism_configuration.dart';
