library module_macie2_classification_job_s3_job_definition_bucket_criteria_excludes_and_tag_criterion;

export 'classification_job_s3_job_definition_bucket_criteria_excludes_and_tag_criterion/classification_job_s3_job_definition_bucket_criteria_excludes_and_tag_criterion.dart';
