library module_macie2_organization_configuration;

export 'organization_configuration/organization_configuration_macie2.dart';
export 'organization_configuration/organization_configuration_macie2_args.dart';
