library module_macie2_organization_admin_account;

export 'organization_admin_account/organization_admin_account_macie2.dart';
export 'organization_admin_account/organization_admin_account_macie2_args.dart';
