library module_compute_autoscaler_autoscaling_policy_scale_down_control_max_scaled_down_replicas;

export 'autoscaler_autoscaling_policy_scale_down_control_max_scaled_down_replicas/autoscaler_autoscaling_policy_scale_down_control_max_scaled_down_replicas.dart';
