library module_compute_get_region_instance_group_manager_status_stateful_per_instance_config;

export 'get_region_instance_group_manager_status_stateful_per_instance_config/get_region_instance_group_manager_status_stateful_per_instance_config.dart';
