library module_compute_get_region_disk_iam_policy;

export 'get_region_disk_iam_policy/get_region_disk_iam_policy.dart';
export 'get_region_disk_iam_policy/get_region_disk_iam_policy_args.dart';
export 'get_region_disk_iam_policy/get_region_disk_iam_policy_result.dart';
