library module_compute_get_region_instance_group_manager_instance_lifecycle_policy;

export 'get_region_instance_group_manager_instance_lifecycle_policy/get_region_instance_group_manager_instance_lifecycle_policy.dart';
