library module_compute_get_region_instance_group_manager_instance_flexibility_policy_instance_selection_disk_resource_manager_tag;

export 'get_region_instance_group_manager_instance_flexibility_policy_instance_selection_disk_resource_manager_tag/get_region_instance_group_manager_instance_flexibility_policy_instance_selection_disk_resource_manager_tag.dart';
