library module_compute_get_snapshot_iam_policy;

export 'get_snapshot_iam_policy/get_snapshot_iam_policy.dart';
export 'get_snapshot_iam_policy/get_snapshot_iam_policy_args.dart';
export 'get_snapshot_iam_policy/get_snapshot_iam_policy_result.dart';
