library module_compute_get_region_backend_service_strong_session_affinity_cooky_ttl;

export 'get_region_backend_service_strong_session_affinity_cooky_ttl/get_region_backend_service_strong_session_affinity_cooky_ttl.dart';
