library module_compute_get_region_instance_template_scheduling_max_run_duration;

export 'get_region_instance_template_scheduling_max_run_duration/get_region_instance_template_scheduling_max_run_duration.dart';
