library module_compute_get_region_instance_group_manager_stateful_external_ip;

export 'get_region_instance_group_manager_stateful_external_ip/get_region_instance_group_manager_stateful_external_ip.dart';
