library module_compute_get_instance_iam_policy;

export 'get_instance_iam_policy/get_instance_iam_policy_compute.dart';
export 'get_instance_iam_policy/get_instance_iam_policy_compute_args.dart';
export 'get_instance_iam_policy/get_instance_iam_policy_compute_result.dart';
