library module_compute_get_instance_group_manager_status_all_instances_config;

export 'get_instance_group_manager_status_all_instances_config/get_instance_group_manager_status_all_instances_config.dart';
