library module_compute_get_region_instance_group_manager_auto_healing_policy;

export 'get_region_instance_group_manager_auto_healing_policy/get_region_instance_group_manager_auto_healing_policy.dart';
