library module_compute_get_region_instance_group_manager;

export 'get_region_instance_group_manager/get_region_instance_group_manager.dart';
export 'get_region_instance_group_manager/get_region_instance_group_manager_args.dart';
export 'get_region_instance_group_manager/get_region_instance_group_manager_result.dart';
