library module_compute_get_region_instance_group_manager_stateful_internal_ip;

export 'get_region_instance_group_manager_stateful_internal_ip/get_region_instance_group_manager_stateful_internal_ip.dart';
