library module_compute_instance_from_template_scheduling_graceful_shutdown_max_duration;

export 'instance_from_template_scheduling_graceful_shutdown_max_duration/instance_from_template_scheduling_graceful_shutdown_max_duration.dart';
