library module_compute_interconnect_attachment_group_logical_structure_region_metro;

export 'interconnect_attachment_group_logical_structure_region_metro/interconnect_attachment_group_logical_structure_region_metro.dart';
