library module_compute_region_disk_resource_policy_attachment;

export 'region_disk_resource_policy_attachment/region_disk_resource_policy_attachment.dart';
export 'region_disk_resource_policy_attachment/region_disk_resource_policy_attachment_args.dart';
