library module_compute_region_per_instance_config_preserved_state_external_ip;

export 'region_per_instance_config_preserved_state_external_ip/region_per_instance_config_preserved_state_external_ip.dart';
