library module_compute_region_instance_template_scheduling_on_instance_stop_action;

export 'region_instance_template_scheduling_on_instance_stop_action/region_instance_template_scheduling_on_instance_stop_action.dart';
