library module_compute_region_resize_request_status_error_error_error_detail;

export 'region_resize_request_status_error_error_error_detail/region_resize_request_status_error_error_error_detail.dart';
