library module_compute_region_backend_service_network_pass_through_lb_traffic_policy;

export 'region_backend_service_network_pass_through_lb_traffic_policy/region_backend_service_network_pass_through_lb_traffic_policy.dart';
