library module_compute_region_instance_group_manager_instance_lifecycle_policy;

export 'region_instance_group_manager_instance_lifecycle_policy/region_instance_group_manager_instance_lifecycle_policy.dart';
