library module_compute_region_instance_template_scheduling_graceful_shutdown_max_duration;

export 'region_instance_template_scheduling_graceful_shutdown_max_duration/region_instance_template_scheduling_graceful_shutdown_max_duration.dart';
