import 'package:pulumi/pulumi.dart' as pulumi;
import 'discovery_source_args.dart';
import 'off_azure_discovery_source_resource_properties_response.dart';
import 'system_data_response.dart';

/// A Discovery Source resource
///
/// Uses Azure REST API version 2025-01-31-preview. In version 2.x of the Azure Native provider, it used API version 2025-01-31-preview.
///
/// Other available API versions: 2025-05-01-preview, 2025-07-01-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native dependencymap [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
///
/// {{% examples %}}
/// ## Example Usage
/// {{% example %}}
/// ### DiscoverySources_CreateOrUpdate - generated by [MaximumSet] rule
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using AzureNative = Pulumi.AzureNative;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var discoverySource = new AzureNative.DependencyMap.DiscoverySource("discoverySource", new()
///     {
///         Location = "y",
///         MapName = "mapsTest1",
///         Properties = new AzureNative.DependencyMap.Inputs.OffAzureDiscoverySourceResourcePropertiesArgs
///         {
///             SourceId = "wzlrkzumplzjmixbqv",
///             SourceType = "OffAzure",
///         },
///         ResourceGroupName = "rgdependencyMap",
///         SourceName = "sourceTest1",
///         Tags = null,
///     });
///
/// });
///
///
/// ```
///
/// ```go
/// package main
///
/// import (
/// 	dependencymap "github.com/pulumi/pulumi-azure-native-sdk/dependencymap/v3"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := dependencymap.NewDiscoverySource(ctx, "discoverySource", &dependencymap.DiscoverySourceArgs{
/// 			Location: pulumi.String("y"),
/// 			MapName:  pulumi.String("mapsTest1"),
/// 			Properties: &dependencymap.OffAzureDiscoverySourceResourcePropertiesArgs{
/// 				SourceId:   pulumi.String("wzlrkzumplzjmixbqv"),
/// 				SourceType: pulumi.String("OffAzure"),
/// 			},
/// 			ResourceGroupName: pulumi.String("rgdependencyMap"),
/// 			SourceName:        pulumi.String("sourceTest1"),
/// 			Tags:              pulumi.StringMap{},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
///
/// ```
///
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.azurenative.dependencymap.DiscoverySource;
/// import com.pulumi.azurenative.dependencymap.DiscoverySourceArgs;
/// import com.pulumi.azurenative.dependencymap.inputs.OffAzureDiscoverySourceResourcePropertiesArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var discoverySource = new DiscoverySource("discoverySource", DiscoverySourceArgs.builder()
///             .location("y")
///             .mapName("mapsTest1")
///             .properties(OffAzureDiscoverySourceResourcePropertiesArgs.builder()
///                 .sourceId("wzlrkzumplzjmixbqv")
///                 .sourceType("OffAzure")
///                 .build())
///             .resourceGroupName("rgdependencyMap")
///             .sourceName("sourceTest1")
///             .tags(Map.ofEntries(
///             ))
///             .build());
///
///     }
/// }
///
/// ```
///
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as azure_native from "@pulumi/azure-native";
///
/// const discoverySource = new azure_native.dependencymap.DiscoverySource("discoverySource", {
///     location: "y",
///     mapName: "mapsTest1",
///     properties: {
///         sourceId: "wzlrkzumplzjmixbqv",
///         sourceType: "OffAzure",
///     },
///     resourceGroupName: "rgdependencyMap",
///     sourceName: "sourceTest1",
///     tags: {},
/// });
///
/// ```
///
/// ```python
/// import pulumi
/// import pulumi_azure_native as azure_native
///
/// discovery_source = azure_native.dependencymap.DiscoverySource("discoverySource",
///     location="y",
///     map_name="mapsTest1",
///     properties={
///         "source_id": "wzlrkzumplzjmixbqv",
///         "source_type": "OffAzure",
///     },
///     resource_group_name="rgdependencyMap",
///     source_name="sourceTest1",
///     tags={})
///
/// ```
///
/// ```yaml
/// resources:
///   discoverySource:
///     type: azure-native:dependencymap:DiscoverySource
///     properties:
///       location: y
///       mapName: mapsTest1
///       properties:
///         sourceId: wzlrkzumplzjmixbqv
///         sourceType: OffAzure
///       resourceGroupName: rgdependencyMap
///       sourceName: sourceTest1
///       tags: {}
///
/// ```
///
/// {{% /example %}}
/// {{% /examples %}}
///
/// ## Import
///
/// An existing resource can be imported using its type token, name, and identifier, e.g.
///
/// ```sh
/// $ pulumi import azure-native:dependencymap:DiscoverySource opthbwbxhckrctnfnpio /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DependencyMap/maps/{mapName}/discoverySources/{sourceName}
/// ```
class DiscoverySource extends pulumi.CustomResource {
  /// The Azure API version of the resource.
  late final pulumi.Output<String> azureApiVersion;
  /// The geo-location where the resource lives
  late final pulumi.Output<String> location;
  /// The name of the resource
  late final pulumi.Output<String> name;
  /// The resource-specific properties for this resource.
  late final pulumi.Output<OffAzureDiscoverySourceResourcePropertiesResponse> properties;
  /// Azure Resource Manager metadata containing createdBy and modifiedBy information.
  late final pulumi.Output<SystemDataResponse> systemData;
  /// Resource tags.
  late final pulumi.Output<Map<String, String>?> tags;
  /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
  late final pulumi.Output<String> type;

  /// Creates a new [DiscoverySource].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [DiscoverySource]. {@macro pulumi_dependencymap_discovery_source_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  DiscoverySource(
    String name, {
    DiscoverySourceArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'azure-native:dependencymap:DiscoverySource',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    azureApiVersion = registerOutput<String>('azureApiVersion');
    location = registerOutput<String>('location');
    this.name = registerOutput<String>('name');
    properties = registerOutput<OffAzureDiscoverySourceResourcePropertiesResponse>('properties', decoder: (raw) { final guardedValue = raw; if (guardedValue == null) return null; return OffAzureDiscoverySourceResourcePropertiesResponse.fromMap((guardedValue as Map).cast<String, dynamic>()); });
    systemData = registerOutput<SystemDataResponse>('systemData', decoder: (raw) { final guardedValue = raw; if (guardedValue == null) return null; return SystemDataResponse.fromMap((guardedValue as Map).cast<String, dynamic>()); });
    tags = registerOutput<Map<String, String>?>('tags');
    type = registerOutput<String>('type');
  }
}
