library module_vertex_ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources_autoscaling_metric_spec;

export 'ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources_autoscaling_metric_spec.dart';
