name: aws_dart_eks_minimal
description: Pulumi AWS EKS minimal example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: 3.0.0
  pulumi_aws: ^7.20.0
  pulumi_eks: 4.3.0

dev_dependencies:
  lints: ^6.1.0
