library module_wafregional_get_subscribed_rule_group;

export 'get_subscribed_rule_group/get_subscribed_rule_group2.dart';
export 'get_subscribed_rule_group/get_subscribed_rule_group_args2.dart';
export 'get_subscribed_rule_group/get_subscribed_rule_group_result2.dart';
