// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_emr_security_configuration_security_configuration_args_doc}
/// The set of arguments for SecurityConfiguration.
/// {@endtemplate}
/// {@macro pulumi_emr_security_configuration_security_configuration_args_doc}
class SecurityConfigurationArgs {
  /// A JSON formatted Security Configuration
  final pulumi.Input<String> configuration;
  /// The name of the EMR Security Configuration. By default generated by this provider.
  final pulumi.Input<String>? name;
  /// Creates a unique name beginning with the specified
  /// prefix. Conflicts with `name`.
  final pulumi.Input<String>? namePrefix;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;

  /// Creates a new [SecurityConfigurationArgs].
  /// [configuration] A JSON formatted Security Configuration
  /// [name] The name of the EMR Security Configuration. By default generated by this provider.
  /// [namePrefix] Creates a unique name beginning with the specified
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  SecurityConfigurationArgs({
    required pulumi.Output<String> configuration,
    pulumi.Output<String>? name,
    pulumi.Output<String>? namePrefix,
    pulumi.Output<String>? region,
  }) :
      configuration = pulumi.Input.asInput<String>(configuration),
      name = pulumi.Input.asOptionalInput<String>(name),
      namePrefix = pulumi.Input.asOptionalInput<String>(namePrefix),
      region = pulumi.Input.asOptionalInput<String>(region);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'configuration': configuration,
      'name': ?name,
      'namePrefix': ?namePrefix,
      'region': ?region,
    };
  }

  factory SecurityConfigurationArgs.fromMap(Map<String, dynamic> map) {
    return SecurityConfigurationArgs(
      configuration: pulumi.Output.create<String>(map['configuration'] as String),
      name: map['name'] == null ? null : pulumi.Output.create<String>(map['name'] as String),
      namePrefix: map['namePrefix'] == null ? null : pulumi.Output.create<String>(map['namePrefix'] as String),
      region: map['region'] == null ? null : pulumi.Output.create<String>(map['region'] as String),
    );
  }
}

