// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering SecurityConfiguration resources.
class SecurityConfigurationState {
  /// A JSON formatted Security Configuration
  final pulumi.Input<String>? configuration;

  /// Date the Security Configuration was created
  final pulumi.Input<String>? creationDate;

  /// The name of the EMR Security Configuration. By default generated by this provider.
  final pulumi.Input<String>? name;

  /// Creates a unique name beginning with the specified
  /// prefix. Conflicts with `name`.
  final pulumi.Input<String>? namePrefix;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;

  /// Creates a new [SecurityConfigurationState].
  /// [configuration] A JSON formatted Security Configuration
  /// [creationDate] Date the Security Configuration was created
  /// [name] The name of the EMR Security Configuration. By default generated by this provider.
  /// [namePrefix] Creates a unique name beginning with the specified
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  SecurityConfigurationState({
    this.configuration,
    this.creationDate,
    this.name,
    this.namePrefix,
    this.region,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'configuration': ?configuration,
      'creationDate': ?creationDate,
      'name': ?name,
      'namePrefix': ?namePrefix,
      'region': ?region,
    };
  }

  factory SecurityConfigurationState.fromMap(Map<String, dynamic> map) {
    return SecurityConfigurationState(
      configuration: (() {
        final guardedValue = map['configuration'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      creationDate: (() {
        final guardedValue = map['creationDate'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      name: (() {
        final guardedValue = map['name'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      namePrefix: (() {
        final guardedValue = map['namePrefix'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      region: (() {
        final guardedValue = map['region'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
    );
  }
}
