// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_dataplex_datascan_iam_policy_datascan_iam_policy_args_doc}
/// The set of arguments for DatascanIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_dataplex_datascan_iam_policy_datascan_iam_policy_args_doc}
class DatascanIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> dataScanId;
  /// The location where the data scan should reside.
  /// Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String?>? location;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String?>? project;

  /// Creates a new [DatascanIamPolicyArgs].
  /// [dataScanId] Used to find the parent resource to bind the IAM policy to
  /// [location] The location where the data scan should reside.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  const DatascanIamPolicyArgs({
    required this.dataScanId,
    this.location,
    required this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'dataScanId': dataScanId,
      'location': ?location,
      'policyData': policyData,
      'project': ?project,
    };
  }

  factory DatascanIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return DatascanIamPolicyArgs(
      dataScanId: pulumi.Input.fromValue(map['dataScanId'] as String),
      location: (() { final guardedValue = map['location']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      policyData: pulumi.Input.fromValue(map['policyData'] as String),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
