library module_appautoscaling_policy_target_tracking_scaling_policy_configuration_customized_metric_specification_metric_metric_stat;

export 'policy_target_tracking_scaling_policy_configuration_customized_metric_specification_metric_metric_stat/policy_target_tracking_scaling_policy_configuration_customized_metric_specification_metric_metric_stat.dart';
