library module_appautoscaling_policy_predictive_scaling_policy_configuration_metric_specification_predefined_metric_pair_specification;

export 'policy_predictive_scaling_policy_configuration_metric_specification_predefined_metric_pair_specification/policy_predictive_scaling_policy_configuration_metric_specification_predefined_metric_pair_specification.dart';
