library module_appautoscaling_policy_target_tracking_scaling_policy_configuration_customized_metric_specification_dimension;

export 'policy_target_tracking_scaling_policy_configuration_customized_metric_specification_dimension/policy_target_tracking_scaling_policy_configuration_customized_metric_specification_dimension.dart';
