library module_route53_records_exclusive_resource_record_set_geoproximity_location_coordinates;

export 'records_exclusive_resource_record_set_geoproximity_location_coordinates/records_exclusive_resource_record_set_geoproximity_location_coordinates.dart';
