library module_bedrock_agentcore_oauth2_credential_provider_oauth2_provider_config_microsoft_oauth2_provider_config_oauth_discovery;

export 'agentcore_oauth2_credential_provider_oauth2_provider_config_microsoft_oauth2_provider_config_oauth_discovery.dart';
