// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for AiFeatureStoreEntityTypeIamPolicy.
class AiFeatureStoreEntityTypeIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final Input<String> entitytype;

  /// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}. Used to find the parent resource to bind the IAM policy to
  final Input<String> featurestore;

  /// The policy data generated by
  /// a <span pulumi-lang-nodejs="`gcp.organizations.getIAMPolicy`" pulumi-lang-dotnet="`gcp.organizations.getIAMPolicy`" pulumi-lang-go="`organizations.getIAMPolicy`" pulumi-lang-python="`organizations_get_iam_policy`" pulumi-lang-yaml="`gcp.organizations.getIAMPolicy`" pulumi-lang-java="`gcp.organizations.getIAMPolicy`">`gcp.organizations.getIAMPolicy`</span> data source.
  final Input<String> policyData;

  AiFeatureStoreEntityTypeIamPolicyArgs({
    required this.entitytype,
    required this.featurestore,
    required this.policyData,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['entitytype'] = entitytype;
    map['featurestore'] = featurestore;
    map['policyData'] = policyData;
    return map;
  }

  factory AiFeatureStoreEntityTypeIamPolicyArgs.fromMap(
      Map<String, dynamic> map) {
    return AiFeatureStoreEntityTypeIamPolicyArgs(
      entitytype: Input.asInput<String>(map['entitytype']),
      featurestore: Input.asInput<String>(map['featurestore']),
      policyData: Input.asInput<String>(map['policyData']),
    );
  }
}
