// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// The set of arguments for AiFeatureStoreEntityTypeIamPolicy.
class AiFeatureStoreEntityTypeIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> entitytype;

  /// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}. Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> featurestore;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  AiFeatureStoreEntityTypeIamPolicyArgs({
    required this.entitytype,
    required this.featurestore,
    required this.policyData,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['entitytype'] = entitytype;
    map['featurestore'] = featurestore;
    map['policyData'] = policyData;
    return map;
  }

  factory AiFeatureStoreEntityTypeIamPolicyArgs.fromMap(
      Map<String, dynamic> map) {
    return AiFeatureStoreEntityTypeIamPolicyArgs(
      entitytype: pulumi.Input.asInput<String>(map['entitytype']),
      featurestore: pulumi.Input.asInput<String>(map['featurestore']),
      policyData: pulumi.Input.asInput<String>(map['policyData']),
    );
  }
}
