library module_binaryauthorization_get_attestor_iam_policy;

export 'get_attestor_iam_policy/get_attestor_iam_policy.dart';
export 'get_attestor_iam_policy/get_attestor_iam_policy_args.dart';
export 'get_attestor_iam_policy/get_attestor_iam_policy_result.dart';
