library module_guardduty_organization_admin_account;

export 'organization_admin_account/organization_admin_account_guardduty.dart';
export 'organization_admin_account/organization_admin_account_guardduty_args.dart';
