import 'package:pulumi/pulumi.dart';
import '../db_cluster_log_delivery_configuration/db_cluster_log_delivery_configuration.dart';
import '../db_cluster_timeouts/db_cluster_timeouts.dart';
import 'db_cluster_args.dart';

/// Resource for managing an Amazon Timestream for InfluxDB read-replica cluster.
///
/// > **NOTE:** This resource requires a subscription to [Timestream for InfluxDB Read Replicas (Add-On) on the AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-lftzfxtb5xlv4?applicationId=AWS-Marketplace-Console&ref_=beagle&sr=0-2).
///
/// ## Example Usage
///
/// ### Basic Usage
///
///
///
/// ### Usage with Prerequisite Resources
///
/// All Timestream for InfluxDB clusters require a VPC, at least two subnets, and a security group. The following example shows how these prerequisite resources can be created and used with `aws.timestreaminfluxdb.DbCluster`.
///
///
///
/// ### Usage with S3 Log Delivery Enabled
///
/// You can use an S3 bucket to store logs generated by your Timestream for InfluxDB cluster. The following example shows what resources and arguments are required to configure an S3 bucket for logging, including the IAM policy that needs to be set in order to allow Timestream for InfluxDB to place logs in your S3 bucket. The configuration of the required VPC, security group, and subnets have been left out of the example for brevity.
///
///
///
/// ### Usage with InfluxDB V3
///
/// For InfluxDB V3 clusters, you can create a cluster without providing `allocated_storage`, `bucket`, `organization`, `username`, `password`, or `deployment_type` by specifying a `db_parameter_group_identifier` such as `"InfluxDBV3Core"`. The following example shows how to create an InfluxDB V3 cluster:
///
///
///
/// ## Cluster Type Requirements
///
/// ### InfluxDB V2 Clusters (default)
///
/// The following arguments are **required** for InfluxDB V2 clusters:
///
/// * `allocated_storage`
/// * `bucket`
/// * `deployment_type`
/// * `organization`
/// * `password`
/// * `username`
///
/// The `deployment_type` argument defaults to `"MULTI_NODE_READ_REPLICAS"` for InfluxDB V2 clusters when not specified.
///
/// ### InfluxDB V3 Clusters (when using V3 parameter groups)
///
/// The following arguments are **forbidden** for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group):
///
/// * `allocated_storage`
/// * `bucket`
/// * `deployment_type`
/// * `organization`
/// * `password`
/// * `username`
///
/// ## Import
///
/// Using `pulumi import`, import Timestream for InfluxDB cluster using its identifier. For example:
///
/// ```sh
/// $ pulumi import aws:timestreaminfluxdb/dbCluster:DbCluster example 12345abcde
/// ```
class DbCluster extends CustomResource {
  /// Amount of storage in GiB (gibibytes). The minimum value is `20`, the maximum value is `16384`. The argument `db_storage_type` places restrictions on this argument's minimum value. The following is a list of `db_storage_type` values and the corresponding minimum value for `allocated_storage`: `"InfluxIOIncludedT1": `20`, `"InfluxIOIncludedT2" and `"InfluxIOIncludedT3": `400`. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group).
  late final Output<int?> allocatedStorage;

  /// ARN of the Timestream for InfluxDB cluster.
  late final Output<String> arn;

  /// Name of the initial InfluxDB bucket. All InfluxDB data is stored in a bucket. A bucket combines the concept of a database and a retention period (the duration of time that each data point persists). A bucket belongs to an organization. Along with `organization`, `username`, and `password`, this argument will be stored in the secret referred to by the `influx_auth_parameters_secret_arn` attribute. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group).
  late final Output<String?> bucket;

  /// Timestream for InfluxDB DB instance type to run InfluxDB on. Valid options are: `"db.influx.medium"`, `"db.influx.large"`, `"db.influx.xlarge"`, `"db.influx.2xlarge"`, `"db.influx.4xlarge"`, `"db.influx.8xlarge"`, `"db.influx.12xlarge"`, and `"db.influx.16xlarge"`. This argument is updatable.
  late final Output<String> dbInstanceType;

  /// ID of the DB parameter group assigned to your cluster. This argument is updatable. If added to an existing Timestream for InfluxDB cluster or given a new value, will cause an in-place update to the cluster. However, if a cluster already has a value for `db_parameter_group_identifier`, removing `db_parameter_group_identifier` will cause the cluster to be destroyed and recreated.
  late final Output<String?> dbParameterGroupIdentifier;

  /// Timestream for InfluxDB DB storage type to read and write InfluxDB data. You can choose between 3 different types of provisioned Influx IOPS included storage according to your workloads requirements: Influx IO Included 3000 IOPS, Influx IO Included 12000 IOPS, Influx IO Included 16000 IOPS. Valid options are: `"InfluxIOIncludedT1"`, `"InfluxIOIncludedT2"`, and `"InfluxIOIncludedT3"`. If you use `"InfluxIOIncludedT2" or "InfluxIOIncludedT3", the minimum value for `allocated_storage` is 400.
  late final Output<String> dbStorageType;

  /// Specifies the type of cluster to create. Valid options are: `"MULTI_NODE_READ_REPLICAS"`. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group).
  late final Output<String> deploymentType;

  /// Endpoint used to connect to InfluxDB. The default InfluxDB port is 8086.
  late final Output<String> endpoint;

  /// Database engine type of the DB cluster.
  late final Output<String> engineType;

  /// Specifies the behavior of failure recovery when the primary node of the cluster fails. Valid options are: `"AUTOMATIC"` and `"NO_FAILOVER"`.
  late final Output<String> failoverMode;

  /// ARN of the AWS Secrets Manager secret containing the initial InfluxDB authorization parameters. For InfluxDB V2 clusters, the secret value is a JSON formatted key-value pair holding InfluxDB authorization values: organization, bucket, username, and password. For InfluxDB V3 clusters, the secret contains the InfluxDB admin token.
  late final Output<String> influxAuthParametersSecretArn;

  /// Configuration for sending InfluxDB engine logs to a specified S3 bucket. This argument is updatable.
  late final Output<DbClusterLogDeliveryConfiguration?>
      logDeliveryConfiguration;

  /// Name that uniquely identifies the DB cluster when interacting with the Amazon Timestream for InfluxDB API and CLI commands. This name will also be a prefix included in the endpoint. Cluster names must be unique per customer and per region. The argument must start with a letter, cannot contain consecutive hyphens (`-`) and cannot end with a hyphen.
  late final Output<String> name;

  /// Specifies whether the network type of the Timestream for InfluxDB cluster is IPV4, which can communicate over IPv4 protocol only, or DUAL, which can communicate over both IPv4 and IPv6 protocols.
  late final Output<String> networkType;

  /// Name of the initial organization for the initial admin user in InfluxDB. An InfluxDB organization is a workspace for a group of users. Along with `bucket`, `username`, and `password`, this argument will be stored in the secret referred to by the `influx_auth_parameters_secret_arn` attribute. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group).
  late final Output<String?> organization;

  /// Password of the initial admin user created in InfluxDB. This password will allow you to access the InfluxDB UI to perform various administrative tasks and also use the InfluxDB CLI to create an operator token. Along with `bucket`, `username`, and `organization`, this argument will be stored in the secret referred to by the `influx_auth_parameters_secret_arn` attribute. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group) as the AWS API rejects it.
  late final Output<String?> password;

  /// The port on which the cluster accepts connections. Valid values: `1024`-`65535`. Cannot be `2375`-`2376`, `7788`-`7799`, `8090`, or `51678`-`51680`. This argument is updatable.
  late final Output<int> port;

  /// Configures the DB cluster with a public IP to facilitate access. Other resources, such as a VPC, a subnet, an internet gateway, and a route table with routes, are also required to enabled public access, in addition to this argument. See "Usage with Public Internet Access Enabled" for an example configuration with all required resources for public internet access.
  late final Output<bool> publiclyAccessible;

  /// The endpoint used to connect to the Timestream for InfluxDB cluster for read-only operations.
  late final Output<String> readerEndpoint;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final Output<String> region;

  /// Map of tags assigned to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  late final Output<Map<String, String>?> tags;

  /// Map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  late final Output<Map<String, String>> tagsAll;
  late final Output<DbClusterTimeouts?> timeouts;

  /// Username of the initial admin user created in InfluxDB. Must start with a letter and can't end with a hyphen or contain two consecutive hyphens. This username will allow you to access the InfluxDB UI to perform various administrative tasks and also use the InfluxDB CLI to create an operator token. Along with `bucket`, `organization`, and `password`, this argument will be stored in the secret referred to by the `influx_auth_parameters_secret_arn` attribute. This field is forbidden for InfluxDB V3 clusters (when using an InfluxDB V3 db parameter group).
  late final Output<String?> username;

  /// List of VPC security group IDs to associate with the cluster.
  late final Output<List<String>> vpcSecurityGroupIds;

  /// List of VPC subnet IDs to associate with the cluster. Provide at least two VPC subnet IDs in different availability zones when deploying with a Multi-AZ standby.
  ///
  /// The following arguments are optional:
  late final Output<List<String>> vpcSubnetIds;

  DbCluster(
    String name, {
    DbClusterArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'aws:timestreaminfluxdb/dbCluster:DbCluster',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.allocatedStorage = registerOutput<int?>('allocatedStorage');
    this.arn = registerOutput<String>('arn');
    this.bucket = registerOutput<String?>('bucket');
    this.dbInstanceType = registerOutput<String>('dbInstanceType');
    this.dbParameterGroupIdentifier =
        registerOutput<String?>('dbParameterGroupIdentifier');
    this.dbStorageType = registerOutput<String>('dbStorageType');
    this.deploymentType = registerOutput<String>('deploymentType');
    this.endpoint = registerOutput<String>('endpoint');
    this.engineType = registerOutput<String>('engineType');
    this.failoverMode = registerOutput<String>('failoverMode');
    this.influxAuthParametersSecretArn =
        registerOutput<String>('influxAuthParametersSecretArn');
    this.logDeliveryConfiguration =
        registerOutput<DbClusterLogDeliveryConfiguration?>(
            'logDeliveryConfiguration');
    this.name = registerOutput<String>('name');
    this.networkType = registerOutput<String>('networkType');
    this.organization = registerOutput<String?>('organization');
    this.password = registerOutput<String?>('password');
    this.port = registerOutput<int>('port');
    this.publiclyAccessible = registerOutput<bool>('publiclyAccessible');
    this.readerEndpoint = registerOutput<String>('readerEndpoint');
    this.region = registerOutput<String>('region');
    this.tags = registerOutput<Map<String, String>?>('tags');
    this.tagsAll = registerOutput<Map<String, String>>('tagsAll');
    this.timeouts = registerOutput<DbClusterTimeouts?>('timeouts');
    this.username = registerOutput<String?>('username');
    this.vpcSecurityGroupIds =
        registerOutput<List<String>>('vpcSecurityGroupIds');
    this.vpcSubnetIds = registerOutput<List<String>>('vpcSubnetIds');
  }
}
