library module_networkfirewall_firewall_transit_gateway_attachment_accepter;

export 'firewall_transit_gateway_attachment_accepter/firewall_transit_gateway_attachment_accepter.dart';
export 'firewall_transit_gateway_attachment_accepter/firewall_transit_gateway_attachment_accepter_args.dart';
