library module_vertex_ai_endpoint_with_model_garden_deployment_model_config_container_spec_liveness_probe_grpc;

export 'ai_endpoint_with_model_garden_deployment_model_config_container_spec_liveness_probe_grpc.dart';
