library module_accessapproval_get_organization_service_account;

export 'get_organization_service_account.dart';
export 'get_organization_service_account_args.dart';
export 'get_organization_service_account_result.dart';
