// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'google_cloud_aiplatform_v1beta1_feature_stats_anomaly.dart';
import 'google_cloud_aiplatform_v1beta1_threshold_config.dart';

/// Historical Stats (and Anomalies) for a specific Feature.
class GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomalies {
  /// Display Name of the Feature.
  final pulumi.Input<String>? featureDisplayName;
  /// A list of historical stats generated by different time window's Prediction Dataset.
  final pulumi.Input<List<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly>>? predictionStats;
  /// Threshold for anomaly detection.
  final pulumi.Input<GoogleCloudAiplatformV1beta1ThresholdConfig>? threshold;
  /// Stats calculated for the Training Dataset.
  final pulumi.Input<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly>? trainingStats;

  /// Creates a new [GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomalies].
  /// [featureDisplayName] Display Name of the Feature.
  /// [predictionStats] A list of historical stats generated by different time window's Prediction Dataset.
  /// [threshold] Threshold for anomaly detection.
  /// [trainingStats] Stats calculated for the Training Dataset.
  const GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomalies({
    this.featureDisplayName,
    this.predictionStats,
    this.threshold,
    this.trainingStats,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'featureDisplayName': ?featureDisplayName,
      'predictionStats': ?pulumi.Input.mapOptionalInputValue<List<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly>, List<Map<String, dynamic>>>(predictionStats, (value) => pulumi.Input.encodeList<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly, Map<String, dynamic>>(value, (value) => value.toMap())),
      'threshold': ?pulumi.Input.mapOptionalInputValue<GoogleCloudAiplatformV1beta1ThresholdConfig, Map<String, dynamic>>(threshold, (value) => value.toMap()),
      'trainingStats': ?pulumi.Input.mapOptionalInputValue<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly, Map<String, dynamic>>(trainingStats, (value) => value.toMap()),
    };
  }

  factory GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomalies.fromMap(Map<String, dynamic> map) {
    return GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomalies(
      featureDisplayName: (() { final guardedValue = map['featureDisplayName']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      predictionStats: (() { final guardedValue = map['predictionStats']; if (guardedValue == null) return null; return pulumi.Input.fromValue(pulumi.Input.decodeList<GoogleCloudAiplatformV1beta1FeatureStatsAnomaly>(guardedValue, (value) => GoogleCloudAiplatformV1beta1FeatureStatsAnomaly.fromMap((value as Map).cast<String, dynamic>()))); })(),
      threshold: (() { final guardedValue = map['threshold']; if (guardedValue == null) return null; return pulumi.Input.fromValue(GoogleCloudAiplatformV1beta1ThresholdConfig.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      trainingStats: (() { final guardedValue = map['trainingStats']; if (guardedValue == null) return null; return pulumi.Input.fromValue(GoogleCloudAiplatformV1beta1FeatureStatsAnomaly.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
    );
  }
}

