// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'metadata_schema_schema_type.dart';

/// {@template pulumi_aiplatform_v1_metadata_schema_args_doc}
/// The set of arguments for MetadataSchema.
/// {@endtemplate}
/// {@macro pulumi_aiplatform_v1_metadata_schema_args_doc}
class MetadataSchemaArgs {
  /// Description of the Metadata Schema
  final pulumi.Input<String>? description;
  final pulumi.Input<String>? location;
  /// The {metadata_schema} portion of the resource name with the format: `projects/{project}/locations/{location}/metadataStores/{metadatastore}/metadataSchemas/{metadataschema}` If not provided, the MetadataStore's ID will be a UUID generated by the service. Must be 4-128 characters in length. Valid characters are `/a-z-/`. Must be unique across all MetadataSchemas in the parent Location. (Otherwise the request will fail with ALREADY_EXISTS, or PERMISSION_DENIED if the caller can't view the preexisting MetadataSchema.)
  final pulumi.Input<String>? metadataSchemaId;
  final pulumi.Input<String> metadataStoreId;
  final pulumi.Input<String>? project;
  /// The raw YAML string representation of the MetadataSchema. The combination of [MetadataSchema.version] and the schema name given by `title` in [MetadataSchema.schema] must be unique within a MetadataStore. The schema is defined as an OpenAPI 3.0.2 [MetadataSchema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject)
  final pulumi.Input<String> schema;
  /// The type of the MetadataSchema. This is a property that identifies which metadata types will use the MetadataSchema.
  final pulumi.Input<MetadataSchemaSchemaType>? schemaType;
  /// The version of the MetadataSchema. The version's format must match the following regular expression: `^[0-9]+.+.+$`, which would allow to order/compare different versions. Example: 1.0.0, 1.0.1, etc.
  final pulumi.Input<String>? schemaVersion;

  /// Creates a new [MetadataSchemaArgs].
  /// [description] Description of the Metadata Schema
  /// [location] Optional.
  /// [metadataSchemaId] The {metadata_schema} portion of the resource name with the format: `projects/{project}/locations/{location}/metadataStores/{metadatastore}/metadataSchemas/{metadataschema}` If not provided, the MetadataStore's ID will be a UUID generated by the service. Must be 4-128 characters in length. Valid characters are `/a-z-/`. Must be unique across all MetadataSchemas in the parent Location. (Otherwise the request will fail with ALREADY_EXISTS, or PERMISSION_DENIED if the caller can't view the preexisting MetadataSchema.)
  /// [metadataStoreId] Required.
  /// [project] Optional.
  /// [schema] The raw YAML string representation of the MetadataSchema. The combination of [MetadataSchema.version] and the schema name given by `title` in [MetadataSchema.schema] must be unique within a MetadataStore. The schema is defined as an OpenAPI 3.0.2 [MetadataSchema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject)
  /// [schemaType] The type of the MetadataSchema. This is a property that identifies which metadata types will use the MetadataSchema.
  /// [schemaVersion] The version of the MetadataSchema. The version's format must match the following regular expression: `^[0-9]+.+.+$`, which would allow to order/compare different versions. Example: 1.0.0, 1.0.1, etc.
  MetadataSchemaArgs({
    pulumi.Output<String>? description,
    pulumi.Output<String>? location,
    pulumi.Output<String>? metadataSchemaId,
    required pulumi.Output<String> metadataStoreId,
    pulumi.Output<String>? project,
    required pulumi.Output<String> schema,
    pulumi.Output<MetadataSchemaSchemaType>? schemaType,
    pulumi.Output<String>? schemaVersion,
  }) :
      description = pulumi.Input.asOptionalInput<String>(description),
      location = pulumi.Input.asOptionalInput<String>(location),
      metadataSchemaId = pulumi.Input.asOptionalInput<String>(metadataSchemaId),
      metadataStoreId = pulumi.Input.asInput<String>(metadataStoreId),
      project = pulumi.Input.asOptionalInput<String>(project),
      schema = pulumi.Input.asInput<String>(schema),
      schemaType = pulumi.Input.asOptionalInput<MetadataSchemaSchemaType>(schemaType),
      schemaVersion = pulumi.Input.asOptionalInput<String>(schemaVersion);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'description': ?description,
      'location': ?location,
      'metadataSchemaId': ?metadataSchemaId,
      'metadataStoreId': metadataStoreId,
      'project': ?project,
      'schema': schema,
      'schemaType': ?pulumi.Input.mapOptionalInputValue<MetadataSchemaSchemaType, String>(schemaType, (value) => value.value),
      'schemaVersion': ?schemaVersion,
    };
  }

  factory MetadataSchemaArgs.fromMap(Map<String, dynamic> map) {
    return MetadataSchemaArgs(
      description: map['description'] == null ? null : pulumi.Output.create<String>(map['description'] as String),
      location: map['location'] == null ? null : pulumi.Output.create<String>(map['location'] as String),
      metadataSchemaId: map['metadataSchemaId'] == null ? null : pulumi.Output.create<String>(map['metadataSchemaId'] as String),
      metadataStoreId: pulumi.Output.create<String>(map['metadataStoreId'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
      schema: pulumi.Output.create<String>(map['schema'] as String),
      schemaType: map['schemaType'] == null ? null : pulumi.Output.create<MetadataSchemaSchemaType>(MetadataSchemaSchemaType.fromValue(map['schemaType'] as String)),
      schemaVersion: map['schemaVersion'] == null ? null : pulumi.Output.create<String>(map['schemaVersion'] as String),
    );
  }
}

