library module_appflow_connector_profile_connector_profile_config_connector_profile_credentials_sapo_data_basic_auth_credentials;

export 'connector_profile_connector_profile_config_connector_profile_credentials_sapo_data_basic_auth_credentials.dart';
