import 'package:pulumi/pulumi.dart' as pulumi;
import 'ledger_args.dart';
import 'ledger_state.dart';

/// Provides an AWS Quantum Ledger Database (QLDB) resource
///
/// &gt; **NOTE:** Deletion protection is enabled by default. To successfully delete this resource via this provider, `deletion_protection = false` must be applied before attempting deletion.
///
/// ## Example Usage
///
///
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as aws from "@pulumi/aws";
///
/// const sample_ledger = new aws.qldb.Ledger("sample-ledger", {
///     name: "sample-ledger",
///     permissionsMode: "STANDARD",
/// });
/// ```
/// ```python
/// import pulumi
/// import pulumi_aws as aws
///
/// sample_ledger = aws.qldb.Ledger("sample-ledger",
///     name="sample-ledger",
///     permissions_mode="STANDARD")
/// ```
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using Aws = Pulumi.Aws;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var sample_ledger = new Aws.Qldb.Ledger("sample-ledger", new()
///     {
///         Name = "sample-ledger",
///         PermissionsMode = "STANDARD",
///     });
///
/// });
/// ```
/// ```go
/// package main
///
/// import (
/// 	"github.com/pulumi/pulumi-aws/sdk/v7/go/aws/qldb"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := qldb.NewLedger(ctx, "sample-ledger", &qldb.LedgerArgs{
/// 			Name:            pulumi.String("sample-ledger"),
/// 			PermissionsMode: pulumi.String("STANDARD"),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
/// ```
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.aws.qldb.Ledger;
/// import com.pulumi.aws.qldb.LedgerArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var sample_ledger = new Ledger("sample-ledger", LedgerArgs.builder()
///             .name("sample-ledger")
///             .permissionsMode("STANDARD")
///             .build());
///
///     }
/// }
/// ```
/// ```yaml
/// resources:
///   sample-ledger:
///     type: aws:qldb:Ledger
///     properties:
///       name: sample-ledger
///       permissionsMode: STANDARD
/// ```
///
///
/// ## Import
///
/// Using `pulumi import`, import QLDB Ledgers using the `name`. For example:
///
/// ```sh
/// $ pulumi import aws:qldb/ledger:Ledger sample-ledger sample-ledger
/// ```
class Ledger extends pulumi.CustomResource {
  /// The ARN of the QLDB Ledger
  late final pulumi.Output<String> arn;
  /// The deletion protection for the QLDB Ledger instance. By default it is `true`. To delete this resource via the provider, this value must be configured to `false` and applied first before attempting deletion.
  late final pulumi.Output<bool?> deletionProtection;
  /// The key in AWS Key Management Service (AWS KMS) to use for encryption of data at rest in the ledger. For more information, see the [AWS documentation](https://docs.aws.amazon.com/qldb/latest/developerguide/encryption-at-rest.html). Valid values are `"AWS_OWNED_KMS_KEY"` to use an AWS KMS key that is owned and managed by AWS on your behalf, or the ARN of a valid symmetric customer managed KMS key.
  late final pulumi.Output<String> kmsKey;
  /// The friendly name for the QLDB Ledger instance. By default generated by the provider.
  late final pulumi.Output<String> name;
  /// The permissions mode for the QLDB ledger instance. Specify either `ALLOW_ALL` or `STANDARD`.
  late final pulumi.Output<String> permissionsMode;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final pulumi.Output<String> region;
  /// Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  late final pulumi.Output<Map<String, String>?> tags;
  /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  late final pulumi.Output<Map<String, String>> tagsAll;

  /// Creates a new [Ledger].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [Ledger]. {@macro pulumi_qldb_ledger_ledger_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  Ledger(
    String name, {
    LedgerArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:qldb/ledger:Ledger',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    arn = registerOutput<String>('arn');
    deletionProtection = registerOutput<bool?>('deletionProtection');
    kmsKey = registerOutput<String>('kmsKey');
    this.name = registerOutput<String>('name');
    permissionsMode = registerOutput<String>('permissionsMode');
    region = registerOutput<String>('region');
    tags = registerOutput<Map<String, String>?>('tags');
    tagsAll = registerOutput<Map<String, String>>('tagsAll');
  }

  /// Gets an existing [Ledger] resource's state with the given [name] and [id].
  static Ledger get(
    String name,
    pulumi.Input<String> id, {
    LedgerState? state,
  }) {
    return Ledger._get(
      name,
      state: state?.toMap(),
      options: pulumi.CustomResourceOptions(id: id),
    );
  }

  Ledger._get(
    String name, {
    Map<String, dynamic>? state,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:qldb/ledger:Ledger',
          name,
          pulumi.Input.mapToInputs(state ?? const <String, dynamic>{}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    arn = registerOutput<String>('arn');
    deletionProtection = registerOutput<bool?>('deletionProtection');
    kmsKey = registerOutput<String>('kmsKey');
    this.name = registerOutput<String>('name');
    permissionsMode = registerOutput<String>('permissionsMode');
    region = registerOutput<String>('region');
    tags = registerOutput<Map<String, String>?>('tags');
    tagsAll = registerOutput<Map<String, String>>('tagsAll');
  }
}
