// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_vertex_ai_feature_store_iam_policy_ai_feature_store_iam_policy_args_doc}
/// The set of arguments for AiFeatureStoreIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_vertex_ai_feature_store_iam_policy_ai_feature_store_iam_policy_args_doc}
class AiFeatureStoreIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> featurestore;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;
  /// The region of the dataset. eg us-central1 Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no region is provided in the parent identifier and no
  /// region is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? region;

  /// Creates a new [AiFeatureStoreIamPolicyArgs].
  /// [featurestore] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [region] The region of the dataset. eg us-central1 Used to find the parent resource to bind the IAM policy to. If not specified,
  AiFeatureStoreIamPolicyArgs({
    required String featurestore,
    required String policyData,
    String? project,
    String? region,
  }) :
      featurestore = pulumi.Input.asInput<String>(featurestore),
      policyData = pulumi.Input.asInput<String>(policyData),
      project = pulumi.Input.asOptionalInput<String>(project),
      region = pulumi.Input.asOptionalInput<String>(region);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'featurestore': featurestore,
      'policyData': policyData,
      'project': ?project,
      'region': ?region,
    };
  }

  factory AiFeatureStoreIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return AiFeatureStoreIamPolicyArgs(
      featurestore: map['featurestore'] as String,
      policyData: map['policyData'] as String,
      project: map['project'] == null ? null : map['project'] as String,
      region: map['region'] == null ? null : map['region'] as String,
    );
  }
}

