library module_medialive_channel_encoder_settings_video_description_codec_settings_h265_settings_color_space_settings_hdr10_settings;

export 'channel_encoder_settings_video_description_codec_settings_h265_settings_color_space_settings_hdr10_settings/channel_encoder_settings_video_description_codec_settings_h265_settings_color_space_settings_hdr10_settings.dart';
