library module_lex_v2models_slot_value_elicitation_setting_prompt_specification_message_group_variation_plain_text_message;

export 'v2models_slot_value_elicitation_setting_prompt_specification_message_group_variation_plain_text_message.dart';
