name: pulumi_postgresql
description: A Pulumi package for creating and managing postgresql cloud resources.
version: 3.18.0
license: Apache-2.0
homepage: https://www.pulumi.com
repository: https://github.com/pulumi/pulumi-postgresql
topics:
    - pulumi
    - postgresql
environment:
    sdk: '>=3.11.0 <4.0.0'
resolution: workspace
dependencies:
    pulumi: 3.0.0
dev_dependencies:
    lints: ^6.1.0
