// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'check_config_selected_check.dart';

/// Input properties used for looking up and filtering CheckConfig resources.
class CheckConfigState {
  /// The configuration of the check item. Valid value:
  final pulumi.Input<String>? configure;
  /// Cycle detection time.
  final pulumi.Input<List<int>>? cycleDays;
  /// Whether to check by default when there are new check items in the selected regulation. Values available:
  /// - **true:** On
  /// - **false:** off
  final pulumi.Input<bool>? enableAddCheck;
  /// Whether automatic cycle detection is enabled. Values available:
  /// - **true:** On
  /// - **false:** off
  final pulumi.Input<bool>? enableAutoCheck;
  /// Check the end time of the time period, which indicates the time of day. The start time and end time of the query can only be selected in the following time range.
  /// - **0~6** When the start time is 0, the end time must be set to 6 o'clock on the current day.
  /// - **6~12** When the start time is 6, the end time needs to be set to 12:00 on the current day.
  /// - **12~18** When the start time is 12, the end time needs to be set to 18 o'clock on the current day.
  /// - **18~24** When the start time is 18, the end time needs to be set to 24 hours of the current day.
  final pulumi.Input<int>? endTime;
  /// The check items selected in the policy. See `selected_checks` below.
  final pulumi.Input<List<CheckConfigSelectedCheck>>? selectedChecks;
  /// The start time of the check. The value specifies a point in time in a day.
  final pulumi.Input<int>? startTime;
  /// Specifies whether to use the configuration automatically generated by the system. Valid values:
  final pulumi.Input<bool>? systemConfig;
  final pulumi.Input<List<String>>? vendors;

  /// Creates a new [CheckConfigState].
  /// [configure] The configuration of the check item. Valid value:
  /// [cycleDays] Cycle detection time.
  /// [enableAddCheck] Whether to check by default when there are new check items in the selected regulation. Values available:
  /// [enableAutoCheck] Whether automatic cycle detection is enabled. Values available:
  /// [endTime] Check the end time of the time period, which indicates the time of day. The start time and end time of the query can only be selected in the following time range.
  /// [selectedChecks] The check items selected in the policy. See `selected_checks` below.
  /// [startTime] The start time of the check. The value specifies a point in time in a day.
  /// [systemConfig] Specifies whether to use the configuration automatically generated by the system. Valid values:
  /// [vendors] Optional.
  CheckConfigState({
    this.configure,
    this.cycleDays,
    this.enableAddCheck,
    this.enableAutoCheck,
    this.endTime,
    this.selectedChecks,
    this.startTime,
    this.systemConfig,
    this.vendors,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'configure': ?configure,
      'cycleDays': ?cycleDays,
      'enableAddCheck': ?enableAddCheck,
      'enableAutoCheck': ?enableAutoCheck,
      'endTime': ?endTime,
      'selectedChecks': ?pulumi.Input.mapOptionalInputValue<List<CheckConfigSelectedCheck>, List<Map<String, dynamic>>>(selectedChecks, (value) => pulumi.Input.encodeList<CheckConfigSelectedCheck, Map<String, dynamic>>(value, (value) => value.toMap())),
      'startTime': ?startTime,
      'systemConfig': ?systemConfig,
      'vendors': ?vendors,
    };
  }

  factory CheckConfigState.fromMap(Map<String, dynamic> map) {
    return CheckConfigState(
      configure: (() { final guardedValue = map['configure']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      cycleDays: (() { final guardedValue = map['cycleDays']; if (guardedValue == null) return null; return pulumi.Input.fromValue((guardedValue as List).cast<int>()); })(),
      enableAddCheck: (() { final guardedValue = map['enableAddCheck']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as bool); })(),
      enableAutoCheck: (() { final guardedValue = map['enableAutoCheck']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as bool); })(),
      endTime: (() { final guardedValue = map['endTime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      selectedChecks: (() { final guardedValue = map['selectedChecks']; if (guardedValue == null) return null; return pulumi.Input.fromValue(pulumi.Input.decodeList<CheckConfigSelectedCheck>(guardedValue, (value) => CheckConfigSelectedCheck.fromMap((value as Map).cast<String, dynamic>()))); })(),
      startTime: (() { final guardedValue = map['startTime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      systemConfig: (() { final guardedValue = map['systemConfig']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as bool); })(),
      vendors: (() { final guardedValue = map['vendors']; if (guardedValue == null) return null; return pulumi.Input.fromValue((guardedValue as List).cast<String>()); })(),
    );
  }
}

