// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for TableIamPolicy.
class TableIamPolicyArgs {
  /// The name or relative resource id of the instance that owns the table.
  final Input<String> instanceName;

  /// The policy data generated by a `gcp.organizations.getIAMPolicy` data source.
  ///
  /// - - -
  final Input<String> policyData;

  /// The project in which the table belongs. If it
  /// is not provided, this provider will use the provider default.
  final Input<String>? project;

  /// The name or relative resource id of the table to manage IAM policies for.
  ///
  /// For `gcp.bigtable.TableIamMember` or `gcp.bigtable.TableIamBinding`:
  final Input<String> table;

  TableIamPolicyArgs({
    required this.instanceName,
    required this.policyData,
    this.project,
    required this.table,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['instanceName'] = instanceName;
    map['policyData'] = policyData;
    final projectValue = project;
    if (projectValue != null) {
      map['project'] = projectValue;
    }
    map['table'] = table;
    return map;
  }

  factory TableIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return TableIamPolicyArgs(
      instanceName: Input.asInput<String>(map['instanceName']),
      policyData: Input.asInput<String>(map['policyData']),
      project: Input.asOptionalInput<String>(map['project']),
      table: Input.asInput<String>(map['table']),
    );
  }
}
