library module_securesourcemanager_instance_iam_policy;

export 'instance_iam_policy/instance_iam_policy_securesourcemanager.dart';
export 'instance_iam_policy/instance_iam_policy_securesourcemanager_args.dart';
