library module_kinesis_analytics_application_reference_data_sources_schema_record_format_mapping_parameters_json;

export 'analytics_application_reference_data_sources_schema_record_format_mapping_parameters_json.dart';
