library module_vpclattice_resource_configuration_resource_configuration_definition_dns_resource;

export 'resource_configuration_resource_configuration_definition_dns_resource/resource_configuration_resource_configuration_definition_dns_resource.dart';
