library module_sagemaker_domain_default_space_settings_jupyter_lab_app_settings_app_lifecycle_management_idle_settings;

export 'domain_default_space_settings_jupyter_lab_app_settings_app_lifecycle_management_idle_settings.dart';
