// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'schema_bundle_proto_schema.dart';

/// {@template pulumi_bigtable_schema_bundle_schema_bundle_args_doc}
/// The set of arguments for SchemaBundle.
/// {@endtemplate}
/// {@macro pulumi_bigtable_schema_bundle_schema_bundle_args_doc}
class SchemaBundleArgs {
  /// Whether Terraform will be prevented from destroying the resource. Defaults to DELETE.
  /// When a 'terraform destroy' or 'pulumi up' would delete the resource,
  /// the command will fail if this field is set to "PREVENT" in Terraform state.
  /// When set to "ABANDON", the command will remove the resource from Terraform
  /// management without updating or deleting the resource in the API.
  /// When set to "DELETE", deleting the resource is allowed.
  final pulumi.Input<String?>? deletionPolicy;
  /// If true, allow backwards incompatible changes.
  final pulumi.Input<bool?>? ignoreWarnings;
  /// The name of the instance to create the schema bundle within.
  final pulumi.Input<String?>? instance;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the provider project is used.
  final pulumi.Input<String?>? project;
  /// File descriptor set, generated by protoc.
  /// To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.
  /// $ protoc --include_imports --include_source_info test.proto -o out.pb
  /// Structure is documented below.
  final pulumi.Input<SchemaBundleProtoSchema> protoSchema;
  /// The unique name of the schema bundle in the form `[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  final pulumi.Input<String> schemaBundleId;
  /// The name of the table to create the schema bundle within.
  final pulumi.Input<String?>? table;

  /// Creates a new [SchemaBundleArgs].
  /// [deletionPolicy] Whether Terraform will be prevented from destroying the resource. Defaults to DELETE.
  /// [ignoreWarnings] If true, allow backwards incompatible changes.
  /// [instance] The name of the instance to create the schema bundle within.
  /// [project] The ID of the project in which the resource belongs.
  /// [protoSchema] File descriptor set, generated by protoc.
  /// [schemaBundleId] The unique name of the schema bundle in the form `[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  /// [table] The name of the table to create the schema bundle within.
  const SchemaBundleArgs({
    this.deletionPolicy,
    this.ignoreWarnings,
    this.instance,
    this.project,
    required this.protoSchema,
    required this.schemaBundleId,
    this.table,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'deletionPolicy': ?deletionPolicy,
      'ignoreWarnings': ?ignoreWarnings,
      'instance': ?instance,
      'project': ?project,
      'protoSchema': pulumi.Input.mapInputValue<SchemaBundleProtoSchema, Map<String, dynamic>>(protoSchema, (value) => value.toMap()),
      'schemaBundleId': schemaBundleId,
      'table': ?table,
    };
  }

  factory SchemaBundleArgs.fromMap(Map<String, dynamic> map) {
    return SchemaBundleArgs(
      deletionPolicy: (() { final guardedValue = map['deletionPolicy']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ignoreWarnings: (() { final guardedValue = map['ignoreWarnings']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as bool); })(),
      instance: (() { final guardedValue = map['instance']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      protoSchema: pulumi.Input.fromValue(SchemaBundleProtoSchema.fromMap((map['protoSchema']! as Map).cast<String, dynamic>())),
      schemaBundleId: pulumi.Input.fromValue(map['schemaBundleId'] as String),
      table: (() { final guardedValue = map['table']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
