targets:
  $default:
    builders:
      pulumi:pulumi_resource_generator:
        enabled: true

builders:
  pulumi_resource_generator:
    import: "package:pulumi/builder.dart"
    builder_factories: ["resourceGenerator"]
    build_extensions: { ".dart": [".resource.g.part"] }
    auto_apply: root_package
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
