library module_ecs_capacity_provider_managed_instances_provider_instance_launch_template_storage_configuration;

export 'capacity_provider_managed_instances_provider_instance_launch_template_storage_configuration/capacity_provider_managed_instances_provider_instance_launch_template_storage_configuration.dart';
