library module_ecs_get_task_definition_volume_efs_volume_configuration_authorization_config;

export 'get_task_definition_volume_efs_volume_configuration_authorization_config/get_task_definition_volume_efs_volume_configuration_authorization_config.dart';
