library module_certificateauthority_authority_config_x509_config_additional_extension_object_id;

export 'authority_config_x509_config_additional_extension_object_id/authority_config_x509_config_additional_extension_object_id.dart';
