library module_certificateauthority_certificate_config_x509_config_additional_extension_object_id;

export 'certificate_config_x509_config_additional_extension_object_id/certificate_config_x509_config_additional_extension_object_id.dart';
