library module_autoscaling_policy_target_tracking_configuration_customized_metric_specification_metric_metric_stat_metric_dimension;

export 'policy_target_tracking_configuration_customized_metric_specification_metric_metric_stat_metric_dimension.dart';
