// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering InstanceIAMPolicy resources.
class InstanceIAMPolicyState {
  /// (Computed) The etag of the instance's IAM policy.
  final pulumi.Input<String?>? etag;
  /// The name of the instance.
  final pulumi.Input<String?>? instance;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String?>? policyData;
  /// The ID of the project in which the resource belongs. If it
  /// is not provided, the provider project is used.
  final pulumi.Input<String?>? project;

  /// Creates a new [InstanceIAMPolicyState].
  /// [etag] (Computed) The etag of the instance's IAM policy.
  /// [instance] The name of the instance.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs. If it
  const InstanceIAMPolicyState({
    this.etag,
    this.instance,
    this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'instance': ?instance,
      'policyData': ?policyData,
      'project': ?project,
    };
  }

  factory InstanceIAMPolicyState.fromMap(Map<String, dynamic> map) {
    return InstanceIAMPolicyState(
      etag: (() { final guardedValue = map['etag']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      instance: (() { final guardedValue = map['instance']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      policyData: (() { final guardedValue = map['policyData']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
