library module_dataloss_prevention_job_trigger_inspect_job_inspect_config_rule_set_info_type_sensitivity_score;

export 'prevention_job_trigger_inspect_job_inspect_config_rule_set_info_type_sensitivity_score.dart';
