// ignore_for_file: non_constant_identifier_names

import 'package:pulumi_postgresql/index.dart' as module_index;
import 'package:pulumi_postgresql/providers.dart' as module_providers;

final index = _IndexModuleNamespace();
final providers = _ProvidersModuleNamespace();

class _IndexModuleNamespace {
  _IndexModuleNamespace();
  final Database = module_index.Database.new;
  final DatabaseArgs = module_index.DatabaseArgs.new;
  final DatabaseState = module_index.DatabaseState.new;
  final DatabaseStateArgs = module_index.DatabaseState.new;
  final DefaultPrivileg = module_index.DefaultPrivileg.new;
  final DefaultPrivilegArgs = module_index.DefaultPrivilegArgs.new;
  final DefaultPrivilegState = module_index.DefaultPrivilegState.new;
  final DefaultPrivilegStateArgs = module_index.DefaultPrivilegState.new;
  final DefaultPrivileges = module_index.DefaultPrivileges.new;
  final DefaultPrivilegesArgs = module_index.DefaultPrivilegesArgs.new;
  final DefaultPrivilegesState = module_index.DefaultPrivilegesState.new;
  final DefaultPrivilegesStateArgs = module_index.DefaultPrivilegesState.new;
  final Extension = module_index.Extension.new;
  final ExtensionArgs = module_index.ExtensionArgs.new;
  final ExtensionState = module_index.ExtensionState.new;
  final ExtensionStateArgs = module_index.ExtensionState.new;
  final FunctionArg = module_index.FunctionArg.new;
  final FunctionArgArgs = module_index.FunctionArg.new;
  final FunctionArgs = module_index.FunctionArgs.new;
  final FunctionState = module_index.FunctionState.new;
  final FunctionStateArgs = module_index.FunctionState.new;
  final FunctionType = module_index.FunctionType.new;
  final GetSchemasArgs = module_index.GetSchemasArgs.new;
  final GetSchemasResult = module_index.GetSchemasResult.new;
  final GetSchemasResultArgs = module_index.GetSchemasResult.new;
  final GetSequencesArgs = module_index.GetSequencesArgs.new;
  final GetSequencesResult = module_index.GetSequencesResult.new;
  final GetSequencesResultArgs = module_index.GetSequencesResult.new;
  final GetSequencesSequence = module_index.GetSequencesSequence.new;
  final GetSequencesSequenceArgs = module_index.GetSequencesSequence.new;
  final GetTablesArgs = module_index.GetTablesArgs.new;
  final GetTablesResult = module_index.GetTablesResult.new;
  final GetTablesResultArgs = module_index.GetTablesResult.new;
  final GetTablesTable = module_index.GetTablesTable.new;
  final GetTablesTableArgs = module_index.GetTablesTable.new;
  final Grant = module_index.Grant.new;
  final GrantArgs = module_index.GrantArgs.new;
  final GrantRole = module_index.GrantRole.new;
  final GrantRoleArgs = module_index.GrantRoleArgs.new;
  final GrantRoleState = module_index.GrantRoleState.new;
  final GrantRoleStateArgs = module_index.GrantRoleState.new;
  final GrantState = module_index.GrantState.new;
  final GrantStateArgs = module_index.GrantState.new;
  final PhysicalReplicationSlot = module_index.PhysicalReplicationSlot.new;
  final PhysicalReplicationSlotArgs = module_index.PhysicalReplicationSlotArgs.new;
  final PhysicalReplicationSlotState = module_index.PhysicalReplicationSlotState.new;
  final PhysicalReplicationSlotStateArgs = module_index.PhysicalReplicationSlotState.new;
  final ProviderClientcert = module_index.ProviderClientcert.new;
  final ProviderClientcertArgs = module_index.ProviderClientcert.new;
  final Publication = module_index.Publication.new;
  final PublicationArgs = module_index.PublicationArgs.new;
  final PublicationState = module_index.PublicationState.new;
  final PublicationStateArgs = module_index.PublicationState.new;
  final ReplicationSlot = module_index.ReplicationSlot.new;
  final ReplicationSlotArgs = module_index.ReplicationSlotArgs.new;
  final ReplicationSlotState = module_index.ReplicationSlotState.new;
  final ReplicationSlotStateArgs = module_index.ReplicationSlotState.new;
  final Role = module_index.Role.new;
  final RoleArgs = module_index.RoleArgs.new;
  final RoleState = module_index.RoleState.new;
  final RoleStateArgs = module_index.RoleState.new;
  final Schema = module_index.Schema.new;
  final SchemaArgs = module_index.SchemaArgs.new;
  final SchemaPolicy = module_index.SchemaPolicy.new;
  final SchemaPolicyArgs = module_index.SchemaPolicy.new;
  final SchemaState = module_index.SchemaState.new;
  final SchemaStateArgs = module_index.SchemaState.new;
  final SecurityLabel = module_index.SecurityLabel.new;
  final SecurityLabelArgs = module_index.SecurityLabelArgs.new;
  final SecurityLabelState = module_index.SecurityLabelState.new;
  final SecurityLabelStateArgs = module_index.SecurityLabelState.new;
  final Server = module_index.Server.new;
  final ServerArgs = module_index.ServerArgs.new;
  final ServerState = module_index.ServerState.new;
  final ServerStateArgs = module_index.ServerState.new;
  final Subscription = module_index.Subscription.new;
  final SubscriptionArgs = module_index.SubscriptionArgs.new;
  final SubscriptionState = module_index.SubscriptionState.new;
  final SubscriptionStateArgs = module_index.SubscriptionState.new;
  final UserMapping = module_index.UserMapping.new;
  final UserMappingArgs = module_index.UserMappingArgs.new;
  final UserMappingState = module_index.UserMappingState.new;
  final UserMappingStateArgs = module_index.UserMappingState.new;
  final getSchemas = module_index.getSchemas;
  final getSequences = module_index.getSequences;
  final getTables = module_index.getTables;
}

class _ProvidersModuleNamespace {
  _ProvidersModuleNamespace();
  final Postgresql = module_providers.ProviderProvider.new;
  final PostgresqlArgs = module_providers.ProviderArgs.new;
  final ProviderArgs = module_providers.ProviderArgs.new;
  final ProviderTerraformConfigResult = module_providers.ProviderTerraformConfigResult.new;
  final ProviderTerraformConfigResultArgs = module_providers.ProviderTerraformConfigResult.new;
  final TerraformConfigArgs = module_providers.TerraformConfigArgs.new;
  final TerraformConfigResult = module_providers.TerraformConfigResult.new;
  final TerraformConfigResultArgs = module_providers.TerraformConfigResult.new;
  final terraformConfig = module_providers.terraformConfig;
}
