name: gcp_dart_gke_serviceaccount
description: Pulumi Dart GKE + service account example.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: ^3.0.0
  pulumi_gcp: 9.36.1+1
  pulumi_kubernetes: 4.34.0+1

dev_dependencies:
  lints: ^6.1.0
