name: provider_authoring_integration
description: Integration fixture for Dart provider authoring server.
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  pulumi:
    path: ../../../packages/pulumi-dart
