// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'google_cloud_aiplatform_v1beta1_feature_stats_anomaly_response.dart';
import 'google_cloud_aiplatform_v1beta1_threshold_config_response.dart';

/// Historical Stats (and Anomalies) for a specific Feature.
class GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomaliesResponse {
  /// Display Name of the Feature.
  final String featureDisplayName;

  /// A list of historical stats generated by different time window's Prediction Dataset.
  final List<GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse>
      predictionStats;

  /// Threshold for anomaly detection.
  final GoogleCloudAiplatformV1beta1ThresholdConfigResponse threshold;

  /// Stats calculated for the Training Dataset.
  final GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse trainingStats;

  GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomaliesResponse({
    required this.featureDisplayName,
    required this.predictionStats,
    required this.threshold,
    required this.trainingStats,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['featureDisplayName'] = featureDisplayName;
    map['predictionStats'] = pulumi.Input.encodeList<
        GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse,
        Map<String, dynamic>>(predictionStats, (value) => value.toMap());
    map['threshold'] = threshold.toMap();
    map['trainingStats'] = trainingStats.toMap();
    return map;
  }

  factory GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomaliesResponse.fromMap(
      Map<String, dynamic> map) {
    return GoogleCloudAiplatformV1beta1ModelMonitoringStatsAnomaliesFeatureHistoricStatsAnomaliesResponse(
      featureDisplayName: map['featureDisplayName'] as String,
      predictionStats: pulumi.Input.decodeList<
              GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse>(
          map['predictionStats'],
          (value) =>
              GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse.fromMap(
                  (value as Map).cast<String, dynamic>())),
      threshold: GoogleCloudAiplatformV1beta1ThresholdConfigResponse.fromMap(
          (map['threshold'] as Map).cast<String, dynamic>()),
      trainingStats:
          GoogleCloudAiplatformV1beta1FeatureStatsAnomalyResponse.fromMap(
              (map['trainingStats'] as Map).cast<String, dynamic>()),
    );
  }
}
