library module_cloudwatch_event_connection_auth_parameters_oauth_oauth_http_parameters_header;

export 'event_connection_auth_parameters_oauth_oauth_http_parameters_header/event_connection_auth_parameters_oauth_oauth_http_parameters_header.dart';
