library module_cloudwatch_internet_monitor_internet_measurements_log_delivery_s3_config;

export 'internet_monitor_internet_measurements_log_delivery_s3_config/internet_monitor_internet_measurements_log_delivery_s3_config.dart';
