library module_cloudwatch_log_transformer_transformer_config_substitute_string_entry;

export 'log_transformer_transformer_config_substitute_string_entry/log_transformer_transformer_config_substitute_string_entry.dart';
