library module_chimesdkmediapipelines_media_insights_pipeline_configuration_element_lambda_function_sink_configuration;

export 'media_insights_pipeline_configuration_element_lambda_function_sink_configuration.dart';
