import 'package:pulumi/pulumi.dart' as pulumi;
import 'provider_args.dart';
import 'provider_terraform_config_result.dart';

/// The provider type for the google-beta package. By default, resources use package-wide configuration
/// settings, however an explicit `Provider` instance may be created and passed during resource
/// construction to achieve fine-grained programmatic control over provider settings. See the
/// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
class ProviderProvider extends pulumi.ProviderResource {
  late final pulumi.Output<String?> accessApprovalCustomEndpoint;
  late final pulumi.Output<String?> accessContextManagerCustomEndpoint;
  late final pulumi.Output<String?> accessToken;
  late final pulumi.Output<String?> activeDirectoryCustomEndpoint;
  late final pulumi.Output<String?> alloydbCustomEndpoint;
  late final pulumi.Output<String?> apiGatewayCustomEndpoint;
  late final pulumi.Output<String?> apigeeCustomEndpoint;
  late final pulumi.Output<String?> apihubCustomEndpoint;
  late final pulumi.Output<String?> apikeysCustomEndpoint;
  late final pulumi.Output<String?> appEngineCustomEndpoint;
  late final pulumi.Output<String?> apphubCustomEndpoint;
  late final pulumi.Output<String?> artifactRegistryCustomEndpoint;
  late final pulumi.Output<String?> assuredWorkloadsCustomEndpoint;
  late final pulumi.Output<String?> backupDrCustomEndpoint;
  late final pulumi.Output<String?> beyondcorpCustomEndpoint;
  late final pulumi.Output<String?> bigQueryCustomEndpoint;
  late final pulumi.Output<String?> biglakeCustomEndpoint;
  late final pulumi.Output<String?> biglakeIcebergCustomEndpoint;
  late final pulumi.Output<String?> bigqueryAnalyticsHubCustomEndpoint;
  late final pulumi.Output<String?> bigqueryConnectionCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDataTransferCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDatapolicyCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDatapolicyv2CustomEndpoint;
  late final pulumi.Output<String?> bigqueryReservationCustomEndpoint;
  late final pulumi.Output<String?> bigtableCustomEndpoint;
  late final pulumi.Output<String?> billingCustomEndpoint;
  late final pulumi.Output<String?> billingProject;
  late final pulumi.Output<String?> binaryAuthorizationCustomEndpoint;
  late final pulumi.Output<String?> blockchainNodeEngineCustomEndpoint;
  late final pulumi.Output<String?> certificateManagerCustomEndpoint;
  late final pulumi.Output<String?> cesCustomEndpoint;
  late final pulumi.Output<String?> chronicleCustomEndpoint;
  late final pulumi.Output<String?> cloudAssetCustomEndpoint;
  late final pulumi.Output<String?> cloudBillingCustomEndpoint;
  late final pulumi.Output<String?> cloudBuildCustomEndpoint;
  late final pulumi.Output<String?> cloudFunctionsCustomEndpoint;
  late final pulumi.Output<String?> cloudIdentityCustomEndpoint;
  late final pulumi.Output<String?> cloudIdsCustomEndpoint;
  late final pulumi.Output<String?> cloudQuotasCustomEndpoint;
  late final pulumi.Output<String?> cloudResourceManagerCustomEndpoint;
  late final pulumi.Output<String?> cloudRunCustomEndpoint;
  late final pulumi.Output<String?> cloudRunV2CustomEndpoint;
  late final pulumi.Output<String?> cloudSchedulerCustomEndpoint;
  late final pulumi.Output<String?> cloudSecurityComplianceCustomEndpoint;
  late final pulumi.Output<String?> cloudTasksCustomEndpoint;
  late final pulumi.Output<String?> cloudbuildv2CustomEndpoint;
  late final pulumi.Output<String?> clouddeployCustomEndpoint;
  late final pulumi.Output<String?> clouddomainsCustomEndpoint;
  late final pulumi.Output<String?> cloudfunctions2CustomEndpoint;
  late final pulumi.Output<String?> colabCustomEndpoint;
  late final pulumi.Output<String?> composerCustomEndpoint;
  late final pulumi.Output<String?> computeCustomEndpoint;
  late final pulumi.Output<String?> contactCenterInsightsCustomEndpoint;
  late final pulumi.Output<String?> containerAnalysisCustomEndpoint;
  late final pulumi.Output<String?> containerAttachedCustomEndpoint;
  late final pulumi.Output<String?> containerAwsCustomEndpoint;
  late final pulumi.Output<String?> containerAzureCustomEndpoint;
  late final pulumi.Output<String?> containerCustomEndpoint;
  late final pulumi.Output<String?> coreBillingCustomEndpoint;
  late final pulumi.Output<String?> credentials;
  late final pulumi.Output<String?> dataCatalogCustomEndpoint;
  late final pulumi.Output<String?> dataFusionCustomEndpoint;
  late final pulumi.Output<String?> dataLossPreventionCustomEndpoint;
  late final pulumi.Output<String?> dataPipelineCustomEndpoint;
  late final pulumi.Output<String?> databaseMigrationServiceCustomEndpoint;
  late final pulumi.Output<String?> dataflowCustomEndpoint;
  late final pulumi.Output<String?> dataformCustomEndpoint;
  late final pulumi.Output<String?> dataplexCustomEndpoint;
  late final pulumi.Output<String?> dataprocCustomEndpoint;
  late final pulumi.Output<String?> dataprocGdcCustomEndpoint;
  late final pulumi.Output<String?> dataprocMetastoreCustomEndpoint;
  late final pulumi.Output<String?> datastreamCustomEndpoint;
  late final pulumi.Output<String?> deploymentManagerCustomEndpoint;
  late final pulumi.Output<String?> developerConnectCustomEndpoint;
  late final pulumi.Output<String?> dialogflowCustomEndpoint;
  late final pulumi.Output<String?> dialogflowCxCustomEndpoint;
  late final pulumi.Output<String?> discoveryEngineCustomEndpoint;
  late final pulumi.Output<String?> dnsCustomEndpoint;
  late final pulumi.Output<String?> documentAiCustomEndpoint;
  late final pulumi.Output<String?> documentAiWarehouseCustomEndpoint;
  late final pulumi.Output<String?> edgecontainerCustomEndpoint;
  late final pulumi.Output<String?> edgenetworkCustomEndpoint;
  late final pulumi.Output<String?> essentialContactsCustomEndpoint;
  late final pulumi.Output<String?> eventarcCustomEndpoint;
  late final pulumi.Output<String?> filestoreCustomEndpoint;
  late final pulumi.Output<String?> firebaseAiLogicCustomEndpoint;
  late final pulumi.Output<String?> firebaseAppCheckCustomEndpoint;
  late final pulumi.Output<String?> firebaseAppHostingCustomEndpoint;
  late final pulumi.Output<String?> firebaseCustomEndpoint;
  late final pulumi.Output<String?> firebaseDataConnectCustomEndpoint;
  late final pulumi.Output<String?> firebaseDatabaseCustomEndpoint;
  late final pulumi.Output<String?> firebaseExtensionsCustomEndpoint;
  late final pulumi.Output<String?> firebaseHostingCustomEndpoint;
  late final pulumi.Output<String?> firebaseStorageCustomEndpoint;
  late final pulumi.Output<String?> firebaserulesCustomEndpoint;
  late final pulumi.Output<String?> firestoreCustomEndpoint;
  late final pulumi.Output<String?> geminiCustomEndpoint;
  late final pulumi.Output<String?> gkeBackupCustomEndpoint;
  late final pulumi.Output<String?> gkeHub2CustomEndpoint;
  late final pulumi.Output<String?> gkeHubCustomEndpoint;
  late final pulumi.Output<String?> gkeonpremCustomEndpoint;
  late final pulumi.Output<String?> googlePartnerName;
  late final pulumi.Output<String?> healthcareCustomEndpoint;
  late final pulumi.Output<String?> iam2CustomEndpoint;
  late final pulumi.Output<String?> iam3CustomEndpoint;
  late final pulumi.Output<String?> iamBetaCustomEndpoint;
  late final pulumi.Output<String?> iamCredentialsCustomEndpoint;
  late final pulumi.Output<String?> iamCustomEndpoint;
  late final pulumi.Output<String?> iamWorkforcePoolCustomEndpoint;
  late final pulumi.Output<String?> iapCustomEndpoint;
  late final pulumi.Output<String?> identityPlatformCustomEndpoint;
  late final pulumi.Output<String?> impersonateServiceAccount;
  late final pulumi.Output<String?> integrationConnectorsCustomEndpoint;
  late final pulumi.Output<String?> integrationsCustomEndpoint;
  late final pulumi.Output<String?> kmsCustomEndpoint;
  late final pulumi.Output<String?> loggingCustomEndpoint;
  late final pulumi.Output<String?> lookerCustomEndpoint;
  late final pulumi.Output<String?> lustreCustomEndpoint;
  late final pulumi.Output<String?> managedKafkaCustomEndpoint;
  late final pulumi.Output<String?> memcacheCustomEndpoint;
  late final pulumi.Output<String?> memorystoreCustomEndpoint;
  late final pulumi.Output<String?> migrationCenterCustomEndpoint;
  late final pulumi.Output<String?> mlEngineCustomEndpoint;
  late final pulumi.Output<String?> modelArmorCustomEndpoint;
  late final pulumi.Output<String?> modelArmorGlobalCustomEndpoint;
  late final pulumi.Output<String?> monitoringCustomEndpoint;
  late final pulumi.Output<String?> netappCustomEndpoint;
  late final pulumi.Output<String?> networkConnectivityCustomEndpoint;
  late final pulumi.Output<String?> networkConnectivityv1CustomEndpoint;
  late final pulumi.Output<String?> networkManagementCustomEndpoint;
  late final pulumi.Output<String?> networkSecurityCustomEndpoint;
  late final pulumi.Output<String?> networkServicesCustomEndpoint;
  late final pulumi.Output<String?> notebooksCustomEndpoint;
  late final pulumi.Output<String?> observabilityCustomEndpoint;
  late final pulumi.Output<String?> oracleDatabaseCustomEndpoint;
  late final pulumi.Output<String?> orgPolicyCustomEndpoint;
  late final pulumi.Output<String?> osConfigCustomEndpoint;
  late final pulumi.Output<String?> osConfigV2CustomEndpoint;
  late final pulumi.Output<String?> osLoginCustomEndpoint;
  late final pulumi.Output<String?> parallelstoreCustomEndpoint;
  late final pulumi.Output<String?> parameterManagerCustomEndpoint;
  late final pulumi.Output<String?> parameterManagerRegionalCustomEndpoint;
  late final pulumi.Output<String?> privatecaCustomEndpoint;
  late final pulumi.Output<String?> privilegedAccessManagerCustomEndpoint;
  late final pulumi.Output<String?> project;
  late final pulumi.Output<String?> publicCaCustomEndpoint;
  late final pulumi.Output<String?> pubsubCustomEndpoint;
  late final pulumi.Output<String?> pubsubLiteCustomEndpoint;
  late final pulumi.Output<String?> pulumiAttributionLabelAdditionStrategy;
  late final pulumi.Output<String?> recaptchaEnterpriseCustomEndpoint;
  late final pulumi.Output<String?> redisCustomEndpoint;
  late final pulumi.Output<String?> region;
  late final pulumi.Output<String?> requestReason;
  late final pulumi.Output<String?> requestTimeout;
  late final pulumi.Output<String?> resourceManager3CustomEndpoint;
  late final pulumi.Output<String?> resourceManagerCustomEndpoint;
  late final pulumi.Output<String?> resourceManagerV3CustomEndpoint;
  late final pulumi.Output<String?> runtimeConfigCustomEndpoint;
  late final pulumi.Output<String?> runtimeconfigCustomEndpoint;
  late final pulumi.Output<String?> saasRuntimeCustomEndpoint;
  late final pulumi.Output<String?> secretManagerCustomEndpoint;
  late final pulumi.Output<String?> secretManagerRegionalCustomEndpoint;
  late final pulumi.Output<String?> secureSourceManagerCustomEndpoint;
  late final pulumi.Output<String?> securityCenterCustomEndpoint;
  late final pulumi.Output<String?> securityCenterManagementCustomEndpoint;
  late final pulumi.Output<String?> securityCenterV2CustomEndpoint;
  late final pulumi.Output<String?> securityScannerCustomEndpoint;
  late final pulumi.Output<String?> securitypostureCustomEndpoint;
  late final pulumi.Output<String?> serviceDirectoryCustomEndpoint;
  late final pulumi.Output<String?> serviceManagementCustomEndpoint;
  late final pulumi.Output<String?> serviceNetworkingCustomEndpoint;
  late final pulumi.Output<String?> serviceUsageCustomEndpoint;
  late final pulumi.Output<String?> siteVerificationCustomEndpoint;
  late final pulumi.Output<String?> sourceRepoCustomEndpoint;
  late final pulumi.Output<String?> spannerCustomEndpoint;
  late final pulumi.Output<String?> sqlCustomEndpoint;
  late final pulumi.Output<String?> storageBatchOperationsCustomEndpoint;
  late final pulumi.Output<String?> storageControlCustomEndpoint;
  late final pulumi.Output<String?> storageCustomEndpoint;
  late final pulumi.Output<String?> storageInsightsCustomEndpoint;
  late final pulumi.Output<String?> storageTransferCustomEndpoint;
  late final pulumi.Output<String?> tagsCustomEndpoint;
  late final pulumi.Output<String?> tagsLocationCustomEndpoint;
  late final pulumi.Output<String?> tpuV2CustomEndpoint;
  late final pulumi.Output<String?> transcoderCustomEndpoint;
  late final pulumi.Output<String?> universeDomain;
  late final pulumi.Output<String?> vertexAiCustomEndpoint;
  late final pulumi.Output<String?> vmwareengineCustomEndpoint;
  late final pulumi.Output<String?> vpcAccessCustomEndpoint;
  late final pulumi.Output<String?> workbenchCustomEndpoint;
  late final pulumi.Output<String?> workflowsCustomEndpoint;
  late final pulumi.Output<String?> workstationsCustomEndpoint;
  late final pulumi.Output<String?> zone;

  /// Creates a new [ProviderProvider].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [ProviderProvider]. {@macro pulumi_providers_provider_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  ProviderProvider(
    String name, {
    ProviderArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'gcp',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    accessApprovalCustomEndpoint = registerOutput<String?>('accessApprovalCustomEndpoint');
    accessContextManagerCustomEndpoint = registerOutput<String?>('accessContextManagerCustomEndpoint');
    accessToken = registerOutput<String?>('accessToken');
    activeDirectoryCustomEndpoint = registerOutput<String?>('activeDirectoryCustomEndpoint');
    alloydbCustomEndpoint = registerOutput<String?>('alloydbCustomEndpoint');
    apiGatewayCustomEndpoint = registerOutput<String?>('apiGatewayCustomEndpoint');
    apigeeCustomEndpoint = registerOutput<String?>('apigeeCustomEndpoint');
    apihubCustomEndpoint = registerOutput<String?>('apihubCustomEndpoint');
    apikeysCustomEndpoint = registerOutput<String?>('apikeysCustomEndpoint');
    appEngineCustomEndpoint = registerOutput<String?>('appEngineCustomEndpoint');
    apphubCustomEndpoint = registerOutput<String?>('apphubCustomEndpoint');
    artifactRegistryCustomEndpoint = registerOutput<String?>('artifactRegistryCustomEndpoint');
    assuredWorkloadsCustomEndpoint = registerOutput<String?>('assuredWorkloadsCustomEndpoint');
    backupDrCustomEndpoint = registerOutput<String?>('backupDrCustomEndpoint');
    beyondcorpCustomEndpoint = registerOutput<String?>('beyondcorpCustomEndpoint');
    bigQueryCustomEndpoint = registerOutput<String?>('bigQueryCustomEndpoint');
    biglakeCustomEndpoint = registerOutput<String?>('biglakeCustomEndpoint');
    biglakeIcebergCustomEndpoint = registerOutput<String?>('biglakeIcebergCustomEndpoint');
    bigqueryAnalyticsHubCustomEndpoint = registerOutput<String?>('bigqueryAnalyticsHubCustomEndpoint');
    bigqueryConnectionCustomEndpoint = registerOutput<String?>('bigqueryConnectionCustomEndpoint');
    bigqueryDataTransferCustomEndpoint = registerOutput<String?>('bigqueryDataTransferCustomEndpoint');
    bigqueryDatapolicyCustomEndpoint = registerOutput<String?>('bigqueryDatapolicyCustomEndpoint');
    bigqueryDatapolicyv2CustomEndpoint = registerOutput<String?>('bigqueryDatapolicyv2CustomEndpoint');
    bigqueryReservationCustomEndpoint = registerOutput<String?>('bigqueryReservationCustomEndpoint');
    bigtableCustomEndpoint = registerOutput<String?>('bigtableCustomEndpoint');
    billingCustomEndpoint = registerOutput<String?>('billingCustomEndpoint');
    billingProject = registerOutput<String?>('billingProject');
    binaryAuthorizationCustomEndpoint = registerOutput<String?>('binaryAuthorizationCustomEndpoint');
    blockchainNodeEngineCustomEndpoint = registerOutput<String?>('blockchainNodeEngineCustomEndpoint');
    certificateManagerCustomEndpoint = registerOutput<String?>('certificateManagerCustomEndpoint');
    cesCustomEndpoint = registerOutput<String?>('cesCustomEndpoint');
    chronicleCustomEndpoint = registerOutput<String?>('chronicleCustomEndpoint');
    cloudAssetCustomEndpoint = registerOutput<String?>('cloudAssetCustomEndpoint');
    cloudBillingCustomEndpoint = registerOutput<String?>('cloudBillingCustomEndpoint');
    cloudBuildCustomEndpoint = registerOutput<String?>('cloudBuildCustomEndpoint');
    cloudFunctionsCustomEndpoint = registerOutput<String?>('cloudFunctionsCustomEndpoint');
    cloudIdentityCustomEndpoint = registerOutput<String?>('cloudIdentityCustomEndpoint');
    cloudIdsCustomEndpoint = registerOutput<String?>('cloudIdsCustomEndpoint');
    cloudQuotasCustomEndpoint = registerOutput<String?>('cloudQuotasCustomEndpoint');
    cloudResourceManagerCustomEndpoint = registerOutput<String?>('cloudResourceManagerCustomEndpoint');
    cloudRunCustomEndpoint = registerOutput<String?>('cloudRunCustomEndpoint');
    cloudRunV2CustomEndpoint = registerOutput<String?>('cloudRunV2CustomEndpoint');
    cloudSchedulerCustomEndpoint = registerOutput<String?>('cloudSchedulerCustomEndpoint');
    cloudSecurityComplianceCustomEndpoint = registerOutput<String?>('cloudSecurityComplianceCustomEndpoint');
    cloudTasksCustomEndpoint = registerOutput<String?>('cloudTasksCustomEndpoint');
    cloudbuildv2CustomEndpoint = registerOutput<String?>('cloudbuildv2CustomEndpoint');
    clouddeployCustomEndpoint = registerOutput<String?>('clouddeployCustomEndpoint');
    clouddomainsCustomEndpoint = registerOutput<String?>('clouddomainsCustomEndpoint');
    cloudfunctions2CustomEndpoint = registerOutput<String?>('cloudfunctions2CustomEndpoint');
    colabCustomEndpoint = registerOutput<String?>('colabCustomEndpoint');
    composerCustomEndpoint = registerOutput<String?>('composerCustomEndpoint');
    computeCustomEndpoint = registerOutput<String?>('computeCustomEndpoint');
    contactCenterInsightsCustomEndpoint = registerOutput<String?>('contactCenterInsightsCustomEndpoint');
    containerAnalysisCustomEndpoint = registerOutput<String?>('containerAnalysisCustomEndpoint');
    containerAttachedCustomEndpoint = registerOutput<String?>('containerAttachedCustomEndpoint');
    containerAwsCustomEndpoint = registerOutput<String?>('containerAwsCustomEndpoint');
    containerAzureCustomEndpoint = registerOutput<String?>('containerAzureCustomEndpoint');
    containerCustomEndpoint = registerOutput<String?>('containerCustomEndpoint');
    coreBillingCustomEndpoint = registerOutput<String?>('coreBillingCustomEndpoint');
    credentials = registerOutput<String?>('credentials');
    dataCatalogCustomEndpoint = registerOutput<String?>('dataCatalogCustomEndpoint');
    dataFusionCustomEndpoint = registerOutput<String?>('dataFusionCustomEndpoint');
    dataLossPreventionCustomEndpoint = registerOutput<String?>('dataLossPreventionCustomEndpoint');
    dataPipelineCustomEndpoint = registerOutput<String?>('dataPipelineCustomEndpoint');
    databaseMigrationServiceCustomEndpoint = registerOutput<String?>('databaseMigrationServiceCustomEndpoint');
    dataflowCustomEndpoint = registerOutput<String?>('dataflowCustomEndpoint');
    dataformCustomEndpoint = registerOutput<String?>('dataformCustomEndpoint');
    dataplexCustomEndpoint = registerOutput<String?>('dataplexCustomEndpoint');
    dataprocCustomEndpoint = registerOutput<String?>('dataprocCustomEndpoint');
    dataprocGdcCustomEndpoint = registerOutput<String?>('dataprocGdcCustomEndpoint');
    dataprocMetastoreCustomEndpoint = registerOutput<String?>('dataprocMetastoreCustomEndpoint');
    datastreamCustomEndpoint = registerOutput<String?>('datastreamCustomEndpoint');
    deploymentManagerCustomEndpoint = registerOutput<String?>('deploymentManagerCustomEndpoint');
    developerConnectCustomEndpoint = registerOutput<String?>('developerConnectCustomEndpoint');
    dialogflowCustomEndpoint = registerOutput<String?>('dialogflowCustomEndpoint');
    dialogflowCxCustomEndpoint = registerOutput<String?>('dialogflowCxCustomEndpoint');
    discoveryEngineCustomEndpoint = registerOutput<String?>('discoveryEngineCustomEndpoint');
    dnsCustomEndpoint = registerOutput<String?>('dnsCustomEndpoint');
    documentAiCustomEndpoint = registerOutput<String?>('documentAiCustomEndpoint');
    documentAiWarehouseCustomEndpoint = registerOutput<String?>('documentAiWarehouseCustomEndpoint');
    edgecontainerCustomEndpoint = registerOutput<String?>('edgecontainerCustomEndpoint');
    edgenetworkCustomEndpoint = registerOutput<String?>('edgenetworkCustomEndpoint');
    essentialContactsCustomEndpoint = registerOutput<String?>('essentialContactsCustomEndpoint');
    eventarcCustomEndpoint = registerOutput<String?>('eventarcCustomEndpoint');
    filestoreCustomEndpoint = registerOutput<String?>('filestoreCustomEndpoint');
    firebaseAiLogicCustomEndpoint = registerOutput<String?>('firebaseAiLogicCustomEndpoint');
    firebaseAppCheckCustomEndpoint = registerOutput<String?>('firebaseAppCheckCustomEndpoint');
    firebaseAppHostingCustomEndpoint = registerOutput<String?>('firebaseAppHostingCustomEndpoint');
    firebaseCustomEndpoint = registerOutput<String?>('firebaseCustomEndpoint');
    firebaseDataConnectCustomEndpoint = registerOutput<String?>('firebaseDataConnectCustomEndpoint');
    firebaseDatabaseCustomEndpoint = registerOutput<String?>('firebaseDatabaseCustomEndpoint');
    firebaseExtensionsCustomEndpoint = registerOutput<String?>('firebaseExtensionsCustomEndpoint');
    firebaseHostingCustomEndpoint = registerOutput<String?>('firebaseHostingCustomEndpoint');
    firebaseStorageCustomEndpoint = registerOutput<String?>('firebaseStorageCustomEndpoint');
    firebaserulesCustomEndpoint = registerOutput<String?>('firebaserulesCustomEndpoint');
    firestoreCustomEndpoint = registerOutput<String?>('firestoreCustomEndpoint');
    geminiCustomEndpoint = registerOutput<String?>('geminiCustomEndpoint');
    gkeBackupCustomEndpoint = registerOutput<String?>('gkeBackupCustomEndpoint');
    gkeHub2CustomEndpoint = registerOutput<String?>('gkeHub2CustomEndpoint');
    gkeHubCustomEndpoint = registerOutput<String?>('gkeHubCustomEndpoint');
    gkeonpremCustomEndpoint = registerOutput<String?>('gkeonpremCustomEndpoint');
    googlePartnerName = registerOutput<String?>('googlePartnerName');
    healthcareCustomEndpoint = registerOutput<String?>('healthcareCustomEndpoint');
    iam2CustomEndpoint = registerOutput<String?>('iam2CustomEndpoint');
    iam3CustomEndpoint = registerOutput<String?>('iam3CustomEndpoint');
    iamBetaCustomEndpoint = registerOutput<String?>('iamBetaCustomEndpoint');
    iamCredentialsCustomEndpoint = registerOutput<String?>('iamCredentialsCustomEndpoint');
    iamCustomEndpoint = registerOutput<String?>('iamCustomEndpoint');
    iamWorkforcePoolCustomEndpoint = registerOutput<String?>('iamWorkforcePoolCustomEndpoint');
    iapCustomEndpoint = registerOutput<String?>('iapCustomEndpoint');
    identityPlatformCustomEndpoint = registerOutput<String?>('identityPlatformCustomEndpoint');
    impersonateServiceAccount = registerOutput<String?>('impersonateServiceAccount');
    integrationConnectorsCustomEndpoint = registerOutput<String?>('integrationConnectorsCustomEndpoint');
    integrationsCustomEndpoint = registerOutput<String?>('integrationsCustomEndpoint');
    kmsCustomEndpoint = registerOutput<String?>('kmsCustomEndpoint');
    loggingCustomEndpoint = registerOutput<String?>('loggingCustomEndpoint');
    lookerCustomEndpoint = registerOutput<String?>('lookerCustomEndpoint');
    lustreCustomEndpoint = registerOutput<String?>('lustreCustomEndpoint');
    managedKafkaCustomEndpoint = registerOutput<String?>('managedKafkaCustomEndpoint');
    memcacheCustomEndpoint = registerOutput<String?>('memcacheCustomEndpoint');
    memorystoreCustomEndpoint = registerOutput<String?>('memorystoreCustomEndpoint');
    migrationCenterCustomEndpoint = registerOutput<String?>('migrationCenterCustomEndpoint');
    mlEngineCustomEndpoint = registerOutput<String?>('mlEngineCustomEndpoint');
    modelArmorCustomEndpoint = registerOutput<String?>('modelArmorCustomEndpoint');
    modelArmorGlobalCustomEndpoint = registerOutput<String?>('modelArmorGlobalCustomEndpoint');
    monitoringCustomEndpoint = registerOutput<String?>('monitoringCustomEndpoint');
    netappCustomEndpoint = registerOutput<String?>('netappCustomEndpoint');
    networkConnectivityCustomEndpoint = registerOutput<String?>('networkConnectivityCustomEndpoint');
    networkConnectivityv1CustomEndpoint = registerOutput<String?>('networkConnectivityv1CustomEndpoint');
    networkManagementCustomEndpoint = registerOutput<String?>('networkManagementCustomEndpoint');
    networkSecurityCustomEndpoint = registerOutput<String?>('networkSecurityCustomEndpoint');
    networkServicesCustomEndpoint = registerOutput<String?>('networkServicesCustomEndpoint');
    notebooksCustomEndpoint = registerOutput<String?>('notebooksCustomEndpoint');
    observabilityCustomEndpoint = registerOutput<String?>('observabilityCustomEndpoint');
    oracleDatabaseCustomEndpoint = registerOutput<String?>('oracleDatabaseCustomEndpoint');
    orgPolicyCustomEndpoint = registerOutput<String?>('orgPolicyCustomEndpoint');
    osConfigCustomEndpoint = registerOutput<String?>('osConfigCustomEndpoint');
    osConfigV2CustomEndpoint = registerOutput<String?>('osConfigV2CustomEndpoint');
    osLoginCustomEndpoint = registerOutput<String?>('osLoginCustomEndpoint');
    parallelstoreCustomEndpoint = registerOutput<String?>('parallelstoreCustomEndpoint');
    parameterManagerCustomEndpoint = registerOutput<String?>('parameterManagerCustomEndpoint');
    parameterManagerRegionalCustomEndpoint = registerOutput<String?>('parameterManagerRegionalCustomEndpoint');
    privatecaCustomEndpoint = registerOutput<String?>('privatecaCustomEndpoint');
    privilegedAccessManagerCustomEndpoint = registerOutput<String?>('privilegedAccessManagerCustomEndpoint');
    project = registerOutput<String?>('project');
    publicCaCustomEndpoint = registerOutput<String?>('publicCaCustomEndpoint');
    pubsubCustomEndpoint = registerOutput<String?>('pubsubCustomEndpoint');
    pubsubLiteCustomEndpoint = registerOutput<String?>('pubsubLiteCustomEndpoint');
    pulumiAttributionLabelAdditionStrategy = registerOutput<String?>('pulumiAttributionLabelAdditionStrategy');
    recaptchaEnterpriseCustomEndpoint = registerOutput<String?>('recaptchaEnterpriseCustomEndpoint');
    redisCustomEndpoint = registerOutput<String?>('redisCustomEndpoint');
    region = registerOutput<String?>('region');
    requestReason = registerOutput<String?>('requestReason');
    requestTimeout = registerOutput<String?>('requestTimeout');
    resourceManager3CustomEndpoint = registerOutput<String?>('resourceManager3CustomEndpoint');
    resourceManagerCustomEndpoint = registerOutput<String?>('resourceManagerCustomEndpoint');
    resourceManagerV3CustomEndpoint = registerOutput<String?>('resourceManagerV3CustomEndpoint');
    runtimeConfigCustomEndpoint = registerOutput<String?>('runtimeConfigCustomEndpoint');
    runtimeconfigCustomEndpoint = registerOutput<String?>('runtimeconfigCustomEndpoint');
    saasRuntimeCustomEndpoint = registerOutput<String?>('saasRuntimeCustomEndpoint');
    secretManagerCustomEndpoint = registerOutput<String?>('secretManagerCustomEndpoint');
    secretManagerRegionalCustomEndpoint = registerOutput<String?>('secretManagerRegionalCustomEndpoint');
    secureSourceManagerCustomEndpoint = registerOutput<String?>('secureSourceManagerCustomEndpoint');
    securityCenterCustomEndpoint = registerOutput<String?>('securityCenterCustomEndpoint');
    securityCenterManagementCustomEndpoint = registerOutput<String?>('securityCenterManagementCustomEndpoint');
    securityCenterV2CustomEndpoint = registerOutput<String?>('securityCenterV2CustomEndpoint');
    securityScannerCustomEndpoint = registerOutput<String?>('securityScannerCustomEndpoint');
    securitypostureCustomEndpoint = registerOutput<String?>('securitypostureCustomEndpoint');
    serviceDirectoryCustomEndpoint = registerOutput<String?>('serviceDirectoryCustomEndpoint');
    serviceManagementCustomEndpoint = registerOutput<String?>('serviceManagementCustomEndpoint');
    serviceNetworkingCustomEndpoint = registerOutput<String?>('serviceNetworkingCustomEndpoint');
    serviceUsageCustomEndpoint = registerOutput<String?>('serviceUsageCustomEndpoint');
    siteVerificationCustomEndpoint = registerOutput<String?>('siteVerificationCustomEndpoint');
    sourceRepoCustomEndpoint = registerOutput<String?>('sourceRepoCustomEndpoint');
    spannerCustomEndpoint = registerOutput<String?>('spannerCustomEndpoint');
    sqlCustomEndpoint = registerOutput<String?>('sqlCustomEndpoint');
    storageBatchOperationsCustomEndpoint = registerOutput<String?>('storageBatchOperationsCustomEndpoint');
    storageControlCustomEndpoint = registerOutput<String?>('storageControlCustomEndpoint');
    storageCustomEndpoint = registerOutput<String?>('storageCustomEndpoint');
    storageInsightsCustomEndpoint = registerOutput<String?>('storageInsightsCustomEndpoint');
    storageTransferCustomEndpoint = registerOutput<String?>('storageTransferCustomEndpoint');
    tagsCustomEndpoint = registerOutput<String?>('tagsCustomEndpoint');
    tagsLocationCustomEndpoint = registerOutput<String?>('tagsLocationCustomEndpoint');
    tpuV2CustomEndpoint = registerOutput<String?>('tpuV2CustomEndpoint');
    transcoderCustomEndpoint = registerOutput<String?>('transcoderCustomEndpoint');
    universeDomain = registerOutput<String?>('universeDomain');
    vertexAiCustomEndpoint = registerOutput<String?>('vertexAiCustomEndpoint');
    vmwareengineCustomEndpoint = registerOutput<String?>('vmwareengineCustomEndpoint');
    vpcAccessCustomEndpoint = registerOutput<String?>('vpcAccessCustomEndpoint');
    workbenchCustomEndpoint = registerOutput<String?>('workbenchCustomEndpoint');
    workflowsCustomEndpoint = registerOutput<String?>('workflowsCustomEndpoint');
    workstationsCustomEndpoint = registerOutput<String?>('workstationsCustomEndpoint');
    zone = registerOutput<String?>('zone');
  }

  /// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
  Future<ProviderTerraformConfigResult> terraformConfig() async {
    final deployment = pulumi.DeploymentImpl.instance as pulumi.DeploymentImpl;
    final result = await deployment.callWithResult<Map<String, dynamic>>(
      'pulumi:providers:gcp/terraformConfig',
      const <String, dynamic>{},
      self: this,
    );
    return ProviderTerraformConfigResult.fromMap(result);
  }
}
