import 'package:pulumi/pulumi.dart' as pulumi;
import 'provider_args.dart';
import 'provider_terraform_config_result.dart';

/// The provider type for the google-beta package. By default, resources use package-wide configuration
/// settings, however an explicit `Provider` instance may be created and passed during resource
/// construction to achieve fine-grained programmatic control over provider settings. See the
/// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
class ProviderProvider extends pulumi.ProviderResource {
  late final pulumi.Output<String?> accessApprovalCustomEndpoint;
  late final pulumi.Output<String?> accessContextManagerCustomEndpoint;
  late final pulumi.Output<String?> accessToken;
  late final pulumi.Output<String?> activeDirectoryCustomEndpoint;
  late final pulumi.Output<String?> alloydbCustomEndpoint;
  late final pulumi.Output<String?> apiGatewayCustomEndpoint;
  late final pulumi.Output<String?> apigeeCustomEndpoint;
  late final pulumi.Output<String?> apihubCustomEndpoint;
  late final pulumi.Output<String?> apikeysCustomEndpoint;
  late final pulumi.Output<String?> appEngineCustomEndpoint;
  late final pulumi.Output<String?> apphubCustomEndpoint;
  late final pulumi.Output<String?> artifactRegistryCustomEndpoint;
  late final pulumi.Output<String?> assuredWorkloadsCustomEndpoint;
  late final pulumi.Output<String?> backupDrCustomEndpoint;
  late final pulumi.Output<String?> beyondcorpCustomEndpoint;
  late final pulumi.Output<String?> bigQueryCustomEndpoint;
  late final pulumi.Output<String?> biglakeCustomEndpoint;
  late final pulumi.Output<String?> biglakeIcebergCustomEndpoint;
  late final pulumi.Output<String?> bigqueryAnalyticsHubCustomEndpoint;
  late final pulumi.Output<String?> bigqueryConnectionCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDataTransferCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDatapolicyCustomEndpoint;
  late final pulumi.Output<String?> bigqueryDatapolicyv2CustomEndpoint;
  late final pulumi.Output<String?> bigqueryReservationCustomEndpoint;
  late final pulumi.Output<String?> bigtableCustomEndpoint;
  late final pulumi.Output<String?> billingCustomEndpoint;
  late final pulumi.Output<String?> billingProject;
  late final pulumi.Output<String?> binaryAuthorizationCustomEndpoint;
  late final pulumi.Output<String?> blockchainNodeEngineCustomEndpoint;
  late final pulumi.Output<String?> certificateManagerCustomEndpoint;
  late final pulumi.Output<String?> cesCustomEndpoint;
  late final pulumi.Output<String?> chronicleCustomEndpoint;
  late final pulumi.Output<String?> cloudAssetCustomEndpoint;
  late final pulumi.Output<String?> cloudBillingCustomEndpoint;
  late final pulumi.Output<String?> cloudBuildCustomEndpoint;
  late final pulumi.Output<String?> cloudFunctionsCustomEndpoint;
  late final pulumi.Output<String?> cloudIdentityCustomEndpoint;
  late final pulumi.Output<String?> cloudIdsCustomEndpoint;
  late final pulumi.Output<String?> cloudQuotasCustomEndpoint;
  late final pulumi.Output<String?> cloudResourceManagerCustomEndpoint;
  late final pulumi.Output<String?> cloudRunCustomEndpoint;
  late final pulumi.Output<String?> cloudRunV2CustomEndpoint;
  late final pulumi.Output<String?> cloudSchedulerCustomEndpoint;
  late final pulumi.Output<String?> cloudSecurityComplianceCustomEndpoint;
  late final pulumi.Output<String?> cloudTasksCustomEndpoint;
  late final pulumi.Output<String?> cloudbuildv2CustomEndpoint;
  late final pulumi.Output<String?> clouddeployCustomEndpoint;
  late final pulumi.Output<String?> clouddomainsCustomEndpoint;
  late final pulumi.Output<String?> cloudfunctions2CustomEndpoint;
  late final pulumi.Output<String?> colabCustomEndpoint;
  late final pulumi.Output<String?> composerCustomEndpoint;
  late final pulumi.Output<String?> computeCustomEndpoint;
  late final pulumi.Output<String?> contactCenterInsightsCustomEndpoint;
  late final pulumi.Output<String?> containerAnalysisCustomEndpoint;
  late final pulumi.Output<String?> containerAttachedCustomEndpoint;
  late final pulumi.Output<String?> containerAwsCustomEndpoint;
  late final pulumi.Output<String?> containerAzureCustomEndpoint;
  late final pulumi.Output<String?> containerCustomEndpoint;
  late final pulumi.Output<String?> coreBillingCustomEndpoint;
  late final pulumi.Output<String?> credentials;
  late final pulumi.Output<String?> dataCatalogCustomEndpoint;
  late final pulumi.Output<String?> dataFusionCustomEndpoint;
  late final pulumi.Output<String?> dataLossPreventionCustomEndpoint;
  late final pulumi.Output<String?> dataPipelineCustomEndpoint;
  late final pulumi.Output<String?> databaseMigrationServiceCustomEndpoint;
  late final pulumi.Output<String?> dataflowCustomEndpoint;
  late final pulumi.Output<String?> dataformCustomEndpoint;
  late final pulumi.Output<String?> dataplexCustomEndpoint;
  late final pulumi.Output<String?> dataprocCustomEndpoint;
  late final pulumi.Output<String?> dataprocGdcCustomEndpoint;
  late final pulumi.Output<String?> dataprocMetastoreCustomEndpoint;
  late final pulumi.Output<String?> datastreamCustomEndpoint;
  late final pulumi.Output<String?> deploymentManagerCustomEndpoint;
  late final pulumi.Output<String?> developerConnectCustomEndpoint;
  late final pulumi.Output<String?> dialogflowCustomEndpoint;
  late final pulumi.Output<String?> dialogflowCxCustomEndpoint;
  late final pulumi.Output<String?> discoveryEngineCustomEndpoint;
  late final pulumi.Output<String?> dnsCustomEndpoint;
  late final pulumi.Output<String?> documentAiCustomEndpoint;
  late final pulumi.Output<String?> documentAiWarehouseCustomEndpoint;
  late final pulumi.Output<String?> edgecontainerCustomEndpoint;
  late final pulumi.Output<String?> edgenetworkCustomEndpoint;
  late final pulumi.Output<String?> essentialContactsCustomEndpoint;
  late final pulumi.Output<String?> eventarcCustomEndpoint;
  late final pulumi.Output<String?> filestoreCustomEndpoint;
  late final pulumi.Output<String?> firebaseAiLogicCustomEndpoint;
  late final pulumi.Output<String?> firebaseAppCheckCustomEndpoint;
  late final pulumi.Output<String?> firebaseAppHostingCustomEndpoint;
  late final pulumi.Output<String?> firebaseCustomEndpoint;
  late final pulumi.Output<String?> firebaseDataConnectCustomEndpoint;
  late final pulumi.Output<String?> firebaseDatabaseCustomEndpoint;
  late final pulumi.Output<String?> firebaseExtensionsCustomEndpoint;
  late final pulumi.Output<String?> firebaseHostingCustomEndpoint;
  late final pulumi.Output<String?> firebaseStorageCustomEndpoint;
  late final pulumi.Output<String?> firebaserulesCustomEndpoint;
  late final pulumi.Output<String?> firestoreCustomEndpoint;
  late final pulumi.Output<String?> geminiCustomEndpoint;
  late final pulumi.Output<String?> gkeBackupCustomEndpoint;
  late final pulumi.Output<String?> gkeHub2CustomEndpoint;
  late final pulumi.Output<String?> gkeHubCustomEndpoint;
  late final pulumi.Output<String?> gkeonpremCustomEndpoint;
  late final pulumi.Output<String?> googlePartnerName;
  late final pulumi.Output<String?> healthcareCustomEndpoint;
  late final pulumi.Output<String?> iam2CustomEndpoint;
  late final pulumi.Output<String?> iam3CustomEndpoint;
  late final pulumi.Output<String?> iamBetaCustomEndpoint;
  late final pulumi.Output<String?> iamCredentialsCustomEndpoint;
  late final pulumi.Output<String?> iamCustomEndpoint;
  late final pulumi.Output<String?> iamWorkforcePoolCustomEndpoint;
  late final pulumi.Output<String?> iapCustomEndpoint;
  late final pulumi.Output<String?> identityPlatformCustomEndpoint;
  late final pulumi.Output<String?> impersonateServiceAccount;
  late final pulumi.Output<String?> integrationConnectorsCustomEndpoint;
  late final pulumi.Output<String?> integrationsCustomEndpoint;
  late final pulumi.Output<String?> kmsCustomEndpoint;
  late final pulumi.Output<String?> loggingCustomEndpoint;
  late final pulumi.Output<String?> lookerCustomEndpoint;
  late final pulumi.Output<String?> lustreCustomEndpoint;
  late final pulumi.Output<String?> managedKafkaCustomEndpoint;
  late final pulumi.Output<String?> memcacheCustomEndpoint;
  late final pulumi.Output<String?> memorystoreCustomEndpoint;
  late final pulumi.Output<String?> migrationCenterCustomEndpoint;
  late final pulumi.Output<String?> mlEngineCustomEndpoint;
  late final pulumi.Output<String?> modelArmorCustomEndpoint;
  late final pulumi.Output<String?> modelArmorGlobalCustomEndpoint;
  late final pulumi.Output<String?> monitoringCustomEndpoint;
  late final pulumi.Output<String?> netappCustomEndpoint;
  late final pulumi.Output<String?> networkConnectivityCustomEndpoint;
  late final pulumi.Output<String?> networkConnectivityv1CustomEndpoint;
  late final pulumi.Output<String?> networkManagementCustomEndpoint;
  late final pulumi.Output<String?> networkSecurityCustomEndpoint;
  late final pulumi.Output<String?> networkServicesCustomEndpoint;
  late final pulumi.Output<String?> notebooksCustomEndpoint;
  late final pulumi.Output<String?> observabilityCustomEndpoint;
  late final pulumi.Output<String?> oracleDatabaseCustomEndpoint;
  late final pulumi.Output<String?> orgPolicyCustomEndpoint;
  late final pulumi.Output<String?> osConfigCustomEndpoint;
  late final pulumi.Output<String?> osConfigV2CustomEndpoint;
  late final pulumi.Output<String?> osLoginCustomEndpoint;
  late final pulumi.Output<String?> parallelstoreCustomEndpoint;
  late final pulumi.Output<String?> parameterManagerCustomEndpoint;
  late final pulumi.Output<String?> parameterManagerRegionalCustomEndpoint;
  late final pulumi.Output<String?> privatecaCustomEndpoint;
  late final pulumi.Output<String?> privilegedAccessManagerCustomEndpoint;
  late final pulumi.Output<String?> project;
  late final pulumi.Output<String?> publicCaCustomEndpoint;
  late final pulumi.Output<String?> pubsubCustomEndpoint;
  late final pulumi.Output<String?> pubsubLiteCustomEndpoint;
  late final pulumi.Output<String?> pulumiAttributionLabelAdditionStrategy;
  late final pulumi.Output<String?> recaptchaEnterpriseCustomEndpoint;
  late final pulumi.Output<String?> redisCustomEndpoint;
  late final pulumi.Output<String?> region;
  late final pulumi.Output<String?> requestReason;
  late final pulumi.Output<String?> requestTimeout;
  late final pulumi.Output<String?> resourceManager3CustomEndpoint;
  late final pulumi.Output<String?> resourceManagerCustomEndpoint;
  late final pulumi.Output<String?> resourceManagerV3CustomEndpoint;
  late final pulumi.Output<String?> runtimeConfigCustomEndpoint;
  late final pulumi.Output<String?> runtimeconfigCustomEndpoint;
  late final pulumi.Output<String?> saasRuntimeCustomEndpoint;
  late final pulumi.Output<String?> secretManagerCustomEndpoint;
  late final pulumi.Output<String?> secretManagerRegionalCustomEndpoint;
  late final pulumi.Output<String?> secureSourceManagerCustomEndpoint;
  late final pulumi.Output<String?> securityCenterCustomEndpoint;
  late final pulumi.Output<String?> securityCenterManagementCustomEndpoint;
  late final pulumi.Output<String?> securityCenterV2CustomEndpoint;
  late final pulumi.Output<String?> securityScannerCustomEndpoint;
  late final pulumi.Output<String?> securitypostureCustomEndpoint;
  late final pulumi.Output<String?> serviceDirectoryCustomEndpoint;
  late final pulumi.Output<String?> serviceManagementCustomEndpoint;
  late final pulumi.Output<String?> serviceNetworkingCustomEndpoint;
  late final pulumi.Output<String?> serviceUsageCustomEndpoint;
  late final pulumi.Output<String?> siteVerificationCustomEndpoint;
  late final pulumi.Output<String?> sourceRepoCustomEndpoint;
  late final pulumi.Output<String?> spannerCustomEndpoint;
  late final pulumi.Output<String?> sqlCustomEndpoint;
  late final pulumi.Output<String?> storageBatchOperationsCustomEndpoint;
  late final pulumi.Output<String?> storageControlCustomEndpoint;
  late final pulumi.Output<String?> storageCustomEndpoint;
  late final pulumi.Output<String?> storageInsightsCustomEndpoint;
  late final pulumi.Output<String?> storageTransferCustomEndpoint;
  late final pulumi.Output<String?> tagsCustomEndpoint;
  late final pulumi.Output<String?> tagsLocationCustomEndpoint;
  late final pulumi.Output<String?> tpuV2CustomEndpoint;
  late final pulumi.Output<String?> transcoderCustomEndpoint;
  late final pulumi.Output<String?> universeDomain;
  late final pulumi.Output<String?> vertexAiCustomEndpoint;
  late final pulumi.Output<String?> vmwareengineCustomEndpoint;
  late final pulumi.Output<String?> vpcAccessCustomEndpoint;
  late final pulumi.Output<String?> workbenchCustomEndpoint;
  late final pulumi.Output<String?> workflowsCustomEndpoint;
  late final pulumi.Output<String?> workstationsCustomEndpoint;
  late final pulumi.Output<String?> zone;

  /// Creates a new [ProviderProvider].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [ProviderProvider]. {@macro pulumi_providers_provider_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  ProviderProvider(
    String name, {
    ProviderArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'gcp',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.accessApprovalCustomEndpoint = registerOutput<String?>('accessApprovalCustomEndpoint');
    this.accessContextManagerCustomEndpoint = registerOutput<String?>('accessContextManagerCustomEndpoint');
    this.accessToken = registerOutput<String?>('accessToken');
    this.activeDirectoryCustomEndpoint = registerOutput<String?>('activeDirectoryCustomEndpoint');
    this.alloydbCustomEndpoint = registerOutput<String?>('alloydbCustomEndpoint');
    this.apiGatewayCustomEndpoint = registerOutput<String?>('apiGatewayCustomEndpoint');
    this.apigeeCustomEndpoint = registerOutput<String?>('apigeeCustomEndpoint');
    this.apihubCustomEndpoint = registerOutput<String?>('apihubCustomEndpoint');
    this.apikeysCustomEndpoint = registerOutput<String?>('apikeysCustomEndpoint');
    this.appEngineCustomEndpoint = registerOutput<String?>('appEngineCustomEndpoint');
    this.apphubCustomEndpoint = registerOutput<String?>('apphubCustomEndpoint');
    this.artifactRegistryCustomEndpoint = registerOutput<String?>('artifactRegistryCustomEndpoint');
    this.assuredWorkloadsCustomEndpoint = registerOutput<String?>('assuredWorkloadsCustomEndpoint');
    this.backupDrCustomEndpoint = registerOutput<String?>('backupDrCustomEndpoint');
    this.beyondcorpCustomEndpoint = registerOutput<String?>('beyondcorpCustomEndpoint');
    this.bigQueryCustomEndpoint = registerOutput<String?>('bigQueryCustomEndpoint');
    this.biglakeCustomEndpoint = registerOutput<String?>('biglakeCustomEndpoint');
    this.biglakeIcebergCustomEndpoint = registerOutput<String?>('biglakeIcebergCustomEndpoint');
    this.bigqueryAnalyticsHubCustomEndpoint = registerOutput<String?>('bigqueryAnalyticsHubCustomEndpoint');
    this.bigqueryConnectionCustomEndpoint = registerOutput<String?>('bigqueryConnectionCustomEndpoint');
    this.bigqueryDataTransferCustomEndpoint = registerOutput<String?>('bigqueryDataTransferCustomEndpoint');
    this.bigqueryDatapolicyCustomEndpoint = registerOutput<String?>('bigqueryDatapolicyCustomEndpoint');
    this.bigqueryDatapolicyv2CustomEndpoint = registerOutput<String?>('bigqueryDatapolicyv2CustomEndpoint');
    this.bigqueryReservationCustomEndpoint = registerOutput<String?>('bigqueryReservationCustomEndpoint');
    this.bigtableCustomEndpoint = registerOutput<String?>('bigtableCustomEndpoint');
    this.billingCustomEndpoint = registerOutput<String?>('billingCustomEndpoint');
    this.billingProject = registerOutput<String?>('billingProject');
    this.binaryAuthorizationCustomEndpoint = registerOutput<String?>('binaryAuthorizationCustomEndpoint');
    this.blockchainNodeEngineCustomEndpoint = registerOutput<String?>('blockchainNodeEngineCustomEndpoint');
    this.certificateManagerCustomEndpoint = registerOutput<String?>('certificateManagerCustomEndpoint');
    this.cesCustomEndpoint = registerOutput<String?>('cesCustomEndpoint');
    this.chronicleCustomEndpoint = registerOutput<String?>('chronicleCustomEndpoint');
    this.cloudAssetCustomEndpoint = registerOutput<String?>('cloudAssetCustomEndpoint');
    this.cloudBillingCustomEndpoint = registerOutput<String?>('cloudBillingCustomEndpoint');
    this.cloudBuildCustomEndpoint = registerOutput<String?>('cloudBuildCustomEndpoint');
    this.cloudFunctionsCustomEndpoint = registerOutput<String?>('cloudFunctionsCustomEndpoint');
    this.cloudIdentityCustomEndpoint = registerOutput<String?>('cloudIdentityCustomEndpoint');
    this.cloudIdsCustomEndpoint = registerOutput<String?>('cloudIdsCustomEndpoint');
    this.cloudQuotasCustomEndpoint = registerOutput<String?>('cloudQuotasCustomEndpoint');
    this.cloudResourceManagerCustomEndpoint = registerOutput<String?>('cloudResourceManagerCustomEndpoint');
    this.cloudRunCustomEndpoint = registerOutput<String?>('cloudRunCustomEndpoint');
    this.cloudRunV2CustomEndpoint = registerOutput<String?>('cloudRunV2CustomEndpoint');
    this.cloudSchedulerCustomEndpoint = registerOutput<String?>('cloudSchedulerCustomEndpoint');
    this.cloudSecurityComplianceCustomEndpoint = registerOutput<String?>('cloudSecurityComplianceCustomEndpoint');
    this.cloudTasksCustomEndpoint = registerOutput<String?>('cloudTasksCustomEndpoint');
    this.cloudbuildv2CustomEndpoint = registerOutput<String?>('cloudbuildv2CustomEndpoint');
    this.clouddeployCustomEndpoint = registerOutput<String?>('clouddeployCustomEndpoint');
    this.clouddomainsCustomEndpoint = registerOutput<String?>('clouddomainsCustomEndpoint');
    this.cloudfunctions2CustomEndpoint = registerOutput<String?>('cloudfunctions2CustomEndpoint');
    this.colabCustomEndpoint = registerOutput<String?>('colabCustomEndpoint');
    this.composerCustomEndpoint = registerOutput<String?>('composerCustomEndpoint');
    this.computeCustomEndpoint = registerOutput<String?>('computeCustomEndpoint');
    this.contactCenterInsightsCustomEndpoint = registerOutput<String?>('contactCenterInsightsCustomEndpoint');
    this.containerAnalysisCustomEndpoint = registerOutput<String?>('containerAnalysisCustomEndpoint');
    this.containerAttachedCustomEndpoint = registerOutput<String?>('containerAttachedCustomEndpoint');
    this.containerAwsCustomEndpoint = registerOutput<String?>('containerAwsCustomEndpoint');
    this.containerAzureCustomEndpoint = registerOutput<String?>('containerAzureCustomEndpoint');
    this.containerCustomEndpoint = registerOutput<String?>('containerCustomEndpoint');
    this.coreBillingCustomEndpoint = registerOutput<String?>('coreBillingCustomEndpoint');
    this.credentials = registerOutput<String?>('credentials');
    this.dataCatalogCustomEndpoint = registerOutput<String?>('dataCatalogCustomEndpoint');
    this.dataFusionCustomEndpoint = registerOutput<String?>('dataFusionCustomEndpoint');
    this.dataLossPreventionCustomEndpoint = registerOutput<String?>('dataLossPreventionCustomEndpoint');
    this.dataPipelineCustomEndpoint = registerOutput<String?>('dataPipelineCustomEndpoint');
    this.databaseMigrationServiceCustomEndpoint = registerOutput<String?>('databaseMigrationServiceCustomEndpoint');
    this.dataflowCustomEndpoint = registerOutput<String?>('dataflowCustomEndpoint');
    this.dataformCustomEndpoint = registerOutput<String?>('dataformCustomEndpoint');
    this.dataplexCustomEndpoint = registerOutput<String?>('dataplexCustomEndpoint');
    this.dataprocCustomEndpoint = registerOutput<String?>('dataprocCustomEndpoint');
    this.dataprocGdcCustomEndpoint = registerOutput<String?>('dataprocGdcCustomEndpoint');
    this.dataprocMetastoreCustomEndpoint = registerOutput<String?>('dataprocMetastoreCustomEndpoint');
    this.datastreamCustomEndpoint = registerOutput<String?>('datastreamCustomEndpoint');
    this.deploymentManagerCustomEndpoint = registerOutput<String?>('deploymentManagerCustomEndpoint');
    this.developerConnectCustomEndpoint = registerOutput<String?>('developerConnectCustomEndpoint');
    this.dialogflowCustomEndpoint = registerOutput<String?>('dialogflowCustomEndpoint');
    this.dialogflowCxCustomEndpoint = registerOutput<String?>('dialogflowCxCustomEndpoint');
    this.discoveryEngineCustomEndpoint = registerOutput<String?>('discoveryEngineCustomEndpoint');
    this.dnsCustomEndpoint = registerOutput<String?>('dnsCustomEndpoint');
    this.documentAiCustomEndpoint = registerOutput<String?>('documentAiCustomEndpoint');
    this.documentAiWarehouseCustomEndpoint = registerOutput<String?>('documentAiWarehouseCustomEndpoint');
    this.edgecontainerCustomEndpoint = registerOutput<String?>('edgecontainerCustomEndpoint');
    this.edgenetworkCustomEndpoint = registerOutput<String?>('edgenetworkCustomEndpoint');
    this.essentialContactsCustomEndpoint = registerOutput<String?>('essentialContactsCustomEndpoint');
    this.eventarcCustomEndpoint = registerOutput<String?>('eventarcCustomEndpoint');
    this.filestoreCustomEndpoint = registerOutput<String?>('filestoreCustomEndpoint');
    this.firebaseAiLogicCustomEndpoint = registerOutput<String?>('firebaseAiLogicCustomEndpoint');
    this.firebaseAppCheckCustomEndpoint = registerOutput<String?>('firebaseAppCheckCustomEndpoint');
    this.firebaseAppHostingCustomEndpoint = registerOutput<String?>('firebaseAppHostingCustomEndpoint');
    this.firebaseCustomEndpoint = registerOutput<String?>('firebaseCustomEndpoint');
    this.firebaseDataConnectCustomEndpoint = registerOutput<String?>('firebaseDataConnectCustomEndpoint');
    this.firebaseDatabaseCustomEndpoint = registerOutput<String?>('firebaseDatabaseCustomEndpoint');
    this.firebaseExtensionsCustomEndpoint = registerOutput<String?>('firebaseExtensionsCustomEndpoint');
    this.firebaseHostingCustomEndpoint = registerOutput<String?>('firebaseHostingCustomEndpoint');
    this.firebaseStorageCustomEndpoint = registerOutput<String?>('firebaseStorageCustomEndpoint');
    this.firebaserulesCustomEndpoint = registerOutput<String?>('firebaserulesCustomEndpoint');
    this.firestoreCustomEndpoint = registerOutput<String?>('firestoreCustomEndpoint');
    this.geminiCustomEndpoint = registerOutput<String?>('geminiCustomEndpoint');
    this.gkeBackupCustomEndpoint = registerOutput<String?>('gkeBackupCustomEndpoint');
    this.gkeHub2CustomEndpoint = registerOutput<String?>('gkeHub2CustomEndpoint');
    this.gkeHubCustomEndpoint = registerOutput<String?>('gkeHubCustomEndpoint');
    this.gkeonpremCustomEndpoint = registerOutput<String?>('gkeonpremCustomEndpoint');
    this.googlePartnerName = registerOutput<String?>('googlePartnerName');
    this.healthcareCustomEndpoint = registerOutput<String?>('healthcareCustomEndpoint');
    this.iam2CustomEndpoint = registerOutput<String?>('iam2CustomEndpoint');
    this.iam3CustomEndpoint = registerOutput<String?>('iam3CustomEndpoint');
    this.iamBetaCustomEndpoint = registerOutput<String?>('iamBetaCustomEndpoint');
    this.iamCredentialsCustomEndpoint = registerOutput<String?>('iamCredentialsCustomEndpoint');
    this.iamCustomEndpoint = registerOutput<String?>('iamCustomEndpoint');
    this.iamWorkforcePoolCustomEndpoint = registerOutput<String?>('iamWorkforcePoolCustomEndpoint');
    this.iapCustomEndpoint = registerOutput<String?>('iapCustomEndpoint');
    this.identityPlatformCustomEndpoint = registerOutput<String?>('identityPlatformCustomEndpoint');
    this.impersonateServiceAccount = registerOutput<String?>('impersonateServiceAccount');
    this.integrationConnectorsCustomEndpoint = registerOutput<String?>('integrationConnectorsCustomEndpoint');
    this.integrationsCustomEndpoint = registerOutput<String?>('integrationsCustomEndpoint');
    this.kmsCustomEndpoint = registerOutput<String?>('kmsCustomEndpoint');
    this.loggingCustomEndpoint = registerOutput<String?>('loggingCustomEndpoint');
    this.lookerCustomEndpoint = registerOutput<String?>('lookerCustomEndpoint');
    this.lustreCustomEndpoint = registerOutput<String?>('lustreCustomEndpoint');
    this.managedKafkaCustomEndpoint = registerOutput<String?>('managedKafkaCustomEndpoint');
    this.memcacheCustomEndpoint = registerOutput<String?>('memcacheCustomEndpoint');
    this.memorystoreCustomEndpoint = registerOutput<String?>('memorystoreCustomEndpoint');
    this.migrationCenterCustomEndpoint = registerOutput<String?>('migrationCenterCustomEndpoint');
    this.mlEngineCustomEndpoint = registerOutput<String?>('mlEngineCustomEndpoint');
    this.modelArmorCustomEndpoint = registerOutput<String?>('modelArmorCustomEndpoint');
    this.modelArmorGlobalCustomEndpoint = registerOutput<String?>('modelArmorGlobalCustomEndpoint');
    this.monitoringCustomEndpoint = registerOutput<String?>('monitoringCustomEndpoint');
    this.netappCustomEndpoint = registerOutput<String?>('netappCustomEndpoint');
    this.networkConnectivityCustomEndpoint = registerOutput<String?>('networkConnectivityCustomEndpoint');
    this.networkConnectivityv1CustomEndpoint = registerOutput<String?>('networkConnectivityv1CustomEndpoint');
    this.networkManagementCustomEndpoint = registerOutput<String?>('networkManagementCustomEndpoint');
    this.networkSecurityCustomEndpoint = registerOutput<String?>('networkSecurityCustomEndpoint');
    this.networkServicesCustomEndpoint = registerOutput<String?>('networkServicesCustomEndpoint');
    this.notebooksCustomEndpoint = registerOutput<String?>('notebooksCustomEndpoint');
    this.observabilityCustomEndpoint = registerOutput<String?>('observabilityCustomEndpoint');
    this.oracleDatabaseCustomEndpoint = registerOutput<String?>('oracleDatabaseCustomEndpoint');
    this.orgPolicyCustomEndpoint = registerOutput<String?>('orgPolicyCustomEndpoint');
    this.osConfigCustomEndpoint = registerOutput<String?>('osConfigCustomEndpoint');
    this.osConfigV2CustomEndpoint = registerOutput<String?>('osConfigV2CustomEndpoint');
    this.osLoginCustomEndpoint = registerOutput<String?>('osLoginCustomEndpoint');
    this.parallelstoreCustomEndpoint = registerOutput<String?>('parallelstoreCustomEndpoint');
    this.parameterManagerCustomEndpoint = registerOutput<String?>('parameterManagerCustomEndpoint');
    this.parameterManagerRegionalCustomEndpoint = registerOutput<String?>('parameterManagerRegionalCustomEndpoint');
    this.privatecaCustomEndpoint = registerOutput<String?>('privatecaCustomEndpoint');
    this.privilegedAccessManagerCustomEndpoint = registerOutput<String?>('privilegedAccessManagerCustomEndpoint');
    this.project = registerOutput<String?>('project');
    this.publicCaCustomEndpoint = registerOutput<String?>('publicCaCustomEndpoint');
    this.pubsubCustomEndpoint = registerOutput<String?>('pubsubCustomEndpoint');
    this.pubsubLiteCustomEndpoint = registerOutput<String?>('pubsubLiteCustomEndpoint');
    this.pulumiAttributionLabelAdditionStrategy = registerOutput<String?>('pulumiAttributionLabelAdditionStrategy');
    this.recaptchaEnterpriseCustomEndpoint = registerOutput<String?>('recaptchaEnterpriseCustomEndpoint');
    this.redisCustomEndpoint = registerOutput<String?>('redisCustomEndpoint');
    this.region = registerOutput<String?>('region');
    this.requestReason = registerOutput<String?>('requestReason');
    this.requestTimeout = registerOutput<String?>('requestTimeout');
    this.resourceManager3CustomEndpoint = registerOutput<String?>('resourceManager3CustomEndpoint');
    this.resourceManagerCustomEndpoint = registerOutput<String?>('resourceManagerCustomEndpoint');
    this.resourceManagerV3CustomEndpoint = registerOutput<String?>('resourceManagerV3CustomEndpoint');
    this.runtimeConfigCustomEndpoint = registerOutput<String?>('runtimeConfigCustomEndpoint');
    this.runtimeconfigCustomEndpoint = registerOutput<String?>('runtimeconfigCustomEndpoint');
    this.saasRuntimeCustomEndpoint = registerOutput<String?>('saasRuntimeCustomEndpoint');
    this.secretManagerCustomEndpoint = registerOutput<String?>('secretManagerCustomEndpoint');
    this.secretManagerRegionalCustomEndpoint = registerOutput<String?>('secretManagerRegionalCustomEndpoint');
    this.secureSourceManagerCustomEndpoint = registerOutput<String?>('secureSourceManagerCustomEndpoint');
    this.securityCenterCustomEndpoint = registerOutput<String?>('securityCenterCustomEndpoint');
    this.securityCenterManagementCustomEndpoint = registerOutput<String?>('securityCenterManagementCustomEndpoint');
    this.securityCenterV2CustomEndpoint = registerOutput<String?>('securityCenterV2CustomEndpoint');
    this.securityScannerCustomEndpoint = registerOutput<String?>('securityScannerCustomEndpoint');
    this.securitypostureCustomEndpoint = registerOutput<String?>('securitypostureCustomEndpoint');
    this.serviceDirectoryCustomEndpoint = registerOutput<String?>('serviceDirectoryCustomEndpoint');
    this.serviceManagementCustomEndpoint = registerOutput<String?>('serviceManagementCustomEndpoint');
    this.serviceNetworkingCustomEndpoint = registerOutput<String?>('serviceNetworkingCustomEndpoint');
    this.serviceUsageCustomEndpoint = registerOutput<String?>('serviceUsageCustomEndpoint');
    this.siteVerificationCustomEndpoint = registerOutput<String?>('siteVerificationCustomEndpoint');
    this.sourceRepoCustomEndpoint = registerOutput<String?>('sourceRepoCustomEndpoint');
    this.spannerCustomEndpoint = registerOutput<String?>('spannerCustomEndpoint');
    this.sqlCustomEndpoint = registerOutput<String?>('sqlCustomEndpoint');
    this.storageBatchOperationsCustomEndpoint = registerOutput<String?>('storageBatchOperationsCustomEndpoint');
    this.storageControlCustomEndpoint = registerOutput<String?>('storageControlCustomEndpoint');
    this.storageCustomEndpoint = registerOutput<String?>('storageCustomEndpoint');
    this.storageInsightsCustomEndpoint = registerOutput<String?>('storageInsightsCustomEndpoint');
    this.storageTransferCustomEndpoint = registerOutput<String?>('storageTransferCustomEndpoint');
    this.tagsCustomEndpoint = registerOutput<String?>('tagsCustomEndpoint');
    this.tagsLocationCustomEndpoint = registerOutput<String?>('tagsLocationCustomEndpoint');
    this.tpuV2CustomEndpoint = registerOutput<String?>('tpuV2CustomEndpoint');
    this.transcoderCustomEndpoint = registerOutput<String?>('transcoderCustomEndpoint');
    this.universeDomain = registerOutput<String?>('universeDomain');
    this.vertexAiCustomEndpoint = registerOutput<String?>('vertexAiCustomEndpoint');
    this.vmwareengineCustomEndpoint = registerOutput<String?>('vmwareengineCustomEndpoint');
    this.vpcAccessCustomEndpoint = registerOutput<String?>('vpcAccessCustomEndpoint');
    this.workbenchCustomEndpoint = registerOutput<String?>('workbenchCustomEndpoint');
    this.workflowsCustomEndpoint = registerOutput<String?>('workflowsCustomEndpoint');
    this.workstationsCustomEndpoint = registerOutput<String?>('workstationsCustomEndpoint');
    this.zone = registerOutput<String?>('zone');
  }

  /// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
  Future<ProviderTerraformConfigResult> terraformConfig() async {
    final deployment = pulumi.Deployment.instance;
    final result = await deployment.callWithResult<Map<String, dynamic>>(
      'pulumi:providers:gcp/terraformConfig',
      const <String, dynamic>{},
      self: this,
    );
    return ProviderTerraformConfigResult.fromMap(result);
  }
}
