library module_dataloss_prevention_discovery_config_target_big_query_target_cadence_inspect_template_modified_cadence;

export 'prevention_discovery_config_target_big_query_target_cadence_inspect_template_modified_cadence.dart';
