name: aws_dart_wordpress_fargate_rds
description: Pulumi AWS WordPress Fargate + RDS example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 3.0.0
  pulumi_aws: ^7.20.0
  pulumi_random: 4.19.1

dev_dependencies:
  lints: ^6.1.0
