import 'package:pulumi/pulumi.dart';
import 'app_connector_args.dart';
import 'google_cloud_beyondcorp_appconnectors_v1_app_connector_principal_info_response.dart';
import 'google_cloud_beyondcorp_appconnectors_v1_resource_info_response.dart';

/// Creates a new AppConnector in a given project and location.
class AppConnector extends CustomResource {
  /// Optional. User-settable AppConnector resource ID. * Must start with a letter. * Must contain between 4-63 characters from `/a-z-/`. * Must end with a number or a letter.
  late final Output<String?> appConnectorId;

  /// Timestamp when the resource was created.
  late final Output<String> createTime;

  /// Optional. An arbitrary user-provided name for the AppConnector. Cannot exceed 64 characters.
  late final Output<String> displayName;

  /// Optional. Resource labels to represent user provided metadata.
  late final Output<Map<String, String>> labels;
  late final Output<String> location;

  /// Unique resource name of the AppConnector. The name is ignored when creating a AppConnector.
  late final Output<String> name;

  /// Principal information about the Identity of the AppConnector.
  late final Output<
          GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoResponse>
      principalInfo;
  late final Output<String> project;

  /// Optional. An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed. The server will guarantee that for at least 60 minutes since the first request. For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments. The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).
  late final Output<String?> requestId;

  /// Optional. Resource info of the connector.
  late final Output<GoogleCloudBeyondcorpAppconnectorsV1ResourceInfoResponse>
      resourceInfo;

  /// The current state of the AppConnector.
  late final Output<String> state;

  /// A unique identifier for the instance generated by the system.
  late final Output<String> uid;

  /// Timestamp when the resource was last modified.
  late final Output<String> updateTime;

  AppConnector(
    String name, {
    AppConnectorArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:beyondcorp/v1:AppConnector',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.appConnectorId = registerOutput<String?>('appConnectorId');
    this.createTime = registerOutput<String>('createTime');
    this.displayName = registerOutput<String>('displayName');
    this.labels = registerOutput<Map<String, String>>('labels');
    this.location = registerOutput<String>('location');
    this.name = registerOutput<String>('name');
    this.principalInfo = registerOutput<
            GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoResponse>(
        'principalInfo');
    this.project = registerOutput<String>('project');
    this.requestId = registerOutput<String?>('requestId');
    this.resourceInfo = registerOutput<
            GoogleCloudBeyondcorpAppconnectorsV1ResourceInfoResponse>(
        'resourceInfo');
    this.state = registerOutput<String>('state');
    this.uid = registerOutput<String>('uid');
    this.updateTime = registerOutput<String>('updateTime');
  }
}
