library module_datacatalog_get_policy_tag_iam_policy;

export 'get_policy_tag_iam_policy/get_policy_tag_iam_policy.dart';
export 'get_policy_tag_iam_policy/get_policy_tag_iam_policy_args.dart';
export 'get_policy_tag_iam_policy/get_policy_tag_iam_policy_result.dart';
