library module_firebase_hosting_custom_domain_cert_verification_dns_discovered_record;

export 'hosting_custom_domain_cert_verification_dns_discovered_record/hosting_custom_domain_cert_verification_dns_discovered_record.dart';
