// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'app_campaign_hook.dart';
import 'app_limits.dart';
import 'app_quiet_time.dart';

/// {@template pulumi_pinpoint_app_app_args_doc}
/// The set of arguments for App.
/// {@endtemplate}
/// {@macro pulumi_pinpoint_app_app_args_doc}
class AppArgs {
  /// Settings for invoking an AWS Lambda function that customizes a segment for a campaign. See below.
  final pulumi.Input<AppCampaignHook?>? campaignHook;
  /// Default campaign limits for the app. These limits apply to each campaign for the app, unless the campaign overrides the default with limits of its own. See below.
  final pulumi.Input<AppLimits?>? limits;
  /// Application name. By default generated by Pulumi.
  final pulumi.Input<String?>? name;
  /// Name of the End User Messaging application. Conflicts with `name`.
  final pulumi.Input<String?>? namePrefix;
  /// Default quiet time for the app. Each campaign for this app sends no messages during this time unless the campaign overrides the default with a quiet time of its own. See below.
  final pulumi.Input<AppQuietTime?>? quietTime;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String?>? region;
  /// Key-value map of resource tags. If configured with a provider `defaultTags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  final pulumi.Input<Map<String, String>?>? tags;

  /// Creates a new [AppArgs].
  /// [campaignHook] Settings for invoking an AWS Lambda function that customizes a segment for a campaign. See below.
  /// [limits] Default campaign limits for the app. These limits apply to each campaign for the app, unless the campaign overrides the default with limits of its own. See below.
  /// [name] Application name. By default generated by Pulumi.
  /// [namePrefix] Name of the End User Messaging application. Conflicts with `name`.
  /// [quietTime] Default quiet time for the app. Each campaign for this app sends no messages during this time unless the campaign overrides the default with a quiet time of its own. See below.
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  /// [tags] Key-value map of resource tags. If configured with a provider `defaultTags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  const AppArgs({
    this.campaignHook,
    this.limits,
    this.name,
    this.namePrefix,
    this.quietTime,
    this.region,
    this.tags,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'campaignHook': ?pulumi.Input.mapOptionalInputValue<AppCampaignHook, Map<String, dynamic>>(campaignHook, (value) => value.toMap()),
      'limits': ?pulumi.Input.mapOptionalInputValue<AppLimits, Map<String, dynamic>>(limits, (value) => value.toMap()),
      'name': ?name,
      'namePrefix': ?namePrefix,
      'quietTime': ?pulumi.Input.mapOptionalInputValue<AppQuietTime, Map<String, dynamic>>(quietTime, (value) => value.toMap()),
      'region': ?region,
      'tags': ?tags,
    };
  }

  factory AppArgs.fromMap(Map<String, dynamic> map) {
    return AppArgs(
      campaignHook: (() { final guardedValue = map['campaignHook']; if (guardedValue == null) return null; return pulumi.Input.fromValue(AppCampaignHook.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      limits: (() { final guardedValue = map['limits']; if (guardedValue == null) return null; return pulumi.Input.fromValue(AppLimits.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      name: (() { final guardedValue = map['name']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      namePrefix: (() { final guardedValue = map['namePrefix']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      quietTime: (() { final guardedValue = map['quietTime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(AppQuietTime.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      region: (() { final guardedValue = map['region']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      tags: (() { final guardedValue = map['tags']; if (guardedValue == null) return null; return pulumi.Input.fromValue((guardedValue as Map).cast<String, String>()); })(),
    );
  }
}
