// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_containeranalysis_note_iam_policy_note_iam_policy_args_doc}
/// The set of arguments for NoteIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_containeranalysis_note_iam_policy_note_iam_policy_args_doc}
class NoteIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> note;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Creates a new [NoteIamPolicyArgs].
  /// [note] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  const NoteIamPolicyArgs({
    required this.note,
    required this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'note': note,
      'policyData': policyData,
      'project': ?project,
    };
  }

  factory NoteIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return NoteIamPolicyArgs(
      note: pulumi.Input.fromValue(map['note'] as String),
      policyData: pulumi.Input.fromValue(map['policyData'] as String),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}

