name: pulumi_newrelic
description: A Pulumi package for creating and managing New Relic resources.
version: 5.61.2
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-newrelic
topics:
    - pulumi
    - new-relic
publish_to: none
environment:
    sdk: ^3.10.0
resolution: workspace
dependencies:
    pulumi:
        path: /home/kingwill101/code/dart_packages/pulumi-dart/pulumi-dart
dev_dependencies:
    lints: ^5.0.0
