// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'pull_request_filter.dart';
import 'push_filter.dart';

/// BitbucketServerTriggerConfig describes the configuration of a trigger that creates a build whenever a Bitbucket Server event is received.
class BitbucketServerTriggerConfig {
  /// The Bitbucket server config resource that this trigger config maps to.
  final pulumi.Input<String> bitbucketServerConfigResource;
  /// Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
  final pulumi.Input<String> projectKey;
  /// Filter to match changes in pull requests.
  final pulumi.Input<PullRequestFilter>? pullRequest;
  /// Filter to match changes in refs like branches, tags.
  final pulumi.Input<PushFilter>? push;
  /// Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL. For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
  final pulumi.Input<String> repoSlug;

  /// Creates a new [BitbucketServerTriggerConfig].
  /// [bitbucketServerConfigResource] The Bitbucket server config resource that this trigger config maps to.
  /// [projectKey] Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
  /// [pullRequest] Filter to match changes in pull requests.
  /// [push] Filter to match changes in refs like branches, tags.
  /// [repoSlug] Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL. For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
  BitbucketServerTriggerConfig({
    required this.bitbucketServerConfigResource,
    required this.projectKey,
    this.pullRequest,
    this.push,
    required this.repoSlug,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'bitbucketServerConfigResource': bitbucketServerConfigResource,
      'projectKey': projectKey,
      'pullRequest': ?pulumi.Input.mapOptionalInputValue<PullRequestFilter, Map<String, dynamic>>(pullRequest, (value) => value.toMap()),
      'push': ?pulumi.Input.mapOptionalInputValue<PushFilter, Map<String, dynamic>>(push, (value) => value.toMap()),
      'repoSlug': repoSlug,
    };
  }

  factory BitbucketServerTriggerConfig.fromMap(Map<String, dynamic> map) {
    return BitbucketServerTriggerConfig(
      bitbucketServerConfigResource: pulumi.Input.fromValue(map['bitbucketServerConfigResource'] as String),
      projectKey: pulumi.Input.fromValue(map['projectKey'] as String),
      pullRequest: (() { final guardedValue = map['pullRequest']; if (guardedValue == null) return null; return pulumi.Input.fromValue(PullRequestFilter.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      push: (() { final guardedValue = map['push']; if (guardedValue == null) return null; return pulumi.Input.fromValue(PushFilter.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      repoSlug: pulumi.Input.fromValue(map['repoSlug'] as String),
    );
  }
}

