library module_timestreamwrite_table_magnetic_store_write_properties_magnetic_store_rejected_data_location_s3_configuration;

export 'table_magnetic_store_write_properties_magnetic_store_rejected_data_location_s3_configuration.dart';
