library module_dataproc_workflow_template_placement_managed_cluster_config_master_config_managed_group_config;

export 'workflow_template_placement_managed_cluster_config_master_config_managed_group_config.dart';
