name: aws_dart_lambda_efs
description: Pulumi AWS Lambda + EFS example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
  pulumi_aws: ^7.20.0
  pulumi_aws_apigateway: any
  pulumi_awsx: any

dev_dependencies:
  lints: ^6.1.0
