library module_dataloss_prevention_job_trigger_inspect_job_storage_config_big_query_options_table_reference;

export 'prevention_job_trigger_inspect_job_storage_config_big_query_options_table_reference.dart';
