// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'tool_client_function.dart';
import 'tool_data_store_tool.dart';
import 'tool_google_search_tool.dart';
import 'tool_open_api_tool.dart';
import 'tool_python_function.dart';
import 'tool_system_tool.dart';

/// Input properties used for looking up and filtering Tool resources.
class ToolState {
  /// Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  final pulumi.Input<String>? app;
  /// Represents a client-side function that the agent can invoke. When the
  /// tool is chosen by the agent, control is handed off to the client.
  /// The client is responsible for executing the function and returning the result
  /// as a ToolResponse to continue the interaction with the agent.
  /// Structure is documented below.
  final pulumi.Input<ToolClientFunction>? clientFunction;
  /// Timestamp when the tool was created.
  final pulumi.Input<String>? createTime;
  /// Tool to retrieve from Vertex AI Search datastore or engine for grounding.
  /// Accepts either a datastore or an engine, but not both.
  /// See Vertex AI Search:
  /// https://cloud.google.com/generative-ai-app-builder/docs/enterprise-search-introduction.
  /// Structure is documented below.
  final pulumi.Input<ToolDataStoreTool>? dataStoreTool;
  /// (Output)
  /// The name of the allowed custom CA certificates. This
  /// can be used to disambiguate the custom CA certificates.
  final pulumi.Input<String>? displayName;
  /// Etag used to ensure the object hasn't changed during a read-modify-write
  /// operation. If the etag is empty, the update will overwrite any concurrent
  /// changes.
  final pulumi.Input<String>? etag;
  /// Possible values:
  /// SYNCHRONOUS
  /// ASYNCHRONOUS
  final pulumi.Input<String>? executionType;
  /// If the tool is generated by the LLM assistant, this field contains a
  /// descriptive summary of the generation.
  final pulumi.Input<String>? generatedSummary;
  /// Represents a tool to perform Google web searches for grounding.
  /// See
  /// https://cloud.google.com/vertex-ai/generative-ai/docs/grounding/grounding-with-google-search.
  /// Structure is documented below.
  final pulumi.Input<ToolGoogleSearchTool>? googleSearchTool;
  /// Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  final pulumi.Input<String>? location;
  /// (Output)
  /// The name of the system tool.
  final pulumi.Input<String>? name;
  /// A remote API tool defined by an OpenAPI schema.
  /// Structure is documented below.
  final pulumi.Input<List<ToolOpenApiTool>>? openApiTools;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the provider project is used.
  final pulumi.Input<String>? project;
  /// A Python function tool.
  /// Structure is documented below.
  final pulumi.Input<ToolPythonFunction>? pythonFunction;
  /// The system tool.
  /// Structure is documented below.
  final pulumi.Input<List<ToolSystemTool>>? systemTools;
  /// The ID to use for the tool, which will become the final component of
  /// the tool's resource name. If not provided, a unique ID will be
  /// automatically assigned for the tool.
  final pulumi.Input<String>? toolId;
  /// Timestamp when the tool was last updated.
  final pulumi.Input<String>? updateTime;

  /// Creates a new [ToolState].
  /// [app] Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  /// [clientFunction] Represents a client-side function that the agent can invoke. When the
  /// [createTime] Timestamp when the tool was created.
  /// [dataStoreTool] Tool to retrieve from Vertex AI Search datastore or engine for grounding.
  /// [displayName] (Output)
  /// [etag] Etag used to ensure the object hasn't changed during a read-modify-write
  /// [executionType] Possible values:
  /// [generatedSummary] If the tool is generated by the LLM assistant, this field contains a
  /// [googleSearchTool] Represents a tool to perform Google web searches for grounding.
  /// [location] Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  /// [name] (Output)
  /// [openApiTools] A remote API tool defined by an OpenAPI schema.
  /// [project] The ID of the project in which the resource belongs.
  /// [pythonFunction] A Python function tool.
  /// [systemTools] The system tool.
  /// [toolId] The ID to use for the tool, which will become the final component of
  /// [updateTime] Timestamp when the tool was last updated.
  ToolState({
    this.app,
    this.clientFunction,
    this.createTime,
    this.dataStoreTool,
    this.displayName,
    this.etag,
    this.executionType,
    this.generatedSummary,
    this.googleSearchTool,
    this.location,
    this.name,
    this.openApiTools,
    this.project,
    this.pythonFunction,
    this.systemTools,
    this.toolId,
    this.updateTime,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'app': ?app,
      'clientFunction': ?pulumi.Input.mapOptionalInputValue<ToolClientFunction, Map<String, dynamic>>(clientFunction, (value) => value.toMap()),
      'createTime': ?createTime,
      'dataStoreTool': ?pulumi.Input.mapOptionalInputValue<ToolDataStoreTool, Map<String, dynamic>>(dataStoreTool, (value) => value.toMap()),
      'displayName': ?displayName,
      'etag': ?etag,
      'executionType': ?executionType,
      'generatedSummary': ?generatedSummary,
      'googleSearchTool': ?pulumi.Input.mapOptionalInputValue<ToolGoogleSearchTool, Map<String, dynamic>>(googleSearchTool, (value) => value.toMap()),
      'location': ?location,
      'name': ?name,
      'openApiTools': ?pulumi.Input.mapOptionalInputValue<List<ToolOpenApiTool>, List<Map<String, dynamic>>>(openApiTools, (value) => pulumi.Input.encodeList<ToolOpenApiTool, Map<String, dynamic>>(value, (value) => value.toMap())),
      'project': ?project,
      'pythonFunction': ?pulumi.Input.mapOptionalInputValue<ToolPythonFunction, Map<String, dynamic>>(pythonFunction, (value) => value.toMap()),
      'systemTools': ?pulumi.Input.mapOptionalInputValue<List<ToolSystemTool>, List<Map<String, dynamic>>>(systemTools, (value) => pulumi.Input.encodeList<ToolSystemTool, Map<String, dynamic>>(value, (value) => value.toMap())),
      'toolId': ?toolId,
      'updateTime': ?updateTime,
    };
  }

  factory ToolState.fromMap(Map<String, dynamic> map) {
    return ToolState(
      app: (() { final guardedValue = map['app']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      clientFunction: (() { final guardedValue = map['clientFunction']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ToolClientFunction.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      createTime: (() { final guardedValue = map['createTime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      dataStoreTool: (() { final guardedValue = map['dataStoreTool']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ToolDataStoreTool.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      displayName: (() { final guardedValue = map['displayName']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      etag: (() { final guardedValue = map['etag']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      executionType: (() { final guardedValue = map['executionType']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      generatedSummary: (() { final guardedValue = map['generatedSummary']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      googleSearchTool: (() { final guardedValue = map['googleSearchTool']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ToolGoogleSearchTool.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      location: (() { final guardedValue = map['location']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      name: (() { final guardedValue = map['name']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      openApiTools: (() { final guardedValue = map['openApiTools']; if (guardedValue == null) return null; return pulumi.Input.fromValue(pulumi.Input.decodeList<ToolOpenApiTool>(guardedValue, (value) => ToolOpenApiTool.fromMap((value as Map).cast<String, dynamic>()))); })(),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      pythonFunction: (() { final guardedValue = map['pythonFunction']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ToolPythonFunction.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      systemTools: (() { final guardedValue = map['systemTools']; if (guardedValue == null) return null; return pulumi.Input.fromValue(pulumi.Input.decodeList<ToolSystemTool>(guardedValue, (value) => ToolSystemTool.fromMap((value as Map).cast<String, dynamic>()))); })(),
      toolId: (() { final guardedValue = map['toolId']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      updateTime: (() { final guardedValue = map['updateTime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}

