library module_sagemaker_domain_default_user_settings_canvas_app_settings_time_series_forecasting_settings;

export 'domain_default_user_settings_canvas_app_settings_time_series_forecasting_settings.dart';
