library module_bedrock_agent_data_source_vector_ingestion_configuration_chunking_configuration_hierarchical_chunking_configuration;

export 'agent_data_source_vector_ingestion_configuration_chunking_configuration_hierarchical_chunking_configuration.dart';
