library module_privilegedaccessmanager_get_entitlement_privileged_access_gcp_iam_access_role_binding;

export 'get_entitlement_privileged_access_gcp_iam_access_role_binding/get_entitlement_privileged_access_gcp_iam_access_role_binding.dart';
