import 'package:pulumi/pulumi.dart';
import 'authentication_response2.dart';
import 'scan_config_args.dart';
import 'schedule_response3.dart';

/// Creates a new ScanConfig.
class ScanConfig extends CustomResource {
  /// The authentication configuration. If specified, service will use the authentication configuration during scanning.
  late final Output<AuthenticationResponse2> authentication;

  /// The excluded URL patterns as described in https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls
  late final Output<List<String>> blacklistPatterns;

  /// The user provided display name of the ScanConfig.
  late final Output<String> displayName;

  /// Controls export of scan configurations and results to Security Command Center.
  late final Output<String> exportToSecurityCommandCenter;

  /// Whether to keep scanning even if most requests return HTTP error codes.
  late final Output<bool> ignoreHttpStatusErrors;

  /// Whether the scan config is managed by Web Security Scanner, output only.
  late final Output<bool> managedScan;

  /// The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively. If the field is unspecified or its value is set 0, server will default to 15. Other values outside of [5, 20] range will be rejected with INVALID_ARGUMENT error.
  late final Output<int> maxQps;

  /// The resource name of the ScanConfig. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are generated by the system.
  late final Output<String> name;
  late final Output<String> project;

  /// The risk level selected for the scan
  late final Output<String> riskLevel;

  /// The schedule of the ScanConfig.
  late final Output<ScheduleResponse3> schedule;

  /// The starting URLs from which the scanner finds site pages.
  late final Output<List<String>> startingUrls;

  /// Whether the scan configuration has enabled static IP address scan feature. If enabled, the scanner will access applications from static IP addresses.
  late final Output<bool> staticIpScan;

  /// The user agent used during scanning.
  late final Output<String> userAgent;

  ScanConfig(
    String name, {
    ScanConfigArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:websecurityscanner/v1:ScanConfig',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.authentication = Output.createUnknown<AuthenticationResponse2>();
    this.blacklistPatterns = Output.createUnknown<List<String>>();
    this.displayName = Output.createUnknown<String>();
    this.exportToSecurityCommandCenter = Output.createUnknown<String>();
    this.ignoreHttpStatusErrors = Output.createUnknown<bool>();
    this.managedScan = Output.createUnknown<bool>();
    this.maxQps = Output.createUnknown<int>();
    this.name = Output.createUnknown<String>();
    this.project = Output.createUnknown<String>();
    this.riskLevel = Output.createUnknown<String>();
    this.schedule = Output.createUnknown<ScheduleResponse3>();
    this.startingUrls = Output.createUnknown<List<String>>();
    this.staticIpScan = Output.createUnknown<bool>();
    this.userAgent = Output.createUnknown<String>();
  }
}
