import 'package:pulumi/pulumi.dart' as pulumi;
import 'authentication_response_websecurityscanner_v1.dart';
import 'scan_config_args.dart';
import 'schedule_response_websecurityscanner_v1.dart';

/// Creates a new ScanConfig.
class ScanConfig extends pulumi.CustomResource {
  /// The authentication configuration. If specified, service will use the authentication configuration during scanning.
  late final pulumi.Output<AuthenticationResponseWebsecurityscannerV1>
      authentication;

  /// The excluded URL patterns as described in https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls
  late final pulumi.Output<List<String>> blacklistPatterns;

  /// The user provided display name of the ScanConfig.
  late final pulumi.Output<String> displayName;

  /// Controls export of scan configurations and results to Security Command Center.
  late final pulumi.Output<String> exportToSecurityCommandCenter;

  /// Whether to keep scanning even if most requests return HTTP error codes.
  late final pulumi.Output<bool> ignoreHttpStatusErrors;

  /// Whether the scan config is managed by Web Security Scanner, output only.
  late final pulumi.Output<bool> managedScan;

  /// The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively. If the field is unspecified or its value is set 0, server will default to 15. Other values outside of [5, 20] range will be rejected with INVALID_ARGUMENT error.
  late final pulumi.Output<int> maxQps;

  /// The resource name of the ScanConfig. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are generated by the system.
  late final pulumi.Output<String> name;
  late final pulumi.Output<String> project;

  /// The risk level selected for the scan
  late final pulumi.Output<String> riskLevel;

  /// The schedule of the ScanConfig.
  late final pulumi.Output<ScheduleResponseWebsecurityscannerV1> schedule;

  /// The starting URLs from which the scanner finds site pages.
  late final pulumi.Output<List<String>> startingUrls;

  /// Whether the scan configuration has enabled static IP address scan feature. If enabled, the scanner will access applications from static IP addresses.
  late final pulumi.Output<bool> staticIpScan;

  /// The user agent used during scanning.
  late final pulumi.Output<String> userAgent;

  ScanConfig(
    String name, {
    ScanConfigArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'google-native:websecurityscanner/v1:ScanConfig',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.authentication =
        registerOutput<AuthenticationResponseWebsecurityscannerV1>(
            'authentication');
    this.blacklistPatterns = registerOutput<List<String>>('blacklistPatterns');
    this.displayName = registerOutput<String>('displayName');
    this.exportToSecurityCommandCenter =
        registerOutput<String>('exportToSecurityCommandCenter');
    this.ignoreHttpStatusErrors =
        registerOutput<bool>('ignoreHttpStatusErrors');
    this.managedScan = registerOutput<bool>('managedScan');
    this.maxQps = registerOutput<int>('maxQps');
    this.name = registerOutput<String>('name');
    this.project = registerOutput<String>('project');
    this.riskLevel = registerOutput<String>('riskLevel');
    this.schedule =
        registerOutput<ScheduleResponseWebsecurityscannerV1>('schedule');
    this.startingUrls = registerOutput<List<String>>('startingUrls');
    this.staticIpScan = registerOutput<bool>('staticIpScan');
    this.userAgent = registerOutput<String>('userAgent');
  }
}
