import 'package:pulumi/pulumi.dart';
import 'google_cloud_dialogflow_cx_v3_nlu_settings_response.dart';
import 'version_args6.dart';

/// Creates a Version in the specified Flow. This method is a [long-running operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation). The returned `Operation` type has the following method-specific fields: - `metadata`: CreateVersionOperationMetadata - `response`: Version
class Version9 extends CustomResource {
  late final Output<String> agentId;

  /// Create time of the version.
  late final Output<String> createTime;

  /// The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.
  late final Output<String> description;

  /// The human-readable name of the version. Limit of 64 characters.
  late final Output<String> displayName;
  late final Output<String> flowId;
  late final Output<String> location;

  /// Format: projects//locations//agents//flows//versions/. Version ID is a self-increasing number generated by Dialogflow upon version creation.
  late final Output<String> name;

  /// The NLU settings of the flow at version creation.
  late final Output<GoogleCloudDialogflowCxV3NluSettingsResponse> nluSettings;
  late final Output<String> project;

  /// The state of this version. This field is read-only and cannot be set by create and update methods.
  late final Output<String> state;

  Version9(
    String name, {
    VersionArgs6? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:dialogflow/v3:Version',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.agentId = Output.createUnknown<String>();
    this.createTime = Output.createUnknown<String>();
    this.description = Output.createUnknown<String>();
    this.displayName = Output.createUnknown<String>();
    this.flowId = Output.createUnknown<String>();
    this.location = Output.createUnknown<String>();
    this.name = Output.createUnknown<String>();
    this.nluSettings =
        Output.createUnknown<GoogleCloudDialogflowCxV3NluSettingsResponse>();
    this.project = Output.createUnknown<String>();
    this.state = Output.createUnknown<String>();
  }
}
