// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// The set of arguments for Version.
class VersionDialogflowV3Args {
  final pulumi.Input<String> agentId;

  /// The description of the version. The maximum length is 500 characters. If exceeded, the request is rejected.
  final pulumi.Input<String>? description;

  /// The human-readable name of the version. Limit of 64 characters.
  final pulumi.Input<String> displayName;
  final pulumi.Input<String> flowId;
  final pulumi.Input<String>? location;

  /// Format: projects//locations//agents//flows//versions/. Version ID is a self-increasing number generated by Dialogflow upon version creation.
  final pulumi.Input<String>? name;
  final pulumi.Input<String>? project;

  VersionDialogflowV3Args({
    required this.agentId,
    this.description,
    required this.displayName,
    required this.flowId,
    this.location,
    this.name,
    this.project,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['agentId'] = agentId;
    final descriptionValue = description;
    if (descriptionValue != null) {
      map['description'] = descriptionValue;
    }
    map['displayName'] = displayName;
    map['flowId'] = flowId;
    final locationValue = location;
    if (locationValue != null) {
      map['location'] = locationValue;
    }
    final nameValue = name;
    if (nameValue != null) {
      map['name'] = nameValue;
    }
    final projectValue = project;
    if (projectValue != null) {
      map['project'] = projectValue;
    }
    return map;
  }

  factory VersionDialogflowV3Args.fromMap(Map<String, dynamic> map) {
    return VersionDialogflowV3Args(
      agentId: pulumi.Input.asInput<String>(map['agentId']),
      description: pulumi.Input.asOptionalInput<String>(map['description']),
      displayName: pulumi.Input.asInput<String>(map['displayName']),
      flowId: pulumi.Input.asInput<String>(map['flowId']),
      location: pulumi.Input.asOptionalInput<String>(map['location']),
      name: pulumi.Input.asOptionalInput<String>(map['name']),
      project: pulumi.Input.asOptionalInput<String>(map['project']),
    );
  }
}
