// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'apigateway_api_config_file.dart';

/// A gRPC service definition.
class ApigatewayApiConfigGrpcServiceDefinition {
  /// Input only. File descriptor set, generated by protoc. To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb. $ protoc --include_imports --include_source_info test.proto -o out.pb
  final ApigatewayApiConfigFile? fileDescriptorSet;
  /// Optional. Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate file_descriptor_set.
  final List<ApigatewayApiConfigFile>? source;

  /// Creates a new [ApigatewayApiConfigGrpcServiceDefinition].
  /// [fileDescriptorSet] Input only. File descriptor set, generated by protoc. To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb. $ protoc --include_imports --include_source_info test.proto -o out.pb
  /// [source] Optional. Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate file_descriptor_set.
  ApigatewayApiConfigGrpcServiceDefinition({
    this.fileDescriptorSet,
    this.source,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'fileDescriptorSet': ?fileDescriptorSet == null ? null : fileDescriptorSet!.toMap(),
      'source': ?source == null ? null : pulumi.Input.encodeList<ApigatewayApiConfigFile, Map<String, dynamic>>(source!, (value) => value.toMap()),
    };
  }

  factory ApigatewayApiConfigGrpcServiceDefinition.fromMap(Map<String, dynamic> map) {
    return ApigatewayApiConfigGrpcServiceDefinition(
      fileDescriptorSet: map['fileDescriptorSet'] == null ? null : ApigatewayApiConfigFile.fromMap((map['fileDescriptorSet'] as Map).cast<String, dynamic>()),
      source: map['source'] == null ? null : pulumi.Input.decodeList<ApigatewayApiConfigFile>(map['source'], (value) => ApigatewayApiConfigFile.fromMap((value as Map).cast<String, dynamic>())),
    );
  }
}

