library module_ssoadmin_permissions_boundary_attachment_permissions_boundary_customer_managed_policy_reference;

export 'permissions_boundary_attachment_permissions_boundary_customer_managed_policy_reference.dart';
