// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_dataproc_cluster_iampolicy_cluster_iampolicy_args_doc}
/// The set of arguments for ClusterIAMPolicy.
/// {@endtemplate}
/// {@macro pulumi_dataproc_cluster_iampolicy_cluster_iampolicy_args_doc}
class ClusterIAMPolicyArgs {
  /// The name or relative resource id of the cluster to manage IAM policies for.
  ///
  /// For `gcp.dataproc.ClusterIAMMember` or `gcp.dataproc.ClusterIAMBinding`:
  final pulumi.Input<String> cluster;
  /// The policy data generated by a `gcp.organizations.getIAMPolicy` data source.
  ///
  /// - - -
  final pulumi.Input<String> policyData;
  /// The project in which the cluster belongs. If it
  /// is not provided, the provider will use a default.
  final pulumi.Input<String?>? project;
  /// The region in which the cluster belongs. If it
  /// is not provided, the provider will use a default.
  final pulumi.Input<String?>? region;

  /// Creates a new [ClusterIAMPolicyArgs].
  /// [cluster] The name or relative resource id of the cluster to manage IAM policies for.
  /// [policyData] The policy data generated by a `gcp.organizations.getIAMPolicy` data source.
  /// [project] The project in which the cluster belongs. If it
  /// [region] The region in which the cluster belongs. If it
  const ClusterIAMPolicyArgs({
    required this.cluster,
    required this.policyData,
    this.project,
    this.region,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'cluster': cluster,
      'policyData': policyData,
      'project': ?project,
      'region': ?region,
    };
  }

  factory ClusterIAMPolicyArgs.fromMap(Map<String, dynamic> map) {
    return ClusterIAMPolicyArgs(
      cluster: pulumi.Input.fromValue(map['cluster'] as String),
      policyData: pulumi.Input.fromValue(map['policyData'] as String),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      region: (() { final guardedValue = map['region']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
