// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_dataproc_job_iampolicy_job_iampolicy_args_doc}
/// The set of arguments for JobIAMPolicy.
/// {@endtemplate}
/// {@macro pulumi_dataproc_job_iampolicy_job_iampolicy_args_doc}
class JobIAMPolicyArgs {
  final pulumi.Input<String> jobId;
  /// The policy data generated by a `gcp.organizations.getIAMPolicy` data source.
  ///
  /// - - -
  final pulumi.Input<String> policyData;
  /// The project in which the job belongs. If it
  /// is not provided, the provider will use a default.
  final pulumi.Input<String>? project;
  /// The region in which the job belongs. If it
  /// is not provided, the provider will use a default.
  final pulumi.Input<String>? region;

  /// Creates a new [JobIAMPolicyArgs].
  /// [jobId] Required.
  /// [policyData] The policy data generated by a `gcp.organizations.getIAMPolicy` data source.
  /// [project] The project in which the job belongs. If it
  /// [region] The region in which the job belongs. If it
  JobIAMPolicyArgs({
    required this.jobId,
    required this.policyData,
    this.project,
    this.region,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'jobId': jobId,
      'policyData': policyData,
      'project': ?project,
      'region': ?region,
    };
  }

  factory JobIAMPolicyArgs.fromMap(Map<String, dynamic> map) {
    return JobIAMPolicyArgs(
      jobId: (map['jobId'] as String).input(),
      policyData: (map['policyData'] as String).input(),
      project: map['project'] == null ? null : (map['project'] as String).input(),
      region: map['region'] == null ? null : (map['region'] as String).input(),
    );
  }
}

