library module_container_cluster_node_pool_defaults_node_config_defaults_containerd_config_private_registry_access_config_certificate_authority_domain_config;

export 'cluster_node_pool_defaults_node_config_defaults_containerd_config_private_registry_access_config_certificate_authority_domain_config.dart';
