library module_discoveryengine_data_store_document_processing_config_parsing_config_override_layout_parsing_config;

export 'data_store_document_processing_config_parsing_config_override_layout_parsing_config/data_store_document_processing_config_parsing_config_override_layout_parsing_config.dart';
