library module_lambda_event_source_mapping_self_managed_kafka_event_source_config_schema_registry_config_access_config;

export 'event_source_mapping_self_managed_kafka_event_source_config_schema_registry_config_access_config/event_source_mapping_self_managed_kafka_event_source_config_schema_registry_config_access_config.dart';
