library module_lambda_function_event_invoke_config;

export 'function_event_invoke_config/function_event_invoke_config.dart';
export 'function_event_invoke_config/function_event_invoke_config_args.dart';
