name: f5bigip_dart_ltm_pool
description: Pulumi F5 BigIP LTM pool example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  pulumi: 3.0.0
  pulumi_f5bigip: 3.19.3

dev_dependencies:
  lints: ^6.1.0
