library module_ssoadmin_permissions_boundary_attachment_permissions_boundary;

export 'permissions_boundary_attachment_permissions_boundary/permissions_boundary_attachment_permissions_boundary.dart';
