import 'package:pulumi/pulumi.dart';
import '../documentation_part_location/documentation_part_location.dart';
import 'documentation_part_args.dart';

/// Provides a settings of an API Gateway Documentation Part.
///
/// ## Example Usage
///
///
///
/// ## Import
///
/// Using `pulumi import`, import API Gateway documentation_parts using `REST-API-ID/DOC-PART-ID`. For example:
///
/// ```sh
/// $ pulumi import aws:apigateway/documentationPart:DocumentationPart example 5i4e1ko720/3oyy3t
/// ```
class DocumentationPart extends CustomResource {
  /// The DocumentationPart identifier, generated by API Gateway when the documentation part is created.
  late final Output<String> documentationPartId;

  /// Location of the targeted API entity of the to-be-created documentation part. See below.
  late final Output<DocumentationPartLocation> location;

  /// Content map of API-specific key-value pairs describing the targeted API entity. The map must be encoded as a JSON string, e.g., "{ \"description\": \"The API does ...\" }". Only Swagger-compliant key-value pairs can be exported and, hence, published.
  late final Output<String> properties;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final Output<String> region;

  /// ID of the associated Rest API
  late final Output<String> restApiId;

  DocumentationPart(
    String name, {
    DocumentationPartArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'aws:apigateway/documentationPart:DocumentationPart',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.documentationPartId = registerOutput<String>('documentationPartId');
    this.location = registerOutput<DocumentationPartLocation>('location');
    this.properties = registerOutput<String>('properties');
    this.region = registerOutput<String>('region');
    this.restApiId = registerOutput<String>('restApiId');
  }
}
