// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering FhirStoreIamPolicy resources.
class FhirStoreIamPolicyState {
  /// (Computed) The etag of the FHIR store's IAM policy.
  final pulumi.Input<String>? etag;
  /// The FHIR store ID, in the form
  /// `{project_id}/{location_name}/{dataset_name}/{fhir_store_name}` or
  /// `{location_name}/{dataset_name}/{fhir_store_name}`. In the second form, the provider's
  /// project setting will be used as a fallback.
  final pulumi.Input<String>? fhirStoreId;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;

  /// Creates a new [FhirStoreIamPolicyState].
  /// [etag] (Computed) The etag of the FHIR store's IAM policy.
  /// [fhirStoreId] The FHIR store ID, in the form
  /// [policyData] The policy data generated by
  FhirStoreIamPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? fhirStoreId,
    pulumi.Output<String>? policyData,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      fhirStoreId = pulumi.Input.asOptionalInput<String>(fhirStoreId),
      policyData = pulumi.Input.asOptionalInput<String>(policyData);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'fhirStoreId': ?fhirStoreId,
      'policyData': ?policyData,
    };
  }

  factory FhirStoreIamPolicyState.fromMap(Map<String, dynamic> map) {
    return FhirStoreIamPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      fhirStoreId: map['fhirStoreId'] == null ? null : pulumi.Output.create<String>(map['fhirStoreId'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
    );
  }
}

