// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'logical_network_interface_network_type.dart';

/// Each logical network interface is effectively a network and IP pair.
class LogicalNetworkInterface {
  /// Whether this interface is the default gateway for the instance. Only one interface can be the default gateway for the instance.
  final pulumi.Input<bool>? defaultGateway;
  /// An identifier for the `Network`, generated by the backend.
  final pulumi.Input<String>? id;
  /// IP address in the network
  final pulumi.Input<String>? ipAddress;
  /// Name of the network
  final pulumi.Input<String>? network;
  /// Type of network.
  final pulumi.Input<LogicalNetworkInterfaceNetworkType>? networkType;

  /// Creates a new [LogicalNetworkInterface].
  /// [defaultGateway] Whether this interface is the default gateway for the instance. Only one interface can be the default gateway for the instance.
  /// [id] An identifier for the `Network`, generated by the backend.
  /// [ipAddress] IP address in the network
  /// [network] Name of the network
  /// [networkType] Type of network.
  LogicalNetworkInterface({
    this.defaultGateway,
    this.id,
    this.ipAddress,
    this.network,
    this.networkType,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'defaultGateway': ?defaultGateway,
      'id': ?id,
      'ipAddress': ?ipAddress,
      'network': ?network,
      'networkType': ?pulumi.Input.mapOptionalInputValue<LogicalNetworkInterfaceNetworkType, String>(networkType, (value) => value.value),
    };
  }

  factory LogicalNetworkInterface.fromMap(Map<String, dynamic> map) {
    return LogicalNetworkInterface(
      defaultGateway: map['defaultGateway'] == null ? null : (map['defaultGateway']! as bool).input(),
      id: map['id'] == null ? null : (map['id']! as String).input(),
      ipAddress: map['ipAddress'] == null ? null : (map['ipAddress']! as String).input(),
      network: map['network'] == null ? null : (map['network']! as String).input(),
      networkType: map['networkType'] == null ? null : (LogicalNetworkInterfaceNetworkType.fromValue(map['networkType']! as String)).input(),
    );
  }
}

