// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'management_project_security_health_analytics_custom_module_custom_config_custom_output.dart';
import 'management_project_security_health_analytics_custom_module_custom_config_predicate.dart';
import 'management_project_security_health_analytics_custom_module_custom_config_resource_selector.dart';

class ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfig {
  /// Custom output properties.
  /// Structure is documented below.
  final pulumi.Input<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigCustomOutput>? customOutput;
  /// Text that describes the vulnerability or misconfiguration that the custom
  /// module detects. This explanation is returned with each finding instance to
  /// help investigators understand the detected issue. The text must be enclosed in quotation marks.
  final pulumi.Input<String>? description;
  /// The CEL expression to evaluate to produce findings. When the expression evaluates
  /// to true against a resource, a finding is generated.
  /// Structure is documented below.
  final pulumi.Input<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigPredicate> predicate;
  /// An explanation of the recommended steps that security teams can take to resolve
  /// the detected issue. This explanation is returned with each finding generated by
  /// this module in the nextSteps property of the finding JSON.
  final pulumi.Input<String> recommendation;
  /// The resource types that the custom module operates on. Each custom module
  /// can specify up to 5 resource types.
  /// Structure is documented below.
  final pulumi.Input<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigResourceSelector> resourceSelector;
  /// The severity to assign to findings generated by the module.
  /// Possible values are: `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`.
  final pulumi.Input<String> severity;

  /// Creates a new [ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfig].
  /// [customOutput] Custom output properties.
  /// [description] Text that describes the vulnerability or misconfiguration that the custom
  /// [predicate] The CEL expression to evaluate to produce findings. When the expression evaluates
  /// [recommendation] An explanation of the recommended steps that security teams can take to resolve
  /// [resourceSelector] The resource types that the custom module operates on. Each custom module
  /// [severity] The severity to assign to findings generated by the module.
  const ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfig({
    this.customOutput,
    this.description,
    required this.predicate,
    required this.recommendation,
    required this.resourceSelector,
    required this.severity,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'customOutput': ?pulumi.Input.mapOptionalInputValue<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigCustomOutput, Map<String, dynamic>>(customOutput, (value) => value.toMap()),
      'description': ?description,
      'predicate': pulumi.Input.mapInputValue<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigPredicate, Map<String, dynamic>>(predicate, (value) => value.toMap()),
      'recommendation': recommendation,
      'resourceSelector': pulumi.Input.mapInputValue<ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigResourceSelector, Map<String, dynamic>>(resourceSelector, (value) => value.toMap()),
      'severity': severity,
    };
  }

  factory ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfig.fromMap(Map<String, dynamic> map) {
    return ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfig(
      customOutput: (() { final guardedValue = map['customOutput']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigCustomOutput.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      description: (() { final guardedValue = map['description']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      predicate: pulumi.Input.fromValue(ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigPredicate.fromMap((map['predicate']! as Map).cast<String, dynamic>())),
      recommendation: pulumi.Input.fromValue(map['recommendation'] as String),
      resourceSelector: pulumi.Input.fromValue(ManagementProjectSecurityHealthAnalyticsCustomModuleCustomConfigResourceSelector.fromMap((map['resourceSelector']! as Map).cast<String, dynamic>())),
      severity: pulumi.Input.fromValue(map['severity'] as String),
    );
  }
}

