// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering V2OrganizationSourceIamPolicy resources.
class V2OrganizationSourceIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;
  final pulumi.Input<String>? organization;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? source;

  /// Creates a new [V2OrganizationSourceIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [organization] Optional.
  /// [policyData] The policy data generated by
  /// [source] Used to find the parent resource to bind the IAM policy to
  V2OrganizationSourceIamPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? organization,
    pulumi.Output<String>? policyData,
    pulumi.Output<String>? source,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      organization = pulumi.Input.asOptionalInput<String>(organization),
      policyData = pulumi.Input.asOptionalInput<String>(policyData),
      source = pulumi.Input.asOptionalInput<String>(source);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'organization': ?organization,
      'policyData': ?policyData,
      'source': ?source,
    };
  }

  factory V2OrganizationSourceIamPolicyState.fromMap(Map<String, dynamic> map) {
    return V2OrganizationSourceIamPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      organization: map['organization'] == null ? null : pulumi.Output.create<String>(map['organization'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
      source: map['source'] == null ? null : pulumi.Output.create<String>(map['source'] as String),
    );
  }
}

