library module_organizations_get_organizational_unit_descendant_accounts_account;

export 'get_organizational_unit_descendant_accounts_account/get_organizational_unit_descendant_accounts_account.dart';
