library module_lex_v2models_intent_closing_setting_conditional_default_branch_response_message_group_variation_plain_text_message;

export 'v2models_intent_closing_setting_conditional_default_branch_response_message_group_variation_plain_text_message.dart';
