library module_diagflow_cx_flow_knowledge_connector_settings_trigger_fulfillment_message;

export 'cx_flow_knowledge_connector_settings_trigger_fulfillment_message/cx_flow_knowledge_connector_settings_trigger_fulfillment_message.dart';
