library module_diagflow_cx_flow_transition_route_trigger_fulfillment_message;

export 'cx_flow_transition_route_trigger_fulfillment_message/cx_flow_transition_route_trigger_fulfillment_message.dart';
