library module_diagflow_cx_flow_knowledge_connector_settings_trigger_fulfillment_message_text;

export 'cx_flow_knowledge_connector_settings_trigger_fulfillment_message_text/cx_flow_knowledge_connector_settings_trigger_fulfillment_message_text.dart';
