library module_diagflow_cx_page_knowledge_connector_settings_trigger_fulfillment;

export 'cx_page_knowledge_connector_settings_trigger_fulfillment/cx_page_knowledge_connector_settings_trigger_fulfillment.dart';
