library module_diagflow_cx_page_event_handler_trigger_fulfillment_message_live_agent_handoff;

export 'cx_page_event_handler_trigger_fulfillment_message_live_agent_handoff/cx_page_event_handler_trigger_fulfillment_message_live_agent_handoff.dart';
