library module_appmesh_get_virtual_node_spec_backend_virtual_service_client_policy_tl_validation_subject_alternative_name;

export 'get_virtual_node_spec_backend_virtual_service_client_policy_tl_validation_subject_alternative_name.dart';
