// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering SigningProfilePermission resources.
class SigningProfilePermissionState {
  /// An AWS Signer action permitted as part of cross-account permissions. Valid values: `signer:StartSigningJob`, `signer:GetSigningProfile`, `signer:RevokeSignature`, or `signer:SignPayload`.
  final pulumi.Input<String>? action;
  /// The AWS principal to be granted a cross-account permission.
  final pulumi.Input<String>? principal;
  /// Name of the signing profile to add the cross-account permissions.
  final pulumi.Input<String>? profileName;
  /// The signing profile version that a permission applies to.
  final pulumi.Input<String>? profileVersion;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;
  /// A unique statement identifier. By default generated by the provider.
  final pulumi.Input<String>? statementId;
  /// A statement identifier prefix. The provider will generate a unique suffix. Conflicts with `statement_id`.
  final pulumi.Input<String>? statementIdPrefix;

  /// Creates a new [SigningProfilePermissionState].
  /// [action] An AWS Signer action permitted as part of cross-account permissions. Valid values: `signer:StartSigningJob`, `signer:GetSigningProfile`, `signer:RevokeSignature`, or `signer:SignPayload`.
  /// [principal] The AWS principal to be granted a cross-account permission.
  /// [profileName] Name of the signing profile to add the cross-account permissions.
  /// [profileVersion] The signing profile version that a permission applies to.
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  /// [statementId] A unique statement identifier. By default generated by the provider.
  /// [statementIdPrefix] A statement identifier prefix. The provider will generate a unique suffix. Conflicts with `statement_id`.
  SigningProfilePermissionState({
    pulumi.Output<String>? action,
    pulumi.Output<String>? principal,
    pulumi.Output<String>? profileName,
    pulumi.Output<String>? profileVersion,
    pulumi.Output<String>? region,
    pulumi.Output<String>? statementId,
    pulumi.Output<String>? statementIdPrefix,
  }) :
      action = pulumi.Input.asOptionalInput<String>(action),
      principal = pulumi.Input.asOptionalInput<String>(principal),
      profileName = pulumi.Input.asOptionalInput<String>(profileName),
      profileVersion = pulumi.Input.asOptionalInput<String>(profileVersion),
      region = pulumi.Input.asOptionalInput<String>(region),
      statementId = pulumi.Input.asOptionalInput<String>(statementId),
      statementIdPrefix = pulumi.Input.asOptionalInput<String>(statementIdPrefix);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'action': ?action,
      'principal': ?principal,
      'profileName': ?profileName,
      'profileVersion': ?profileVersion,
      'region': ?region,
      'statementId': ?statementId,
      'statementIdPrefix': ?statementIdPrefix,
    };
  }

  factory SigningProfilePermissionState.fromMap(Map<String, dynamic> map) {
    return SigningProfilePermissionState(
      action: map['action'] == null ? null : pulumi.Output.create<String>(map['action'] as String),
      principal: map['principal'] == null ? null : pulumi.Output.create<String>(map['principal'] as String),
      profileName: map['profileName'] == null ? null : pulumi.Output.create<String>(map['profileName'] as String),
      profileVersion: map['profileVersion'] == null ? null : pulumi.Output.create<String>(map['profileVersion'] as String),
      region: map['region'] == null ? null : pulumi.Output.create<String>(map['region'] as String),
      statementId: map['statementId'] == null ? null : pulumi.Output.create<String>(map['statementId'] as String),
      statementIdPrefix: map['statementIdPrefix'] == null ? null : pulumi.Output.create<String>(map['statementIdPrefix'] as String),
    );
  }
}

