// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'cloud_hsm_cluster_sku.dart';
import 'managed_service_identity.dart';

/// {@template pulumi_hardwaresecuritymodules_cloud_hsm_cluster_args_doc}
/// The set of arguments for CloudHsmCluster.
/// {@endtemplate}
/// {@macro pulumi_hardwaresecuritymodules_cloud_hsm_cluster_args_doc}
class CloudHsmClusterArgs {
  /// The Cloud HSM Cluster's auto-generated Domain Name Label Scope
  final pulumi.Input<dynamic>? autoGeneratedDomainNameLabelScope;
  /// The name of the Cloud HSM Cluster within the specified resource group. Cloud HSM Cluster names must be between 3 and 23 characters in length.
  final pulumi.Input<String?>? cloudHsmClusterName;
  /// Managed service identity (system assigned and/or user assigned identities)
  final pulumi.Input<ManagedServiceIdentity?>? identity;
  /// The geo-location where the resource lives
  final pulumi.Input<String?>? location;
  /// The Cloud HSM Cluster public network access
  final pulumi.Input<dynamic>? publicNetworkAccess;
  /// The name of the resource group. The name is case insensitive.
  final pulumi.Input<String> resourceGroupName;
  /// SKU details
  final pulumi.Input<CloudHsmClusterSku?>? sku;
  /// Resource tags.
  final pulumi.Input<Map<String, String>?>? tags;

  /// Creates a new [CloudHsmClusterArgs].
  /// [autoGeneratedDomainNameLabelScope] The Cloud HSM Cluster's auto-generated Domain Name Label Scope
  /// [cloudHsmClusterName] The name of the Cloud HSM Cluster within the specified resource group. Cloud HSM Cluster names must be between 3 and 23 characters in length.
  /// [identity] Managed service identity (system assigned and/or user assigned identities)
  /// [location] The geo-location where the resource lives
  /// [publicNetworkAccess] The Cloud HSM Cluster public network access
  /// [resourceGroupName] The name of the resource group. The name is case insensitive.
  /// [sku] SKU details
  /// [tags] Resource tags.
  const CloudHsmClusterArgs({
    this.autoGeneratedDomainNameLabelScope,
    this.cloudHsmClusterName,
    this.identity,
    this.location,
    this.publicNetworkAccess,
    required this.resourceGroupName,
    this.sku,
    this.tags,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'autoGeneratedDomainNameLabelScope': ?autoGeneratedDomainNameLabelScope,
      'cloudHsmClusterName': ?cloudHsmClusterName,
      'identity': ?pulumi.Input.mapOptionalInputValue<ManagedServiceIdentity, Map<String, dynamic>>(identity, (value) => value.toMap()),
      'location': ?location,
      'publicNetworkAccess': ?publicNetworkAccess,
      'resourceGroupName': resourceGroupName,
      'sku': ?pulumi.Input.mapOptionalInputValue<CloudHsmClusterSku, Map<String, dynamic>>(sku, (value) => value.toMap()),
      'tags': ?tags,
    };
  }

  factory CloudHsmClusterArgs.fromMap(Map<String, dynamic> map) {
    return CloudHsmClusterArgs(
      autoGeneratedDomainNameLabelScope: (() { final guardedValue = map['autoGeneratedDomainNameLabelScope']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue); })(),
      cloudHsmClusterName: (() { final guardedValue = map['cloudHsmClusterName']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      identity: (() { final guardedValue = map['identity']; if (guardedValue == null) return null; return pulumi.Input.fromValue(ManagedServiceIdentity.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      location: (() { final guardedValue = map['location']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      publicNetworkAccess: (() { final guardedValue = map['publicNetworkAccess']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue); })(),
      resourceGroupName: pulumi.Input.fromValue(map['resourceGroupName'] as String),
      sku: (() { final guardedValue = map['sku']; if (guardedValue == null) return null; return pulumi.Input.fromValue(CloudHsmClusterSku.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      tags: (() { final guardedValue = map['tags']; if (guardedValue == null) return null; return pulumi.Input.fromValue((guardedValue as Map).cast<String, String>()); })(),
    );
  }
}
