name: command_lambda_invoke
description: Pulumi Command lambda invoke example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: 3.0.0
  pulumi_aws: 7.43.0
  pulumi_command: 1.2.1

dev_dependencies:
  lints: ^6.1.0
