library module_kinesis_firehose_delivery_stream_http_endpoint_configuration_secrets_manager_configuration;

export 'firehose_delivery_stream_http_endpoint_configuration_secrets_manager_configuration.dart';
