/// Property value
enum OpenSearchPartitionInstanceType {
  c42xlargeSearch("c4.2xlarge.search"),
  c44xlargeSearch("c4.4xlarge.search"),
  c48xlargeSearch("c4.8xlarge.search"),
  c4LargeSearch("c4.large.search"),
  c4XlargeSearch("c4.xlarge.search"),
  c518xlargeSearch("c5.18xlarge.search"),
  c52xlargeSearch("c5.2xlarge.search"),
  c54xlargeSearch("c5.4xlarge.search"),
  c59xlargeSearch("c5.9xlarge.search"),
  c5LargeSearch("c5.large.search"),
  c5XlargeSearch("c5.xlarge.search"),
  c6g12xlargeSearch("c6g.12xlarge.search"),
  c6g2xlargeSearch("c6g.2xlarge.search"),
  c6g4xlargeSearch("c6g.4xlarge.search"),
  c6g8xlargeSearch("c6g.8xlarge.search"),
  c6gLargeSearch("c6g.large.search"),
  c6gXlargeSearch("c6g.xlarge.search"),
  d22xlargeSearch("d2.2xlarge.search"),
  d24xlargeSearch("d2.4xlarge.search"),
  d28xlargeSearch("d2.8xlarge.search"),
  d2XlargeSearch("d2.xlarge.search"),
  i22xlargeSearch("i2.2xlarge.search"),
  i2XlargeSearch("i2.xlarge.search"),
  i316xlargeSearch("i3.16xlarge.search"),
  i32xlargeSearch("i3.2xlarge.search"),
  i34xlargeSearch("i3.4xlarge.search"),
  i38xlargeSearch("i3.8xlarge.search"),
  i3LargeSearch("i3.large.search"),
  i3XlargeSearch("i3.xlarge.search"),
  m32xlargeSearch("m3.2xlarge.search"),
  m3LargeSearch("m3.large.search"),
  m3MediumSearch("m3.medium.search"),
  m3XlargeSearch("m3.xlarge.search"),
  m410xlargeSearch("m4.10xlarge.search"),
  m42xlargeSearch("m4.2xlarge.search"),
  m44xlargeSearch("m4.4xlarge.search"),
  m4LargeSearch("m4.large.search"),
  m4XlargeSearch("m4.xlarge.search"),
  m512xlargeSearch("m5.12xlarge.search"),
  m524xlargeSearch("m5.24xlarge.search"),
  m52xlargeSearch("m5.2xlarge.search"),
  m54xlargeSearch("m5.4xlarge.search"),
  m5LargeSearch("m5.large.search"),
  m5XlargeSearch("m5.xlarge.search"),
  m6g12xlargeSearch("m6g.12xlarge.search"),
  m6g2xlargeSearch("m6g.2xlarge.search"),
  m6g4xlargeSearch("m6g.4xlarge.search"),
  m6g8xlargeSearch("m6g.8xlarge.search"),
  m6gLargeSearch("m6g.large.search"),
  m6gXlargeSearch("m6g.xlarge.search"),
  or112xlargeSearch("or1.12xlarge.search"),
  or116xlargeSearch("or1.16xlarge.search"),
  or12xlargeSearch("or1.2xlarge.search"),
  or14xlargeSearch("or1.4xlarge.search"),
  or18xlargeSearch("or1.8xlarge.search"),
  or1LargeSearch("or1.large.search"),
  or1MediumSearch("or1.medium.search"),
  or1XlargeSearch("or1.xlarge.search"),
  r32xlargeSearch("r3.2xlarge.search"),
  r34xlargeSearch("r3.4xlarge.search"),
  r38xlargeSearch("r3.8xlarge.search"),
  r3LargeSearch("r3.large.search"),
  r3XlargeSearch("r3.xlarge.search"),
  r416xlargeSearch("r4.16xlarge.search"),
  r42xlargeSearch("r4.2xlarge.search"),
  r44xlargeSearch("r4.4xlarge.search"),
  r48xlargeSearch("r4.8xlarge.search"),
  r4LargeSearch("r4.large.search"),
  r4XlargeSearch("r4.xlarge.search"),
  r512xlargeSearch("r5.12xlarge.search"),
  r524xlargeSearch("r5.24xlarge.search"),
  r52xlargeSearch("r5.2xlarge.search"),
  r54xlargeSearch("r5.4xlarge.search"),
  r5LargeSearch("r5.large.search"),
  r5XlargeSearch("r5.xlarge.search"),
  r6g12xlargeSearch("r6g.12xlarge.search"),
  r6g2xlargeSearch("r6g.2xlarge.search"),
  r6g4xlargeSearch("r6g.4xlarge.search"),
  r6g8xlargeSearch("r6g.8xlarge.search"),
  r6gLargeSearch("r6g.large.search"),
  r6gXlargeSearch("r6g.xlarge.search"),
  r6gd12xlargeSearch("r6gd.12xlarge.search"),
  r6gd16xlargeSearch("r6gd.16xlarge.search"),
  r6gd2xlargeSearch("r6gd.2xlarge.search"),
  r6gd4xlargeSearch("r6gd.4xlarge.search"),
  r6gd8xlargeSearch("r6gd.8xlarge.search"),
  r6gdLargeSearch("r6gd.large.search"),
  r6gdXlargeSearch("r6gd.xlarge.search"),
  t2MediumSearch("t2.medium.search"),
  t2MicroSearch("t2.micro.search"),
  t2SmallSearch("t2.small.search"),
  t32xlargeSearch("t3.2xlarge.search"),
  t3LargeSearch("t3.large.search"),
  t3MediumSearch("t3.medium.search"),
  t3MicroSearch("t3.micro.search"),
  t3NanoSearch("t3.nano.search"),
  t3SmallSearch("t3.small.search"),
  t3XlargeSearch("t3.xlarge.search"),
  t4gMediumSearch("t4g.medium.search"),
  t4gSmallSearch("t4g.small.search"),
  ultrawarm1LargeSearch("ultrawarm1.large.search"),
  ultrawarm1MediumSearch("ultrawarm1.medium.search"),
  ultrawarm1XlargeSearch("ultrawarm1.xlarge.search");

  const OpenSearchPartitionInstanceType(this.wireValue);
  final String wireValue;

  static OpenSearchPartitionInstanceType fromValue(String value) {
    for (final item in OpenSearchPartitionInstanceType.values) {
      if (item.wireValue == value) {
        return item;
      }
    }
    throw ArgumentError('Unknown OpenSearchPartitionInstanceType value: $value');
  }
}

