library module_s3_bucket_metadata_configuration_metadata_configuration_journal_table_configuration_record_expiration;

export 'bucket_metadata_configuration_metadata_configuration_journal_table_configuration_record_expiration.dart';
