library module_iap_settings_application_settings_attribute_propagation_settings;

export 'settings_application_settings_attribute_propagation_settings/settings_application_settings_attribute_propagation_settings.dart';
