name: libvirt_dart_vm
description: Pulumi Libvirt VM example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: 3.0.0
  pulumi_azure_native: 3.14.0
  pulumi_libvirt: 0.9.3
  pulumi_tls: 5.3.0

dev_dependencies:
  lints: ^6.1.0
