/// Property stackStatus
enum StackStatus {
  cREATECOMPLETE("CREATE_COMPLETE"),
  cREATEFAILED("CREATE_FAILED"),
  cREATEINPROGRESS("CREATE_IN_PROGRESS"),
  dELETECOMPLETE("DELETE_COMPLETE"),
  dELETEFAILED("DELETE_FAILED"),
  dELETEINPROGRESS("DELETE_IN_PROGRESS"),
  iMPORTCOMPLETE("IMPORT_COMPLETE"),
  iMPORTINPROGRESS("IMPORT_IN_PROGRESS"),
  iMPORTROLLBACKCOMPLETE("IMPORT_ROLLBACK_COMPLETE"),
  iMPORTROLLBACKFAILED("IMPORT_ROLLBACK_FAILED"),
  iMPORTROLLBACKINPROGRESS("IMPORT_ROLLBACK_IN_PROGRESS"),
  rEVIEWINPROGRESS("REVIEW_IN_PROGRESS"),
  rOLLBACKCOMPLETE("ROLLBACK_COMPLETE"),
  rOLLBACKFAILED("ROLLBACK_FAILED"),
  rOLLBACKINPROGRESS("ROLLBACK_IN_PROGRESS"),
  uPDATECOMPLETE("UPDATE_COMPLETE"),
  uPDATECOMPLETECLEANUPINPROGRESS("UPDATE_COMPLETE_CLEANUP_IN_PROGRESS"),
  uPDATEFAILED("UPDATE_FAILED"),
  uPDATEINPROGRESS("UPDATE_IN_PROGRESS"),
  uPDATEROLLBACKCOMPLETE("UPDATE_ROLLBACK_COMPLETE"),
  uPDATEROLLBACKCOMPLETECLEANUPINPROGRESS("UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS"),
  uPDATEROLLBACKFAILED("UPDATE_ROLLBACK_FAILED"),
  uPDATEROLLBACKINPROGRESS("UPDATE_ROLLBACK_IN_PROGRESS");

  const StackStatus(this.value);
  final String value;

  static StackStatus fromValue(String value) {
    for (final item in StackStatus.values) {
      if (item.value == value) {
        return item;
      }
    }
    throw ArgumentError('Unknown StackStatus value: $value');
  }
}

