name: pulumi_mysql
description: A Pulumi package for creating and managing mysql cloud resources.
version: 3.2.14
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-mysql
topics:
    - pulumi
    - mysql
environment:
    sdk: '>=3.11.0 <4.0.0'
resolution: workspace
dependencies:
    pulumi: ^3.0.0-alpha.0
dev_dependencies:
    lints: ^6.1.0
