import 'package:pulumi/pulumi.dart' as pulumi;
import 'event_subscription_docdb_args.dart';

/// Provides a DocumentDB event subscription resource.
///
/// ## Example Usage
///
///
///
/// ## Import
///
/// Using `pulumi import`, import DocumentDB Event Subscriptions using the `name`. For example:
///
/// ```sh
/// $ pulumi import aws:docdb/eventSubscription:EventSubscription example event-sub
/// ```
class EventSubscriptionDocdb extends pulumi.CustomResource {
  /// The Amazon Resource Name of the DocumentDB event notification subscription
  late final pulumi.Output<String> arn;

  /// The AWS customer account associated with the DocumentDB event notification subscription
  late final pulumi.Output<String> customerAwsId;

  /// A boolean flag to enable/disable the subscription. Defaults to true.
  late final pulumi.Output<bool?> enabled;

  /// A list of event categories for a SourceType that you want to subscribe to. See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_Event.html or run `aws docdb describe-event-categories`.
  late final pulumi.Output<List<String>?> eventCategories;

  /// The name of the DocumentDB event subscription. By default generated by this provider.
  late final pulumi.Output<String> name;

  /// The name of the DocumentDB event subscription. Conflicts with `name`.
  late final pulumi.Output<String> namePrefix;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final pulumi.Output<String> region;
  late final pulumi.Output<String> snsTopicArn;

  /// A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified.
  late final pulumi.Output<List<String>?> sourceIds;

  /// The type of source that will be generating the events. Valid options are `db-instance`, `db-cluster`, `db-parameter-group`, `db-security-group`,` db-cluster-snapshot`. If not set, all sources will be subscribed to.
  late final pulumi.Output<String?> sourceType;

  /// A map of tags to assign to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  late final pulumi.Output<Map<String, String>?> tags;

  /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  late final pulumi.Output<Map<String, String>> tagsAll;

  EventSubscriptionDocdb(
    String name, {
    EventSubscriptionDocdbArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:docdb/eventSubscription:EventSubscription',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.arn = registerOutput<String>('arn');
    this.customerAwsId = registerOutput<String>('customerAwsId');
    this.enabled = registerOutput<bool?>('enabled');
    this.eventCategories = registerOutput<List<String>?>('eventCategories');
    this.name = registerOutput<String>('name');
    this.namePrefix = registerOutput<String>('namePrefix');
    this.region = registerOutput<String>('region');
    this.snsTopicArn = registerOutput<String>('snsTopicArn');
    this.sourceIds = registerOutput<List<String>?>('sourceIds');
    this.sourceType = registerOutput<String?>('sourceType');
    this.tags = registerOutput<Map<String, String>?>('tags');
    this.tagsAll = registerOutput<Map<String, String>>('tagsAll');
  }
}
