import 'package:pulumi/pulumi.dart';
import '../file_system_lifecycle_policy/file_system_lifecycle_policy.dart';
import '../file_system_protection/file_system_protection.dart';
import '../file_system_size_in_byte/file_system_size_in_byte.dart';
import 'file_system_args.dart';

/// Provides an Elastic File System (EFS) File System resource.
///
/// ## Example Usage
///
/// ### EFS File System w/ tags
///
///
///
/// ### Using lifecycle policy
///
///
///
/// ## Import
///
/// Using `pulumi import`, import the EFS file systems using the `id`. For example:
///
/// ```sh
/// $ pulumi import aws:efs/fileSystem:FileSystem foo fs-6fa144c6
/// ```
class FileSystem extends CustomResource {
  /// Amazon Resource Name of the file system.
  late final Output<String> arn;

  /// The identifier of the Availability Zone in which the file system's One Zone storage classes exist.
  late final Output<String> availabilityZoneId;

  /// the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
  late final Output<String> availabilityZoneName;

  /// A unique name (a maximum of 64 characters are allowed)
  /// used as reference when creating the Elastic File System to ensure idempotent file
  /// system creation. By default generated by this provider. See [Elastic File System]
  /// user guide for more information.
  late final Output<String> creationToken;

  /// The DNS name for the filesystem per [documented convention](http://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html).
  late final Output<String> dnsName;

  /// If true, the disk will be encrypted.
  late final Output<bool> encrypted;

  /// The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
  late final Output<String> kmsKeyId;

  /// A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
  late final Output<List<FileSystemLifecyclePolicy>?> lifecyclePolicies;

  /// The value of the file system's `Name` tag.
  late final Output<String> name;

  /// The current number of mount targets that the file system has.
  late final Output<int> numberOfMountTargets;

  /// The AWS account that created the file system. If the file system was createdby an IAM user, the parent account to which the user belongs is the owner.
  late final Output<String> ownerId;

  /// The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
  late final Output<String> performanceMode;

  /// A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
  late final Output<FileSystemProtection> protection;

  /// The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
  late final Output<double?> provisionedThroughputInMibps;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final Output<String> region;

  /// The latest known metered size (in bytes) of data stored in the file system, the value is not the exact size that the file system was at any point in time. See Size In Bytes.
  late final Output<List<FileSystemSizeInByte>> sizeInBytes;

  /// A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  late final Output<Map<String, String>?> tags;

  /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  late final Output<Map<String, String>> tagsAll;

  /// Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
  late final Output<String?> throughputMode;

  FileSystem(
    String name, {
    FileSystemArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'aws:efs/fileSystem:FileSystem',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.arn = registerOutput<String>('arn');
    this.availabilityZoneId = registerOutput<String>('availabilityZoneId');
    this.availabilityZoneName = registerOutput<String>('availabilityZoneName');
    this.creationToken = registerOutput<String>('creationToken');
    this.dnsName = registerOutput<String>('dnsName');
    this.encrypted = registerOutput<bool>('encrypted');
    this.kmsKeyId = registerOutput<String>('kmsKeyId');
    this.lifecyclePolicies =
        registerOutput<List<FileSystemLifecyclePolicy>?>('lifecyclePolicies');
    this.name = registerOutput<String>('name');
    this.numberOfMountTargets = registerOutput<int>('numberOfMountTargets');
    this.ownerId = registerOutput<String>('ownerId');
    this.performanceMode = registerOutput<String>('performanceMode');
    this.protection = registerOutput<FileSystemProtection>('protection');
    this.provisionedThroughputInMibps =
        registerOutput<double?>('provisionedThroughputInMibps');
    this.region = registerOutput<String>('region');
    this.sizeInBytes =
        registerOutput<List<FileSystemSizeInByte>>('sizeInBytes');
    this.tags = registerOutput<Map<String, String>?>('tags');
    this.tagsAll = registerOutput<Map<String, String>>('tagsAll');
    this.throughputMode = registerOutput<String?>('throughputMode');
  }
}
