// ignore_for_file: unused_element, unnecessary_cast

/// Result data returned by getRepositoryIamPolicy.
class GetRepositoryIamPolicyResult4 {
  /// (Computed) The etag of the IAM policy.
  final String etag;

  /// The provider-assigned unique ID for this managed resource.
  final String id;

  /// (Required only by `gcp.sourcerepo.RepositoryIamPolicy`) The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final String policyData;
  final String project;
  final String repository;

  GetRepositoryIamPolicyResult4({
    required this.etag,
    required this.id,
    required this.policyData,
    required this.project,
    required this.repository,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['etag'] = etag;
    map['id'] = id;
    map['policyData'] = policyData;
    map['project'] = project;
    map['repository'] = repository;
    return map;
  }

  factory GetRepositoryIamPolicyResult4.fromMap(Map<String, dynamic> map) {
    return GetRepositoryIamPolicyResult4(
      etag: map['etag'] as String,
      id: map['id'] as String,
      policyData: map['policyData'] as String,
      project: map['project'] as String,
      repository: map['repository'] as String,
    );
  }
}
