library module_lambda_event_source_mapping_amazon_managed_kafka_event_source_config_schema_registry_config_schema_validation_config;

export 'event_source_mapping_amazon_managed_kafka_event_source_config_schema_registry_config_schema_validation_config.dart';
