library module_appflow_connector_profile_connector_profile_config_connector_profile_properties_sapo_data_oauth_properties;

export 'connector_profile_connector_profile_config_connector_profile_properties_sapo_data_oauth_properties.dart';
