library module_appmesh_virtual_node_spec_backend_virtual_service_client_policy_tls_validation_trust_file;

export 'virtual_node_spec_backend_virtual_service_client_policy_tls_validation_trust_file.dart';
