// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'attestation_source.dart';
import 'verification_rule_trusted_builder.dart';

/// Specifies verification rules for evaluating the SLSA attestations including: which builders to trust, where to fetch the SLSA attestations generated by those builders, and other builder-specific evaluation rules such as which source repositories are trusted. An image is considered verified by the rule if any of the fetched SLSA attestations is verified.
class VerificationRule {
  /// Specifies where to fetch the provenances attestations generated by the builder (group).
  final pulumi.Input<AttestationSource>? attestationSource;

  /// If true, require the image to be built from a top-level configuration. `trusted_source_repo_patterns` specifies the repositories containing this configuration.
  final pulumi.Input<bool>? configBasedBuildRequired;

  /// Each verification rule is used for evaluation against provenances generated by a specific builder (group). For some of the builders, such as the Google Cloud Build, users don't need to explicitly specify their roots of trust in the policy since the evaluation service can automatically fetch them based on the builder (group).
  final pulumi.Input<VerificationRuleTrustedBuilder>? trustedBuilder;

  /// List of trusted source code repository URL patterns. These patterns match the full repository URL without its scheme (e.g. `https://`). The patterns must not include schemes. For example, the pattern `source.cloud.google.com/my-project/my-repo-name` matches the following URLs: - `source.cloud.google.com/my-project/my-repo-name` - `git+ssh://source.cloud.google.com/my-project/my-repo-name` - `https://source.cloud.google.com/my-project/my-repo-name` A pattern matches a URL either exactly or with `*` wildcards. `*` can be used in only two ways: 1. trailing `*` after hosturi/ to match varying endings; 2. trailing `**` after hosturi/ to match `/` as well. `*` and `**` can only be used as wildcards and can only occur at the end of the pattern after a `/`. (So it's not possible to match a URL that contains literal `*`.) For example: - `github.com/my-project/my-repo` is valid to match a single repo - `github.com/my-project/*` will match all direct repos in `my-project` - `github.com/**` matches all repos in GitHub
  final pulumi.Input<List<String>>? trustedSourceRepoPatterns;

  /// Creates a new [VerificationRule].
  /// [attestationSource] Specifies where to fetch the provenances attestations generated by the builder (group).
  /// [configBasedBuildRequired] If true, require the image to be built from a top-level configuration. `trusted_source_repo_patterns` specifies the repositories containing this configuration.
  /// [trustedBuilder] Each verification rule is used for evaluation against provenances generated by a specific builder (group). For some of the builders, such as the Google Cloud Build, users don't need to explicitly specify their roots of trust in the policy since the evaluation service can automatically fetch them based on the builder (group).
  /// [trustedSourceRepoPatterns] List of trusted source code repository URL patterns. These patterns match the full repository URL without its scheme (e.g. `https://`). The patterns must not include schemes. For example, the pattern `source.cloud.google.com/my-project/my-repo-name` matches the following URLs: - `source.cloud.google.com/my-project/my-repo-name` - `git+ssh://source.cloud.google.com/my-project/my-repo-name` - `https://source.cloud.google.com/my-project/my-repo-name` A pattern matches a URL either exactly or with `*` wildcards. `*` can be used in only two ways: 1. trailing `*` after hosturi/ to match varying endings; 2. trailing `**` after hosturi/ to match `/` as well. `*` and `**` can only be used as wildcards and can only occur at the end of the pattern after a `/`. (So it's not possible to match a URL that contains literal `*`.) For example: - `github.com/my-project/my-repo` is valid to match a single repo - `github.com/my-project/*` will match all direct repos in `my-project` - `github.com/**` matches all repos in GitHub
  VerificationRule({
    this.attestationSource,
    this.configBasedBuildRequired,
    this.trustedBuilder,
    this.trustedSourceRepoPatterns,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'attestationSource':
          ?pulumi.Input.mapOptionalInputValue<
            AttestationSource,
            Map<String, dynamic>
          >(attestationSource, (value) => value.toMap()),
      'configBasedBuildRequired': ?configBasedBuildRequired,
      'trustedBuilder':
          ?pulumi.Input.mapOptionalInputValue<
            VerificationRuleTrustedBuilder,
            String
          >(trustedBuilder, (value) => value.wireValue),
      'trustedSourceRepoPatterns': ?trustedSourceRepoPatterns,
    };
  }

  factory VerificationRule.fromMap(Map<String, dynamic> map) {
    return VerificationRule(
      attestationSource: (() {
        final guardedValue = map['attestationSource'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(
          AttestationSource.fromMap(
            (guardedValue as Map).cast<String, dynamic>(),
          ),
        );
      })(),
      configBasedBuildRequired: (() {
        final guardedValue = map['configBasedBuildRequired'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as bool);
      })(),
      trustedBuilder: (() {
        final guardedValue = map['trustedBuilder'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(
          VerificationRuleTrustedBuilder.fromValue(guardedValue as String),
        );
      })(),
      trustedSourceRepoPatterns: (() {
        final guardedValue = map['trustedSourceRepoPatterns'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue((guardedValue as List).cast<String>());
      })(),
    );
  }
}
