library module_kinesis_firehose_delivery_stream_opensearchserverless_configuration_processing_configuration;

export 'firehose_delivery_stream_opensearchserverless_configuration_processing_configuration.dart';
