library module_kinesisanalyticsv2_application_application_configuration_sql_application_configuration_output_kinesis_firehose_output;

export 'application_application_configuration_sql_application_configuration_output_kinesis_firehose_output/application_application_configuration_sql_application_configuration_output_kinesis_firehose_output.dart';
