library module_timestreamquery_scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings;

export 'scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings/scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings.dart';
