library module_timestreamquery_scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings_multi_measure_attribute_mapping;

export 'scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings_multi_measure_attribute_mapping/scheduled_query_target_configuration_timestream_configuration_multi_measure_mappings_multi_measure_attribute_mapping.dart';
