library module_timestreamquery_scheduled_query_notification_configuration_sns_configuration;

export 'scheduled_query_notification_configuration_sns_configuration/scheduled_query_notification_configuration_sns_configuration.dart';
