library module_kendra_data_source_custom_document_enrichment_configuration_post_extraction_hook_configuration;

export 'data_source_custom_document_enrichment_configuration_post_extraction_hook_configuration.dart';
