library module_observabilityadmin_centralization_rule_for_organization_rule_destination_destination_logs_configuration;

export 'centralization_rule_for_organization_rule_destination_destination_logs_configuration.dart';
