library module_apigateway_get_api_config_iam_policy;

export 'get_api_config_iam_policy/get_api_config_iam_policy.dart';
export 'get_api_config_iam_policy/get_api_config_iam_policy_args.dart';
export 'get_api_config_iam_policy/get_api_config_iam_policy_result.dart';
