// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'component_source.dart';
import 'component_transform.dart';
import 'execution_stage_summary_kind.dart';
import 'stage_source.dart';

/// Description of the composing transforms, names/ids, and input/outputs of a stage of execution. Some composing transforms and sources may have been generated by the Dataflow service during execution planning.
class ExecutionStageSummary {
  /// Collections produced and consumed by component transforms of this stage.
  final List<ComponentSource>? componentSource;
  /// Transforms that comprise this execution stage.
  final List<ComponentTransform>? componentTransform;
  /// Dataflow service generated id for this stage.
  final String? id;
  /// Input sources for this stage.
  final List<StageSource>? inputSource;
  /// Type of transform this stage is executing.
  final ExecutionStageSummaryKind? kind;
  /// Dataflow service generated name for this stage.
  final String? name;
  /// Output sources for this stage.
  final List<StageSource>? outputSource;
  /// Other stages that must complete before this stage can run.
  final List<String>? prerequisiteStage;

  /// Creates a new [ExecutionStageSummary].
  /// [componentSource] Collections produced and consumed by component transforms of this stage.
  /// [componentTransform] Transforms that comprise this execution stage.
  /// [id] Dataflow service generated id for this stage.
  /// [inputSource] Input sources for this stage.
  /// [kind] Type of transform this stage is executing.
  /// [name] Dataflow service generated name for this stage.
  /// [outputSource] Output sources for this stage.
  /// [prerequisiteStage] Other stages that must complete before this stage can run.
  ExecutionStageSummary({
    this.componentSource,
    this.componentTransform,
    this.id,
    this.inputSource,
    this.kind,
    this.name,
    this.outputSource,
    this.prerequisiteStage,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'componentSource': ?componentSource == null ? null : pulumi.Input.encodeList<ComponentSource, Map<String, dynamic>>(componentSource!, (value) => value.toMap()),
      'componentTransform': ?componentTransform == null ? null : pulumi.Input.encodeList<ComponentTransform, Map<String, dynamic>>(componentTransform!, (value) => value.toMap()),
      'id': ?id,
      'inputSource': ?inputSource == null ? null : pulumi.Input.encodeList<StageSource, Map<String, dynamic>>(inputSource!, (value) => value.toMap()),
      'kind': ?kind == null ? null : kind!.value,
      'name': ?name,
      'outputSource': ?outputSource == null ? null : pulumi.Input.encodeList<StageSource, Map<String, dynamic>>(outputSource!, (value) => value.toMap()),
      'prerequisiteStage': ?prerequisiteStage,
    };
  }

  factory ExecutionStageSummary.fromMap(Map<String, dynamic> map) {
    return ExecutionStageSummary(
      componentSource: map['componentSource'] == null ? null : pulumi.Input.decodeList<ComponentSource>(map['componentSource'], (value) => ComponentSource.fromMap((value as Map).cast<String, dynamic>())),
      componentTransform: map['componentTransform'] == null ? null : pulumi.Input.decodeList<ComponentTransform>(map['componentTransform'], (value) => ComponentTransform.fromMap((value as Map).cast<String, dynamic>())),
      id: map['id'] == null ? null : map['id'] as String,
      inputSource: map['inputSource'] == null ? null : pulumi.Input.decodeList<StageSource>(map['inputSource'], (value) => StageSource.fromMap((value as Map).cast<String, dynamic>())),
      kind: map['kind'] == null ? null : ExecutionStageSummaryKind.fromValue(map['kind'] as String),
      name: map['name'] == null ? null : map['name'] as String,
      outputSource: map['outputSource'] == null ? null : pulumi.Input.decodeList<StageSource>(map['outputSource'], (value) => StageSource.fromMap((value as Map).cast<String, dynamic>())),
      prerequisiteStage: map['prerequisiteStage'] == null ? null : (map['prerequisiteStage'] as List).cast<String>(),
    );
  }
}

