library module_batch_get_job_definition_node_property_node_range_property_container_fargate_platform_configuration;

export 'get_job_definition_node_property_node_range_property_container_fargate_platform_configuration.dart';
