library module_sagemaker_endpoint_deployment_config_blue_green_update_policy_traffic_routing_configuration;

export 'endpoint_deployment_config_blue_green_update_policy_traffic_routing_configuration.dart';
