name: pulumi_alicloud
description: A Pulumi package for creating and managing AliCloud resources.
version: 3.95.0
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-alicloud
topics:
    - pulumi
    - alicloud
environment:
    sdk: ^3.10.0
resolution: workspace
dependencies:
    pulumi: 0.1.0
dev_dependencies:
    lints: ^6.1.0
