// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' hide Config;
import 'accelerator_response2.dart';
import 'crypto_key_config_response.dart';
import 'event_publish_config_response.dart';
import 'network_config_response11.dart';
import 'version_response4.dart';

/// Result data returned by getInstance.
class GetInstanceResult10 {
  /// List of accelerators enabled for this CDF instance.
  final List<AcceleratorResponse2> accelerators;

  /// Endpoint on which the REST APIs is accessible.
  final String apiEndpoint;

  /// Available versions that the instance can be upgraded to using UpdateInstanceRequest.
  final List<VersionResponse4> availableVersion;

  /// The time the instance was created.
  final String createTime;

  /// The crypto key configuration. This field is used by the Customer-Managed Encryption Keys (CMEK) feature.
  final CryptoKeyConfigResponse cryptoKeyConfig;

  /// User-managed service account to set on Dataproc when Cloud Data Fusion creates Dataproc to run data processing pipelines. This allows users to have fine-grained access control on Dataproc's accesses to cloud resources.
  final String dataprocServiceAccount;

  /// A description of this instance.
  final String description;

  /// If the instance state is DISABLED, the reason for disabling the instance.
  final List<String> disabledReason;

  /// Display name for an instance.
  final String displayName;

  /// Option to enable granular role-based access control.
  final bool enableRbac;

  /// Option to enable Stackdriver Logging.
  final bool enableStackdriverLogging;

  /// Option to enable Stackdriver Monitoring.
  final bool enableStackdriverMonitoring;

  /// Option to enable granular zone separation.
  final bool enableZoneSeparation;

  /// Option to enable and pass metadata for event publishing.
  final EventPublishConfigResponse eventPublishConfig;

  /// Cloud Storage bucket generated by Data Fusion in the customer project.
  final String gcsBucket;

  /// The resource labels for instance to use to annotate any related underlying resources such as Compute Engine VMs. The character '=' is not allowed to be used within the labels.
  final Map<String, String> labels;

  /// The name of this instance is in the form of projects/{project}/locations/{location}/instances/{instance}.
  final String name;

  /// Network configuration options. These are required when a private Data Fusion instance is to be created.
  final NetworkConfigResponse11 networkConfig;

  /// Map of additional options used to configure the behavior of Data Fusion instance.
  final Map<String, String> options;

  /// P4 service account for the customer project.
  final String p4ServiceAccount;

  /// Optional. Current patch revision of the Data Fusion.
  final String patchRevision;

  /// Specifies whether the Data Fusion instance should be private. If set to true, all Data Fusion nodes will have private IP addresses and will not be able to access the public internet.
  final bool privateInstance;

  /// Reserved for future use.
  final bool satisfiesPzs;

  /// Deprecated. Use tenant_project_id instead to extract the tenant project ID.
  final String serviceAccount;

  /// Endpoint on which the Data Fusion UI is accessible.
  final String serviceEndpoint;

  /// The current state of this Data Fusion instance.
  final String state;

  /// Additional information about the current state of this Data Fusion instance if available.
  final String stateMessage;

  /// The name of the tenant project.
  final String tenantProjectId;

  /// Instance type.
  final String type;

  /// The time the instance was last updated.
  final String updateTime;

  /// Current version of the Data Fusion. Only specifiable in Update.
  final String version;

  /// Endpoint on which the Data Fusion UI is accessible to third-party users
  final String workforceIdentityServiceEndpoint;

  /// Name of the zone in which the Data Fusion instance will be created. Only DEVELOPER instances use this field.
  final String zone;

  GetInstanceResult10({
    required this.accelerators,
    required this.apiEndpoint,
    required this.availableVersion,
    required this.createTime,
    required this.cryptoKeyConfig,
    required this.dataprocServiceAccount,
    required this.description,
    required this.disabledReason,
    required this.displayName,
    required this.enableRbac,
    required this.enableStackdriverLogging,
    required this.enableStackdriverMonitoring,
    required this.enableZoneSeparation,
    required this.eventPublishConfig,
    required this.gcsBucket,
    required this.labels,
    required this.name,
    required this.networkConfig,
    required this.options,
    required this.p4ServiceAccount,
    required this.patchRevision,
    required this.privateInstance,
    required this.satisfiesPzs,
    required this.serviceAccount,
    required this.serviceEndpoint,
    required this.state,
    required this.stateMessage,
    required this.tenantProjectId,
    required this.type,
    required this.updateTime,
    required this.version,
    required this.workforceIdentityServiceEndpoint,
    required this.zone,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['accelerators'] =
        Input.encodeList<AcceleratorResponse2, Map<String, dynamic>>(
            accelerators, (value) => value.toMap());
    map['apiEndpoint'] = apiEndpoint;
    map['availableVersion'] =
        Input.encodeList<VersionResponse4, Map<String, dynamic>>(
            availableVersion, (value) => value.toMap());
    map['createTime'] = createTime;
    map['cryptoKeyConfig'] = cryptoKeyConfig.toMap();
    map['dataprocServiceAccount'] = dataprocServiceAccount;
    map['description'] = description;
    map['disabledReason'] = disabledReason;
    map['displayName'] = displayName;
    map['enableRbac'] = enableRbac;
    map['enableStackdriverLogging'] = enableStackdriverLogging;
    map['enableStackdriverMonitoring'] = enableStackdriverMonitoring;
    map['enableZoneSeparation'] = enableZoneSeparation;
    map['eventPublishConfig'] = eventPublishConfig.toMap();
    map['gcsBucket'] = gcsBucket;
    map['labels'] = labels;
    map['name'] = name;
    map['networkConfig'] = networkConfig.toMap();
    map['options'] = options;
    map['p4ServiceAccount'] = p4ServiceAccount;
    map['patchRevision'] = patchRevision;
    map['privateInstance'] = privateInstance;
    map['satisfiesPzs'] = satisfiesPzs;
    map['serviceAccount'] = serviceAccount;
    map['serviceEndpoint'] = serviceEndpoint;
    map['state'] = state;
    map['stateMessage'] = stateMessage;
    map['tenantProjectId'] = tenantProjectId;
    map['type'] = type;
    map['updateTime'] = updateTime;
    map['version'] = version;
    map['workforceIdentityServiceEndpoint'] = workforceIdentityServiceEndpoint;
    map['zone'] = zone;
    return map;
  }

  factory GetInstanceResult10.fromMap(Map<String, dynamic> map) {
    return GetInstanceResult10(
      accelerators: Input.decodeList<AcceleratorResponse2>(
          map['accelerators'],
          (value) => AcceleratorResponse2.fromMap(
              (value as Map).cast<String, dynamic>())),
      apiEndpoint: map['apiEndpoint'] as String,
      availableVersion: Input.decodeList<VersionResponse4>(
          map['availableVersion'],
          (value) =>
              VersionResponse4.fromMap((value as Map).cast<String, dynamic>())),
      createTime: map['createTime'] as String,
      cryptoKeyConfig: CryptoKeyConfigResponse.fromMap(
          (map['cryptoKeyConfig'] as Map).cast<String, dynamic>()),
      dataprocServiceAccount: map['dataprocServiceAccount'] as String,
      description: map['description'] as String,
      disabledReason: (map['disabledReason'] as List).cast<String>(),
      displayName: map['displayName'] as String,
      enableRbac: map['enableRbac'] as bool,
      enableStackdriverLogging: map['enableStackdriverLogging'] as bool,
      enableStackdriverMonitoring: map['enableStackdriverMonitoring'] as bool,
      enableZoneSeparation: map['enableZoneSeparation'] as bool,
      eventPublishConfig: EventPublishConfigResponse.fromMap(
          (map['eventPublishConfig'] as Map).cast<String, dynamic>()),
      gcsBucket: map['gcsBucket'] as String,
      labels: (map['labels'] as Map).cast<String, String>(),
      name: map['name'] as String,
      networkConfig: NetworkConfigResponse11.fromMap(
          (map['networkConfig'] as Map).cast<String, dynamic>()),
      options: (map['options'] as Map).cast<String, String>(),
      p4ServiceAccount: map['p4ServiceAccount'] as String,
      patchRevision: map['patchRevision'] as String,
      privateInstance: map['privateInstance'] as bool,
      satisfiesPzs: map['satisfiesPzs'] as bool,
      serviceAccount: map['serviceAccount'] as String,
      serviceEndpoint: map['serviceEndpoint'] as String,
      state: map['state'] as String,
      stateMessage: map['stateMessage'] as String,
      tenantProjectId: map['tenantProjectId'] as String,
      type: map['type'] as String,
      updateTime: map['updateTime'] as String,
      version: map['version'] as String,
      workforceIdentityServiceEndpoint:
          map['workforceIdentityServiceEndpoint'] as String,
      zone: map['zone'] as String,
    );
  }
}
