name: pulumi_postgresql
description: A Pulumi package for creating and managing postgresql cloud resources.
version: 3.16.2
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-postgresql
topics:
    - pulumi
    - postgresql
publish_to: none
environment:
    sdk: ^3.10.0
resolution: workspace
dependencies:
    pulumi:
        path: /home/kingwill101/code/dart_packages/pulumi-dart/pulumi-dart
dev_dependencies:
    lints: ^5.0.0
