// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_iap_agent_registry_mcp_server_iam_policy_agent_registry_mcp_server_iam_policy_args_doc}
/// The set of arguments for AgentRegistryMcpServerIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_iap_agent_registry_mcp_server_iam_policy_agent_registry_mcp_server_iam_policy_args_doc}
class AgentRegistryMcpServerIamPolicyArgs {
  /// The location of the resource. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? location;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> mcpServerId;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Creates a new [AgentRegistryMcpServerIamPolicyArgs].
  /// [location] The location of the resource. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// [mcpServerId] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  const AgentRegistryMcpServerIamPolicyArgs({
    this.location,
    required this.mcpServerId,
    required this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'location': ?location,
      'mcpServerId': mcpServerId,
      'policyData': policyData,
      'project': ?project,
    };
  }

  factory AgentRegistryMcpServerIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return AgentRegistryMcpServerIamPolicyArgs(
      location: (() { final guardedValue = map['location']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      mcpServerId: pulumi.Input.fromValue(map['mcpServerId'] as String),
      policyData: pulumi.Input.fromValue(map['policyData'] as String),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
