// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering WebTypeComputeIamPolicy resources.
class WebTypeComputeIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String?>? etag;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String?>? policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String?>? project;

  /// Creates a new [WebTypeComputeIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  const WebTypeComputeIamPolicyState({
    this.etag,
    this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'policyData': ?policyData,
      'project': ?project,
    };
  }

  factory WebTypeComputeIamPolicyState.fromMap(Map<String, dynamic> map) {
    return WebTypeComputeIamPolicyState(
      etag: (() { final guardedValue = map['etag']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      policyData: (() { final guardedValue = map['policyData']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
