library module_dataloss_prevention_discovery_config_target_cloud_storage_target_filter_cloud_storage_resource_reference;

export 'prevention_discovery_config_target_cloud_storage_target_filter_cloud_storage_resource_reference.dart';
