import 'package:pulumi/pulumi.dart' as pulumi;
import 'domain_dkim_args.dart';

/// Provides an SES domain DKIM generation resource.
///
/// Domain ownership needs to be confirmed first using ses_domain_identity Resource
///
/// ## Example Usage
///
///
///
/// ## Import
///
/// Using `pulumi import`, import DKIM tokens using the `domain` attribute. For example:
///
/// ```sh
/// $ pulumi import aws:ses/domainDkim:DomainDkim example example.com
/// ```
class DomainDkim extends pulumi.CustomResource {
  /// DKIM tokens generated by SES.
  /// These tokens should be used to create CNAME records used to verify SES Easy DKIM.
  /// See below for an example of how this might be achieved
  /// when the domain is hosted in Route 53 and managed by this provider.
  /// Find out more about verifying domains in Amazon SES
  /// in the [AWS SES docs](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim-dns-records.html).
  late final pulumi.Output<List<String>> dkimTokens;

  /// Verified domain name to generate DKIM tokens for.
  late final pulumi.Output<String> domain;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final pulumi.Output<String> region;

  DomainDkim(
    String name, {
    DomainDkimArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'aws:ses/domainDkim:DomainDkim',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.dkimTokens = registerOutput<List<String>>('dkimTokens');
    this.domain = registerOutput<String>('domain');
    this.region = registerOutput<String>('region');
  }
}
