/// Category of the connection
enum ConnectionCategory {
  valuePythonFeed("PythonFeed"),
  valueContainerRegistry("ContainerRegistry"),
  valueGit("Git"),
  valueS3("S3"),
  valueSnowflake("Snowflake"),
  valueAzureSqlDb("AzureSqlDb"),
  valueAzureSynapseAnalytics("AzureSynapseAnalytics"),
  valueAzureMySqlDb("AzureMySqlDb"),
  valueAzurePostgresDb("AzurePostgresDb"),
  valueADLSGen2("ADLSGen2"),
  valueRedis("Redis"),
  valueApiKey("ApiKey"),
  valueAzureOpenAI("AzureOpenAI"),
  valueAIServices("AIServices"),
  valueCognitiveSearch("CognitiveSearch"),
  valueCognitiveService("CognitiveService"),
  valueCustomKeys("CustomKeys"),
  valueAzureBlob("AzureBlob"),
  valueAzureOneLake("AzureOneLake"),
  valueCosmosDb("CosmosDb"),
  valueCosmosDbMongoDbApi("CosmosDbMongoDbApi"),
  valueAzureDataExplorer("AzureDataExplorer"),
  valueAzureMariaDb("AzureMariaDb"),
  valueAzureDatabricksDeltaLake("AzureDatabricksDeltaLake"),
  valueAzureSqlMi("AzureSqlMi"),
  valueAzureTableStorage("AzureTableStorage"),
  valueAmazonRdsForOracle("AmazonRdsForOracle"),
  valueAmazonRdsForSqlServer("AmazonRdsForSqlServer"),
  valueAmazonRedshift("AmazonRedshift"),
  valueDb2("Db2"),
  valueDrill("Drill"),
  valueGoogleBigQuery("GoogleBigQuery"),
  valueGreenplum("Greenplum"),
  valueHbase("Hbase"),
  valueHive("Hive"),
  valueImpala("Impala"),
  valueInformix("Informix"),
  valueMariaDb("MariaDb"),
  valueMicrosoftAccess("MicrosoftAccess"),
  valueMySql("MySql"),
  valueNetezza("Netezza"),
  valueOracle("Oracle"),
  valuePhoenix("Phoenix"),
  valuePostgreSql("PostgreSql"),
  valuePresto("Presto"),
  valueSapOpenHub("SapOpenHub"),
  valueSapBw("SapBw"),
  valueSapHana("SapHana"),
  valueSapTable("SapTable"),
  valueSpark("Spark"),
  valueSqlServer("SqlServer"),
  valueSybase("Sybase"),
  valueTeradata("Teradata"),
  valueVertica("Vertica"),
  valuePinecone("Pinecone"),
  valueCassandra("Cassandra"),
  valueCouchbase("Couchbase"),
  valueMongoDbV2("MongoDbV2"),
  valueMongoDbAtlas("MongoDbAtlas"),
  valueAmazonS3Compatible("AmazonS3Compatible"),
  valueFileServer("FileServer"),
  valueFtpServer("FtpServer"),
  valueGoogleCloudStorage("GoogleCloudStorage"),
  valueHdfs("Hdfs"),
  valueOracleCloudStorage("OracleCloudStorage"),
  valueSftp("Sftp"),
  valueGenericHttp("GenericHttp"),
  valueODataRest("ODataRest"),
  valueOdbc("Odbc"),
  valueGenericRest("GenericRest"),
  valueAmazonMws("AmazonMws"),
  valueConcur("Concur"),
  valueDynamics("Dynamics"),
  valueDynamicsAx("DynamicsAx"),
  valueDynamicsCrm("DynamicsCrm"),
  valueGoogleAdWords("GoogleAdWords"),
  valueHubspot("Hubspot"),
  valueJira("Jira"),
  valueMagento("Magento"),
  valueMarketo("Marketo"),
  valueOffice365("Office365"),
  valueEloqua("Eloqua"),
  valueResponsys("Responsys"),
  valueOracleServiceCloud("OracleServiceCloud"),
  valuePayPal("PayPal"),
  valueQuickBooks("QuickBooks"),
  valueSalesforce("Salesforce"),
  valueSalesforceServiceCloud("SalesforceServiceCloud"),
  valueSalesforceMarketingCloud("SalesforceMarketingCloud"),
  valueSapCloudForCustomer("SapCloudForCustomer"),
  valueSapEcc("SapEcc"),
  valueServiceNow("ServiceNow"),
  valueSharePointOnlineList("SharePointOnlineList"),
  valueShopify("Shopify"),
  valueSquare("Square"),
  valueWebTable("WebTable"),
  valueXero("Xero"),
  valueZoho("Zoho"),
  valueGenericContainerRegistry("GenericContainerRegistry"),
  valueElasticsearch("Elasticsearch"),
  valueOpenAI("OpenAI"),
  valueSerp("Serp"),
  valueBingLLMSearch("BingLLMSearch"),
  valueServerless("Serverless"),
  valueManagedOnlineEndpoint("ManagedOnlineEndpoint");

  const ConnectionCategory(this.wireValue);
  final String wireValue;

  static ConnectionCategory fromValue(String value) {
    for (final item in ConnectionCategory.values) {
      if (item.wireValue == value) {
        return item;
      }
    }
    throw ArgumentError('Unknown ConnectionCategory value: $value');
  }
}

