library module_imagebuilder_get_container_recipe_instance_configuration_block_device_mapping_eb;

export 'get_container_recipe_instance_configuration_block_device_mapping_eb/get_container_recipe_instance_configuration_block_device_mapping_eb.dart';
