library module_imagebuilder_image_pipeline_image_scanning_configuration_ecr_configuration;

export 'image_pipeline_image_scanning_configuration_ecr_configuration/image_pipeline_image_scanning_configuration_ecr_configuration.dart';
