library module_kinesis_firehose_delivery_stream_snowflake_configuration_snowflake_role_configuration;

export 'firehose_delivery_stream_snowflake_configuration_snowflake_role_configuration/firehose_delivery_stream_snowflake_configuration_snowflake_role_configuration.dart';
