library module_kinesis_firehose_delivery_stream_extended_s3_configuration_processing_configuration_processor_parameter;

export 'firehose_delivery_stream_extended_s3_configuration_processing_configuration_processor_parameter/firehose_delivery_stream_extended_s3_configuration_processing_configuration_processor_parameter.dart';
