library module_kinesis_firehose_delivery_stream_extended_s3_configuration_processing_configuration;

export 'firehose_delivery_stream_extended_s3_configuration_processing_configuration/firehose_delivery_stream_extended_s3_configuration_processing_configuration.dart';
