library module_kinesis_firehose_delivery_stream_iceberg_configuration_destination_table_configuration;

export 'firehose_delivery_stream_iceberg_configuration_destination_table_configuration/firehose_delivery_stream_iceberg_configuration_destination_table_configuration.dart';
