library module_kinesis_firehose_delivery_stream_opensearch_configuration_s3_configuration;

export 'firehose_delivery_stream_opensearch_configuration_s3_configuration/firehose_delivery_stream_opensearch_configuration_s3_configuration.dart';
