library module_kinesis_firehose_delivery_stream_opensearchserverless_configuration_cloudwatch_logging_options;

export 'firehose_delivery_stream_opensearchserverless_configuration_cloudwatch_logging_options/firehose_delivery_stream_opensearchserverless_configuration_cloudwatch_logging_options.dart';
