library module_kinesis_firehose_delivery_stream_extended_s3_configuration_data_format_conversion_configuration_schema_configuration;

export 'firehose_delivery_stream_extended_s3_configuration_data_format_conversion_configuration_schema_configuration/firehose_delivery_stream_extended_s3_configuration_data_format_conversion_configuration_schema_configuration.dart';
