library module_kinesis_firehose_delivery_stream_http_endpoint_configuration_processing_configuration;

export 'firehose_delivery_stream_http_endpoint_configuration_processing_configuration/firehose_delivery_stream_http_endpoint_configuration_processing_configuration.dart';
