library module_kinesis_firehose_delivery_stream_extended_s3_configuration_dynamic_partitioning_configuration;

export 'firehose_delivery_stream_extended_s3_configuration_dynamic_partitioning_configuration/firehose_delivery_stream_extended_s3_configuration_dynamic_partitioning_configuration.dart';
