library module_kinesis_firehose_delivery_stream_opensearchserverless_configuration_processing_configuration_processor;

export 'firehose_delivery_stream_opensearchserverless_configuration_processing_configuration_processor/firehose_delivery_stream_opensearchserverless_configuration_processing_configuration_processor.dart';
