library module_osconfig_os_policy_assignment_os_policy_resource_group_resource;

export 'os_policy_assignment_os_policy_resource_group_resource/os_policy_assignment_os_policy_resource_group_resource.dart';
