library module_osconfig_v2_policy_orchestrator_for_folder_orchestrated_resource_os_policy_assignment_v1_payload_instance_filter_inventory;

export 'v2_policy_orchestrator_for_folder_orchestrated_resource_os_policy_assignment_v1_payload_instance_filter_inventory/v2_policy_orchestrator_for_folder_orchestrated_resource_os_policy_assignment_v1_payload_instance_filter_inventory.dart';
