library module_osconfig_v2_policy_orchestrator_for_organization_orchestrated_resource;

export 'v2_policy_orchestrator_for_organization_orchestrated_resource/v2_policy_orchestrator_for_organization_orchestrated_resource.dart';
