library module_osconfig_v2_policy_orchestrator_for_folder_orchestration_scope_selector_resource_hierarchy_selector;

export 'v2_policy_orchestrator_for_folder_orchestration_scope_selector_resource_hierarchy_selector/v2_policy_orchestrator_for_folder_orchestration_scope_selector_resource_hierarchy_selector.dart';
