library module_storage_control_organization_intelligence_config;

export 'control_organization_intelligence_config/control_organization_intelligence_config.dart';
export 'control_organization_intelligence_config/control_organization_intelligence_config_args.dart';
