library module_storage_transfer_job_transfer_spec_aws_s3_compatible_data_source_s3_metadata;

export 'transfer_job_transfer_spec_aws_s3_compatible_data_source_s3_metadata/transfer_job_transfer_spec_aws_s3_compatible_data_source_s3_metadata.dart';
