library module_dataplex_datascan_data_quality_spec_post_scan_actions_notification_report_score_threshold_trigger;

export 'datascan_data_quality_spec_post_scan_actions_notification_report_score_threshold_trigger/datascan_data_quality_spec_post_scan_actions_notification_report_score_threshold_trigger.dart';
