library module_dataplex_datascan_data_quality_spec_post_scan_actions_notification_report_recipients;

export 'datascan_data_quality_spec_post_scan_actions_notification_report_recipients/datascan_data_quality_spec_post_scan_actions_notification_report_recipients.dart';
