library module_dataplex_get_glossary_iam_policy;

export 'get_glossary_iam_policy/get_glossary_iam_policy.dart';
export 'get_glossary_iam_policy/get_glossary_iam_policy_args.dart';
export 'get_glossary_iam_policy/get_glossary_iam_policy_result.dart';
