library module_dataplex_get_datascan_iam_policy;

export 'get_datascan_iam_policy/get_datascan_iam_policy.dart';
export 'get_datascan_iam_policy/get_datascan_iam_policy_args.dart';
export 'get_datascan_iam_policy/get_datascan_iam_policy_result.dart';
