library module_dataplex_get_aspect_type_iam_policy;

export 'get_aspect_type_iam_policy/get_aspect_type_iam_policy.dart';
export 'get_aspect_type_iam_policy/get_aspect_type_iam_policy_args.dart';
export 'get_aspect_type_iam_policy/get_aspect_type_iam_policy_result.dart';
