name: awsx_dart_ts_lb_simple
description: AWSX simple ALB and Fargate service in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: 3.0.0
  pulumi_aws: ^7.20.0
  pulumi_awsx: ^3.2.1

dev_dependencies:
  lints: ^6.1.0
