library module_ec2transitgateway_get_route_table;

export 'get_route_table/get_route_table_ec2transitgateway.dart';
export 'get_route_table/get_route_table_ec2transitgateway_args.dart';
export 'get_route_table/get_route_table_ec2transitgateway_result.dart';
