library module_certificateauthority_certificate_certificate_description_x509_description_additional_extension_object_id;

export 'certificate_certificate_description_x509_description_additional_extension_object_id.dart';
