// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

class GroupInitialLifecycleHook {
  final pulumi.Input<String>? defaultResult;
  final pulumi.Input<int>? heartbeatTimeout;
  final pulumi.Input<String> lifecycleTransition;
  /// Name of the Auto Scaling Group. By default generated by Pulumi. Conflicts with `name_prefix`.
  final pulumi.Input<String> name;
  final pulumi.Input<String>? notificationMetadata;
  final pulumi.Input<String>? notificationTargetArn;
  final pulumi.Input<String>? roleArn;

  /// Creates a new [GroupInitialLifecycleHook].
  /// [defaultResult] Optional.
  /// [heartbeatTimeout] Optional.
  /// [lifecycleTransition] Required.
  /// [name] Name of the Auto Scaling Group. By default generated by Pulumi. Conflicts with `name_prefix`.
  /// [notificationMetadata] Optional.
  /// [notificationTargetArn] Optional.
  /// [roleArn] Optional.
  GroupInitialLifecycleHook({
    this.defaultResult,
    this.heartbeatTimeout,
    required this.lifecycleTransition,
    required this.name,
    this.notificationMetadata,
    this.notificationTargetArn,
    this.roleArn,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'defaultResult': ?defaultResult,
      'heartbeatTimeout': ?heartbeatTimeout,
      'lifecycleTransition': lifecycleTransition,
      'name': name,
      'notificationMetadata': ?notificationMetadata,
      'notificationTargetArn': ?notificationTargetArn,
      'roleArn': ?roleArn,
    };
  }

  factory GroupInitialLifecycleHook.fromMap(Map<String, dynamic> map) {
    return GroupInitialLifecycleHook(
      defaultResult: map['defaultResult'] == null ? null : ((map['defaultResult'] as String).input()).input(),
      heartbeatTimeout: map['heartbeatTimeout'] == null ? null : ((map['heartbeatTimeout'] as int).input()).input(),
      lifecycleTransition: (map['lifecycleTransition'] as String).input(),
      name: (map['name'] as String).input(),
      notificationMetadata: map['notificationMetadata'] == null ? null : ((map['notificationMetadata'] as String).input()).input(),
      notificationTargetArn: map['notificationTargetArn'] == null ? null : ((map['notificationTargetArn'] as String).input()).input(),
      roleArn: map['roleArn'] == null ? null : ((map['roleArn'] as String).input()).input(),
    );
  }
}

