library module_cloudwatch_get_log_data_protection_policy_document_statement_operation_audit_findings_destination_cloudwatch_logs;

export 'get_log_data_protection_policy_document_statement_operation_audit_findings_destination_cloudwatch_logs.dart';
