library module_cognito_risk_configuration_account_takeover_risk_configuration_notify_configuration_no_action_email;

export 'risk_configuration_account_takeover_risk_configuration_notify_configuration_no_action_email.dart';
