library module_diagflow_cx_flow_knowledge_connector_settings_trigger_fulfillment_message_output_audio_text;

export 'cx_flow_knowledge_connector_settings_trigger_fulfillment_message_output_audio_text.dart';
