// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering AiFeatureOnlineStoreIamPolicy resources.
class AiFeatureOnlineStoreIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;

  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? featureOnlineStore;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;

  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// The region of feature online store. eg us-central1 Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no region is provided in the parent identifier and no
  /// region is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? region;

  /// Creates a new [AiFeatureOnlineStoreIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [featureOnlineStore] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [region] The region of feature online store. eg us-central1 Used to find the parent resource to bind the IAM policy to. If not specified,
  AiFeatureOnlineStoreIamPolicyState({
    this.etag,
    this.featureOnlineStore,
    this.policyData,
    this.project,
    this.region,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'featureOnlineStore': ?featureOnlineStore,
      'policyData': ?policyData,
      'project': ?project,
      'region': ?region,
    };
  }

  factory AiFeatureOnlineStoreIamPolicyState.fromMap(Map<String, dynamic> map) {
    return AiFeatureOnlineStoreIamPolicyState(
      etag: (() {
        final guardedValue = map['etag'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      featureOnlineStore: (() {
        final guardedValue = map['featureOnlineStore'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      policyData: (() {
        final guardedValue = map['policyData'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      project: (() {
        final guardedValue = map['project'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
      region: (() {
        final guardedValue = map['region'];
        if (guardedValue == null) return null;
        return pulumi.Input.fromValue(guardedValue as String);
      })(),
    );
  }
}
