// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_vertex_ai_feature_online_store_featureview_iam_policy_ai_feature_online_store_featureview_iam_policy_args_doc}
/// The set of arguments for AiFeatureOnlineStoreFeatureviewIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_vertex_ai_feature_online_store_featureview_iam_policy_ai_feature_online_store_featureview_iam_policy_args_doc}
class AiFeatureOnlineStoreFeatureviewIamPolicyArgs {
  /// The name of the FeatureOnlineStore to use for the featureview. Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> featureOnlineStore;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> featureView;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String?>? project;
  /// The region for the resource. It should be the same as the featureonlinestore region. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no region is provided in the parent identifier and no
  /// region is specified, it is taken from the provider configuration.
  final pulumi.Input<String?>? region;

  /// Creates a new [AiFeatureOnlineStoreFeatureviewIamPolicyArgs].
  /// [featureOnlineStore] The name of the FeatureOnlineStore to use for the featureview. Used to find the parent resource to bind the IAM policy to
  /// [featureView] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [region] The region for the resource. It should be the same as the featureonlinestore region. Used to find the parent resource to bind the IAM policy to. If not specified,
  const AiFeatureOnlineStoreFeatureviewIamPolicyArgs({
    required this.featureOnlineStore,
    required this.featureView,
    required this.policyData,
    this.project,
    this.region,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'featureOnlineStore': featureOnlineStore,
      'featureView': featureView,
      'policyData': policyData,
      'project': ?project,
      'region': ?region,
    };
  }

  factory AiFeatureOnlineStoreFeatureviewIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return AiFeatureOnlineStoreFeatureviewIamPolicyArgs(
      featureOnlineStore: pulumi.Input.fromValue(map['featureOnlineStore'] as String),
      featureView: pulumi.Input.fromValue(map['featureView'] as String),
      policyData: pulumi.Input.fromValue(map['policyData'] as String),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      region: (() { final guardedValue = map['region']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
