library module_diagflow_cx_flow_knowledge_connector_settings_trigger_fulfillment_message_telephony_transfer_call;

export 'cx_flow_knowledge_connector_settings_trigger_fulfillment_message_telephony_transfer_call.dart';
