library module_s3_bucket_metadata_configuration_metadata_configuration_journal_table_configuration_encryption_configuration;

export 'bucket_metadata_configuration_metadata_configuration_journal_table_configuration_encryption_configuration.dart';
