library module_networksecurity_authz_policy_http_rule_from_not_source_principal_principal;

export 'authz_policy_http_rule_from_not_source_principal_principal/authz_policy_http_rule_from_not_source_principal_principal.dart';
