library module_networksecurity_authz_policy_http_rule_from_not_source_resource_iam_service_account;

export 'authz_policy_http_rule_from_not_source_resource_iam_service_account/authz_policy_http_rule_from_not_source_resource_iam_service_account.dart';
