library module_workspacesweb_user_settings_cookie_synchronization_configuration_blocklist;

export 'user_settings_cookie_synchronization_configuration_blocklist/user_settings_cookie_synchronization_configuration_blocklist.dart';
