// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// The set of arguments for ConsumersIamPolicy.
class ConsumersIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> consumerProject;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// The name of the service. Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> serviceName;

  ConsumersIamPolicyArgs({
    required this.consumerProject,
    required this.policyData,
    required this.serviceName,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['consumerProject'] = consumerProject;
    map['policyData'] = policyData;
    map['serviceName'] = serviceName;
    return map;
  }

  factory ConsumersIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return ConsumersIamPolicyArgs(
      consumerProject: pulumi.Input.asInput<String>(map['consumerProject']),
      policyData: pulumi.Input.asInput<String>(map['policyData']),
      serviceName: pulumi.Input.asInput<String>(map['serviceName']),
    );
  }
}
