library module_lex_v2models_intent_confirmation_setting_prompt_specification_message_group_variation;

export 'v2models_intent_confirmation_setting_prompt_specification_message_group_variation.dart';
