library module_dataloss_prevention_discovery_config_target_cloud_storage_target_filter_collection_include_regexes_pattern_cloud_storage_regex;

export 'prevention_discovery_config_target_cloud_storage_target_filter_collection_include_regexes_pattern_cloud_storage_regex.dart';
