name: pulumi_mysql
description: A Pulumi package for creating and managing mysql cloud resources.
version: 3.2.14
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-mysql
topics:
    - pulumi
    - mysql
publish_to: none
environment:
    sdk: ^3.10.0
resolution: workspace
dependencies:
    pulumi:
        path: /home/kingwill101/code/dart_packages/pulumi-dart/pulumi-dart
dev_dependencies:
    lints: ^5.0.0
