library module_edgenetwork_interconnect_attachment;

export 'interconnect_attachment/interconnect_attachment_edgenetwork.dart';
export 'interconnect_attachment/interconnect_attachment_edgenetwork_args.dart';
