name: aws_dart_langserve
description: Pulumi Dart translation of aws-py-langserve
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
  pulumi_aws: any
  pulumi_awsx: any

dev_dependencies:
  lints: ^6.1.0