library module_datastream_stream_rule_set_customization_rule_bigquery_partitioning_integer_range_partition;

export 'stream_rule_set_customization_rule_bigquery_partitioning_integer_range_partition/stream_rule_set_customization_rule_bigquery_partitioning_integer_range_partition.dart';
