library module_autoscaling_policy_predictive_scaling_configuration_metric_specification_predefined_load_metric_specification;

export 'policy_predictive_scaling_configuration_metric_specification_predefined_load_metric_specification/policy_predictive_scaling_configuration_metric_specification_predefined_load_metric_specification.dart';
