library module_autoscaling_policy_target_tracking_configuration_customized_metric_specification_metric;

export 'policy_target_tracking_configuration_customized_metric_specification_metric/policy_target_tracking_configuration_customized_metric_specification_metric.dart';
