library module_autoscaling_policy_predictive_scaling_configuration_metric_specification_customized_capacity_metric_specification_metric_data_query;

export 'policy_predictive_scaling_configuration_metric_specification_customized_capacity_metric_specification_metric_data_query/policy_predictive_scaling_configuration_metric_specification_customized_capacity_metric_specification_metric_data_query.dart';
