library module_container_cluster_node_pool_node_config_ephemeral_storage_local_ssd_config;

export 'cluster_node_pool_node_config_ephemeral_storage_local_ssd_config/cluster_node_pool_node_config_ephemeral_storage_local_ssd_config.dart';
