library module_container_get_cluster_node_pool_node_config_containerd_config_private_registry_access_config_certificate_authority_domain_config;

export 'get_cluster_node_pool_node_config_containerd_config_private_registry_access_config_certificate_authority_domain_config/get_cluster_node_pool_node_config_containerd_config_private_registry_access_config_certificate_authority_domain_config.dart';
