library module_container_node_pool_node_config_ephemeral_storage_local_ssd_config;

export 'node_pool_node_config_ephemeral_storage_local_ssd_config/node_pool_node_config_ephemeral_storage_local_ssd_config.dart';
