// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'backup_plan_backup_rule.dart';
import 'backup_plan_compute_instance_backup_plan_properties.dart';
import 'backup_plan_disk_backup_plan_properties.dart';

/// {@template pulumi_backupdisasterrecovery_backup_plan_backup_plan_args_doc}
/// The set of arguments for BackupPlan.
/// {@endtemplate}
/// {@macro pulumi_backupdisasterrecovery_backup_plan_backup_plan_args_doc}
class BackupPlanArgs {
  /// The ID of the backup plan
  final pulumi.Input<String> backupPlanId;
  /// The backup rules for this `BackupPlan`.
  /// Structure is documented below.
  final pulumi.Input<List<BackupPlanBackupRule>>? backupRules;
  /// Backup vault where the backups gets stored using this Backup plan.
  final pulumi.Input<String> backupVault;
  /// Defines optional compute instance related properties for backups generated by this plan.
  /// Structure is documented below.
  final pulumi.Input<BackupPlanComputeInstanceBackupPlanProperties>? computeInstanceBackupPlanProperties;
  /// Whether Terraform will be prevented from destroying the resource. Defaults to DELETE.
  /// When a 'terraform destroy' or 'pulumi up' would delete the resource,
  /// the command will fail if this field is set to "PREVENT" in Terraform state.
  /// When set to "ABANDON", the command will remove the resource from Terraform
  /// management without updating or deleting the resource in the API.
  /// When set to "DELETE", deleting the resource is allowed.
  final pulumi.Input<String>? deletionPolicy;
  /// The description allows for additional details about `BackupPlan` and its use cases to be provided.
  final pulumi.Input<String>? description;
  /// Defines optional disk related properties for backups generated by this plan.
  /// Structure is documented below.
  final pulumi.Input<BackupPlanDiskBackupPlanProperties>? diskBackupPlanProperties;
  /// The location for the backup plan
  final pulumi.Input<String> location;
  /// This is only applicable for CloudSql resource. Days for which logs will be stored. This value should be greater than or equal to minimum enforced log retention duration of the backup vault.
  final pulumi.Input<int>? logRetentionDays;
  /// The maximum number of days for which an on-demand backup taken with custom retention can be retained.
  final pulumi.Input<int>? maxCustomOnDemandRetentionDays;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the provider project is used.
  final pulumi.Input<String>? project;
  /// The resource type to which the `BackupPlan` will be applied.
  /// Examples include, "compute.googleapis.com/Instance", "compute.googleapis.com/Disk", "sqladmin.googleapis.com/Instance", "alloydb.googleapis.com/Cluster", "file.googleapis.com/Instance" and "storage.googleapis.com/Bucket".
  final pulumi.Input<String> resourceType;

  /// Creates a new [BackupPlanArgs].
  /// [backupPlanId] The ID of the backup plan
  /// [backupRules] The backup rules for this `BackupPlan`.
  /// [backupVault] Backup vault where the backups gets stored using this Backup plan.
  /// [computeInstanceBackupPlanProperties] Defines optional compute instance related properties for backups generated by this plan.
  /// [deletionPolicy] Whether Terraform will be prevented from destroying the resource. Defaults to DELETE.
  /// [description] The description allows for additional details about `BackupPlan` and its use cases to be provided.
  /// [diskBackupPlanProperties] Defines optional disk related properties for backups generated by this plan.
  /// [location] The location for the backup plan
  /// [logRetentionDays] This is only applicable for CloudSql resource. Days for which logs will be stored. This value should be greater than or equal to minimum enforced log retention duration of the backup vault.
  /// [maxCustomOnDemandRetentionDays] The maximum number of days for which an on-demand backup taken with custom retention can be retained.
  /// [project] The ID of the project in which the resource belongs.
  /// [resourceType] The resource type to which the `BackupPlan` will be applied.
  const BackupPlanArgs({
    required this.backupPlanId,
    this.backupRules,
    required this.backupVault,
    this.computeInstanceBackupPlanProperties,
    this.deletionPolicy,
    this.description,
    this.diskBackupPlanProperties,
    required this.location,
    this.logRetentionDays,
    this.maxCustomOnDemandRetentionDays,
    this.project,
    required this.resourceType,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'backupPlanId': backupPlanId,
      'backupRules': ?pulumi.Input.mapOptionalInputValue<List<BackupPlanBackupRule>, List<Map<String, dynamic>>>(backupRules, (value) => pulumi.Input.encodeList<BackupPlanBackupRule, Map<String, dynamic>>(value, (value) => value.toMap())),
      'backupVault': backupVault,
      'computeInstanceBackupPlanProperties': ?pulumi.Input.mapOptionalInputValue<BackupPlanComputeInstanceBackupPlanProperties, Map<String, dynamic>>(computeInstanceBackupPlanProperties, (value) => value.toMap()),
      'deletionPolicy': ?deletionPolicy,
      'description': ?description,
      'diskBackupPlanProperties': ?pulumi.Input.mapOptionalInputValue<BackupPlanDiskBackupPlanProperties, Map<String, dynamic>>(diskBackupPlanProperties, (value) => value.toMap()),
      'location': location,
      'logRetentionDays': ?logRetentionDays,
      'maxCustomOnDemandRetentionDays': ?maxCustomOnDemandRetentionDays,
      'project': ?project,
      'resourceType': resourceType,
    };
  }

  factory BackupPlanArgs.fromMap(Map<String, dynamic> map) {
    return BackupPlanArgs(
      backupPlanId: pulumi.Input.fromValue(map['backupPlanId'] as String),
      backupRules: (() { final guardedValue = map['backupRules']; if (guardedValue == null) return null; return pulumi.Input.fromValue(pulumi.Input.decodeList<BackupPlanBackupRule>(guardedValue, (value) => BackupPlanBackupRule.fromMap((value as Map).cast<String, dynamic>()))); })(),
      backupVault: pulumi.Input.fromValue(map['backupVault'] as String),
      computeInstanceBackupPlanProperties: (() { final guardedValue = map['computeInstanceBackupPlanProperties']; if (guardedValue == null) return null; return pulumi.Input.fromValue(BackupPlanComputeInstanceBackupPlanProperties.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      deletionPolicy: (() { final guardedValue = map['deletionPolicy']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      description: (() { final guardedValue = map['description']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      diskBackupPlanProperties: (() { final guardedValue = map['diskBackupPlanProperties']; if (guardedValue == null) return null; return pulumi.Input.fromValue(BackupPlanDiskBackupPlanProperties.fromMap((guardedValue as Map).cast<String, dynamic>())); })(),
      location: pulumi.Input.fromValue(map['location'] as String),
      logRetentionDays: (() { final guardedValue = map['logRetentionDays']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      maxCustomOnDemandRetentionDays: (() { final guardedValue = map['maxCustomOnDemandRetentionDays']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      project: (() { final guardedValue = map['project']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      resourceType: pulumi.Input.fromValue(map['resourceType'] as String),
    );
  }
}
