// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'google_cloud_identitytoolkit_admin_v2_sp_certificate_response.dart';

/// The SAML SP (Service Provider) configuration when the project acts as the relying party to receive and accept an authentication assertion issued by a SAML identity provider.
class GoogleCloudIdentitytoolkitAdminV2SpConfigResponse {
  /// Callback URI where responses from IDP are handled.
  final String callbackUri;
  /// Public certificates generated by the server to verify the signature in SAMLRequest in the SP-initiated flow.
  final List<GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse> spCertificates;
  /// Unique identifier for all SAML entities.
  final String spEntityId;

  /// Creates a new [GoogleCloudIdentitytoolkitAdminV2SpConfigResponse].
  /// [callbackUri] Callback URI where responses from IDP are handled.
  /// [spCertificates] Public certificates generated by the server to verify the signature in SAMLRequest in the SP-initiated flow.
  /// [spEntityId] Unique identifier for all SAML entities.
  GoogleCloudIdentitytoolkitAdminV2SpConfigResponse({
    required this.callbackUri,
    required this.spCertificates,
    required this.spEntityId,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'callbackUri': callbackUri,
      'spCertificates': pulumi.Input.encodeList<GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse, Map<String, dynamic>>(spCertificates, (value) => value.toMap()),
      'spEntityId': spEntityId,
    };
  }

  factory GoogleCloudIdentitytoolkitAdminV2SpConfigResponse.fromMap(Map<String, dynamic> map) {
    return GoogleCloudIdentitytoolkitAdminV2SpConfigResponse(
      callbackUri: map['callbackUri'] as String,
      spCertificates: pulumi.Input.decodeList<GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse>(map['spCertificates'], (value) => GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse.fromMap((value as Map).cast<String, dynamic>())),
      spEntityId: map['spEntityId'] as String,
    );
  }
}

