library module_artifactregistry_repository_remote_repository_config_common_repository;

export 'repository_remote_repository_config_common_repository/repository_remote_repository_config_common_repository.dart';
