library module_artifactregistry_repository_remote_repository_config_apt_repository_public_repository;

export 'repository_remote_repository_config_apt_repository_public_repository/repository_remote_repository_config_apt_repository_public_repository.dart';
