library module_artifactregistry_repository_remote_repository_config_docker_repository_custom_repository;

export 'repository_remote_repository_config_docker_repository_custom_repository/repository_remote_repository_config_docker_repository_custom_repository.dart';
