library module_artifactregistry_repository_remote_repository_config_docker_repository;

export 'repository_remote_repository_config_docker_repository/repository_remote_repository_config_docker_repository.dart';
