library module_kendra_data_source_custom_document_enrichment_configuration_inline_configuration_target;

export 'data_source_custom_document_enrichment_configuration_inline_configuration_target.dart';
