library module_athena_workgroup_configuration_monitoring_configuration_cloud_watch_logging_configuration;

export 'workgroup_configuration_monitoring_configuration_cloud_watch_logging_configuration/workgroup_configuration_monitoring_configuration_cloud_watch_logging_configuration.dart';
