library module_modelarmor_template_filter_config_malicious_uri_filter_settings;

export 'template_filter_config_malicious_uri_filter_settings/template_filter_config_malicious_uri_filter_settings.dart';
