library module_sesv2_configuration_set_event_destination_event_destination_cloud_watch_destination_dimension_configuration;

export 'configuration_set_event_destination_event_destination_cloud_watch_destination_dimension_configuration.dart';
