/// Optional. The severity of an alert policy indicates how important alerts generated by that policy are. The severity level, if specified, will be displayed on the Incident detail page and in notifications.
enum AlertPolicySeverity {
  severityUnspecified("SEVERITY_UNSPECIFIED"),
  critical("CRITICAL"),
  error("ERROR"),
  warning("WARNING");

  const AlertPolicySeverity(this.value);
  final String value;

  static AlertPolicySeverity fromValue(String value) {
    for (final item in AlertPolicySeverity.values) {
      if (item.value == value) {
        return item;
      }
    }
    throw ArgumentError('Unknown AlertPolicySeverity value: $value');
  }
}
