library module_ec2_encryption_control_resource_exclusions_egress_only_internet_gateway;

export 'encryption_control_resource_exclusions_egress_only_internet_gateway/encryption_control_resource_exclusions_egress_only_internet_gateway.dart';
