library module_ec2_get_local_gateway_route_tables;

export 'get_local_gateway_route_tables/get_local_gateway_route_tables.dart';
export 'get_local_gateway_route_tables/get_local_gateway_route_tables_args.dart';
export 'get_local_gateway_route_tables/get_local_gateway_route_tables_result.dart';
