library module_ec2_managed_prefix_list_entry;

export 'managed_prefix_list_entry/managed_prefix_list_entry.dart';
export 'managed_prefix_list_entry/managed_prefix_list_entry_args.dart';
export 'managed_prefix_list_entry/managed_prefix_list_entry_ec2.dart';
