library module_ec2_vpc_encryption_control_resource_exclusions_virtual_private_gateway;

export 'vpc_encryption_control_resource_exclusions_virtual_private_gateway/vpc_encryption_control_resource_exclusions_virtual_private_gateway.dart';
