name: aws_dart_django_voting_app
description: Voting app using Django and MySQL on ECS.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
  pulumi_aws: ^7.20.0
  pulumi_docker: 4.11.0
  pulumi_mysql: 3.2.14

dev_dependencies:
  lints: ^6.1.0
