library module_quicksight_get_data_set_logical_table_map_data_transform_tag_column_operation_tag_column_description;

export 'get_data_set_logical_table_map_data_transform_tag_column_operation_tag_column_description.dart';
