name: aws_dart_ruby_on_rails
description: Ruby on Rails single-EC2 baseline in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
  pulumi_aws: any

dev_dependencies:
  lints: ^6.1.0