library module_lex_v2models_intent_qna_intent_configuration_data_source_configuration_bedrock_knowledge_store_configuration;

export 'v2models_intent_qna_intent_configuration_data_source_configuration_bedrock_knowledge_store_configuration.dart';
