library module_osconfig_v2_policy_orchestrator_orchestration_scope_selector_resource_hierarchy_selector;

export 'v2_policy_orchestrator_orchestration_scope_selector_resource_hierarchy_selector.dart';
