library module_bedrockmodel_invocation_logging_configuration_logging_config_cloudwatch_config;

export 'invocation_logging_configuration_logging_config_cloudwatch_config/invocation_logging_configuration_logging_config_cloudwatch_config.dart';
