library module_dataproc_cluster_virtual_cluster_config_auxiliary_services_config_spark_history_server_config;

export 'cluster_virtual_cluster_config_auxiliary_services_config_spark_history_server_config.dart';
