library module_clouddeploy_delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config_cloud_run;

export 'delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config_cloud_run/delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config_cloud_run.dart';
