library module_clouddeploy_delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config;

export 'delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config/delivery_pipeline_serial_pipeline_stage_strategy_canary_runtime_config.dart';
