library module_dataproc_cluster_cluster_config_preemptible_worker_config_disk_config;

export 'cluster_cluster_config_preemptible_worker_config_disk_config/cluster_cluster_config_preemptible_worker_config_disk_config.dart';
