library module_dataproc_cluster_cluster_config_gce_cluster_config_shielded_instance_config;

export 'cluster_cluster_config_gce_cluster_config_shielded_instance_config/cluster_cluster_config_gce_cluster_config_shielded_instance_config.dart';
