library module_dataproc_workflow_template_placement_managed_cluster_config_gce_cluster_config_shielded_instance_config;

export 'workflow_template_placement_managed_cluster_config_gce_cluster_config_shielded_instance_config/workflow_template_placement_managed_cluster_config_gce_cluster_config_shielded_instance_config.dart';
