library module_dataproc_workflow_template_placement_managed_cluster_config_master_config_accelerator;

export 'workflow_template_placement_managed_cluster_config_master_config_accelerator/workflow_template_placement_managed_cluster_config_master_config_accelerator.dart';
