library module_timestreamwrite_get_table_magnetic_store_write_property_magnetic_store_rejected_data_location_s3_configuration;

export 'get_table_magnetic_store_write_property_magnetic_store_rejected_data_location_s3_configuration.dart';
