name: pulumi_libvirt
description: A Pulumi provider dynamically bridged from libvirt.
version: 0.9.8
repository: https://github.com/dmacvicar/terraform-provider-libvirt
environment:
    sdk: '>=3.11.0 <4.0.0'
resolution: workspace
dependencies:
    pulumi: ^3.0.0
dev_dependencies:
    lints: ^6.1.0
