library module_backupdisasterrecovery_restore_workload_compute_instance_restore_properties_confidential_instance_config;

export 'restore_workload_compute_instance_restore_properties_confidential_instance_config/restore_workload_compute_instance_restore_properties_confidential_instance_config.dart';
