// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'cors_policy_compute_beta.dart';
import 'duration_compute_beta.dart';
import 'http_fault_injection_compute_beta.dart';
import 'http_retry_policy_compute_beta.dart';
import 'request_mirror_policy_compute_beta.dart';
import 'url_rewrite_compute_beta.dart';
import 'weighted_backend_service_compute_beta.dart';

class HttpRouteActionComputeBeta {
  /// The specification for allowing client-side cross-origin requests. For more information about the W3C recommendation for cross-origin resource sharing (CORS), see Fetch API Living Standard. Not supported when the URL map is bound to a target gRPC proxy.
  final CorsPolicyComputeBeta? corsPolicy;

  /// The specification for fault injection introduced into traffic to test the resiliency of clients to backend service failure. As part of fault injection, when clients send requests to a backend service, delays can be introduced by a load balancer on a percentage of requests before sending those requests to the backend service. Similarly requests from clients can be aborted by the load balancer for a percentage of requests. timeout and retry_policy is ignored by clients that are configured with a fault_injection_policy if: 1. The traffic is generated by fault injection AND 2. The fault injection is not a delay fault injection. Fault injection is not supported with the classic Application Load Balancer . To see which load balancers support fault injection, see Load balancing: Routing and traffic management features.
  final HttpFaultInjectionComputeBeta? faultInjectionPolicy;

  /// Specifies the maximum duration (timeout) for streams on the selected route. Unlike the timeout field where the timeout duration starts from the time the request has been fully processed (known as *end-of-stream*), the duration in this field is computed from the beginning of the stream until the response has been processed, including all retries. A stream that does not complete in this duration is closed. If not specified, this field uses the maximum maxStreamDuration value among all backend services associated with the route. This field is only allowed if the Url map is used with backend services with loadBalancingScheme set to INTERNAL_SELF_MANAGED.
  final DurationComputeBeta? maxStreamDuration;

  /// Specifies the policy on how requests intended for the route's backends are shadowed to a separate mirrored backend service. The load balancer does not wait for responses from the shadow service. Before sending traffic to the shadow service, the host / authority header is suffixed with -shadow. Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
  final RequestMirrorPolicyComputeBeta? requestMirrorPolicy;

  /// Specifies the retry policy associated with this route.
  final HttpRetryPolicyComputeBeta? retryPolicy;

  /// Specifies the timeout for the selected route. Timeout is computed from the time the request has been fully processed (known as *end-of-stream*) up until the response has been processed. Timeout includes all retries. If not specified, this field uses the largest timeout among all backend services associated with the route. Not supported when the URL map is bound to a target gRPC proxy that has validateForProxyless field set to true.
  final DurationComputeBeta? timeout;

  /// The spec to modify the URL of the request, before forwarding the request to the matched service. urlRewrite is the only action supported in UrlMaps for classic Application Load Balancers. Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
  final UrlRewriteComputeBeta? urlRewrite;

  /// A list of weighted backend services to send traffic to when a route match occurs. The weights determine the fraction of traffic that flows to their corresponding backend service. If all traffic needs to go to a single backend service, there must be one weightedBackendService with weight set to a non-zero number. After a backend service is identified and before forwarding the request to the backend service, advanced routing actions such as URL rewrites and header transformations are applied depending on additional settings specified in this HttpRouteAction.
  final List<WeightedBackendServiceComputeBeta>? weightedBackendServices;

  HttpRouteActionComputeBeta({
    this.corsPolicy,
    this.faultInjectionPolicy,
    this.maxStreamDuration,
    this.requestMirrorPolicy,
    this.retryPolicy,
    this.timeout,
    this.urlRewrite,
    this.weightedBackendServices,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    final corsPolicyValue = corsPolicy;
    if (corsPolicyValue != null) {
      map['corsPolicy'] = corsPolicyValue.toMap();
    }
    final faultInjectionPolicyValue = faultInjectionPolicy;
    if (faultInjectionPolicyValue != null) {
      map['faultInjectionPolicy'] = faultInjectionPolicyValue.toMap();
    }
    final maxStreamDurationValue = maxStreamDuration;
    if (maxStreamDurationValue != null) {
      map['maxStreamDuration'] = maxStreamDurationValue.toMap();
    }
    final requestMirrorPolicyValue = requestMirrorPolicy;
    if (requestMirrorPolicyValue != null) {
      map['requestMirrorPolicy'] = requestMirrorPolicyValue.toMap();
    }
    final retryPolicyValue = retryPolicy;
    if (retryPolicyValue != null) {
      map['retryPolicy'] = retryPolicyValue.toMap();
    }
    final timeoutValue = timeout;
    if (timeoutValue != null) {
      map['timeout'] = timeoutValue.toMap();
    }
    final urlRewriteValue = urlRewrite;
    if (urlRewriteValue != null) {
      map['urlRewrite'] = urlRewriteValue.toMap();
    }
    final weightedBackendServicesValue = weightedBackendServices;
    if (weightedBackendServicesValue != null) {
      map['weightedBackendServices'] = pulumi.Input.encodeList<
              WeightedBackendServiceComputeBeta, Map<String, dynamic>>(
          weightedBackendServicesValue, (value) => value.toMap());
    }
    return map;
  }

  factory HttpRouteActionComputeBeta.fromMap(Map<String, dynamic> map) {
    return HttpRouteActionComputeBeta(
      corsPolicy: map['corsPolicy'] == null
          ? null
          : CorsPolicyComputeBeta.fromMap(
              (map['corsPolicy'] as Map).cast<String, dynamic>()),
      faultInjectionPolicy: map['faultInjectionPolicy'] == null
          ? null
          : HttpFaultInjectionComputeBeta.fromMap(
              (map['faultInjectionPolicy'] as Map).cast<String, dynamic>()),
      maxStreamDuration: map['maxStreamDuration'] == null
          ? null
          : DurationComputeBeta.fromMap(
              (map['maxStreamDuration'] as Map).cast<String, dynamic>()),
      requestMirrorPolicy: map['requestMirrorPolicy'] == null
          ? null
          : RequestMirrorPolicyComputeBeta.fromMap(
              (map['requestMirrorPolicy'] as Map).cast<String, dynamic>()),
      retryPolicy: map['retryPolicy'] == null
          ? null
          : HttpRetryPolicyComputeBeta.fromMap(
              (map['retryPolicy'] as Map).cast<String, dynamic>()),
      timeout: map['timeout'] == null
          ? null
          : DurationComputeBeta.fromMap(
              (map['timeout'] as Map).cast<String, dynamic>()),
      urlRewrite: map['urlRewrite'] == null
          ? null
          : UrlRewriteComputeBeta.fromMap(
              (map['urlRewrite'] as Map).cast<String, dynamic>()),
      weightedBackendServices: map['weightedBackendServices'] == null
          ? null
          : pulumi.Input.decodeList<WeightedBackendServiceComputeBeta>(
              map['weightedBackendServices'],
              (value) => WeightedBackendServiceComputeBeta.fromMap(
                  (value as Map).cast<String, dynamic>())),
    );
  }
}
