import 'package:pulumi/pulumi.dart';
import 'customer_encryption_key_response2.dart';
import 'guest_os_feature_response2.dart';
import 'snapshot_args3.dart';

/// Creates a snapshot in the specified project using the data included in the request. For regular snapshot creation, consider using this method instead of disks.createSnapshot, as this method supports more features, such as creating snapshots in a project different from the source disk project.
class Snapshot3 extends CustomResource {
  /// The architecture of the snapshot. Valid values are ARM64 or X86_64.
  late final Output<String> architecture;

  /// Set to true if snapshots are automatically created by applying resource policy on the target disk.
  late final Output<bool> autoCreated;

  /// Creates the new snapshot in the snapshot chain labeled with the specified name. The chain name must be 1-63 characters long and comply with RFC1035. This is an uncommon option only for advanced service owners who needs to create separate snapshot chains, for example, for chargeback tracking. When you describe your snapshot resource, this field is visible only if it has a non-empty value.
  late final Output<String> chainName;

  /// Size in bytes of the snapshot at creation time.
  late final Output<String> creationSizeBytes;

  /// Creation timestamp in RFC3339 text format.
  late final Output<String> creationTimestamp;

  /// An optional description of this resource. Provide this property when you create the resource.
  late final Output<String> description;

  /// Size of the source disk, specified in GB.
  late final Output<String> diskSizeGb;

  /// Number of bytes downloaded to restore a snapshot to a disk.
  late final Output<String> downloadBytes;

  /// Whether this snapshot is created from a confidential compute mode disk. [Output Only]: This field is not set by user, but from source disk.
  late final Output<bool> enableConfidentialCompute;

  /// [Input Only] Whether to attempt an application consistent snapshot by informing the OS to prepare for the snapshot process.
  late final Output<bool> guestFlush;

  /// A list of features to enable on the guest operating system. Applicable only for bootable images. Read Enabling guest operating system features to see a list of available options.
  late final Output<List<GuestOsFeatureResponse2>> guestOsFeatures;

  /// Type of the resource. Always compute#snapshot for Snapshot resources.
  late final Output<String> kind;

  /// A fingerprint for the labels being applied to this snapshot, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error 412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve a snapshot.
  late final Output<String> labelFingerprint;

  /// Labels to apply to this snapshot. These can be later modified by the setLabels method. Label values may be empty.
  late final Output<Map<String, String>> labels;

  /// Integer license codes indicating which licenses are attached to this snapshot.
  late final Output<List<String>> licenseCodes;

  /// A list of public visible licenses that apply to this snapshot. This can be because the original image had licenses attached (such as a Windows image).
  late final Output<List<String>> licenses;

  /// An opaque location hint used to place the snapshot close to other resources. This field is for use by internal tools that use the public API.
  late final Output<String> locationHint;

  /// Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
  late final Output<String> name;
  late final Output<String> project;

  /// An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed. For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments. The request ID must be a valid UUID with the exception that zero UUID is not supported ( 00000000-0000-0000-0000-000000000000).
  late final Output<String?> requestId;

  /// Reserved for future use.
  late final Output<bool> satisfiesPzs;

  /// Server-defined URL for the resource.
  late final Output<String> selfLink;

  /// Encrypts the snapshot using a customer-supplied encryption key. After you encrypt a snapshot using a customer-supplied key, you must provide the same key if you use the snapshot later. For example, you must provide the encryption key when you create a disk from the encrypted snapshot in a future request. Customer-supplied encryption keys do not protect access to metadata of the snapshot. If you do not provide an encryption key when creating the snapshot, then the snapshot will be encrypted using an automatically generated key and you do not need to provide a key to use the snapshot later.
  late final Output<CustomerEncryptionKeyResponse2> snapshotEncryptionKey;

  /// Indicates the type of the snapshot.
  late final Output<String> snapshotType;

  /// The source disk used to create this snapshot.
  late final Output<String> sourceDisk;

  /// The customer-supplied encryption key of the source disk. Required if the source disk is protected by a customer-supplied encryption key.
  late final Output<CustomerEncryptionKeyResponse2> sourceDiskEncryptionKey;

  /// The source disk whose recovery checkpoint will be used to create this snapshot.
  late final Output<String> sourceDiskForRecoveryCheckpoint;

  /// The ID value of the disk used to create this snapshot. This value may be used to determine whether the snapshot was taken from the current or a previous instance of a given disk name.
  late final Output<String> sourceDiskId;

  /// The source instant snapshot used to create this snapshot. You can provide this as a partial or full URL to the resource. For example, the following are valid values: - https://www.googleapis.com/compute/v1/projects/project/zones/zone /instantSnapshots/instantSnapshot - projects/project/zones/zone/instantSnapshots/instantSnapshot - zones/zone/instantSnapshots/instantSnapshot
  late final Output<String> sourceInstantSnapshot;

  /// Customer provided encryption key when creating Snapshot from Instant Snapshot.
  late final Output<CustomerEncryptionKeyResponse2>
      sourceInstantSnapshotEncryptionKey;

  /// The unique ID of the instant snapshot used to create this snapshot. This value identifies the exact instant snapshot that was used to create this persistent disk. For example, if you created the persistent disk from an instant snapshot that was later deleted and recreated under the same name, the source instant snapshot ID would identify the exact instant snapshot that was used.
  late final Output<String> sourceInstantSnapshotId;

  /// URL of the resource policy which created this scheduled snapshot.
  late final Output<String> sourceSnapshotSchedulePolicy;

  /// ID of the resource policy which created this scheduled snapshot.
  late final Output<String> sourceSnapshotSchedulePolicyId;

  /// The status of the snapshot. This can be CREATING, DELETING, FAILED, READY, or UPLOADING.
  late final Output<String> status;

  /// A size of the storage used by the snapshot. As snapshots share storage, this number is expected to change with snapshot creation/deletion.
  late final Output<String> storageBytes;

  /// An indicator whether storageBytes is in a stable state or it is being adjusted as a result of shared storage reallocation. This status can either be UPDATING, meaning the size of the snapshot is being updated, or UP_TO_DATE, meaning the size of the snapshot is up-to-date.
  late final Output<String> storageBytesStatus;

  /// Cloud Storage bucket storage location of the snapshot (regional or multi-regional).
  late final Output<List<String>> storageLocations;

  /// A list of user provided licenses represented by a list of URLs to the license resource.
  late final Output<List<String>> userLicenses;

  Snapshot3(
    String name, {
    SnapshotArgs3? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:compute/beta:Snapshot',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.architecture = Output.createUnknown<String>();
    this.autoCreated = Output.createUnknown<bool>();
    this.chainName = Output.createUnknown<String>();
    this.creationSizeBytes = Output.createUnknown<String>();
    this.creationTimestamp = Output.createUnknown<String>();
    this.description = Output.createUnknown<String>();
    this.diskSizeGb = Output.createUnknown<String>();
    this.downloadBytes = Output.createUnknown<String>();
    this.enableConfidentialCompute = Output.createUnknown<bool>();
    this.guestFlush = Output.createUnknown<bool>();
    this.guestOsFeatures =
        Output.createUnknown<List<GuestOsFeatureResponse2>>();
    this.kind = Output.createUnknown<String>();
    this.labelFingerprint = Output.createUnknown<String>();
    this.labels = Output.createUnknown<Map<String, String>>();
    this.licenseCodes = Output.createUnknown<List<String>>();
    this.licenses = Output.createUnknown<List<String>>();
    this.locationHint = Output.createUnknown<String>();
    this.name = Output.createUnknown<String>();
    this.project = Output.createUnknown<String>();
    this.requestId = Output.createUnknown<String?>();
    this.satisfiesPzs = Output.createUnknown<bool>();
    this.selfLink = Output.createUnknown<String>();
    this.snapshotEncryptionKey =
        Output.createUnknown<CustomerEncryptionKeyResponse2>();
    this.snapshotType = Output.createUnknown<String>();
    this.sourceDisk = Output.createUnknown<String>();
    this.sourceDiskEncryptionKey =
        Output.createUnknown<CustomerEncryptionKeyResponse2>();
    this.sourceDiskForRecoveryCheckpoint = Output.createUnknown<String>();
    this.sourceDiskId = Output.createUnknown<String>();
    this.sourceInstantSnapshot = Output.createUnknown<String>();
    this.sourceInstantSnapshotEncryptionKey =
        Output.createUnknown<CustomerEncryptionKeyResponse2>();
    this.sourceInstantSnapshotId = Output.createUnknown<String>();
    this.sourceSnapshotSchedulePolicy = Output.createUnknown<String>();
    this.sourceSnapshotSchedulePolicyId = Output.createUnknown<String>();
    this.status = Output.createUnknown<String>();
    this.storageBytes = Output.createUnknown<String>();
    this.storageBytesStatus = Output.createUnknown<String>();
    this.storageLocations = Output.createUnknown<List<String>>();
    this.userLicenses = Output.createUnknown<List<String>>();
  }
}
