name: policy_dart_kubernetes
description: Dart policy pack example ported from policy-packs/kubernetes-ts.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  pulumi_policy: 1.0.0

dev_dependencies:
  lints: ^6.1.0
