import 'package:pulumi/pulumi.dart';
import 'execution_args.dart';

/// Creates an Execution associated with a MetadataStore.
/// Auto-naming is currently not supported for this resource.
class Execution extends CustomResource {
  /// Timestamp when this Execution was created.
  late final Output<String> createTime;

  /// Description of the Execution
  late final Output<String> description;

  /// User provided display name of the Execution. May be up to 128 Unicode characters.
  late final Output<String> displayName;

  /// An eTag used to perform consistent read-modify-write updates. If not set, a blind "overwrite" update happens.
  late final Output<String> etag;

  /// The {execution} portion of the resource name with the format: `projects/{project}/locations/{location}/metadataStores/{metadatastore}/executions/{execution}` If not provided, the Execution's ID will be a UUID generated by the service. Must be 4-128 characters in length. Valid characters are `/a-z-/`. Must be unique across all Executions in the parent MetadataStore. (Otherwise the request will fail with ALREADY_EXISTS, or PERMISSION_DENIED if the caller can't view the preexisting Execution.)
  late final Output<String?> executionId;

  /// The labels with user-defined metadata to organize your Executions. Label keys and values can be no longer than 64 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes. International characters are allowed. No more than 64 user labels can be associated with one Execution (System labels are excluded).
  late final Output<Map<String, String>> labels;
  late final Output<String> location;

  /// Properties of the Execution. Top level metadata keys' heading and trailing spaces will be trimmed. The size of this field should not exceed 200KB.
  late final Output<Map<String, String>> metadata;
  late final Output<String> metadataStoreId;

  /// The resource name of the Execution.
  late final Output<String> name;
  late final Output<String> project;

  /// The title of the schema describing the metadata. Schema title and version is expected to be registered in earlier Create Schema calls. And both are used together as unique identifiers to identify schemas within the local metadata store.
  late final Output<String> schemaTitle;

  /// The version of the schema in `schema_title` to use. Schema title and version is expected to be registered in earlier Create Schema calls. And both are used together as unique identifiers to identify schemas within the local metadata store.
  late final Output<String> schemaVersion;

  /// The state of this Execution. This is a property of the Execution, and does not imply or capture any ongoing process. This property is managed by clients (such as Vertex AI Pipelines) and the system does not prescribe or check the validity of state transitions.
  late final Output<String> state;

  /// Timestamp when this Execution was last updated.
  late final Output<String> updateTime;

  Execution(
    String name, {
    ExecutionArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:aiplatform/v1:Execution',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.createTime = registerOutput<String>('createTime');
    this.description = registerOutput<String>('description');
    this.displayName = registerOutput<String>('displayName');
    this.etag = registerOutput<String>('etag');
    this.executionId = registerOutput<String?>('executionId');
    this.labels = registerOutput<Map<String, String>>('labels');
    this.location = registerOutput<String>('location');
    this.metadata = registerOutput<Map<String, String>>('metadata');
    this.metadataStoreId = registerOutput<String>('metadataStoreId');
    this.name = registerOutput<String>('name');
    this.project = registerOutput<String>('project');
    this.schemaTitle = registerOutput<String>('schemaTitle');
    this.schemaVersion = registerOutput<String>('schemaVersion');
    this.state = registerOutput<String>('state');
    this.updateTime = registerOutput<String>('updateTime');
  }
}
