// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' hide Config;
import 'metadata_schema_schema_type.dart';

/// The set of arguments for MetadataSchema.
class MetadataSchemaArgs {
  /// Description of the Metadata Schema
  final Input<String>? description;
  final Input<String>? location;

  /// The {metadata_schema} portion of the resource name with the format: `projects/{project}/locations/{location}/metadataStores/{metadatastore}/metadataSchemas/{metadataschema}` If not provided, the MetadataStore's ID will be a UUID generated by the service. Must be 4-128 characters in length. Valid characters are `/a-z-/`. Must be unique across all MetadataSchemas in the parent Location. (Otherwise the request will fail with ALREADY_EXISTS, or PERMISSION_DENIED if the caller can't view the preexisting MetadataSchema.)
  final Input<String>? metadataSchemaId;
  final Input<String> metadataStoreId;
  final Input<String>? project;

  /// The raw YAML string representation of the MetadataSchema. The combination of [MetadataSchema.version] and the schema name given by `title` in [MetadataSchema.schema] must be unique within a MetadataStore. The schema is defined as an OpenAPI 3.0.2 [MetadataSchema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject)
  final Input<String> schema;

  /// The type of the MetadataSchema. This is a property that identifies which metadata types will use the MetadataSchema.
  final Input<MetadataSchemaSchemaType>? schemaType;

  /// The version of the MetadataSchema. The version's format must match the following regular expression: `^[0-9]+.+.+$`, which would allow to order/compare different versions. Example: 1.0.0, 1.0.1, etc.
  final Input<String>? schemaVersion;

  MetadataSchemaArgs({
    this.description,
    this.location,
    this.metadataSchemaId,
    required this.metadataStoreId,
    this.project,
    required this.schema,
    this.schemaType,
    this.schemaVersion,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    final descriptionValue = description;
    if (descriptionValue != null) {
      map['description'] = descriptionValue;
    }
    final locationValue = location;
    if (locationValue != null) {
      map['location'] = locationValue;
    }
    final metadataSchemaIdValue = metadataSchemaId;
    if (metadataSchemaIdValue != null) {
      map['metadataSchemaId'] = metadataSchemaIdValue;
    }
    map['metadataStoreId'] = metadataStoreId;
    final projectValue = project;
    if (projectValue != null) {
      map['project'] = projectValue;
    }
    map['schema'] = schema;
    final schemaTypeValue = schemaType;
    if (schemaTypeValue != null) {
      map['schemaType'] =
          Input.mapOptionalInputValue<MetadataSchemaSchemaType, String>(
              schemaTypeValue, (value) => value.value);
    }
    final schemaVersionValue = schemaVersion;
    if (schemaVersionValue != null) {
      map['schemaVersion'] = schemaVersionValue;
    }
    return map;
  }

  factory MetadataSchemaArgs.fromMap(Map<String, dynamic> map) {
    return MetadataSchemaArgs(
      description: Input.asOptionalInput<String>(map['description']),
      location: Input.asOptionalInput<String>(map['location']),
      metadataSchemaId: Input.asOptionalInput<String>(map['metadataSchemaId']),
      metadataStoreId: Input.asInput<String>(map['metadataStoreId']),
      project: Input.asOptionalInput<String>(map['project']),
      schema: Input.asInput<String>(map['schema']),
      schemaType:
          Input.asOptionalInput<MetadataSchemaSchemaType>(map['schemaType']),
      schemaVersion: Input.asOptionalInput<String>(map['schemaVersion']),
    );
  }
}
