name: aws_dart_serverless_datawarehouse
description: Serverless analytics baseline on AWS in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
  pulumi_aws: any

dev_dependencies:
  lints: ^6.1.0