name: mysql_dart_user_database
description: Pulumi mysql user and database example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  pulumi: 3.0.0
  pulumi_mysql: 3.2.14

dev_dependencies:
  lints: ^6.1.0
