library module_lex_v2models_intent_initial_response_setting_initial_response_message_group_message_plain_text_message;

export 'v2models_intent_initial_response_setting_initial_response_message_group_message_plain_text_message.dart';
