name: aliases_retype_parents
description: A Dart integration test fixture for nested parent retype aliases.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  pulumi:
    path: ../../../../pulumi-dart

dev_dependencies:
  lints: ^6.1.0
