import 'package:pulumi/pulumi.dart' as pulumi;
import 'tenant_jobs_v4_args.dart';

/// Creates a new tenant entity.
class TenantJobsV4 extends pulumi.CustomResource {
  /// Client side tenant identifier, used to uniquely identify the tenant. The maximum number of allowed characters is 255.
  late final pulumi.Output<String> externalId;

  /// Required during tenant update. The resource name for a tenant. This is generated by the service when a tenant is created. The format is "projects/{project_id}/tenants/{tenant_id}", for example, "projects/foo/tenants/bar".
  late final pulumi.Output<String> name;
  late final pulumi.Output<String> project;

  TenantJobsV4(
    String name, {
    TenantJobsV4Args? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'google-native:jobs/v4:Tenant',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.externalId = registerOutput<String>('externalId');
    this.name = registerOutput<String>('name');
    this.project = registerOutput<String>('project');
  }
}
