library module_dlm_lifecycle_policy_policy_details_action_cross_region_copy_retain_rule;

export 'lifecycle_policy_policy_details_action_cross_region_copy_retain_rule/lifecycle_policy_policy_details_action_cross_region_copy_retain_rule.dart';
