library module_secretmanager_get_regional_secret_version;

export 'get_regional_secret_version/get_regional_secret_version.dart';
export 'get_regional_secret_version/get_regional_secret_version_args.dart';
export 'get_regional_secret_version/get_regional_secret_version_result.dart';
