library module_secretmanager_get_regional_secret_version_access;

export 'get_regional_secret_version_access/get_regional_secret_version_access.dart';
export 'get_regional_secret_version_access/get_regional_secret_version_access_args.dart';
export 'get_regional_secret_version_access/get_regional_secret_version_access_result.dart';
