library module_lex_v2models_slot_sub_slot_setting_slot_specification_value_elicitation_setting_prompt_specification;

export 'v2models_slot_sub_slot_setting_slot_specification_value_elicitation_setting_prompt_specification.dart';
