library module_cloudwatch_get_log_data_protection_policy_document_statement_operation_audit_findings_destination_firehose;

export 'get_log_data_protection_policy_document_statement_operation_audit_findings_destination_firehose.dart';
