library module_lex_v2models_intent_confirmation_setting_code_hook_post_code_hook_specification_failure_conditional_default_branch_response;

export 'v2models_intent_confirmation_setting_code_hook_post_code_hook_specification_failure_conditional_default_branch_response.dart';
