// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering CryptoKeyIAMPolicy resources.
class CryptoKeyIAMPolicyState {
  /// The crypto key ID, in the form
  /// `{project_id}/{location_name}/{key_ring_name}/{crypto_key_name}` or
  /// `{location_name}/{key_ring_name}/{crypto_key_name}`. In the second form,
  /// the provider's project setting will be used as a fallback.
  final pulumi.Input<String>? cryptoKeyId;
  /// (Computed) The etag of the project's IAM policy.
  final pulumi.Input<String>? etag;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;

  /// Creates a new [CryptoKeyIAMPolicyState].
  /// [cryptoKeyId] The crypto key ID, in the form
  /// [etag] (Computed) The etag of the project's IAM policy.
  /// [policyData] The policy data generated by
  CryptoKeyIAMPolicyState({
    pulumi.Output<String>? cryptoKeyId,
    pulumi.Output<String>? etag,
    pulumi.Output<String>? policyData,
  }) :
      cryptoKeyId = pulumi.Input.asOptionalInput<String>(cryptoKeyId),
      etag = pulumi.Input.asOptionalInput<String>(etag),
      policyData = pulumi.Input.asOptionalInput<String>(policyData);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'cryptoKeyId': ?cryptoKeyId,
      'etag': ?etag,
      'policyData': ?policyData,
    };
  }

  factory CryptoKeyIAMPolicyState.fromMap(Map<String, dynamic> map) {
    return CryptoKeyIAMPolicyState(
      cryptoKeyId: map['cryptoKeyId'] == null ? null : pulumi.Output.create<String>(map['cryptoKeyId'] as String),
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
    );
  }
}

