// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_kms_crypto_key_iampolicy_crypto_key_iampolicy_args_doc}
/// The set of arguments for CryptoKeyIAMPolicy.
/// {@endtemplate}
/// {@macro pulumi_kms_crypto_key_iampolicy_crypto_key_iampolicy_args_doc}
class CryptoKeyIAMPolicyArgs {
  /// The crypto key ID, in the form
  /// `{project_id}/{location_name}/{key_ring_name}/{crypto_key_name}` or
  /// `{location_name}/{key_ring_name}/{crypto_key_name}`. In the second form,
  /// the provider's project setting will be used as a fallback.
  final pulumi.Input<String> cryptoKeyId;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// Creates a new [CryptoKeyIAMPolicyArgs].
  /// [cryptoKeyId] The crypto key ID, in the form
  /// [policyData] The policy data generated by
  CryptoKeyIAMPolicyArgs({
    required pulumi.Output<String> cryptoKeyId,
    required pulumi.Output<String> policyData,
  }) :
      cryptoKeyId = pulumi.Input.asInput<String>(cryptoKeyId),
      policyData = pulumi.Input.asInput<String>(policyData);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'cryptoKeyId': cryptoKeyId,
      'policyData': policyData,
    };
  }

  factory CryptoKeyIAMPolicyArgs.fromMap(Map<String, dynamic> map) {
    return CryptoKeyIAMPolicyArgs(
      cryptoKeyId: pulumi.Output.create<String>(map['cryptoKeyId'] as String),
      policyData: pulumi.Output.create<String>(map['policyData'] as String),
    );
  }
}

