// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering KeyRingIAMPolicy resources.
class KeyRingIAMPolicyState {
  /// (Computed) The etag of the key ring's IAM policy.
  final pulumi.Input<String>? etag;
  /// The key ring ID, in the form
  /// `{project_id}/{location_name}/{key_ring_name}` or
  /// `{location_name}/{key_ring_name}`. In the second form, the provider's
  /// project setting will be used as a fallback.
  final pulumi.Input<String>? keyRingId;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;

  /// Creates a new [KeyRingIAMPolicyState].
  /// [etag] (Computed) The etag of the key ring's IAM policy.
  /// [keyRingId] The key ring ID, in the form
  /// [policyData] The policy data generated by
  KeyRingIAMPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? keyRingId,
    pulumi.Output<String>? policyData,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      keyRingId = pulumi.Input.asOptionalInput<String>(keyRingId),
      policyData = pulumi.Input.asOptionalInput<String>(policyData);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'keyRingId': ?keyRingId,
      'policyData': ?policyData,
    };
  }

  factory KeyRingIAMPolicyState.fromMap(Map<String, dynamic> map) {
    return KeyRingIAMPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      keyRingId: map['keyRingId'] == null ? null : pulumi.Output.create<String>(map['keyRingId'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
    );
  }
}

