library module_wafv2_rule_group_rule_statement_rate_based_statement_scope_down_statement_geo_match_statement_forwarded_ip_config;

export 'rule_group_rule_statement_rate_based_statement_scope_down_statement_geo_match_statement_forwarded_ip_config.dart';
