library module_kinesisanalyticsv2_application_application_configuration_sql_application_configuration_input_input_schema_record_format;

export 'application_application_configuration_sql_application_configuration_input_input_schema_record_format.dart';
