// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'schema_bundle_proto_schema.dart';

/// {@template pulumi_bigtable_schema_bundle_schema_bundle_args_doc}
/// The set of arguments for SchemaBundle.
/// {@endtemplate}
/// {@macro pulumi_bigtable_schema_bundle_schema_bundle_args_doc}
class SchemaBundleArgs {
  /// If true, allow backwards incompatible changes.
  final pulumi.Input<bool>? ignoreWarnings;

  /// The name of the instance to create the schema bundle within.
  final pulumi.Input<String>? instance;

  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the provider project is used.
  final pulumi.Input<String>? project;

  /// File descriptor set, generated by protoc.
  /// To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.
  /// $ protoc --include_imports --include_source_info test.proto -o out.pb
  /// Structure is documented below.
  final pulumi.Input<SchemaBundleProtoSchema> protoSchema;

  /// The unique name of the schema bundle in the form `[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  final pulumi.Input<String> schemaBundleId;

  /// The name of the table to create the schema bundle within.
  final pulumi.Input<String>? table;

  /// Creates a new [SchemaBundleArgs].
  /// [ignoreWarnings] If true, allow backwards incompatible changes.
  /// [instance] The name of the instance to create the schema bundle within.
  /// [project] The ID of the project in which the resource belongs.
  /// [protoSchema] File descriptor set, generated by protoc.
  /// [schemaBundleId] The unique name of the schema bundle in the form `[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  /// [table] The name of the table to create the schema bundle within.
  SchemaBundleArgs({
    bool? ignoreWarnings,
    String? instance,
    String? project,
    required SchemaBundleProtoSchema protoSchema,
    required String schemaBundleId,
    String? table,
  }) : ignoreWarnings = pulumi.Input.asOptionalInput<bool>(ignoreWarnings),
       instance = pulumi.Input.asOptionalInput<String>(instance),
       project = pulumi.Input.asOptionalInput<String>(project),
       protoSchema = pulumi.Input.asInput<SchemaBundleProtoSchema>(protoSchema),
       schemaBundleId = pulumi.Input.asInput<String>(schemaBundleId),
       table = pulumi.Input.asOptionalInput<String>(table);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'ignoreWarnings': ?ignoreWarnings,
      'instance': ?instance,
      'project': ?project,
      'protoSchema':
          pulumi.Input.mapInputValue<
            SchemaBundleProtoSchema,
            Map<String, dynamic>
          >(protoSchema, (value) => value.toMap()),
      'schemaBundleId': schemaBundleId,
      'table': ?table,
    };
  }

  factory SchemaBundleArgs.fromMap(Map<String, dynamic> map) {
    return SchemaBundleArgs(
      ignoreWarnings: map['ignoreWarnings'] == null
          ? null
          : map['ignoreWarnings'] as bool,
      instance: map['instance'] == null ? null : map['instance'] as String,
      project: map['project'] == null ? null : map['project'] as String,
      protoSchema: SchemaBundleProtoSchema.fromMap(
        (map['protoSchema'] as Map).cast<String, dynamic>(),
      ),
      schemaBundleId: map['schemaBundleId'] as String,
      table: map['table'] == null ? null : map['table'] as String,
    );
  }
}
