library module_securityhub_automation_rule_criteria_first_observed_at_date_range;

export 'automation_rule_criteria_first_observed_at_date_range/automation_rule_criteria_first_observed_at_date_range.dart';
