library module_securityhub_automation_rule_criteria_compliance_associated_standards_id;

export 'automation_rule_criteria_compliance_associated_standards_id/automation_rule_criteria_compliance_associated_standards_id.dart';
