library module_securityhub_configuration_policy_configuration_policy_security_controls_configuration_security_control_custom_parameter_parameter_bool;

export 'configuration_policy_configuration_policy_security_controls_configuration_security_control_custom_parameter_parameter_bool/configuration_policy_configuration_policy_security_controls_configuration_security_control_custom_parameter_parameter_bool.dart';
