name: gcp_dart_cloud_run_deploy
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: ^3.0.0
  pulumi_docker: 5.2.0+1
  pulumi_gcp: 9.35.1+1

dev_dependencies:
  lints: ^6.1.0
