library module_bedrock_agent_prompt_variant_template_configuration_chat_tool_configuration_tool_tool_spec_input_schema;

export 'agent_prompt_variant_template_configuration_chat_tool_configuration_tool_tool_spec_input_schema.dart';
