library module_appmesh_get_gateway_route_spec_grpc_route_action_target_virtual_service;

export 'get_gateway_route_spec_grpc_route_action_target_virtual_service/get_gateway_route_spec_grpc_route_action_target_virtual_service.dart';
