library module_appmesh_get_virtual_node_spec_backend_default_client_policy_tl_certificate_file;

export 'get_virtual_node_spec_backend_default_client_policy_tl_certificate_file/get_virtual_node_spec_backend_default_client_policy_tl_certificate_file.dart';
