library module_appmesh_virtual_node_spec_backend_virtual_service_client_policy_tls_certificate_file;

export 'virtual_node_spec_backend_virtual_service_client_policy_tls_certificate_file/virtual_node_spec_backend_virtual_service_client_policy_tls_certificate_file.dart';
