library module_appmesh_virtual_node_spec_backend_virtual_service_client_policy;

export 'virtual_node_spec_backend_virtual_service_client_policy/virtual_node_spec_backend_virtual_service_client_policy.dart';
