library module_appmesh_virtual_gateway_spec_backend_defaults_client_policy_tls_validation_subject_alternative_names_match;

export 'virtual_gateway_spec_backend_defaults_client_policy_tls_validation_subject_alternative_names_match/virtual_gateway_spec_backend_defaults_client_policy_tls_validation_subject_alternative_names_match.dart';
