// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'cloud_control_parameter_spec.dart';
import 'cloud_control_rule.dart';

/// {@template pulumi_cloudsecuritycompliance_cloud_control_cloud_control_args_doc}
/// The set of arguments for CloudControl.
/// {@endtemplate}
/// {@macro pulumi_cloudsecuritycompliance_cloud_control_cloud_control_args_doc}
class CloudControlArgs {
  /// The categories of the cloud control.
  final pulumi.Input<List<String>>? categories;
  /// ID of the CloudControl.
  /// This is the last segment of the CloudControl resource name.
  /// Format: `^a-zA-Z{0,61}[a-zA-Z0-9]$`.
  final pulumi.Input<String> cloudControlId;
  /// A description of the cloud control. The maximum length is 2000 characters.
  final pulumi.Input<String>? description;
  /// The display name of the cloud control. The maximum length is 200
  /// characters.
  final pulumi.Input<String>? displayName;
  /// The finding_category of the cloud control. The maximum length is 255
  /// characters.
  final pulumi.Input<String>? findingCategory;
  /// Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122. Currently, only "global" is supported as a location.
  final pulumi.Input<String> location;
  /// Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  final pulumi.Input<String> organization;
  /// The parameter spec of the cloud control.
  /// Structure is documented below.
  final pulumi.Input<List<CloudControlParameterSpec>>? parameterSpecs;
  /// The remediation steps for the findings generated by the cloud control. The
  /// maximum length is 400 characters.
  final pulumi.Input<String>? remediationSteps;
  /// The Policy to be enforced to prevent/detect resource non-compliance.
  /// Structure is documented below.
  final pulumi.Input<List<CloudControlRule>>? rules;
  /// Possible values:
  /// CRITICAL
  /// HIGH
  /// MEDIUM
  /// LOW
  final pulumi.Input<String>? severity;
  /// cloud providers supported
  final pulumi.Input<List<String>>? supportedCloudProviders;

  /// Creates a new [CloudControlArgs].
  /// [categories] The categories of the cloud control.
  /// [cloudControlId] ID of the CloudControl.
  /// [description] A description of the cloud control. The maximum length is 2000 characters.
  /// [displayName] The display name of the cloud control. The maximum length is 200
  /// [findingCategory] The finding_category of the cloud control. The maximum length is 255
  /// [location] Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122. Currently, only "global" is supported as a location.
  /// [organization] Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
  /// [parameterSpecs] The parameter spec of the cloud control.
  /// [remediationSteps] The remediation steps for the findings generated by the cloud control. The
  /// [rules] The Policy to be enforced to prevent/detect resource non-compliance.
  /// [severity] Possible values:
  /// [supportedCloudProviders] cloud providers supported
  CloudControlArgs({
    this.categories,
    required this.cloudControlId,
    this.description,
    this.displayName,
    this.findingCategory,
    required this.location,
    required this.organization,
    this.parameterSpecs,
    this.remediationSteps,
    this.rules,
    this.severity,
    this.supportedCloudProviders,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'categories': ?categories,
      'cloudControlId': cloudControlId,
      'description': ?description,
      'displayName': ?displayName,
      'findingCategory': ?findingCategory,
      'location': location,
      'organization': organization,
      'parameterSpecs': ?pulumi.Input.mapOptionalInputValue<List<CloudControlParameterSpec>, List<Map<String, dynamic>>>(parameterSpecs, (value) => pulumi.Input.encodeList<CloudControlParameterSpec, Map<String, dynamic>>(value, (value) => value.toMap())),
      'remediationSteps': ?remediationSteps,
      'rules': ?pulumi.Input.mapOptionalInputValue<List<CloudControlRule>, List<Map<String, dynamic>>>(rules, (value) => pulumi.Input.encodeList<CloudControlRule, Map<String, dynamic>>(value, (value) => value.toMap())),
      'severity': ?severity,
      'supportedCloudProviders': ?supportedCloudProviders,
    };
  }

  factory CloudControlArgs.fromMap(Map<String, dynamic> map) {
    return CloudControlArgs(
      categories: map['categories'] == null ? null : ((map['categories']! as List).cast<String>()).input(),
      cloudControlId: (map['cloudControlId'] as String).input(),
      description: map['description'] == null ? null : (map['description']! as String).input(),
      displayName: map['displayName'] == null ? null : (map['displayName']! as String).input(),
      findingCategory: map['findingCategory'] == null ? null : (map['findingCategory']! as String).input(),
      location: (map['location'] as String).input(),
      organization: (map['organization'] as String).input(),
      parameterSpecs: map['parameterSpecs'] == null ? null : (pulumi.Input.decodeList<CloudControlParameterSpec>(map['parameterSpecs']!, (value) => CloudControlParameterSpec.fromMap((value as Map).cast<String, dynamic>()))).input(),
      remediationSteps: map['remediationSteps'] == null ? null : (map['remediationSteps']! as String).input(),
      rules: map['rules'] == null ? null : (pulumi.Input.decodeList<CloudControlRule>(map['rules']!, (value) => CloudControlRule.fromMap((value as Map).cast<String, dynamic>()))).input(),
      severity: map['severity'] == null ? null : (map['severity']! as String).input(),
      supportedCloudProviders: map['supportedCloudProviders'] == null ? null : ((map['supportedCloudProviders']! as List).cast<String>()).input(),
    );
  }
}

