library module_discoveryengine_data_store_document_processing_config_default_parsing_config_ocr_parsing_config;

export 'data_store_document_processing_config_default_parsing_config_ocr_parsing_config.dart';
