name: aws_dart_containers_dockerbuild
description: Pulumi AWS ECS containers example with Docker Build.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: ^3.0.0
  pulumi_aws: ^7.20.0
  pulumi_awsx: 3.8.0+1
  pulumi_docker_build: 0.0.22+1

dev_dependencies:
  lints: ^6.1.0
