library module_kendra_data_source_configuration_web_crawler_configuration_proxy_configuration;

export 'data_source_configuration_web_crawler_configuration_proxy_configuration/data_source_configuration_web_crawler_configuration_proxy_configuration.dart';
