library module_kendra_data_source_configuration_s3_configuration_documents_metadata_configuration;

export 'data_source_configuration_s3_configuration_documents_metadata_configuration/data_source_configuration_s3_configuration_documents_metadata_configuration.dart';
