library module_kendra_query_suggestions_block_list;

export 'query_suggestions_block_list/query_suggestions_block_list.dart';
export 'query_suggestions_block_list/query_suggestions_block_list_args.dart';
