library module_lex_v2models_intent_qna_intent_configuration_data_source_configuration_opensearch_configuration_exact_response_fields;

export 'v2models_intent_qna_intent_configuration_data_source_configuration_opensearch_configuration_exact_response_fields.dart';
