library module_appsync_channel_namespace_handler_configs_on_publish_integration_lambda_config;

export 'channel_namespace_handler_configs_on_publish_integration_lambda_config/channel_namespace_handler_configs_on_publish_integration_lambda_config.dart';
