library module_networkservices_edge_cache_service_routing_path_matcher_route_rule_url_redirect;

export 'edge_cache_service_routing_path_matcher_route_rule_url_redirect/edge_cache_service_routing_path_matcher_route_rule_url_redirect.dart';
