library module_migrationcenter_preference_set_virtual_machine_preferences_sole_tenancy_preferences_node_type;

export 'preference_set_virtual_machine_preferences_sole_tenancy_preferences_node_type/preference_set_virtual_machine_preferences_sole_tenancy_preferences_node_type.dart';
