library module_migrationcenter_preference_set_virtual_machine_preferences_sole_tenancy_preferences;

export 'preference_set_virtual_machine_preferences_sole_tenancy_preferences/preference_set_virtual_machine_preferences_sole_tenancy_preferences.dart';
