name: azure_dart_vm_scaleset
description: Azure VM Scale Set example with load balancer and autoscaling.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: 3.0.0
  pulumi_azure: 6.33.0
  pulumi_random: 4.19.1

dev_dependencies:
  lints: ^6.1.0
