// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Specifies Kerberos related configuration.
class KerberosConfig {
  /// Optional. The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  final pulumi.Input<String>? crossRealmTrustAdminServer;
  /// Optional. The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  final pulumi.Input<String>? crossRealmTrustKdc;
  /// Optional. The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.
  final pulumi.Input<String>? crossRealmTrustRealm;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship.
  final pulumi.Input<String>? crossRealmTrustSharedPasswordUri;
  /// Optional. Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.
  final pulumi.Input<bool>? enableKerberos;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database.
  final pulumi.Input<String>? kdcDbKeyUri;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc.
  final pulumi.Input<String>? keyPasswordUri;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc.
  final pulumi.Input<String>? keystorePasswordUri;
  /// Optional. The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  final pulumi.Input<String>? keystoreUri;
  /// Optional. The uri of the KMS key used to encrypt various sensitive files.
  final pulumi.Input<String>? kmsKeyUri;
  /// Optional. The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.
  final pulumi.Input<String>? realm;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the root principal password.
  final pulumi.Input<String>? rootPrincipalPasswordUri;
  /// Optional. The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.
  final pulumi.Input<int>? tgtLifetimeHours;
  /// Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.
  final pulumi.Input<String>? truststorePasswordUri;
  /// Optional. The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  final pulumi.Input<String>? truststoreUri;

  /// Creates a new [KerberosConfig].
  /// [crossRealmTrustAdminServer] Optional. The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  /// [crossRealmTrustKdc] Optional. The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.
  /// [crossRealmTrustRealm] Optional. The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.
  /// [crossRealmTrustSharedPasswordUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship.
  /// [enableKerberos] Optional. Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.
  /// [kdcDbKeyUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database.
  /// [keyPasswordUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc.
  /// [keystorePasswordUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc.
  /// [keystoreUri] Optional. The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  /// [kmsKeyUri] Optional. The uri of the KMS key used to encrypt various sensitive files.
  /// [realm] Optional. The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.
  /// [rootPrincipalPasswordUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the root principal password.
  /// [tgtLifetimeHours] Optional. The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.
  /// [truststorePasswordUri] Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.
  /// [truststoreUri] Optional. The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.
  const KerberosConfig({
    this.crossRealmTrustAdminServer,
    this.crossRealmTrustKdc,
    this.crossRealmTrustRealm,
    this.crossRealmTrustSharedPasswordUri,
    this.enableKerberos,
    this.kdcDbKeyUri,
    this.keyPasswordUri,
    this.keystorePasswordUri,
    this.keystoreUri,
    this.kmsKeyUri,
    this.realm,
    this.rootPrincipalPasswordUri,
    this.tgtLifetimeHours,
    this.truststorePasswordUri,
    this.truststoreUri,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'crossRealmTrustAdminServer': ?crossRealmTrustAdminServer,
      'crossRealmTrustKdc': ?crossRealmTrustKdc,
      'crossRealmTrustRealm': ?crossRealmTrustRealm,
      'crossRealmTrustSharedPasswordUri': ?crossRealmTrustSharedPasswordUri,
      'enableKerberos': ?enableKerberos,
      'kdcDbKeyUri': ?kdcDbKeyUri,
      'keyPasswordUri': ?keyPasswordUri,
      'keystorePasswordUri': ?keystorePasswordUri,
      'keystoreUri': ?keystoreUri,
      'kmsKeyUri': ?kmsKeyUri,
      'realm': ?realm,
      'rootPrincipalPasswordUri': ?rootPrincipalPasswordUri,
      'tgtLifetimeHours': ?tgtLifetimeHours,
      'truststorePasswordUri': ?truststorePasswordUri,
      'truststoreUri': ?truststoreUri,
    };
  }

  factory KerberosConfig.fromMap(Map<String, dynamic> map) {
    return KerberosConfig(
      crossRealmTrustAdminServer: (() { final guardedValue = map['crossRealmTrustAdminServer']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      crossRealmTrustKdc: (() { final guardedValue = map['crossRealmTrustKdc']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      crossRealmTrustRealm: (() { final guardedValue = map['crossRealmTrustRealm']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      crossRealmTrustSharedPasswordUri: (() { final guardedValue = map['crossRealmTrustSharedPasswordUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      enableKerberos: (() { final guardedValue = map['enableKerberos']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as bool); })(),
      kdcDbKeyUri: (() { final guardedValue = map['kdcDbKeyUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      keyPasswordUri: (() { final guardedValue = map['keyPasswordUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      keystorePasswordUri: (() { final guardedValue = map['keystorePasswordUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      keystoreUri: (() { final guardedValue = map['keystoreUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      kmsKeyUri: (() { final guardedValue = map['kmsKeyUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      realm: (() { final guardedValue = map['realm']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      rootPrincipalPasswordUri: (() { final guardedValue = map['rootPrincipalPasswordUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      tgtLifetimeHours: (() { final guardedValue = map['tgtLifetimeHours']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      truststorePasswordUri: (() { final guardedValue = map['truststorePasswordUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      truststoreUri: (() { final guardedValue = map['truststoreUri']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
