import 'package:pulumi/pulumi.dart';
import 'criteria_response.dart';
import 'snooze_args.dart';
import 'time_interval_response.dart';

/// Creates a Snooze that will prevent alerts, which match the provided criteria, from being opened. The Snooze applies for a specific time interval.
/// Note - this resource's API doesn't support deletion. When deleted, the resource will persist
/// on Google Cloud even though it will be deleted from Pulumi state.
class Snooze extends CustomResource {
  /// This defines the criteria for applying the Snooze. See Criteria for more information.
  late final Output<CriteriaResponse> criteria;

  /// A display name for the Snooze. This can be, at most, 512 unicode characters.
  late final Output<String> displayName;

  /// The Snooze will be active from interval.start_time through interval.end_time. interval.start_time cannot be in the past. There is a 15 second clock skew to account for the time it takes for a request to reach the API from the UI.
  late final Output<TimeIntervalResponse> interval;

  /// The name of the Snooze. The format is: projects/[PROJECT_ID_OR_NUMBER]/snoozes/[SNOOZE_ID] The ID of the Snooze will be generated by the system.
  late final Output<String> name;
  late final Output<String> project;

  Snooze(
    String name, {
    SnoozeArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:monitoring/v3:Snooze',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.criteria = Output.createUnknown<CriteriaResponse>();
    this.displayName = Output.createUnknown<String>();
    this.interval = Output.createUnknown<TimeIntervalResponse>();
    this.name = Output.createUnknown<String>();
    this.project = Output.createUnknown<String>();
  }
}
