// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'workspace_custom_parameters.dart';
import 'workspace_enhanced_security_compliance.dart';
import 'workspace_managed_disk_identity.dart';
import 'workspace_storage_account_identity.dart';

/// Input properties used for looking up and filtering Workspace resources.
class WorkspaceState {
  /// Access Connector ID to use when default storage account firewall is enabled.
  ///
  /// > **Note:** The `access_connector_id` field is only required if `default_storage_firewall_enabled` is set to `true`.
  final pulumi.Input<String>? accessConnectorId;
  /// A `custom_parameters` block as documented below.
  final pulumi.Input<WorkspaceCustomParameters>? customParameters;
  /// Is the workspace enabled for customer managed key encryption? If `true` this enables the Managed Identity for the managed storage account. Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`.
  final pulumi.Input<bool>? customerManagedKeyEnabled;
  /// Disallow public access to default storage account. Defaults to `false`.
  final pulumi.Input<bool>? defaultStorageFirewallEnabled;
  /// The ID of Managed Disk Encryption Set created by the Databricks Workspace.
  final pulumi.Input<String>? diskEncryptionSetId;
  /// An `enhanced_security_compliance` block as documented below. This feature is only valid if `sku` is set to `premium`.
  final pulumi.Input<WorkspaceEnhancedSecurityCompliance>? enhancedSecurityCompliance;
  /// Is the Databricks File System root file system enabled with a secondary layer of encryption with platform managed keys? Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`. Changing this forces a new resource to be created.
  final pulumi.Input<bool>? infrastructureEncryptionEnabled;
  /// Resource ID of the Outbound Load balancer Backend Address Pool for Secure Cluster Connectivity (No Public IP) workspace with managed virtual network. Changing this forces a new resource to be created.
  final pulumi.Input<String>? loadBalancerBackendAddressPoolId;
  /// Specifies the supported Azure location where the resource has to be created. Changing this forces a new resource to be created.
  final pulumi.Input<String>? location;
  /// Resource ID of the Key Vault which contains the `managed_disk_cmk_key_vault_key_id` key.
  ///
  /// > **Note:** The `managed_disk_cmk_key_vault_id` field is only required if the Key Vault exists in a different subscription than the Databricks Workspace. If the `managed_disk_cmk_key_vault_id` field is not specified it is assumed that the `managed_disk_cmk_key_vault_key_id` is hosted in the same subscriptioin as the Databricks Workspace.
  ///
  /// > **Note:** If you are using multiple service principals to execute Terraform across subscriptions you will need to add an additional `azure.keyvault.AccessPolicy` resource granting the service principal access to the key vault in that subscription.
  final pulumi.Input<String>? managedDiskCmkKeyVaultId;
  /// Customer managed encryption properties for the Databricks Workspace managed disks.
  final pulumi.Input<String>? managedDiskCmkKeyVaultKeyId;
  /// Whether customer managed keys for disk encryption will automatically be rotated to the latest version.
  final pulumi.Input<bool>? managedDiskCmkRotationToLatestVersionEnabled;
  /// A `managed_disk_identity` block as documented below.
  final pulumi.Input<List<WorkspaceManagedDiskIdentity>>? managedDiskIdentities;
  /// The ID of the Managed Resource Group created by the Databricks Workspace.
  final pulumi.Input<String>? managedResourceGroupId;
  /// The name of the resource group where Azure should place the managed Databricks resources. Changing this forces a new resource to be created.
  ///
  /// > **Note:** Make sure that this field is unique if you have multiple Databrick Workspaces deployed in your subscription and choose to not have the `managed_resource_group_name` auto generated by the Azure Resource Provider. Having multiple Databrick Workspaces deployed in the same subscription with the same `manage_resource_group_name` may result in some resources that cannot be deleted.
  final pulumi.Input<String>? managedResourceGroupName;
  /// Resource ID of the Key Vault which contains the `managed_services_cmk_key_vault_key_id` key.
  ///
  /// > **Note:** The `managed_services_cmk_key_vault_id` field is only required if the Key Vault exists in a different subscription than the Databricks Workspace. If the `managed_services_cmk_key_vault_id` field is not specified it is assumed that the `managed_services_cmk_key_vault_key_id` is hosted in the same subscriptioin as the Databricks Workspace.
  ///
  /// > **Note:** If you are using multiple service principals to execute Terraform across subscriptions you will need to add an additional `azure.keyvault.AccessPolicy` resource granting the service principal access to the key vault in that subscription.
  final pulumi.Input<String>? managedServicesCmkKeyVaultId;
  /// Customer managed encryption properties for the Databricks Workspace managed resources(e.g. Notebooks and Artifacts).
  final pulumi.Input<String>? managedServicesCmkKeyVaultKeyId;
  /// Specifies the name of the Databricks Workspace resource. Changing this forces a new resource to be created.
  final pulumi.Input<String>? name;
  /// Does the data plane (clusters) to control plane communication happen over private link endpoint only or publicly? Possible values `AllRules`, `NoAzureDatabricksRules` or `NoAzureServiceRules`. Required when `public_network_access_enabled` is set to `false`.
  final pulumi.Input<String>? networkSecurityGroupRulesRequired;
  /// Allow public access for accessing workspace. Set value to `false` to access workspace only via private link endpoint. Possible values include `true` or `false`. Defaults to `true`.
  final pulumi.Input<bool>? publicNetworkAccessEnabled;
  /// The name of the Resource Group in which the Databricks Workspace should exist. Changing this forces a new resource to be created.
  final pulumi.Input<String>? resourceGroupName;
  /// The `sku` to use for the Databricks Workspace. Possible values are `standard`, `premium`, or `trial`.
  ///
  /// > **Note:** Downgrading to a `trial sku` from a `standard` or `premium sku` will force a new resource to be created.
  final pulumi.Input<String>? sku;
  /// A `storage_account_identity` block as documented below.
  final pulumi.Input<List<WorkspaceStorageAccountIdentity>>? storageAccountIdentities;
  /// A mapping of tags to assign to the resource.
  final pulumi.Input<Map<String, String>>? tags;
  /// The unique identifier of the databricks workspace in Databricks control plane.
  final pulumi.Input<String>? workspaceId;
  /// The workspace URL which is of the format 'adb-{workspaceId}.{random}.azuredatabricks.net'
  final pulumi.Input<String>? workspaceUrl;

  /// Creates a new [WorkspaceState].
  /// [accessConnectorId] Access Connector ID to use when default storage account firewall is enabled.
  /// [customParameters] A `custom_parameters` block as documented below.
  /// [customerManagedKeyEnabled] Is the workspace enabled for customer managed key encryption? If `true` this enables the Managed Identity for the managed storage account. Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`.
  /// [defaultStorageFirewallEnabled] Disallow public access to default storage account. Defaults to `false`.
  /// [diskEncryptionSetId] The ID of Managed Disk Encryption Set created by the Databricks Workspace.
  /// [enhancedSecurityCompliance] An `enhanced_security_compliance` block as documented below. This feature is only valid if `sku` is set to `premium`.
  /// [infrastructureEncryptionEnabled] Is the Databricks File System root file system enabled with a secondary layer of encryption with platform managed keys? Possible values are `true` or `false`. Defaults to `false`. This field is only valid if the Databricks Workspace `sku` is set to `premium`. Changing this forces a new resource to be created.
  /// [loadBalancerBackendAddressPoolId] Resource ID of the Outbound Load balancer Backend Address Pool for Secure Cluster Connectivity (No Public IP) workspace with managed virtual network. Changing this forces a new resource to be created.
  /// [location] Specifies the supported Azure location where the resource has to be created. Changing this forces a new resource to be created.
  /// [managedDiskCmkKeyVaultId] Resource ID of the Key Vault which contains the `managed_disk_cmk_key_vault_key_id` key.
  /// [managedDiskCmkKeyVaultKeyId] Customer managed encryption properties for the Databricks Workspace managed disks.
  /// [managedDiskCmkRotationToLatestVersionEnabled] Whether customer managed keys for disk encryption will automatically be rotated to the latest version.
  /// [managedDiskIdentities] A `managed_disk_identity` block as documented below.
  /// [managedResourceGroupId] The ID of the Managed Resource Group created by the Databricks Workspace.
  /// [managedResourceGroupName] The name of the resource group where Azure should place the managed Databricks resources. Changing this forces a new resource to be created.
  /// [managedServicesCmkKeyVaultId] Resource ID of the Key Vault which contains the `managed_services_cmk_key_vault_key_id` key.
  /// [managedServicesCmkKeyVaultKeyId] Customer managed encryption properties for the Databricks Workspace managed resources(e.g. Notebooks and Artifacts).
  /// [name] Specifies the name of the Databricks Workspace resource. Changing this forces a new resource to be created.
  /// [networkSecurityGroupRulesRequired] Does the data plane (clusters) to control plane communication happen over private link endpoint only or publicly? Possible values `AllRules`, `NoAzureDatabricksRules` or `NoAzureServiceRules`. Required when `public_network_access_enabled` is set to `false`.
  /// [publicNetworkAccessEnabled] Allow public access for accessing workspace. Set value to `false` to access workspace only via private link endpoint. Possible values include `true` or `false`. Defaults to `true`.
  /// [resourceGroupName] The name of the Resource Group in which the Databricks Workspace should exist. Changing this forces a new resource to be created.
  /// [sku] The `sku` to use for the Databricks Workspace. Possible values are `standard`, `premium`, or `trial`.
  /// [storageAccountIdentities] A `storage_account_identity` block as documented below.
  /// [tags] A mapping of tags to assign to the resource.
  /// [workspaceId] The unique identifier of the databricks workspace in Databricks control plane.
  /// [workspaceUrl] The workspace URL which is of the format 'adb-{workspaceId}.{random}.azuredatabricks.net'
  WorkspaceState({
    this.accessConnectorId,
    this.customParameters,
    this.customerManagedKeyEnabled,
    this.defaultStorageFirewallEnabled,
    this.diskEncryptionSetId,
    this.enhancedSecurityCompliance,
    this.infrastructureEncryptionEnabled,
    this.loadBalancerBackendAddressPoolId,
    this.location,
    this.managedDiskCmkKeyVaultId,
    this.managedDiskCmkKeyVaultKeyId,
    this.managedDiskCmkRotationToLatestVersionEnabled,
    this.managedDiskIdentities,
    this.managedResourceGroupId,
    this.managedResourceGroupName,
    this.managedServicesCmkKeyVaultId,
    this.managedServicesCmkKeyVaultKeyId,
    this.name,
    this.networkSecurityGroupRulesRequired,
    this.publicNetworkAccessEnabled,
    this.resourceGroupName,
    this.sku,
    this.storageAccountIdentities,
    this.tags,
    this.workspaceId,
    this.workspaceUrl,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'accessConnectorId': ?accessConnectorId,
      'customParameters': ?pulumi.Input.mapOptionalInputValue<WorkspaceCustomParameters, Map<String, dynamic>>(customParameters, (value) => value.toMap()),
      'customerManagedKeyEnabled': ?customerManagedKeyEnabled,
      'defaultStorageFirewallEnabled': ?defaultStorageFirewallEnabled,
      'diskEncryptionSetId': ?diskEncryptionSetId,
      'enhancedSecurityCompliance': ?pulumi.Input.mapOptionalInputValue<WorkspaceEnhancedSecurityCompliance, Map<String, dynamic>>(enhancedSecurityCompliance, (value) => value.toMap()),
      'infrastructureEncryptionEnabled': ?infrastructureEncryptionEnabled,
      'loadBalancerBackendAddressPoolId': ?loadBalancerBackendAddressPoolId,
      'location': ?location,
      'managedDiskCmkKeyVaultId': ?managedDiskCmkKeyVaultId,
      'managedDiskCmkKeyVaultKeyId': ?managedDiskCmkKeyVaultKeyId,
      'managedDiskCmkRotationToLatestVersionEnabled': ?managedDiskCmkRotationToLatestVersionEnabled,
      'managedDiskIdentities': ?pulumi.Input.mapOptionalInputValue<List<WorkspaceManagedDiskIdentity>, List<Map<String, dynamic>>>(managedDiskIdentities, (value) => pulumi.Input.encodeList<WorkspaceManagedDiskIdentity, Map<String, dynamic>>(value, (value) => value.toMap())),
      'managedResourceGroupId': ?managedResourceGroupId,
      'managedResourceGroupName': ?managedResourceGroupName,
      'managedServicesCmkKeyVaultId': ?managedServicesCmkKeyVaultId,
      'managedServicesCmkKeyVaultKeyId': ?managedServicesCmkKeyVaultKeyId,
      'name': ?name,
      'networkSecurityGroupRulesRequired': ?networkSecurityGroupRulesRequired,
      'publicNetworkAccessEnabled': ?publicNetworkAccessEnabled,
      'resourceGroupName': ?resourceGroupName,
      'sku': ?sku,
      'storageAccountIdentities': ?pulumi.Input.mapOptionalInputValue<List<WorkspaceStorageAccountIdentity>, List<Map<String, dynamic>>>(storageAccountIdentities, (value) => pulumi.Input.encodeList<WorkspaceStorageAccountIdentity, Map<String, dynamic>>(value, (value) => value.toMap())),
      'tags': ?tags,
      'workspaceId': ?workspaceId,
      'workspaceUrl': ?workspaceUrl,
    };
  }

  factory WorkspaceState.fromMap(Map<String, dynamic> map) {
    return WorkspaceState(
      accessConnectorId: map['accessConnectorId'] == null ? null : (map['accessConnectorId'] as String).input(),
      customParameters: map['customParameters'] == null ? null : (WorkspaceCustomParameters.fromMap((map['customParameters'] as Map).cast<String, dynamic>())).input(),
      customerManagedKeyEnabled: map['customerManagedKeyEnabled'] == null ? null : (map['customerManagedKeyEnabled'] as bool).input(),
      defaultStorageFirewallEnabled: map['defaultStorageFirewallEnabled'] == null ? null : (map['defaultStorageFirewallEnabled'] as bool).input(),
      diskEncryptionSetId: map['diskEncryptionSetId'] == null ? null : (map['diskEncryptionSetId'] as String).input(),
      enhancedSecurityCompliance: map['enhancedSecurityCompliance'] == null ? null : (WorkspaceEnhancedSecurityCompliance.fromMap((map['enhancedSecurityCompliance'] as Map).cast<String, dynamic>())).input(),
      infrastructureEncryptionEnabled: map['infrastructureEncryptionEnabled'] == null ? null : (map['infrastructureEncryptionEnabled'] as bool).input(),
      loadBalancerBackendAddressPoolId: map['loadBalancerBackendAddressPoolId'] == null ? null : (map['loadBalancerBackendAddressPoolId'] as String).input(),
      location: map['location'] == null ? null : (map['location'] as String).input(),
      managedDiskCmkKeyVaultId: map['managedDiskCmkKeyVaultId'] == null ? null : (map['managedDiskCmkKeyVaultId'] as String).input(),
      managedDiskCmkKeyVaultKeyId: map['managedDiskCmkKeyVaultKeyId'] == null ? null : (map['managedDiskCmkKeyVaultKeyId'] as String).input(),
      managedDiskCmkRotationToLatestVersionEnabled: map['managedDiskCmkRotationToLatestVersionEnabled'] == null ? null : (map['managedDiskCmkRotationToLatestVersionEnabled'] as bool).input(),
      managedDiskIdentities: map['managedDiskIdentities'] == null ? null : (pulumi.Input.decodeList<WorkspaceManagedDiskIdentity>(map['managedDiskIdentities'], (value) => WorkspaceManagedDiskIdentity.fromMap((value as Map).cast<String, dynamic>()))).input(),
      managedResourceGroupId: map['managedResourceGroupId'] == null ? null : (map['managedResourceGroupId'] as String).input(),
      managedResourceGroupName: map['managedResourceGroupName'] == null ? null : (map['managedResourceGroupName'] as String).input(),
      managedServicesCmkKeyVaultId: map['managedServicesCmkKeyVaultId'] == null ? null : (map['managedServicesCmkKeyVaultId'] as String).input(),
      managedServicesCmkKeyVaultKeyId: map['managedServicesCmkKeyVaultKeyId'] == null ? null : (map['managedServicesCmkKeyVaultKeyId'] as String).input(),
      name: map['name'] == null ? null : (map['name'] as String).input(),
      networkSecurityGroupRulesRequired: map['networkSecurityGroupRulesRequired'] == null ? null : (map['networkSecurityGroupRulesRequired'] as String).input(),
      publicNetworkAccessEnabled: map['publicNetworkAccessEnabled'] == null ? null : (map['publicNetworkAccessEnabled'] as bool).input(),
      resourceGroupName: map['resourceGroupName'] == null ? null : (map['resourceGroupName'] as String).input(),
      sku: map['sku'] == null ? null : (map['sku'] as String).input(),
      storageAccountIdentities: map['storageAccountIdentities'] == null ? null : (pulumi.Input.decodeList<WorkspaceStorageAccountIdentity>(map['storageAccountIdentities'], (value) => WorkspaceStorageAccountIdentity.fromMap((value as Map).cast<String, dynamic>()))).input(),
      tags: map['tags'] == null ? null : ((map['tags'] as Map).cast<String, String>()).input(),
      workspaceId: map['workspaceId'] == null ? null : (map['workspaceId'] as String).input(),
      workspaceUrl: map['workspaceUrl'] == null ? null : (map['workspaceUrl'] as String).input(),
    );
  }
}

