import 'package:pulumi/pulumi.dart' as pulumi;
import 'criteria_response.dart';
import 'snooze_args.dart';
import 'time_interval_response.dart';

/// Creates a Snooze that will prevent alerts, which match the provided criteria, from being opened. The Snooze applies for a specific time interval.
/// Note - this resource's API doesn't support deletion. When deleted, the resource will persist
/// on Google Cloud even though it will be deleted from Pulumi state.
class Snooze extends pulumi.CustomResource {
  /// This defines the criteria for applying the Snooze. See Criteria for more information.
  late final pulumi.Output<CriteriaResponse> criteria;
  /// A display name for the Snooze. This can be, at most, 512 unicode characters.
  late final pulumi.Output<String> displayName;
  /// The Snooze will be active from interval.start_time through interval.end_time. interval.start_time cannot be in the past. There is a 15 second clock skew to account for the time it takes for a request to reach the API from the UI.
  late final pulumi.Output<TimeIntervalResponse> interval;
  /// The name of the Snooze. The format is: projects/[PROJECT_ID_OR_NUMBER]/snoozes/[SNOOZE_ID] The ID of the Snooze will be generated by the system.
  late final pulumi.Output<String> name;
  late final pulumi.Output<String> project;

  /// Creates a new [Snooze].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [Snooze]. {@macro pulumi_monitoring_v3_snooze_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  Snooze(
    String name, {
    SnoozeArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'google-native:monitoring/v3:Snooze',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    this.criteria = registerOutput<CriteriaResponse>('criteria');
    this.displayName = registerOutput<String>('displayName');
    this.interval = registerOutput<TimeIntervalResponse>('interval');
    this.name = registerOutput<String>('name');
    this.project = registerOutput<String>('project');
  }
}
