library module_dataloss_prevention_discovery_config_target_big_query_target_filter_tables_include_regexes_pattern;

export 'prevention_discovery_config_target_big_query_target_filter_tables_include_regexes_pattern.dart';
