library module_spanner_instance_autoscaling_config_asymmetric_autoscaling_option;

export 'instance_autoscaling_config_asymmetric_autoscaling_option/instance_autoscaling_config_asymmetric_autoscaling_option.dart';
