// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'authentication_websecurityscanner_v1beta.dart';
import 'scan_config_export_to_security_command_center_websecurityscanner_v1beta.dart';
import 'scan_config_risk_level_websecurityscanner_v1beta.dart';
import 'scan_config_target_platforms_item_websecurityscanner_v1beta.dart';
import 'scan_config_user_agent_websecurityscanner_v1beta.dart';
import 'scan_run_websecurityscanner_v1beta.dart';
import 'schedule_websecurityscanner_v1beta.dart';

/// {@template pulumi_websecurityscanner_v1beta_scan_config_websecurityscanner_v1beta_args_doc}
/// The set of arguments for ScanConfig.
/// {@endtemplate}
/// {@macro pulumi_websecurityscanner_v1beta_scan_config_websecurityscanner_v1beta_args_doc}
class ScanConfigWebsecurityscannerV1betaArgs {
  /// The authentication configuration. If specified, service will use the authentication configuration during scanning.
  final pulumi.Input<AuthenticationWebsecurityscannerV1beta>? authentication;
  /// The excluded URL patterns as described in https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls
  final pulumi.Input<List<String>>? blacklistPatterns;
  /// The user provided display name of the ScanConfig.
  final pulumi.Input<String> displayName;
  /// Controls export of scan configurations and results to Security Command Center.
  final pulumi.Input<ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta>? exportToSecurityCommandCenter;
  /// Whether to keep scanning even if most requests return HTTP error codes.
  final pulumi.Input<bool>? ignoreHttpStatusErrors;
  /// Latest ScanRun if available.
  final pulumi.Input<ScanRunWebsecurityscannerV1beta>? latestRun;
  /// Whether the scan config is managed by Web Security Scanner, output only.
  final pulumi.Input<bool>? managedScan;
  /// The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively. If the field is unspecified or its value is set 0, server will default to 15. Other values outside of [5, 20] range will be rejected with INVALID_ARGUMENT error.
  final pulumi.Input<int>? maxQps;
  /// The resource name of the ScanConfig. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are generated by the system.
  final pulumi.Input<String>? name;
  final pulumi.Input<String>? project;
  /// The risk level selected for the scan
  final pulumi.Input<ScanConfigRiskLevelWebsecurityscannerV1beta>? riskLevel;
  /// The schedule of the ScanConfig.
  final pulumi.Input<ScheduleWebsecurityscannerV1beta>? schedule;
  /// The starting URLs from which the scanner finds site pages.
  final pulumi.Input<List<String>> startingUrls;
  /// Whether the scan configuration has enabled static IP address scan feature. If enabled, the scanner will access applications from static IP addresses.
  final pulumi.Input<bool>? staticIpScan;
  /// Set of Google Cloud platforms targeted by the scan. If empty, APP_ENGINE will be used as a default.
  final pulumi.Input<List<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>>? targetPlatforms;
  /// The user agent used during scanning.
  final pulumi.Input<ScanConfigUserAgentWebsecurityscannerV1beta>? userAgent;

  /// Creates a new [ScanConfigWebsecurityscannerV1betaArgs].
  /// [authentication] The authentication configuration. If specified, service will use the authentication configuration during scanning.
  /// [blacklistPatterns] The excluded URL patterns as described in https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls
  /// [displayName] The user provided display name of the ScanConfig.
  /// [exportToSecurityCommandCenter] Controls export of scan configurations and results to Security Command Center.
  /// [ignoreHttpStatusErrors] Whether to keep scanning even if most requests return HTTP error codes.
  /// [latestRun] Latest ScanRun if available.
  /// [managedScan] Whether the scan config is managed by Web Security Scanner, output only.
  /// [maxQps] The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively. If the field is unspecified or its value is set 0, server will default to 15. Other values outside of [5, 20] range will be rejected with INVALID_ARGUMENT error.
  /// [name] The resource name of the ScanConfig. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are generated by the system.
  /// [project] Optional.
  /// [riskLevel] The risk level selected for the scan
  /// [schedule] The schedule of the ScanConfig.
  /// [startingUrls] The starting URLs from which the scanner finds site pages.
  /// [staticIpScan] Whether the scan configuration has enabled static IP address scan feature. If enabled, the scanner will access applications from static IP addresses.
  /// [targetPlatforms] Set of Google Cloud platforms targeted by the scan. If empty, APP_ENGINE will be used as a default.
  /// [userAgent] The user agent used during scanning.
  ScanConfigWebsecurityscannerV1betaArgs({
    pulumi.Output<AuthenticationWebsecurityscannerV1beta>? authentication,
    pulumi.Output<List<String>>? blacklistPatterns,
    required pulumi.Output<String> displayName,
    pulumi.Output<ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta>? exportToSecurityCommandCenter,
    pulumi.Output<bool>? ignoreHttpStatusErrors,
    pulumi.Output<ScanRunWebsecurityscannerV1beta>? latestRun,
    pulumi.Output<bool>? managedScan,
    pulumi.Output<int>? maxQps,
    pulumi.Output<String>? name,
    pulumi.Output<String>? project,
    pulumi.Output<ScanConfigRiskLevelWebsecurityscannerV1beta>? riskLevel,
    pulumi.Output<ScheduleWebsecurityscannerV1beta>? schedule,
    required pulumi.Output<List<String>> startingUrls,
    pulumi.Output<bool>? staticIpScan,
    pulumi.Output<List<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>>? targetPlatforms,
    pulumi.Output<ScanConfigUserAgentWebsecurityscannerV1beta>? userAgent,
  }) :
      authentication = pulumi.Input.asOptionalInput<AuthenticationWebsecurityscannerV1beta>(authentication),
      blacklistPatterns = pulumi.Input.asOptionalInput<List<String>>(blacklistPatterns),
      displayName = pulumi.Input.asInput<String>(displayName),
      exportToSecurityCommandCenter = pulumi.Input.asOptionalInput<ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta>(exportToSecurityCommandCenter),
      ignoreHttpStatusErrors = pulumi.Input.asOptionalInput<bool>(ignoreHttpStatusErrors),
      latestRun = pulumi.Input.asOptionalInput<ScanRunWebsecurityscannerV1beta>(latestRun),
      managedScan = pulumi.Input.asOptionalInput<bool>(managedScan),
      maxQps = pulumi.Input.asOptionalInput<int>(maxQps),
      name = pulumi.Input.asOptionalInput<String>(name),
      project = pulumi.Input.asOptionalInput<String>(project),
      riskLevel = pulumi.Input.asOptionalInput<ScanConfigRiskLevelWebsecurityscannerV1beta>(riskLevel),
      schedule = pulumi.Input.asOptionalInput<ScheduleWebsecurityscannerV1beta>(schedule),
      startingUrls = pulumi.Input.asInput<List<String>>(startingUrls),
      staticIpScan = pulumi.Input.asOptionalInput<bool>(staticIpScan),
      targetPlatforms = pulumi.Input.asOptionalInput<List<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>>(targetPlatforms),
      userAgent = pulumi.Input.asOptionalInput<ScanConfigUserAgentWebsecurityscannerV1beta>(userAgent);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'authentication': ?pulumi.Input.mapOptionalInputValue<AuthenticationWebsecurityscannerV1beta, Map<String, dynamic>>(authentication, (value) => value.toMap()),
      'blacklistPatterns': ?blacklistPatterns,
      'displayName': displayName,
      'exportToSecurityCommandCenter': ?pulumi.Input.mapOptionalInputValue<ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta, String>(exportToSecurityCommandCenter, (value) => value.value),
      'ignoreHttpStatusErrors': ?ignoreHttpStatusErrors,
      'latestRun': ?pulumi.Input.mapOptionalInputValue<ScanRunWebsecurityscannerV1beta, Map<String, dynamic>>(latestRun, (value) => value.toMap()),
      'managedScan': ?managedScan,
      'maxQps': ?maxQps,
      'name': ?name,
      'project': ?project,
      'riskLevel': ?pulumi.Input.mapOptionalInputValue<ScanConfigRiskLevelWebsecurityscannerV1beta, String>(riskLevel, (value) => value.value),
      'schedule': ?pulumi.Input.mapOptionalInputValue<ScheduleWebsecurityscannerV1beta, Map<String, dynamic>>(schedule, (value) => value.toMap()),
      'startingUrls': startingUrls,
      'staticIpScan': ?staticIpScan,
      'targetPlatforms': ?pulumi.Input.mapOptionalInputValue<List<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>, List<String>>(targetPlatforms, (value) => pulumi.Input.encodeList<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta, String>(value, (value) => value.value)),
      'userAgent': ?pulumi.Input.mapOptionalInputValue<ScanConfigUserAgentWebsecurityscannerV1beta, String>(userAgent, (value) => value.value),
    };
  }

  factory ScanConfigWebsecurityscannerV1betaArgs.fromMap(Map<String, dynamic> map) {
    return ScanConfigWebsecurityscannerV1betaArgs(
      authentication: map['authentication'] == null ? null : pulumi.Output.create<AuthenticationWebsecurityscannerV1beta>(AuthenticationWebsecurityscannerV1beta.fromMap((map['authentication'] as Map).cast<String, dynamic>())),
      blacklistPatterns: map['blacklistPatterns'] == null ? null : pulumi.Output.create<List<String>>((map['blacklistPatterns'] as List).cast<String>()),
      displayName: pulumi.Output.create<String>(map['displayName'] as String),
      exportToSecurityCommandCenter: map['exportToSecurityCommandCenter'] == null ? null : pulumi.Output.create<ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta>(ScanConfigExportToSecurityCommandCenterWebsecurityscannerV1beta.fromValue(map['exportToSecurityCommandCenter'] as String)),
      ignoreHttpStatusErrors: map['ignoreHttpStatusErrors'] == null ? null : pulumi.Output.create<bool>(map['ignoreHttpStatusErrors'] as bool),
      latestRun: map['latestRun'] == null ? null : pulumi.Output.create<ScanRunWebsecurityscannerV1beta>(ScanRunWebsecurityscannerV1beta.fromMap((map['latestRun'] as Map).cast<String, dynamic>())),
      managedScan: map['managedScan'] == null ? null : pulumi.Output.create<bool>(map['managedScan'] as bool),
      maxQps: map['maxQps'] == null ? null : pulumi.Output.create<int>(map['maxQps'] as int),
      name: map['name'] == null ? null : pulumi.Output.create<String>(map['name'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
      riskLevel: map['riskLevel'] == null ? null : pulumi.Output.create<ScanConfigRiskLevelWebsecurityscannerV1beta>(ScanConfigRiskLevelWebsecurityscannerV1beta.fromValue(map['riskLevel'] as String)),
      schedule: map['schedule'] == null ? null : pulumi.Output.create<ScheduleWebsecurityscannerV1beta>(ScheduleWebsecurityscannerV1beta.fromMap((map['schedule'] as Map).cast<String, dynamic>())),
      startingUrls: pulumi.Output.create<List<String>>((map['startingUrls'] as List).cast<String>()),
      staticIpScan: map['staticIpScan'] == null ? null : pulumi.Output.create<bool>(map['staticIpScan'] as bool),
      targetPlatforms: map['targetPlatforms'] == null ? null : pulumi.Output.create<List<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>>(pulumi.Input.decodeList<ScanConfigTargetPlatformsItemWebsecurityscannerV1beta>(map['targetPlatforms'], (value) => ScanConfigTargetPlatformsItemWebsecurityscannerV1beta.fromValue(value as String))),
      userAgent: map['userAgent'] == null ? null : pulumi.Output.create<ScanConfigUserAgentWebsecurityscannerV1beta>(ScanConfigUserAgentWebsecurityscannerV1beta.fromValue(map['userAgent'] as String)),
    );
  }
}

