library module_apihub_plugin_instance_auth_config_oauth2_client_credentials_config_client_secret;

export 'plugin_instance_auth_config_oauth2_client_credentials_config_client_secret/plugin_instance_auth_config_oauth2_client_credentials_config_client_secret.dart';
