name: azure_native_dart_functions_many
description: Pulumi Azure Native Functions-many example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: 3.0.0
  pulumi_azure_native: 3.26.0

dev_dependencies:
  lints: ^6.1.0
