library module_kinesis_firehose_delivery_stream_elasticsearch_configuration_processing_configuration_processor;

export 'firehose_delivery_stream_elasticsearch_configuration_processing_configuration_processor.dart';
