// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_runtimeconfig_config_iam_policy_config_iam_policy_args_doc}
/// The set of arguments for ConfigIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_runtimeconfig_config_iam_policy_config_iam_policy_args_doc}
class ConfigIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> config;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Creates a new [ConfigIamPolicyArgs].
  /// [config] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  ConfigIamPolicyArgs({
    required this.config,
    required this.policyData,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'config': config,
      'policyData': policyData,
      'project': ?project,
    };
  }

  factory ConfigIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return ConfigIamPolicyArgs(
      config: (map['config'] as String).input(),
      policyData: (map['policyData'] as String).input(),
      project: map['project'] == null ? null : (map['project']! as String).input(),
    );
  }
}

