// ignore_for_file: unused_element, unnecessary_cast

class JobPlacement {
  /// The name of the cluster where the job will be submitted
  final String clusterName;

  /// Output-only. A cluster UUID generated by the Cloud Dataproc service when the job is submitted
  final String? clusterUuid;

  JobPlacement({
    required this.clusterName,
    this.clusterUuid,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['clusterName'] = clusterName;
    final clusterUuidValue = clusterUuid;
    if (clusterUuidValue != null) {
      map['clusterUuid'] = clusterUuidValue;
    }
    return map;
  }

  factory JobPlacement.fromMap(Map<String, dynamic> map) {
    return JobPlacement(
      clusterName: map['clusterName'] as String,
      clusterUuid:
          map['clusterUuid'] == null ? null : map['clusterUuid'] as String,
    );
  }
}
