library module_datastream_stream_source_config_postgresql_source_config_include_objects_postgresql_schema_postgresql_table;

export 'stream_source_config_postgresql_source_config_include_objects_postgresql_schema_postgresql_table.dart';
