library module_s3control_object_lambda_access_point_configuration_transformation_configuration;

export 'object_lambda_access_point_configuration_transformation_configuration/object_lambda_access_point_configuration_transformation_configuration.dart';
