library module_s3control_object_lambda_access_point_configuration_transformation_configuration_content_transformation_aws_lambda;

export 'object_lambda_access_point_configuration_transformation_configuration_content_transformation_aws_lambda/object_lambda_access_point_configuration_transformation_configuration_content_transformation_aws_lambda.dart';
