library module_autoscaling_policy_predictive_scaling_configuration_metric_specification_predefined_metric_pair_specification;

export 'policy_predictive_scaling_configuration_metric_specification_predefined_metric_pair_specification.dart';
