library module_ec2_get_local_gateway_virtual_interface_groups;

export 'get_local_gateway_virtual_interface_groups.dart';
export 'get_local_gateway_virtual_interface_groups_args.dart';
export 'get_local_gateway_virtual_interface_groups_result.dart';
