library module_cloudfront_multitenant_distribution_origin_custom_origin_config;

export 'multitenant_distribution_origin_custom_origin_config/multitenant_distribution_origin_custom_origin_config.dart';
