library module_cloudfront_multitenant_distribution_tenant_config_parameter_definition_definition;

export 'multitenant_distribution_tenant_config_parameter_definition_definition/multitenant_distribution_tenant_config_parameter_definition_definition.dart';
