library module_cloudrunv2_get_service_iam_policy;

export 'get_service_iam_policy/get_service_iam_policy2.dart';
export 'get_service_iam_policy/get_service_iam_policy_args2.dart';
export 'get_service_iam_policy/get_service_iam_policy_result2.dart';
