// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for AccessPolicyIamPolicy.
class AccessPolicyIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final Input<String>? name;

  /// The policy data generated by
  /// a <span pulumi-lang-nodejs="`gcp.organizations.getIAMPolicy`" pulumi-lang-dotnet="`gcp.organizations.getIAMPolicy`" pulumi-lang-go="`organizations.getIAMPolicy`" pulumi-lang-python="`organizations_get_iam_policy`" pulumi-lang-yaml="`gcp.organizations.getIAMPolicy`" pulumi-lang-java="`gcp.organizations.getIAMPolicy`">`gcp.organizations.getIAMPolicy`</span> data source.
  final Input<String> policyData;

  AccessPolicyIamPolicyArgs({
    this.name,
    required this.policyData,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    final nameValue = name;
    if (nameValue != null) {
      map['name'] = nameValue;
    }
    map['policyData'] = policyData;
    return map;
  }

  factory AccessPolicyIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return AccessPolicyIamPolicyArgs(
      name: Input.asOptionalInput<String>(map['name']),
      policyData: Input.asInput<String>(map['policyData']),
    );
  }
}
