library module_kinesisanalyticsv2_application_application_configuration_sql_application_configuration_input_input_parallelism;

export 'application_application_configuration_sql_application_configuration_input_input_parallelism.dart';
