library module_rds_instance_automated_backups_replication;

export 'instance_automated_backups_replication/instance_automated_backups_replication.dart';
export 'instance_automated_backups_replication/instance_automated_backups_replication_args.dart';
