// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering FileUpload resources.
class FileUploadState {
  /// The type used to authenticate against the storage account. Possible values are `keyBased` and `identityBased`. Defaults to `keyBased`.
  final pulumi.Input<String>? authenticationType;
  /// The connection string for the Azure Storage account to which files are uploaded.
  final pulumi.Input<String>? connectionString;
  /// The name of the root container where the files should be uploaded to. The container need not exist but should be creatable using the `connection_string` specified.
  final pulumi.Input<String>? containerName;
  /// The period of time for which a file upload notification message is available to consume before it expires, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 1 minute and 48 hours. Defaults to `PT1H`.
  final pulumi.Input<String>? defaultTtl;
  /// The ID of the User Managed Identity used to authenticate against the storage account.
  ///
  /// > **Note:** `identity_id` can only be specified when `authentication_type` is `identityBased`. It must be one of the `identity_ids` of the IoT Hub. If `identity_id` is omitted when `authentication_type` is `identityBased`, then the System-Assigned Managed Identity of the IoT Hub will be used.
  final pulumi.Input<String>? identityId;
  /// The ID of the IoT Hub. Changing this forces a new IoT Hub to be created.
  final pulumi.Input<String>? iothubId;
  /// The lock duration for the file upload notifications queue, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 5 and 300 seconds. Defaults to `PT1M`.
  final pulumi.Input<String>? lockDuration;
  /// The number of times the IoT Hub attempts to deliver a file upload notification message. Defaults to `10`.
  final pulumi.Input<int>? maxDeliveryCount;
  /// Used to specify whether file notifications are sent to IoT Hub on upload. Defaults to `false`.
  final pulumi.Input<bool>? notificationsEnabled;
  /// The period of time for which the SAS URI generated by IoT Hub for file upload is valid, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 1 minute and 24 hours. Defaults to `PT1H`.
  final pulumi.Input<String>? sasTtl;

  /// Creates a new [FileUploadState].
  /// [authenticationType] The type used to authenticate against the storage account. Possible values are `keyBased` and `identityBased`. Defaults to `keyBased`.
  /// [connectionString] The connection string for the Azure Storage account to which files are uploaded.
  /// [containerName] The name of the root container where the files should be uploaded to. The container need not exist but should be creatable using the `connection_string` specified.
  /// [defaultTtl] The period of time for which a file upload notification message is available to consume before it expires, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 1 minute and 48 hours. Defaults to `PT1H`.
  /// [identityId] The ID of the User Managed Identity used to authenticate against the storage account.
  /// [iothubId] The ID of the IoT Hub. Changing this forces a new IoT Hub to be created.
  /// [lockDuration] The lock duration for the file upload notifications queue, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 5 and 300 seconds. Defaults to `PT1M`.
  /// [maxDeliveryCount] The number of times the IoT Hub attempts to deliver a file upload notification message. Defaults to `10`.
  /// [notificationsEnabled] Used to specify whether file notifications are sent to IoT Hub on upload. Defaults to `false`.
  /// [sasTtl] The period of time for which the SAS URI generated by IoT Hub for file upload is valid, specified as an [ISO 8601 timespan duration](https://en.wikipedia.org/wiki/ISO_8601#Durations). This value must be between 1 minute and 24 hours. Defaults to `PT1H`.
  FileUploadState({
    pulumi.Output<String>? authenticationType,
    pulumi.Output<String>? connectionString,
    pulumi.Output<String>? containerName,
    pulumi.Output<String>? defaultTtl,
    pulumi.Output<String>? identityId,
    pulumi.Output<String>? iothubId,
    pulumi.Output<String>? lockDuration,
    pulumi.Output<int>? maxDeliveryCount,
    pulumi.Output<bool>? notificationsEnabled,
    pulumi.Output<String>? sasTtl,
  }) :
      authenticationType = pulumi.Input.asOptionalInput<String>(authenticationType),
      connectionString = pulumi.Input.asOptionalInput<String>(connectionString),
      containerName = pulumi.Input.asOptionalInput<String>(containerName),
      defaultTtl = pulumi.Input.asOptionalInput<String>(defaultTtl),
      identityId = pulumi.Input.asOptionalInput<String>(identityId),
      iothubId = pulumi.Input.asOptionalInput<String>(iothubId),
      lockDuration = pulumi.Input.asOptionalInput<String>(lockDuration),
      maxDeliveryCount = pulumi.Input.asOptionalInput<int>(maxDeliveryCount),
      notificationsEnabled = pulumi.Input.asOptionalInput<bool>(notificationsEnabled),
      sasTtl = pulumi.Input.asOptionalInput<String>(sasTtl);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'authenticationType': ?authenticationType,
      'connectionString': ?connectionString,
      'containerName': ?containerName,
      'defaultTtl': ?defaultTtl,
      'identityId': ?identityId,
      'iothubId': ?iothubId,
      'lockDuration': ?lockDuration,
      'maxDeliveryCount': ?maxDeliveryCount,
      'notificationsEnabled': ?notificationsEnabled,
      'sasTtl': ?sasTtl,
    };
  }

  factory FileUploadState.fromMap(Map<String, dynamic> map) {
    return FileUploadState(
      authenticationType: map['authenticationType'] == null ? null : pulumi.Output.create<String>(map['authenticationType'] as String),
      connectionString: map['connectionString'] == null ? null : pulumi.Output.create<String>(map['connectionString'] as String),
      containerName: map['containerName'] == null ? null : pulumi.Output.create<String>(map['containerName'] as String),
      defaultTtl: map['defaultTtl'] == null ? null : pulumi.Output.create<String>(map['defaultTtl'] as String),
      identityId: map['identityId'] == null ? null : pulumi.Output.create<String>(map['identityId'] as String),
      iothubId: map['iothubId'] == null ? null : pulumi.Output.create<String>(map['iothubId'] as String),
      lockDuration: map['lockDuration'] == null ? null : pulumi.Output.create<String>(map['lockDuration'] as String),
      maxDeliveryCount: map['maxDeliveryCount'] == null ? null : pulumi.Output.create<int>(map['maxDeliveryCount'] as int),
      notificationsEnabled: map['notificationsEnabled'] == null ? null : pulumi.Output.create<bool>(map['notificationsEnabled'] as bool),
      sasTtl: map['sasTtl'] == null ? null : pulumi.Output.create<String>(map['sasTtl'] as String),
    );
  }
}

