library module_tpu;

export 'tpu/get_v2_accelerator_types.dart';
export 'tpu/get_v2_runtime_versions.dart';
export 'tpu/v2_queued_resource.dart';
export 'tpu/v2_queued_resource_tpu.dart';
export 'tpu/v2_queued_resource_tpu_node_spec.dart';
export 'tpu/v2_queued_resource_tpu_node_spec_node.dart';
export 'tpu/v2_queued_resource_tpu_node_spec_node_network_config.dart';
export 'tpu/v2_vm.dart';
export 'tpu/v2_vm_accelerator_config.dart';
export 'tpu/v2_vm_data_disk.dart';
export 'tpu/v2_vm_network_config.dart';
export 'tpu/v2_vm_network_endpoint.dart';
export 'tpu/v2_vm_network_endpoint_access_config.dart';
export 'tpu/v2_vm_scheduling_config.dart';
export 'tpu/v2_vm_service_account.dart';
export 'tpu/v2_vm_shielded_instance_config.dart';
export 'tpu/v2_vm_symptom.dart';
