name: pulumi_azure_native
description: A native Pulumi package for creating and managing Azure resources.
version: 3.14.0
license: Apache-2.0
homepage: https://pulumi.com
repository: https://github.com/pulumi/pulumi-azure-native
topics:
    - pulumi
    - azure
    - azure-native
    - category-cloud
    - kind-native
environment:
    sdk: ">=3.11.0 <4.0.0"
resolution: workspace
dependencies:
    pulumi: 3.0.0
dev_dependencies:
    lints: ^6.1.0
