// ignore_for_file: non_constant_identifier_names

import 'package:pulumi_pulumiservice/index.dart' as module_index;
import 'package:pulumi_pulumiservice/providers.dart' as module_providers;

final index = const _IndexModuleNamespace();
final providers = const _ProvidersModuleNamespace();

class _IndexModuleNamespace {
  const _IndexModuleNamespace();
  final AWSOIDCConfiguration = module_index.AWSOIDCConfiguration.new;
  final AWSOIDCConfigurationArgs = module_index.AWSOIDCConfiguration.new;
  final AccessToken = module_index.AccessToken.new;
  final AccessTokenArgs = module_index.AccessTokenArgs.new;
  final AgentPool = module_index.AgentPool.new;
  final AgentPoolArgs = module_index.AgentPoolArgs.new;
  final ApprovalRule = module_index.ApprovalRule.new;
  final ApprovalRuleArgs = module_index.ApprovalRuleArgs.new;
  final ApprovalRuleConfig = module_index.ApprovalRuleConfig.new;
  final ApprovalRuleConfigArgs = module_index.ApprovalRuleConfig.new;
  final AuthPolicyDecision = module_index.AuthPolicyDecision.values;
  final AuthPolicyDefinition = module_index.AuthPolicyDefinition.new;
  final AuthPolicyDefinitionArgs = module_index.AuthPolicyDefinition.new;
  final AuthPolicyPermissionLevel = module_index.AuthPolicyPermissionLevel.values;
  final AuthPolicyTokenType = module_index.AuthPolicyTokenType.values;
  final AzureOIDCConfiguration = module_index.AzureOIDCConfiguration.new;
  final AzureOIDCConfigurationArgs = module_index.AzureOIDCConfiguration.new;
  final CloudProvider = module_index.CloudProvider.values;
  final DeploymentSchedule = module_index.DeploymentSchedule.new;
  final DeploymentScheduleArgs = module_index.DeploymentScheduleArgs.new;
  final DeploymentSettings = module_index.DeploymentSettings.new;
  final DeploymentSettingsArgs = module_index.DeploymentSettingsArgs.new;
  final DeploymentSettingsCacheOptions = module_index.DeploymentSettingsCacheOptions.new;
  final DeploymentSettingsCacheOptionsArgs = module_index.DeploymentSettingsCacheOptions.new;
  final DeploymentSettingsExecutorContext = module_index.DeploymentSettingsExecutorContext.new;
  final DeploymentSettingsExecutorContextArgs = module_index.DeploymentSettingsExecutorContext.new;
  final DeploymentSettingsGitAuthBasicAuth = module_index.DeploymentSettingsGitAuthBasicAuth.new;
  final DeploymentSettingsGitAuthBasicAuthArgs = module_index.DeploymentSettingsGitAuthBasicAuth.new;
  final DeploymentSettingsGitAuthSSHAuth = module_index.DeploymentSettingsGitAuthSSHAuth.new;
  final DeploymentSettingsGitAuthSSHAuthArgs = module_index.DeploymentSettingsGitAuthSSHAuth.new;
  final DeploymentSettingsGitSource = module_index.DeploymentSettingsGitSource.new;
  final DeploymentSettingsGitSourceArgs = module_index.DeploymentSettingsGitSource.new;
  final DeploymentSettingsGitSourceGitAuth = module_index.DeploymentSettingsGitSourceGitAuth.new;
  final DeploymentSettingsGitSourceGitAuthArgs = module_index.DeploymentSettingsGitSourceGitAuth.new;
  final DeploymentSettingsGithub = module_index.DeploymentSettingsGithub.new;
  final DeploymentSettingsGithubArgs = module_index.DeploymentSettingsGithub.new;
  final DeploymentSettingsOperationContext = module_index.DeploymentSettingsOperationContext.new;
  final DeploymentSettingsOperationContextArgs = module_index.DeploymentSettingsOperationContext.new;
  final DeploymentSettingsSourceContext = module_index.DeploymentSettingsSourceContext.new;
  final DeploymentSettingsSourceContextArgs = module_index.DeploymentSettingsSourceContext.new;
  final DriftSchedule = module_index.DriftSchedule.new;
  final DriftScheduleArgs = module_index.DriftScheduleArgs.new;
  final EligibleApprover = module_index.EligibleApprover.new;
  final EligibleApproverArgs = module_index.EligibleApprover.new;
  final Environment = module_index.Environment.new;
  final EnvironmentArgs = module_index.EnvironmentArgs.new;
  final EnvironmentIdentifier = module_index.EnvironmentIdentifier.new;
  final EnvironmentIdentifierArgs = module_index.EnvironmentIdentifier.new;
  final EnvironmentPermission = module_index.EnvironmentPermission.values;
  final EnvironmentRotationSchedule = module_index.EnvironmentRotationSchedule.new;
  final EnvironmentRotationScheduleArgs = module_index.EnvironmentRotationScheduleArgs.new;
  final EnvironmentVersionTag = module_index.EnvironmentVersionTag.new;
  final EnvironmentVersionTagArgs = module_index.EnvironmentVersionTagArgs.new;
  final GCPOIDCConfiguration = module_index.GCPOIDCConfiguration.new;
  final GCPOIDCConfigurationArgs = module_index.GCPOIDCConfiguration.new;
  final GetInsightsAccountArgs = module_index.GetInsightsAccountArgs.new;
  final GetInsightsAccountResult = module_index.GetInsightsAccountResult.new;
  final GetInsightsAccountResultArgs = module_index.GetInsightsAccountResult.new;
  final GetInsightsAccountsArgs = module_index.GetInsightsAccountsArgs.new;
  final GetInsightsAccountsResult = module_index.GetInsightsAccountsResult.new;
  final GetInsightsAccountsResultArgs = module_index.GetInsightsAccountsResult.new;
  final GetPolicyPackArgs = module_index.GetPolicyPackArgs.new;
  final GetPolicyPackResult = module_index.GetPolicyPackResult.new;
  final GetPolicyPackResultArgs = module_index.GetPolicyPackResult.new;
  final GetPolicyPacksArgs = module_index.GetPolicyPacksArgs.new;
  final GetPolicyPacksResult = module_index.GetPolicyPacksResult.new;
  final GetPolicyPacksResultArgs = module_index.GetPolicyPacksResult.new;
  final InsightsAccount = module_index.InsightsAccount.new;
  final InsightsAccountArgs = module_index.InsightsAccountArgs.new;
  final InsightsAccountState = module_index.InsightsAccountState.new;
  final InsightsAccountStateArgs = module_index.InsightsAccountState.new;
  final OidcIssuer = module_index.OidcIssuer.new;
  final OidcIssuerArgs = module_index.OidcIssuerArgs.new;
  final OperationContextOIDC = module_index.OperationContextOIDC.new;
  final OperationContextOIDCArgs = module_index.OperationContextOIDC.new;
  final OperationContextOptions = module_index.OperationContextOptions.new;
  final OperationContextOptionsArgs = module_index.OperationContextOptions.new;
  final OrgAccessToken = module_index.OrgAccessToken.new;
  final OrgAccessTokenArgs = module_index.OrgAccessTokenArgs.new;
  final PolicyGroup = module_index.PolicyGroup.new;
  final PolicyGroupArgs = module_index.PolicyGroupArgs.new;
  final PolicyGroupPolicyPackReference = module_index.PolicyGroupPolicyPackReference.new;
  final PolicyGroupPolicyPackReferenceArgs = module_index.PolicyGroupPolicyPackReference.new;
  final PolicyGroupStackReference = module_index.PolicyGroupStackReference.new;
  final PolicyGroupStackReferenceArgs = module_index.PolicyGroupStackReference.new;
  final PulumiOperation = module_index.PulumiOperation.values;
  final RbacPermission = module_index.RbacPermission.values;
  final ScanSchedule = module_index.ScanSchedule.values;
  final Stack = module_index.Stack.new;
  final StackArgs = module_index.StackArgs.new;
  final StackTag = module_index.StackTag.new;
  final StackTagArgs = module_index.StackTagArgs.new;
  final TargetActionType = module_index.TargetActionType.values;
  final Team = module_index.Team.new;
  final TeamAccessToken = module_index.TeamAccessToken.new;
  final TeamAccessTokenArgs = module_index.TeamAccessTokenArgs.new;
  final TeamArgs = module_index.TeamArgs.new;
  final TeamEnvironmentPermission = module_index.TeamEnvironmentPermission.new;
  final TeamEnvironmentPermissionArgs = module_index.TeamEnvironmentPermissionArgs.new;
  final TeamStackPermission = module_index.TeamStackPermission.new;
  final TeamStackPermissionArgs = module_index.TeamStackPermissionArgs.new;
  final TeamStackPermissionScope = module_index.TeamStackPermissionScope.values;
  final TemplateSource = module_index.TemplateSource.new;
  final TemplateSourceArgs = module_index.TemplateSourceArgs.new;
  final TemplateSourceDestination = module_index.TemplateSourceDestination.new;
  final TemplateSourceDestinationArgs = module_index.TemplateSourceDestination.new;
  final TtlSchedule = module_index.TtlSchedule.new;
  final TtlScheduleArgs = module_index.TtlScheduleArgs.new;
  final Webhook = module_index.Webhook.new;
  final WebhookArgs = module_index.WebhookArgs.new;
  final WebhookFilters = module_index.WebhookFilters.values;
  final WebhookFormat = module_index.WebhookFormat.values;
  final WebhookGroup = module_index.WebhookGroup.values;
  final getInsightsAccount = module_index.getInsightsAccount;
  final getInsightsAccounts = module_index.getInsightsAccounts;
  final getPolicyPack = module_index.getPolicyPack;
  final getPolicyPacks = module_index.getPolicyPacks;
}

class _ProvidersModuleNamespace {
  const _ProvidersModuleNamespace();
  final ProviderArgs = module_providers.ProviderArgs.new;
  final Pulumiservice = module_providers.ProviderProvider.new;
  final PulumiserviceArgs = module_providers.ProviderArgs.new;
}
