library module_dataloss_prevention_discovery_config_target_cloud_storage_target_filter_collection_include_regexes_pattern;

export 'prevention_discovery_config_target_cloud_storage_target_filter_collection_include_regexes_pattern.dart';
