library module_storage_get_transfer_project_servie_account;

export 'get_transfer_project_servie_account.dart';
export 'get_transfer_project_servie_account_args.dart';
export 'get_transfer_project_servie_account_result.dart';
