name: service_provider_dart
description: Dart fixture for integration tests.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.11.0

dependencies:
  path: ^1.9.1
  pulumi:
    path: ../../packages/pulumi-dart

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
