import 'package:pulumi/pulumi.dart' as pulumi;
import 'accelerator_response.dart';
import 'crypto_key_config_response.dart';
import 'event_publish_config_response.dart';
import 'instance_args.dart';
import 'network_config_response.dart';
import 'version_response.dart';

/// Creates a new Data Fusion instance in the specified project and location.
/// Auto-naming is currently not supported for this resource.
class Instance extends pulumi.CustomResource {
  /// List of accelerators enabled for this CDF instance.
  late final pulumi.Output<List<AcceleratorResponse>> accelerators;

  /// Endpoint on which the REST APIs is accessible.
  late final pulumi.Output<String> apiEndpoint;

  /// Available versions that the instance can be upgraded to using UpdateInstanceRequest.
  late final pulumi.Output<List<VersionResponse>> availableVersion;

  /// The time the instance was created.
  late final pulumi.Output<String> createTime;

  /// The crypto key configuration. This field is used by the Customer-Managed Encryption Keys (CMEK) feature.
  late final pulumi.Output<CryptoKeyConfigResponse> cryptoKeyConfig;

  /// User-managed service account to set on Dataproc when Cloud Data Fusion creates Dataproc to run data processing pipelines. This allows users to have fine-grained access control on Dataproc's accesses to cloud resources.
  late final pulumi.Output<String> dataprocServiceAccount;

  /// A description of this instance.
  late final pulumi.Output<String> description;

  /// If the instance state is DISABLED, the reason for disabling the instance.
  late final pulumi.Output<List<String>> disabledReason;

  /// Display name for an instance.
  late final pulumi.Output<String> displayName;

  /// Option to enable granular role-based access control.
  late final pulumi.Output<bool> enableRbac;

  /// Option to enable Stackdriver Logging.
  late final pulumi.Output<bool> enableStackdriverLogging;

  /// Option to enable Stackdriver Monitoring.
  late final pulumi.Output<bool> enableStackdriverMonitoring;

  /// Option to enable granular zone separation.
  late final pulumi.Output<bool> enableZoneSeparation;

  /// Option to enable and pass metadata for event publishing.
  late final pulumi.Output<EventPublishConfigResponse> eventPublishConfig;

  /// Cloud Storage bucket generated by Data Fusion in the customer project.
  late final pulumi.Output<String> gcsBucket;

  /// Required. The name of the instance to create.
  late final pulumi.Output<String> instanceId;

  /// The resource labels for instance to use to annotate any related underlying resources such as Compute Engine VMs. The character '=' is not allowed to be used within the labels.
  late final pulumi.Output<Map<String, String>> labels;
  late final pulumi.Output<String> location;

  /// The name of this instance is in the form of projects/{project}/locations/{location}/instances/{instance}.
  late final pulumi.Output<String> name;

  /// Network configuration options. These are required when a private Data Fusion instance is to be created.
  late final pulumi.Output<NetworkConfigResponse> networkConfig;

  /// Map of additional options used to configure the behavior of Data Fusion instance.
  late final pulumi.Output<Map<String, String>> options;

  /// P4 service account for the customer project.
  late final pulumi.Output<String> p4ServiceAccount;

  /// Optional. Current patch revision of the Data Fusion.
  late final pulumi.Output<String> patchRevision;

  /// Specifies whether the Data Fusion instance should be private. If set to true, all Data Fusion nodes will have private IP addresses and will not be able to access the public internet.
  late final pulumi.Output<bool> privateInstance;
  late final pulumi.Output<String> project;

  /// Reserved for future use.
  late final pulumi.Output<bool> satisfiesPzs;

  /// Deprecated. Use tenant_project_id instead to extract the tenant project ID.
  late final pulumi.Output<String> serviceAccount;

  /// Endpoint on which the Data Fusion UI is accessible.
  late final pulumi.Output<String> serviceEndpoint;

  /// The current state of this Data Fusion instance.
  late final pulumi.Output<String> state;

  /// Additional information about the current state of this Data Fusion instance if available.
  late final pulumi.Output<String> stateMessage;

  /// The name of the tenant project.
  late final pulumi.Output<String> tenantProjectId;

  /// Instance type.
  late final pulumi.Output<String> type;

  /// The time the instance was last updated.
  late final pulumi.Output<String> updateTime;

  /// Current version of the Data Fusion. Only specifiable in Update.
  late final pulumi.Output<String> version;

  /// Endpoint on which the Data Fusion UI is accessible to third-party users
  late final pulumi.Output<String> workforceIdentityServiceEndpoint;

  /// Name of the zone in which the Data Fusion instance will be created. Only DEVELOPER instances use this field.
  late final pulumi.Output<String> zone;

  /// Creates a new [Instance].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [Instance]. {@macro pulumi_datafusion_v1_instance_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  Instance(
    String name, {
    InstanceArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
         'google-native:datafusion/v1:Instance',
         name,
         pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
         options ?? pulumi.CustomResourceOptions(),
       ) {
    this.accelerators = registerOutput<List<AcceleratorResponse>>(
      'accelerators',
    );
    this.apiEndpoint = registerOutput<String>('apiEndpoint');
    this.availableVersion = registerOutput<List<VersionResponse>>(
      'availableVersion',
    );
    this.createTime = registerOutput<String>('createTime');
    this.cryptoKeyConfig = registerOutput<CryptoKeyConfigResponse>(
      'cryptoKeyConfig',
    );
    this.dataprocServiceAccount = registerOutput<String>(
      'dataprocServiceAccount',
    );
    this.description = registerOutput<String>('description');
    this.disabledReason = registerOutput<List<String>>('disabledReason');
    this.displayName = registerOutput<String>('displayName');
    this.enableRbac = registerOutput<bool>('enableRbac');
    this.enableStackdriverLogging = registerOutput<bool>(
      'enableStackdriverLogging',
    );
    this.enableStackdriverMonitoring = registerOutput<bool>(
      'enableStackdriverMonitoring',
    );
    this.enableZoneSeparation = registerOutput<bool>('enableZoneSeparation');
    this.eventPublishConfig = registerOutput<EventPublishConfigResponse>(
      'eventPublishConfig',
    );
    this.gcsBucket = registerOutput<String>('gcsBucket');
    this.instanceId = registerOutput<String>('instanceId');
    this.labels = registerOutput<Map<String, String>>('labels');
    this.location = registerOutput<String>('location');
    this.name = registerOutput<String>('name');
    this.networkConfig = registerOutput<NetworkConfigResponse>('networkConfig');
    this.options = registerOutput<Map<String, String>>('options');
    this.p4ServiceAccount = registerOutput<String>('p4ServiceAccount');
    this.patchRevision = registerOutput<String>('patchRevision');
    this.privateInstance = registerOutput<bool>('privateInstance');
    this.project = registerOutput<String>('project');
    this.satisfiesPzs = registerOutput<bool>('satisfiesPzs');
    this.serviceAccount = registerOutput<String>('serviceAccount');
    this.serviceEndpoint = registerOutput<String>('serviceEndpoint');
    this.state = registerOutput<String>('state');
    this.stateMessage = registerOutput<String>('stateMessage');
    this.tenantProjectId = registerOutput<String>('tenantProjectId');
    this.type = registerOutput<String>('type');
    this.updateTime = registerOutput<String>('updateTime');
    this.version = registerOutput<String>('version');
    this.workforceIdentityServiceEndpoint = registerOutput<String>(
      'workforceIdentityServiceEndpoint',
    );
    this.zone = registerOutput<String>('zone');
  }
}
