library module_vertex_ai_deployment_resource_pool_dedicated_resources_autoscaling_metric_spec;

export 'ai_deployment_resource_pool_dedicated_resources_autoscaling_metric_spec/ai_deployment_resource_pool_dedicated_resources_autoscaling_metric_spec.dart';
