library module_vertex_ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources_machine_spec_reservation_affinity;

export 'ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources_machine_spec_reservation_affinity/ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources_machine_spec_reservation_affinity.dart';
