library module_vertex_ai_endpoint_with_model_garden_deployment_deploy_config;

export 'ai_endpoint_with_model_garden_deployment_deploy_config/ai_endpoint_with_model_garden_deployment_deploy_config.dart';
