library module_vertex_ai_endpoint_with_model_garden_deployment_endpoint_config_private_service_connect_config_psc_automation_configs;

export 'ai_endpoint_with_model_garden_deployment_endpoint_config_private_service_connect_config_psc_automation_configs/ai_endpoint_with_model_garden_deployment_endpoint_config_private_service_connect_config_psc_automation_configs.dart';
