library module_vertex_ai_endpoint_with_model_garden_deployment;

export 'ai_endpoint_with_model_garden_deployment/ai_endpoint_with_model_garden_deployment.dart';
export 'ai_endpoint_with_model_garden_deployment/ai_endpoint_with_model_garden_deployment_args.dart';
