library module_vertex_ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources;

export 'ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources/ai_endpoint_with_model_garden_deployment_deploy_config_dedicated_resources.dart';
