library module_vertex_ai_endpoint_with_model_garden_deployment_model_config_container_spec;

export 'ai_endpoint_with_model_garden_deployment_model_config_container_spec/ai_endpoint_with_model_garden_deployment_model_config_container_spec.dart';
