library module_vertex_ai_endpoint_with_model_garden_deployment_model_config_container_spec_port;

export 'ai_endpoint_with_model_garden_deployment_model_config_container_spec_port/ai_endpoint_with_model_garden_deployment_model_config_container_spec_port.dart';
