library module_vertex_ai_feature_store_entity_type_iam_policy;

export 'ai_feature_store_entity_type_iam_policy/ai_feature_store_entity_type_iam_policy.dart';
export 'ai_feature_store_entity_type_iam_policy/ai_feature_store_entity_type_iam_policy_args.dart';
