library module_vertex_ai_feature_store_entity_type_iam_binding;

export 'ai_feature_store_entity_type_iam_binding/ai_feature_store_entity_type_iam_binding.dart';
export 'ai_feature_store_entity_type_iam_binding/ai_feature_store_entity_type_iam_binding_args.dart';
