library module_vertex_ai_index_endpoint_deployed_index_dedicated_resources_machine_spec;

export 'ai_index_endpoint_deployed_index_dedicated_resources_machine_spec/ai_index_endpoint_deployed_index_dedicated_resources_machine_spec.dart';
