// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'conversation_conversation_stage_dialogflow_v2beta1.dart';

/// {@template pulumi_dialogflow_v2beta1_conversation_dialogflow_v2beta1_args_doc}
/// The set of arguments for Conversation.
/// {@endtemplate}
/// {@macro pulumi_dialogflow_v2beta1_conversation_dialogflow_v2beta1_args_doc}
class ConversationDialogflowV2beta1Args {
  /// Optional. Identifier of the conversation. Generally it's auto generated by Google. Only set it if you cannot wait for the response to return a auto-generated one to you. The conversation ID must be compliant with the regression fomula `a-zA-Z*` with the characters length in range of [3,64]. If the field is provided, the caller is resposible for 1. the uniqueness of the ID, otherwise the request will be rejected. 2. the consistency for whether to use custom ID or not under a project to better ensure uniqueness.
  final pulumi.Input<String>? conversationId;
  /// The Conversation Profile to be used to configure this Conversation. This field cannot be updated. Format: `projects//locations//conversationProfiles/`.
  final pulumi.Input<String> conversationProfile;
  /// The stage of a conversation. It indicates whether the virtual agent or a human agent is handling the conversation. If the conversation is created with the conversation profile that has Dialogflow config set, defaults to ConversationStage.VIRTUAL_AGENT_STAGE; Otherwise, defaults to ConversationStage.HUMAN_ASSIST_STAGE. If the conversation is created with the conversation profile that has Dialogflow config set but explicitly sets conversation_stage to ConversationStage.HUMAN_ASSIST_STAGE, it skips ConversationStage.VIRTUAL_AGENT_STAGE stage and directly goes to ConversationStage.HUMAN_ASSIST_STAGE.
  final pulumi.Input<ConversationConversationStageDialogflowV2beta1>? conversationStage;
  final pulumi.Input<String>? location;
  final pulumi.Input<String>? project;

  /// Creates a new [ConversationDialogflowV2beta1Args].
  /// [conversationId] Optional. Identifier of the conversation. Generally it's auto generated by Google. Only set it if you cannot wait for the response to return a auto-generated one to you. The conversation ID must be compliant with the regression fomula `a-zA-Z*` with the characters length in range of [3,64]. If the field is provided, the caller is resposible for 1. the uniqueness of the ID, otherwise the request will be rejected. 2. the consistency for whether to use custom ID or not under a project to better ensure uniqueness.
  /// [conversationProfile] The Conversation Profile to be used to configure this Conversation. This field cannot be updated. Format: `projects//locations//conversationProfiles/`.
  /// [conversationStage] The stage of a conversation. It indicates whether the virtual agent or a human agent is handling the conversation. If the conversation is created with the conversation profile that has Dialogflow config set, defaults to ConversationStage.VIRTUAL_AGENT_STAGE; Otherwise, defaults to ConversationStage.HUMAN_ASSIST_STAGE. If the conversation is created with the conversation profile that has Dialogflow config set but explicitly sets conversation_stage to ConversationStage.HUMAN_ASSIST_STAGE, it skips ConversationStage.VIRTUAL_AGENT_STAGE stage and directly goes to ConversationStage.HUMAN_ASSIST_STAGE.
  /// [location] Optional.
  /// [project] Optional.
  ConversationDialogflowV2beta1Args({
    this.conversationId,
    required this.conversationProfile,
    this.conversationStage,
    this.location,
    this.project,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'conversationId': ?conversationId,
      'conversationProfile': conversationProfile,
      'conversationStage': ?pulumi.Input.mapOptionalInputValue<ConversationConversationStageDialogflowV2beta1, String>(conversationStage, (value) => value.value),
      'location': ?location,
      'project': ?project,
    };
  }

  factory ConversationDialogflowV2beta1Args.fromMap(Map<String, dynamic> map) {
    return ConversationDialogflowV2beta1Args(
      conversationId: map['conversationId'] == null ? null : (map['conversationId'] as String).input(),
      conversationProfile: (map['conversationProfile'] as String).input(),
      conversationStage: map['conversationStage'] == null ? null : (ConversationConversationStageDialogflowV2beta1.fromValue(map['conversationStage'] as String)).input(),
      location: map['location'] == null ? null : (map['location'] as String).input(),
      project: map['project'] == null ? null : (map['project'] as String).input(),
    );
  }
}

