library module_dataloss_prevention_discovery_config_target_other_cloud_target_filter_single_resource_amazon_s3_bucket;

export 'prevention_discovery_config_target_other_cloud_target_filter_single_resource_amazon_s3_bucket.dart';
