name: command_stdin
description: Pulumi Command stdin example in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: ^3.0.0
  pulumi_command: 1.2.1

dev_dependencies:
  lints: ^6.1.0
