// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for Hl7StoreIamPolicy.
class Hl7StoreIamPolicyArgs {
  /// The HL7v2 store ID, in the form
  /// `{project_id}/{location_name}/{dataset_name}/{hl7_v2_store_name}` or
  /// `{location_name}/{dataset_name}/{hl7_v2_store_name}`. In the second form, the provider's
  /// project setting will be used as a fallback.
  final Input<String> hl7V2StoreId;

  /// The policy data generated by
  /// a <span pulumi-lang-nodejs="`gcp.organizations.getIAMPolicy`" pulumi-lang-dotnet="`gcp.organizations.getIAMPolicy`" pulumi-lang-go="`organizations.getIAMPolicy`" pulumi-lang-python="`organizations_get_iam_policy`" pulumi-lang-yaml="`gcp.organizations.getIAMPolicy`" pulumi-lang-java="`gcp.organizations.getIAMPolicy`">`gcp.organizations.getIAMPolicy`</span> data source.
  final Input<String> policyData;

  Hl7StoreIamPolicyArgs({
    required this.hl7V2StoreId,
    required this.policyData,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['hl7V2StoreId'] = hl7V2StoreId;
    map['policyData'] = policyData;
    return map;
  }

  factory Hl7StoreIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return Hl7StoreIamPolicyArgs(
      hl7V2StoreId: Input.asInput<String>(map['hl7V2StoreId']),
      policyData: Input.asInput<String>(map['policyData']),
    );
  }
}
