name: aws_dart_k8s_voting_app
description: Pulumi Dart Kubernetes voting app baseline example.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  pulumi: ^3.0.0
  pulumi_awsx: 3.8.0+1
  pulumi_eks: 4.3.0+1
  pulumi_kubernetes: 4.34.0+1

dev_dependencies:
  lints: ^6.1.0
