library module_bedrockmodel_invocation_logging_configuration_logging_config_cloudwatch_config_large_data_delivery_s3_config;

export 'invocation_logging_configuration_logging_config_cloudwatch_config_large_data_delivery_s3_config.dart';
