// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_compute_storage_pool_iam_policy_storage_pool_iam_policy_args_doc}
/// The set of arguments for StoragePoolIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_compute_storage_pool_iam_policy_storage_pool_iam_policy_args_doc}
class StoragePoolIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? name;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// A reference to the zone where the storage pool resides. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no zone is provided in the parent identifier and no
  /// zone is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? zone;

  /// Creates a new [StoragePoolIamPolicyArgs].
  /// [name] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [zone] A reference to the zone where the storage pool resides. Used to find the parent resource to bind the IAM policy to. If not specified,
  StoragePoolIamPolicyArgs({
    String? name,
    required String policyData,
    String? project,
    String? zone,
  }) : name = pulumi.Input.asOptionalInput<String>(name),
       policyData = pulumi.Input.asInput<String>(policyData),
       project = pulumi.Input.asOptionalInput<String>(project),
       zone = pulumi.Input.asOptionalInput<String>(zone);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'name': ?name,
      'policyData': policyData,
      'project': ?project,
      'zone': ?zone,
    };
  }

  factory StoragePoolIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return StoragePoolIamPolicyArgs(
      name: map['name'] == null ? null : map['name'] as String,
      policyData: map['policyData'] as String,
      project: map['project'] == null ? null : map['project'] as String,
      zone: map['zone'] == null ? null : map['zone'] as String,
    );
  }
}
