import 'package:pulumi/pulumi.dart' as pulumi;
import 'system_data_response.dart';
import 'task_args.dart';
import 'task_properties_response.dart';

/// Tasks resource.
///
/// Uses Azure REST API version 2025-03-30-preview.
///
/// Other available API versions: 2025-12-01-preview, 2026-02-01-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native migrate [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
///
/// {{% examples %}}
/// ## Example Usage
/// {{% example %}}
/// ### Tasks_Create_MaximumSet - generated by [MaximumSet] rule - generated by [MaximumSet] rule - generated by [MaximumSet] rule - generated by [MaximumSet] rule
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using AzureNative = Pulumi.AzureNative;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var task = new AzureNative.Migrate.Task("task", new()
///     {
///         ProjectName = "myProjectName",
///         Properties = new AzureNative.Migrate.Inputs.TaskPropertiesArgs
///         {
///             Description = "lzhl",
///             DisplayName = "hhbrpibobilcoypvyiofvr",
///             Scope = AzureNative.Migrate.TaskScope.Wave,
///             ScopeId = "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave",
///             Stage = "klaemxmckhvyoooxyauqglexjna",
///             Status = "Pending",
///         },
///         ResourceGroupName = "rgwaves",
///         TaskName = "myTaskName",
///     });
///
/// });
///
///
/// ```
///
/// ```go
/// package main
///
/// import (
/// 	migrate "github.com/pulumi/pulumi-azure-native-sdk/migrate/v3"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := migrate.NewTask(ctx, "task", &migrate.TaskArgs{
/// 			ProjectName: pulumi.String("myProjectName"),
/// 			Properties: &migrate.TaskPropertiesArgs{
/// 				Description: pulumi.String("lzhl"),
/// 				DisplayName: pulumi.String("hhbrpibobilcoypvyiofvr"),
/// 				Scope:       pulumi.String(migrate.TaskScopeWave),
/// 				ScopeId:     pulumi.String("/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave"),
/// 				Stage:       pulumi.String("klaemxmckhvyoooxyauqglexjna"),
/// 				Status:      pulumi.String("Pending"),
/// 			},
/// 			ResourceGroupName: pulumi.String("rgwaves"),
/// 			TaskName:          pulumi.String("myTaskName"),
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
///
/// ```
///
/// ```hcl
/// pulumi {
///   required_providers {
///     azure-native = {
///       source = "pulumi/azure-native"
///     }
///   }
/// }
///
/// resource "azure-native_migrate_task" "task" {
///   project_name = "myProjectName"
///   properties = {
///     description  = "lzhl"
///     display_name = "hhbrpibobilcoypvyiofvr"
///     scope        = "Wave"
///     scope_id     = "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave"
///     stage        = "klaemxmckhvyoooxyauqglexjna"
///     status       = "Pending"
///   }
///   resource_group_name = "rgwaves"
///   task_name           = "myTaskName"
/// }
///
/// ```
///
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.azurenative.migrate.Task;
/// import com.pulumi.azurenative.migrate.TaskArgs;
/// import com.pulumi.azurenative.migrate.inputs.TaskPropertiesArgs;
/// import java.util.ArrayList;
/// import java.util.Arrays;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var task = new Task("task", TaskArgs.builder()
///             .projectName("myProjectName")
///             .properties(TaskPropertiesArgs.builder()
///                 .description("lzhl")
///                 .displayName("hhbrpibobilcoypvyiofvr")
///                 .scope("Wave")
///                 .scopeId("/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave")
///                 .stage("klaemxmckhvyoooxyauqglexjna")
///                 .status("Pending")
///                 .build())
///             .resourceGroupName("rgwaves")
///             .taskName("myTaskName")
///             .build());
///
///     }
/// }
///
/// ```
///
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as azure_native from "@pulumi/azure-native";
///
/// const task = new azure_native.migrate.Task("task", {
///     projectName: "myProjectName",
///     properties: {
///         description: "lzhl",
///         displayName: "hhbrpibobilcoypvyiofvr",
///         scope: azure_native.migrate.TaskScope.Wave,
///         scopeId: "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave",
///         stage: "klaemxmckhvyoooxyauqglexjna",
///         status: "Pending",
///     },
///     resourceGroupName: "rgwaves",
///     taskName: "myTaskName",
/// });
///
/// ```
///
/// ```python
/// import pulumi
/// import pulumi_azure_native as azure_native
///
/// task = azure_native.migrate.Task("task",
///     project_name="myProjectName",
///     properties={
///         "description": "lzhl",
///         "display_name": "hhbrpibobilcoypvyiofvr",
///         "scope": azure_native.migrate.TaskScope.WAVE,
///         "scope_id": "/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave",
///         "stage": "klaemxmckhvyoooxyauqglexjna",
///         "status": "Pending",
///     },
///     resource_group_name="rgwaves",
///     task_name="myTaskName")
///
/// ```
///
/// ```yaml
/// resources:
///   task:
///     type: azure-native:migrate:Task
///     properties:
///       projectName: myProjectName
///       properties:
///         description: lzhl
///         displayName: hhbrpibobilcoypvyiofvr
///         scope: Wave
///         scopeId: /subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/MyResourceGroup/providers/Microsoft.Migrate/migrateProjects/MyMigrateProject/waves/myWave
///         stage: klaemxmckhvyoooxyauqglexjna
///         status: Pending
///       resourceGroupName: rgwaves
///       taskName: myTaskName
///
/// ```
///
/// {{% /example %}}
/// {{% /examples %}}
///
/// ## Import
///
/// An existing resource can be imported using its type token, name, and identifier, e.g.
///
/// ```sh
/// $ pulumi import azure-native:migrate:Task ejdnhrqdoevhryqij /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{projectName}/tasks/{taskName}
/// ```
class Task extends pulumi.CustomResource {
  /// The Azure API version of the resource.
  late final pulumi.Output<String> azureApiVersion;
  /// If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
  late final pulumi.Output<String> eTag;
  /// The name of the resource
  late final pulumi.Output<String> name;
  /// The resource-specific properties for this resource.
  late final pulumi.Output<TaskPropertiesResponse> properties;
  /// Azure Resource Manager metadata containing createdBy and modifiedBy information.
  late final pulumi.Output<SystemDataResponse> systemData;
  /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
  late final pulumi.Output<String> type;

  /// Creates a new [Task].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [Task]. {@macro pulumi_migrate_task_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  Task(
    String name, {
    TaskArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
          'azure-native:migrate:Task',
          name,
          pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? pulumi.CustomResourceOptions(),
        ) {
    azureApiVersion = registerOutput<String>('azureApiVersion');
    eTag = registerOutput<String>('eTag');
    this.name = registerOutput<String>('name');
    properties = registerOutput<TaskPropertiesResponse>('properties', decoder: (raw) { final guardedValue = raw; if (guardedValue == null) return null; return TaskPropertiesResponse.fromMap((guardedValue as Map).cast<String, dynamic>()); });
    systemData = registerOutput<SystemDataResponse>('systemData', decoder: (raw) { final guardedValue = raw; if (guardedValue == null) return null; return SystemDataResponse.fromMap((guardedValue as Map).cast<String, dynamic>()); });
    type = registerOutput<String>('type');
  }
}
