library module_kinesisanalyticsv2_application_application_configuration_sql_application_configuration_input_kinesis_firehose_input;

export 'application_application_configuration_sql_application_configuration_input_kinesis_firehose_input.dart';
