library module_gkehub_get_feature_spec_fleetobservability_logging_config_fleet_scope_logs_config;

export 'get_feature_spec_fleetobservability_logging_config_fleet_scope_logs_config/get_feature_spec_fleetobservability_logging_config_fleet_scope_logs_config.dart';
