import 'package:pulumi/pulumi.dart' as pulumi;
import 'disk_encryption_configuration_response.dart';
import 'disk_encryption_status_response.dart';
import 'instance_args.dart';
import 'instance_failover_replica_response.dart';
import 'on_premises_configuration_response.dart';
import 'replica_configuration_response.dart';
import 'settings_response.dart';
import 'sql_out_of_disk_report_response.dart';
import 'sql_scheduled_maintenance_response.dart';
import 'ssl_cert_response.dart';

/// Creates a new Cloud SQL instance.
class Instance extends pulumi.CustomResource {
  /// List all maintenance versions applicable on the instance
  late final pulumi.Output<List<String>> availableMaintenanceVersions;

  /// The backend type. `SECOND_GEN`: Cloud SQL database instance. `EXTERNAL`: A database server that is not managed by Google. This property is read-only; use the `tier` property in the `settings` object to determine the database type.
  late final pulumi.Output<String> backendType;

  /// Connection name of the Cloud SQL instance used in connection strings.
  late final pulumi.Output<String> connectionName;

  /// The time when the instance was created in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example `2012-11-15T16:19:00.094Z`.
  late final pulumi.Output<String> createTime;

  /// The current disk usage of the instance in bytes. This property has been deprecated. Use the "cloudsql.googleapis.com/database/disk/bytes_used" metric in Cloud Monitoring API instead. Please see [this announcement](https://groups.google.com/d/msg/google-cloud-sql-announce/I_7-F9EBhT0/BtvFtdFeAgAJ) for details.
  late final pulumi.Output<String> currentDiskSize;

  /// Stores the current database version running on the instance including minor version such as `MYSQL_8_0_18`.
  late final pulumi.Output<String> databaseInstalledVersion;

  /// The database engine type and version. The `databaseVersion` field cannot be changed after instance creation.
  late final pulumi.Output<String> databaseVersion;

  /// Disk encryption configuration specific to an instance.
  late final pulumi.Output<DiskEncryptionConfigurationResponse>
  diskEncryptionConfiguration;

  /// Disk encryption status specific to an instance.
  late final pulumi.Output<DiskEncryptionStatusResponse> diskEncryptionStatus;

  /// The dns name of the instance.
  late final pulumi.Output<String> dnsName;

  /// This field is deprecated and will be removed from a future version of the API. Use the `settings.settingsVersion` field instead.
  late final pulumi.Output<String> etag;

  /// The name and status of the failover replica.
  late final pulumi.Output<InstanceFailoverReplicaResponse> failoverReplica;

  /// The Compute Engine zone that the instance is currently serving from. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary zone. WARNING: Changing this might restart the instance.
  late final pulumi.Output<String> gceZone;

  /// The instance type.
  late final pulumi.Output<String> instanceType;

  /// The assigned IP addresses for the instance.
  late final pulumi.Output<List<Map<String, dynamic>>> ipAddresses;

  /// The IPv6 address assigned to the instance. (Deprecated) This property was applicable only to First Generation instances.
  late final pulumi.Output<String> ipv6Address;

  /// This is always `sql#instance`.
  late final pulumi.Output<String> kind;

  /// The current software version on the instance.
  late final pulumi.Output<String> maintenanceVersion;

  /// The name of the instance which will act as primary in the replication setup.
  late final pulumi.Output<String> masterInstanceName;

  /// The maximum disk size of the instance in bytes.
  late final pulumi.Output<String> maxDiskSize;

  /// Name of the Cloud SQL instance. This does not include the project ID.
  late final pulumi.Output<String> name;

  /// Configuration specific to on-premises instances.
  late final pulumi.Output<OnPremisesConfigurationResponse>
  onPremisesConfiguration;

  /// This field represents the report generated by the proactive database wellness job for OutOfDisk issues. * Writers: * the proactive database wellness job for OOD. * Readers: * the proactive database wellness job
  late final pulumi.Output<SqlOutOfDiskReportResponse> outOfDiskReport;

  /// DEPRECATED: please use write_endpoint instead.
  late final pulumi.Output<String> primaryDnsName;
  late final pulumi.Output<String> project;

  /// The link to service attachment of PSC instance.
  late final pulumi.Output<String> pscServiceAttachmentLink;

  /// The geographical region. Can be: * `us-central` (`FIRST_GEN` instances only) * `us-central1` (`SECOND_GEN` instances only) * `asia-east1` or `europe-west1`. Defaults to `us-central` or `us-central1` depending on the instance type. The region cannot be changed after instance creation.
  late final pulumi.Output<String> region;

  /// Configuration specific to failover replicas and read replicas.
  late final pulumi.Output<ReplicaConfigurationResponse> replicaConfiguration;

  /// The replicas of the instance.
  late final pulumi.Output<List<String>> replicaNames;

  /// Initial root password. Use only on creation. You must set root passwords before you can connect to PostgreSQL instances.
  late final pulumi.Output<String> rootPassword;

  /// The status indicating if instance satisfiesPzs. Reserved for future use.
  late final pulumi.Output<bool> satisfiesPzs;

  /// The start time of any upcoming scheduled maintenance for this instance.
  late final pulumi.Output<SqlScheduledMaintenanceResponse>
  scheduledMaintenance;

  /// The Compute Engine zone that the failover instance is currently serving from for a regional instance. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary/failover zone.
  late final pulumi.Output<String> secondaryGceZone;

  /// The URI of this resource.
  late final pulumi.Output<String> selfLink;

  /// SSL configuration.
  late final pulumi.Output<SslCertResponse> serverCaCert;

  /// The service account email address assigned to the instance.\This property is read-only.
  late final pulumi.Output<String> serviceAccountEmailAddress;

  /// The user settings.
  late final pulumi.Output<SettingsResponse> settings;
  late final pulumi.Output<String> sqlNetworkArchitecture;

  /// The current serving state of the Cloud SQL instance.
  late final pulumi.Output<String> state;

  /// If the instance state is SUSPENDED, the reason for the suspension.
  late final pulumi.Output<List<String>> suspensionReason;

  /// The dns name of the primary instance in a replication group.
  late final pulumi.Output<String> writeEndpoint;

  /// Creates a new [Instance].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [Instance]. {@macro pulumi_sqladmin_v1_instance_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  Instance(
    String name, {
    InstanceArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
         'google-native:sqladmin/v1:Instance',
         name,
         pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
         options ?? pulumi.CustomResourceOptions(),
       ) {
    availableMaintenanceVersions = registerOutput<List<String>>(
      'availableMaintenanceVersions',
    );
    backendType = registerOutput<String>('backendType');
    connectionName = registerOutput<String>('connectionName');
    createTime = registerOutput<String>('createTime');
    currentDiskSize = registerOutput<String>('currentDiskSize');
    databaseInstalledVersion = registerOutput<String>(
      'databaseInstalledVersion',
    );
    databaseVersion = registerOutput<String>('databaseVersion');
    diskEncryptionConfiguration =
        registerOutput<DiskEncryptionConfigurationResponse>(
          'diskEncryptionConfiguration',
        );
    diskEncryptionStatus = registerOutput<DiskEncryptionStatusResponse>(
      'diskEncryptionStatus',
    );
    dnsName = registerOutput<String>('dnsName');
    etag = registerOutput<String>('etag');
    failoverReplica = registerOutput<InstanceFailoverReplicaResponse>(
      'failoverReplica',
    );
    gceZone = registerOutput<String>('gceZone');
    instanceType = registerOutput<String>('instanceType');
    ipAddresses = registerOutput<List<Map<String, dynamic>>>('ipAddresses');
    ipv6Address = registerOutput<String>('ipv6Address');
    kind = registerOutput<String>('kind');
    maintenanceVersion = registerOutput<String>('maintenanceVersion');
    masterInstanceName = registerOutput<String>('masterInstanceName');
    maxDiskSize = registerOutput<String>('maxDiskSize');
    this.name = registerOutput<String>('name');
    onPremisesConfiguration = registerOutput<OnPremisesConfigurationResponse>(
      'onPremisesConfiguration',
    );
    outOfDiskReport = registerOutput<SqlOutOfDiskReportResponse>(
      'outOfDiskReport',
    );
    primaryDnsName = registerOutput<String>('primaryDnsName');
    project = registerOutput<String>('project');
    pscServiceAttachmentLink = registerOutput<String>(
      'pscServiceAttachmentLink',
    );
    region = registerOutput<String>('region');
    replicaConfiguration = registerOutput<ReplicaConfigurationResponse>(
      'replicaConfiguration',
    );
    replicaNames = registerOutput<List<String>>('replicaNames');
    rootPassword = registerOutput<String>('rootPassword');
    satisfiesPzs = registerOutput<bool>('satisfiesPzs');
    scheduledMaintenance = registerOutput<SqlScheduledMaintenanceResponse>(
      'scheduledMaintenance',
    );
    secondaryGceZone = registerOutput<String>('secondaryGceZone');
    selfLink = registerOutput<String>('selfLink');
    serverCaCert = registerOutput<SslCertResponse>('serverCaCert');
    serviceAccountEmailAddress = registerOutput<String>(
      'serviceAccountEmailAddress',
    );
    settings = registerOutput<SettingsResponse>('settings');
    sqlNetworkArchitecture = registerOutput<String>('sqlNetworkArchitecture');
    state = registerOutput<String>('state');
    suspensionReason = registerOutput<List<String>>('suspensionReason');
    writeEndpoint = registerOutput<String>('writeEndpoint');
  }
}
