// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'disk_encryption_configuration.dart';
import 'disk_encryption_status.dart';
import 'instance_backend_type.dart';
import 'instance_database_version.dart';
import 'instance_failover_replica.dart';
import 'instance_instance_type.dart';
import 'instance_sql_network_architecture.dart';
import 'instance_state.dart';
import 'instance_suspension_reason_item.dart';
import 'ip_mapping.dart';
import 'on_premises_configuration.dart';
import 'replica_configuration.dart';
import 'settings.dart';
import 'sql_out_of_disk_report.dart';
import 'sql_scheduled_maintenance.dart';
import 'ssl_cert_sqladmin_v1.dart';

/// {@template pulumi_sqladmin_v1_instance_args_doc}
/// The set of arguments for Instance.
/// {@endtemplate}
/// {@macro pulumi_sqladmin_v1_instance_args_doc}
class InstanceArgs {
  /// The backend type. `SECOND_GEN`: Cloud SQL database instance. `EXTERNAL`: A database server that is not managed by Google. This property is read-only; use the `tier` property in the `settings` object to determine the database type.
  final pulumi.Input<InstanceBackendType>? backendType;
  /// Connection name of the Cloud SQL instance used in connection strings.
  final pulumi.Input<String>? connectionName;
  /// The current disk usage of the instance in bytes. This property has been deprecated. Use the "cloudsql.googleapis.com/database/disk/bytes_used" metric in Cloud Monitoring API instead. Please see [this announcement](https://groups.google.com/d/msg/google-cloud-sql-announce/I_7-F9EBhT0/BtvFtdFeAgAJ) for details.
  final pulumi.Input<String>? currentDiskSize;
  /// The database engine type and version. The `databaseVersion` field cannot be changed after instance creation.
  final pulumi.Input<InstanceDatabaseVersion>? databaseVersion;
  /// Disk encryption configuration specific to an instance.
  final pulumi.Input<DiskEncryptionConfiguration>? diskEncryptionConfiguration;
  /// Disk encryption status specific to an instance.
  final pulumi.Input<DiskEncryptionStatus>? diskEncryptionStatus;
  /// This field is deprecated and will be removed from a future version of the API. Use the `settings.settingsVersion` field instead.
  final pulumi.Input<String>? etag;
  /// The name and status of the failover replica.
  final pulumi.Input<InstanceFailoverReplica>? failoverReplica;
  /// The Compute Engine zone that the instance is currently serving from. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary zone. WARNING: Changing this might restart the instance.
  final pulumi.Input<String>? gceZone;
  /// The instance type.
  final pulumi.Input<InstanceInstanceType>? instanceType;
  /// The assigned IP addresses for the instance.
  final pulumi.Input<List<IpMapping>>? ipAddresses;
  /// The IPv6 address assigned to the instance. (Deprecated) This property was applicable only to First Generation instances.
  final pulumi.Input<String>? ipv6Address;
  /// This is always `sql#instance`.
  final pulumi.Input<String>? kind;
  /// The current software version on the instance.
  final pulumi.Input<String>? maintenanceVersion;
  /// The name of the instance which will act as primary in the replication setup.
  final pulumi.Input<String>? masterInstanceName;
  /// The maximum disk size of the instance in bytes.
  final pulumi.Input<String>? maxDiskSize;
  /// Name of the Cloud SQL instance. This does not include the project ID.
  final pulumi.Input<String>? name;
  /// Configuration specific to on-premises instances.
  final pulumi.Input<OnPremisesConfiguration>? onPremisesConfiguration;
  /// This field represents the report generated by the proactive database wellness job for OutOfDisk issues. * Writers: * the proactive database wellness job for OOD. * Readers: * the proactive database wellness job
  final pulumi.Input<SqlOutOfDiskReport>? outOfDiskReport;
  /// The project ID of the project containing the Cloud SQL instance. The Google apps domain is prefixed if applicable.
  final pulumi.Input<String>? project;
  /// The geographical region. Can be: * `us-central` (`FIRST_GEN` instances only) * `us-central1` (`SECOND_GEN` instances only) * `asia-east1` or `europe-west1`. Defaults to `us-central` or `us-central1` depending on the instance type. The region cannot be changed after instance creation.
  final pulumi.Input<String>? region;
  /// Configuration specific to failover replicas and read replicas.
  final pulumi.Input<ReplicaConfiguration>? replicaConfiguration;
  /// The replicas of the instance.
  final pulumi.Input<List<String>>? replicaNames;
  /// Initial root password. Use only on creation. You must set root passwords before you can connect to PostgreSQL instances.
  final pulumi.Input<String>? rootPassword;
  /// The status indicating if instance satisfiesPzs. Reserved for future use.
  final pulumi.Input<bool>? satisfiesPzs;
  /// The start time of any upcoming scheduled maintenance for this instance.
  final pulumi.Input<SqlScheduledMaintenance>? scheduledMaintenance;
  /// The Compute Engine zone that the failover instance is currently serving from for a regional instance. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary/failover zone.
  final pulumi.Input<String>? secondaryGceZone;
  /// The URI of this resource.
  final pulumi.Input<String>? selfLink;
  /// SSL configuration.
  final pulumi.Input<SslCertSqladminV1>? serverCaCert;
  /// The service account email address assigned to the instance.\This property is read-only.
  final pulumi.Input<String>? serviceAccountEmailAddress;
  /// The user settings.
  final pulumi.Input<Settings>? settings;
  final pulumi.Input<InstanceSqlNetworkArchitecture>? sqlNetworkArchitecture;
  /// The current serving state of the Cloud SQL instance.
  final pulumi.Input<InstanceState>? state;
  /// If the instance state is SUSPENDED, the reason for the suspension.
  final pulumi.Input<List<InstanceSuspensionReasonItem>>? suspensionReason;

  /// Creates a new [InstanceArgs].
  /// [backendType] The backend type. `SECOND_GEN`: Cloud SQL database instance. `EXTERNAL`: A database server that is not managed by Google. This property is read-only; use the `tier` property in the `settings` object to determine the database type.
  /// [connectionName] Connection name of the Cloud SQL instance used in connection strings.
  /// [currentDiskSize] The current disk usage of the instance in bytes. This property has been deprecated. Use the "cloudsql.googleapis.com/database/disk/bytes_used" metric in Cloud Monitoring API instead. Please see [this announcement](https://groups.google.com/d/msg/google-cloud-sql-announce/I_7-F9EBhT0/BtvFtdFeAgAJ) for details.
  /// [databaseVersion] The database engine type and version. The `databaseVersion` field cannot be changed after instance creation.
  /// [diskEncryptionConfiguration] Disk encryption configuration specific to an instance.
  /// [diskEncryptionStatus] Disk encryption status specific to an instance.
  /// [etag] This field is deprecated and will be removed from a future version of the API. Use the `settings.settingsVersion` field instead.
  /// [failoverReplica] The name and status of the failover replica.
  /// [gceZone] The Compute Engine zone that the instance is currently serving from. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary zone. WARNING: Changing this might restart the instance.
  /// [instanceType] The instance type.
  /// [ipAddresses] The assigned IP addresses for the instance.
  /// [ipv6Address] The IPv6 address assigned to the instance. (Deprecated) This property was applicable only to First Generation instances.
  /// [kind] This is always `sql#instance`.
  /// [maintenanceVersion] The current software version on the instance.
  /// [masterInstanceName] The name of the instance which will act as primary in the replication setup.
  /// [maxDiskSize] The maximum disk size of the instance in bytes.
  /// [name] Name of the Cloud SQL instance. This does not include the project ID.
  /// [onPremisesConfiguration] Configuration specific to on-premises instances.
  /// [outOfDiskReport] This field represents the report generated by the proactive database wellness job for OutOfDisk issues. * Writers: * the proactive database wellness job for OOD. * Readers: * the proactive database wellness job
  /// [project] The project ID of the project containing the Cloud SQL instance. The Google apps domain is prefixed if applicable.
  /// [region] The geographical region. Can be: * `us-central` (`FIRST_GEN` instances only) * `us-central1` (`SECOND_GEN` instances only) * `asia-east1` or `europe-west1`. Defaults to `us-central` or `us-central1` depending on the instance type. The region cannot be changed after instance creation.
  /// [replicaConfiguration] Configuration specific to failover replicas and read replicas.
  /// [replicaNames] The replicas of the instance.
  /// [rootPassword] Initial root password. Use only on creation. You must set root passwords before you can connect to PostgreSQL instances.
  /// [satisfiesPzs] The status indicating if instance satisfiesPzs. Reserved for future use.
  /// [scheduledMaintenance] The start time of any upcoming scheduled maintenance for this instance.
  /// [secondaryGceZone] The Compute Engine zone that the failover instance is currently serving from for a regional instance. This value could be different from the zone that was specified when the instance was created if the instance has failed over to its secondary/failover zone.
  /// [selfLink] The URI of this resource.
  /// [serverCaCert] SSL configuration.
  /// [serviceAccountEmailAddress] The service account email address assigned to the instance.\This property is read-only.
  /// [settings] The user settings.
  /// [sqlNetworkArchitecture] Optional.
  /// [state] The current serving state of the Cloud SQL instance.
  /// [suspensionReason] If the instance state is SUSPENDED, the reason for the suspension.
  InstanceArgs({
    this.backendType,
    this.connectionName,
    this.currentDiskSize,
    this.databaseVersion,
    this.diskEncryptionConfiguration,
    this.diskEncryptionStatus,
    this.etag,
    this.failoverReplica,
    this.gceZone,
    this.instanceType,
    this.ipAddresses,
    this.ipv6Address,
    this.kind,
    this.maintenanceVersion,
    this.masterInstanceName,
    this.maxDiskSize,
    this.name,
    this.onPremisesConfiguration,
    this.outOfDiskReport,
    this.project,
    this.region,
    this.replicaConfiguration,
    this.replicaNames,
    this.rootPassword,
    this.satisfiesPzs,
    this.scheduledMaintenance,
    this.secondaryGceZone,
    this.selfLink,
    this.serverCaCert,
    this.serviceAccountEmailAddress,
    this.settings,
    this.sqlNetworkArchitecture,
    this.state,
    this.suspensionReason,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'backendType': ?pulumi.Input.mapOptionalInputValue<InstanceBackendType, String>(backendType, (value) => value.value),
      'connectionName': ?connectionName,
      'currentDiskSize': ?currentDiskSize,
      'databaseVersion': ?pulumi.Input.mapOptionalInputValue<InstanceDatabaseVersion, String>(databaseVersion, (value) => value.value),
      'diskEncryptionConfiguration': ?pulumi.Input.mapOptionalInputValue<DiskEncryptionConfiguration, Map<String, dynamic>>(diskEncryptionConfiguration, (value) => value.toMap()),
      'diskEncryptionStatus': ?pulumi.Input.mapOptionalInputValue<DiskEncryptionStatus, Map<String, dynamic>>(diskEncryptionStatus, (value) => value.toMap()),
      'etag': ?etag,
      'failoverReplica': ?pulumi.Input.mapOptionalInputValue<InstanceFailoverReplica, Map<String, dynamic>>(failoverReplica, (value) => value.toMap()),
      'gceZone': ?gceZone,
      'instanceType': ?pulumi.Input.mapOptionalInputValue<InstanceInstanceType, String>(instanceType, (value) => value.value),
      'ipAddresses': ?pulumi.Input.mapOptionalInputValue<List<IpMapping>, List<Map<String, dynamic>>>(ipAddresses, (value) => pulumi.Input.encodeList<IpMapping, Map<String, dynamic>>(value, (value) => value.toMap())),
      'ipv6Address': ?ipv6Address,
      'kind': ?kind,
      'maintenanceVersion': ?maintenanceVersion,
      'masterInstanceName': ?masterInstanceName,
      'maxDiskSize': ?maxDiskSize,
      'name': ?name,
      'onPremisesConfiguration': ?pulumi.Input.mapOptionalInputValue<OnPremisesConfiguration, Map<String, dynamic>>(onPremisesConfiguration, (value) => value.toMap()),
      'outOfDiskReport': ?pulumi.Input.mapOptionalInputValue<SqlOutOfDiskReport, Map<String, dynamic>>(outOfDiskReport, (value) => value.toMap()),
      'project': ?project,
      'region': ?region,
      'replicaConfiguration': ?pulumi.Input.mapOptionalInputValue<ReplicaConfiguration, Map<String, dynamic>>(replicaConfiguration, (value) => value.toMap()),
      'replicaNames': ?replicaNames,
      'rootPassword': ?rootPassword,
      'satisfiesPzs': ?satisfiesPzs,
      'scheduledMaintenance': ?pulumi.Input.mapOptionalInputValue<SqlScheduledMaintenance, Map<String, dynamic>>(scheduledMaintenance, (value) => value.toMap()),
      'secondaryGceZone': ?secondaryGceZone,
      'selfLink': ?selfLink,
      'serverCaCert': ?serverCaCert,
      'serviceAccountEmailAddress': ?serviceAccountEmailAddress,
      'settings': ?pulumi.Input.mapOptionalInputValue<Settings, Map<String, dynamic>>(settings, (value) => value.toMap()),
      'sqlNetworkArchitecture': ?pulumi.Input.mapOptionalInputValue<InstanceSqlNetworkArchitecture, String>(sqlNetworkArchitecture, (value) => value.value),
      'state': ?pulumi.Input.mapOptionalInputValue<InstanceState, String>(state, (value) => value.value),
      'suspensionReason': ?pulumi.Input.mapOptionalInputValue<List<InstanceSuspensionReasonItem>, List<String>>(suspensionReason, (value) => pulumi.Input.encodeList<InstanceSuspensionReasonItem, String>(value, (value) => value.value)),
    };
  }

  factory InstanceArgs.fromMap(Map<String, dynamic> map) {
    return InstanceArgs(
      backendType: map['backendType'] == null ? null : (InstanceBackendType.fromValue(map['backendType'] as String)).input(),
      connectionName: map['connectionName'] == null ? null : (map['connectionName'] as String).input(),
      currentDiskSize: map['currentDiskSize'] == null ? null : (map['currentDiskSize'] as String).input(),
      databaseVersion: map['databaseVersion'] == null ? null : (InstanceDatabaseVersion.fromValue(map['databaseVersion'] as String)).input(),
      diskEncryptionConfiguration: map['diskEncryptionConfiguration'] == null ? null : (DiskEncryptionConfiguration.fromMap((map['diskEncryptionConfiguration'] as Map).cast<String, dynamic>())).input(),
      diskEncryptionStatus: map['diskEncryptionStatus'] == null ? null : (DiskEncryptionStatus.fromMap((map['diskEncryptionStatus'] as Map).cast<String, dynamic>())).input(),
      etag: map['etag'] == null ? null : (map['etag'] as String).input(),
      failoverReplica: map['failoverReplica'] == null ? null : (InstanceFailoverReplica.fromMap((map['failoverReplica'] as Map).cast<String, dynamic>())).input(),
      gceZone: map['gceZone'] == null ? null : (map['gceZone'] as String).input(),
      instanceType: map['instanceType'] == null ? null : (InstanceInstanceType.fromValue(map['instanceType'] as String)).input(),
      ipAddresses: map['ipAddresses'] == null ? null : (pulumi.Input.decodeList<IpMapping>(map['ipAddresses'], (value) => IpMapping.fromMap((value as Map).cast<String, dynamic>()))).input(),
      ipv6Address: map['ipv6Address'] == null ? null : (map['ipv6Address'] as String).input(),
      kind: map['kind'] == null ? null : (map['kind'] as String).input(),
      maintenanceVersion: map['maintenanceVersion'] == null ? null : (map['maintenanceVersion'] as String).input(),
      masterInstanceName: map['masterInstanceName'] == null ? null : (map['masterInstanceName'] as String).input(),
      maxDiskSize: map['maxDiskSize'] == null ? null : (map['maxDiskSize'] as String).input(),
      name: map['name'] == null ? null : (map['name'] as String).input(),
      onPremisesConfiguration: map['onPremisesConfiguration'] == null ? null : (OnPremisesConfiguration.fromMap((map['onPremisesConfiguration'] as Map).cast<String, dynamic>())).input(),
      outOfDiskReport: map['outOfDiskReport'] == null ? null : (SqlOutOfDiskReport.fromMap((map['outOfDiskReport'] as Map).cast<String, dynamic>())).input(),
      project: map['project'] == null ? null : (map['project'] as String).input(),
      region: map['region'] == null ? null : (map['region'] as String).input(),
      replicaConfiguration: map['replicaConfiguration'] == null ? null : (ReplicaConfiguration.fromMap((map['replicaConfiguration'] as Map).cast<String, dynamic>())).input(),
      replicaNames: map['replicaNames'] == null ? null : ((map['replicaNames'] as List).cast<String>()).input(),
      rootPassword: map['rootPassword'] == null ? null : (map['rootPassword'] as String).input(),
      satisfiesPzs: map['satisfiesPzs'] == null ? null : (map['satisfiesPzs'] as bool).input(),
      scheduledMaintenance: map['scheduledMaintenance'] == null ? null : (SqlScheduledMaintenance.fromMap((map['scheduledMaintenance'] as Map).cast<String, dynamic>())).input(),
      secondaryGceZone: map['secondaryGceZone'] == null ? null : (map['secondaryGceZone'] as String).input(),
      selfLink: map['selfLink'] == null ? null : (map['selfLink'] as String).input(),
      serverCaCert: map['serverCaCert'] == null ? null : (map['serverCaCert'] as SslCertSqladminV1).input(),
      serviceAccountEmailAddress: map['serviceAccountEmailAddress'] == null ? null : (map['serviceAccountEmailAddress'] as String).input(),
      settings: map['settings'] == null ? null : (Settings.fromMap((map['settings'] as Map).cast<String, dynamic>())).input(),
      sqlNetworkArchitecture: map['sqlNetworkArchitecture'] == null ? null : (InstanceSqlNetworkArchitecture.fromValue(map['sqlNetworkArchitecture'] as String)).input(),
      state: map['state'] == null ? null : (InstanceState.fromValue(map['state'] as String)).input(),
      suspensionReason: map['suspensionReason'] == null ? null : (pulumi.Input.decodeList<InstanceSuspensionReasonItem>(map['suspensionReason'], (value) => InstanceSuspensionReasonItem.fromValue(value as String))).input(),
    );
  }
}

