// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering WorkstationConfigIamPolicy resources.
class WorkstationConfigIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;
  /// The location where the workstation cluster config should reside.
  /// Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? location;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;
  /// The ID of the parent workstation cluster.
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? workstationClusterId;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? workstationConfigId;

  /// Creates a new [WorkstationConfigIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [location] The location where the workstation cluster config should reside.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [workstationClusterId] The ID of the parent workstation cluster.
  /// [workstationConfigId] Used to find the parent resource to bind the IAM policy to
  WorkstationConfigIamPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? location,
    pulumi.Output<String>? policyData,
    pulumi.Output<String>? project,
    pulumi.Output<String>? workstationClusterId,
    pulumi.Output<String>? workstationConfigId,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      location = pulumi.Input.asOptionalInput<String>(location),
      policyData = pulumi.Input.asOptionalInput<String>(policyData),
      project = pulumi.Input.asOptionalInput<String>(project),
      workstationClusterId = pulumi.Input.asOptionalInput<String>(workstationClusterId),
      workstationConfigId = pulumi.Input.asOptionalInput<String>(workstationConfigId);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'location': ?location,
      'policyData': ?policyData,
      'project': ?project,
      'workstationClusterId': ?workstationClusterId,
      'workstationConfigId': ?workstationConfigId,
    };
  }

  factory WorkstationConfigIamPolicyState.fromMap(Map<String, dynamic> map) {
    return WorkstationConfigIamPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      location: map['location'] == null ? null : pulumi.Output.create<String>(map['location'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
      workstationClusterId: map['workstationClusterId'] == null ? null : pulumi.Output.create<String>(map['workstationClusterId'] as String),
      workstationConfigId: map['workstationConfigId'] == null ? null : pulumi.Output.create<String>(map['workstationConfigId'] as String),
    );
  }
}

