library module_s3_bucket_metadata_configuration_metadata_configuration_inventory_table_configuration;

export 'bucket_metadata_configuration_metadata_configuration_inventory_table_configuration.dart';
