// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';
import 'customer_encryption_key_response3.dart';
import 'deprecation_status_response3.dart';
import 'guest_os_feature_response3.dart';
import 'image_raw_disk_response3.dart';
import 'initial_state_config_response3.dart';

/// Result data returned by getImage.
class GetImageResult3 {
  /// The architecture of the image. Valid values are ARM64 or X86_64.
  final String architecture;

  /// Size of the image tar.gz archive stored in Google Cloud Storage (in bytes).
  final String archiveSizeBytes;

  /// Creation timestamp in RFC3339 text format.
  final String creationTimestamp;

  /// The deprecation status associated with this image.
  final DeprecationStatusResponse3 deprecated;

  /// An optional description of this resource. Provide this property when you create the resource.
  final String description;

  /// Size of the image when restored onto a persistent disk (in GB).
  final String diskSizeGb;

  /// The name of the image family to which this image belongs. The image family name can be from a publicly managed image family provided by Compute Engine, or from a custom image family you create. For example, centos-stream-9 is a publicly available image family. For more information, see Image family best practices. When creating disks, you can specify an image family instead of a specific image name. The image family always returns its latest image that is not deprecated. The name of the image family must comply with RFC1035.
  final String family;

  /// A list of features to enable on the guest operating system. Applicable only for bootable images. To see a list of available options, see the guestOSfeatures[].type parameter.
  final List<GuestOsFeatureResponse3> guestOsFeatures;

  /// Encrypts the image using a customer-supplied encryption key. After you encrypt an image with a customer-supplied key, you must provide the same key if you use the image later (e.g. to create a disk from the image). Customer-supplied encryption keys do not protect access to metadata of the disk. If you do not provide an encryption key when creating the image, then the disk will be encrypted using an automatically generated key and you do not need to provide a key to use the image later.
  final CustomerEncryptionKeyResponse3 imageEncryptionKey;

  /// Type of the resource. Always compute#image for images.
  final String kind;

  /// A fingerprint for the labels being applied to this image, which is essentially a hash of the labels used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error 412 conditionNotMet. To see the latest fingerprint, make a get() request to retrieve an image.
  final String labelFingerprint;

  /// Labels to apply to this image. These can be later modified by the setLabels method.
  final Map<String, String> labels;

  /// Integer license codes indicating which licenses are attached to this image.
  final List<String> licenseCodes;

  /// Any applicable license URI.
  final List<String> licenses;

  /// Name of the resource; provided by the client when the resource is created. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
  final String name;

  /// The parameters of the raw disk image.
  final ImageRawDiskResponse3 rawDisk;

  /// Reserved for future use.
  final bool satisfiesPzs;

  /// Server-defined URL for the resource.
  final String selfLink;

  /// Set the secure boot keys of shielded instance.
  final InitialStateConfigResponse3 shieldedInstanceInitialState;

  /// URL of the source disk used to create this image. For example, the following are valid values: - https://www.googleapis.com/compute/v1/projects/project/zones/zone /disks/disk - projects/project/zones/zone/disks/disk - zones/zone/disks/disk In order to create an image, you must provide the full or partial URL of one of the following: - The rawDisk.source URL - The sourceDisk URL - The sourceImage URL - The sourceSnapshot URL
  final String sourceDisk;

  /// The customer-supplied encryption key of the source disk. Required if the source disk is protected by a customer-supplied encryption key.
  final CustomerEncryptionKeyResponse3 sourceDiskEncryptionKey;

  /// The ID value of the disk used to create this image. This value may be used to determine whether the image was taken from the current or a previous instance of a given disk name.
  final String sourceDiskId;

  /// URL of the source image used to create this image. The following are valid formats for the URL: - https://www.googleapis.com/compute/v1/projects/project_id/global/ images/image_name - projects/project_id/global/images/image_name In order to create an image, you must provide the full or partial URL of one of the following: - The rawDisk.source URL - The sourceDisk URL - The sourceImage URL - The sourceSnapshot URL
  final String sourceImage;

  /// The customer-supplied encryption key of the source image. Required if the source image is protected by a customer-supplied encryption key.
  final CustomerEncryptionKeyResponse3 sourceImageEncryptionKey;

  /// The ID value of the image used to create this image. This value may be used to determine whether the image was taken from the current or a previous instance of a given image name.
  final String sourceImageId;

  /// URL of the source snapshot used to create this image. The following are valid formats for the URL: - https://www.googleapis.com/compute/v1/projects/project_id/global/ snapshots/snapshot_name - projects/project_id/global/snapshots/snapshot_name In order to create an image, you must provide the full or partial URL of one of the following: - The rawDisk.source URL - The sourceDisk URL - The sourceImage URL - The sourceSnapshot URL
  final String sourceSnapshot;

  /// The customer-supplied encryption key of the source snapshot. Required if the source snapshot is protected by a customer-supplied encryption key.
  final CustomerEncryptionKeyResponse3 sourceSnapshotEncryptionKey;

  /// The ID value of the snapshot used to create this image. This value may be used to determine whether the snapshot was taken from the current or a previous instance of a given snapshot name.
  final String sourceSnapshotId;

  /// The type of the image used to create this disk. The default and only valid value is RAW.
  final String sourceType;

  /// The status of the image. An image can be used to create other resources, such as instances, only after the image has been successfully created and the status is set to READY. Possible values are FAILED, PENDING, or READY.
  final String status;

  /// Cloud Storage bucket storage location of the image (regional or multi-regional).
  final List<String> storageLocations;

  GetImageResult3({
    required this.architecture,
    required this.archiveSizeBytes,
    required this.creationTimestamp,
    required this.deprecated,
    required this.description,
    required this.diskSizeGb,
    required this.family,
    required this.guestOsFeatures,
    required this.imageEncryptionKey,
    required this.kind,
    required this.labelFingerprint,
    required this.labels,
    required this.licenseCodes,
    required this.licenses,
    required this.name,
    required this.rawDisk,
    required this.satisfiesPzs,
    required this.selfLink,
    required this.shieldedInstanceInitialState,
    required this.sourceDisk,
    required this.sourceDiskEncryptionKey,
    required this.sourceDiskId,
    required this.sourceImage,
    required this.sourceImageEncryptionKey,
    required this.sourceImageId,
    required this.sourceSnapshot,
    required this.sourceSnapshotEncryptionKey,
    required this.sourceSnapshotId,
    required this.sourceType,
    required this.status,
    required this.storageLocations,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['architecture'] = architecture;
    map['archiveSizeBytes'] = archiveSizeBytes;
    map['creationTimestamp'] = creationTimestamp;
    map['deprecated'] = deprecated.toMap();
    map['description'] = description;
    map['diskSizeGb'] = diskSizeGb;
    map['family'] = family;
    map['guestOsFeatures'] =
        Input.encodeList<GuestOsFeatureResponse3, Map<String, dynamic>>(
            guestOsFeatures, (value) => value.toMap());
    map['imageEncryptionKey'] = imageEncryptionKey.toMap();
    map['kind'] = kind;
    map['labelFingerprint'] = labelFingerprint;
    map['labels'] = labels;
    map['licenseCodes'] = licenseCodes;
    map['licenses'] = licenses;
    map['name'] = name;
    map['rawDisk'] = rawDisk.toMap();
    map['satisfiesPzs'] = satisfiesPzs;
    map['selfLink'] = selfLink;
    map['shieldedInstanceInitialState'] = shieldedInstanceInitialState.toMap();
    map['sourceDisk'] = sourceDisk;
    map['sourceDiskEncryptionKey'] = sourceDiskEncryptionKey.toMap();
    map['sourceDiskId'] = sourceDiskId;
    map['sourceImage'] = sourceImage;
    map['sourceImageEncryptionKey'] = sourceImageEncryptionKey.toMap();
    map['sourceImageId'] = sourceImageId;
    map['sourceSnapshot'] = sourceSnapshot;
    map['sourceSnapshotEncryptionKey'] = sourceSnapshotEncryptionKey.toMap();
    map['sourceSnapshotId'] = sourceSnapshotId;
    map['sourceType'] = sourceType;
    map['status'] = status;
    map['storageLocations'] = storageLocations;
    return map;
  }

  factory GetImageResult3.fromMap(Map<String, dynamic> map) {
    return GetImageResult3(
      architecture: map['architecture'] as String,
      archiveSizeBytes: map['archiveSizeBytes'] as String,
      creationTimestamp: map['creationTimestamp'] as String,
      deprecated: DeprecationStatusResponse3.fromMap(
          (map['deprecated'] as Map).cast<String, dynamic>()),
      description: map['description'] as String,
      diskSizeGb: map['diskSizeGb'] as String,
      family: map['family'] as String,
      guestOsFeatures: Input.decodeList<GuestOsFeatureResponse3>(
          map['guestOsFeatures'],
          (value) => GuestOsFeatureResponse3.fromMap(
              (value as Map).cast<String, dynamic>())),
      imageEncryptionKey: CustomerEncryptionKeyResponse3.fromMap(
          (map['imageEncryptionKey'] as Map).cast<String, dynamic>()),
      kind: map['kind'] as String,
      labelFingerprint: map['labelFingerprint'] as String,
      labels: (map['labels'] as Map).cast<String, String>(),
      licenseCodes: (map['licenseCodes'] as List).cast<String>(),
      licenses: (map['licenses'] as List).cast<String>(),
      name: map['name'] as String,
      rawDisk: ImageRawDiskResponse3.fromMap(
          (map['rawDisk'] as Map).cast<String, dynamic>()),
      satisfiesPzs: map['satisfiesPzs'] as bool,
      selfLink: map['selfLink'] as String,
      shieldedInstanceInitialState: InitialStateConfigResponse3.fromMap(
          (map['shieldedInstanceInitialState'] as Map).cast<String, dynamic>()),
      sourceDisk: map['sourceDisk'] as String,
      sourceDiskEncryptionKey: CustomerEncryptionKeyResponse3.fromMap(
          (map['sourceDiskEncryptionKey'] as Map).cast<String, dynamic>()),
      sourceDiskId: map['sourceDiskId'] as String,
      sourceImage: map['sourceImage'] as String,
      sourceImageEncryptionKey: CustomerEncryptionKeyResponse3.fromMap(
          (map['sourceImageEncryptionKey'] as Map).cast<String, dynamic>()),
      sourceImageId: map['sourceImageId'] as String,
      sourceSnapshot: map['sourceSnapshot'] as String,
      sourceSnapshotEncryptionKey: CustomerEncryptionKeyResponse3.fromMap(
          (map['sourceSnapshotEncryptionKey'] as Map).cast<String, dynamic>()),
      sourceSnapshotId: map['sourceSnapshotId'] as String,
      sourceType: map['sourceType'] as String,
      status: map['status'] as String,
      storageLocations: (map['storageLocations'] as List).cast<String>(),
    );
  }
}
