// ignore_for_file: unused_element, unnecessary_cast

/// Description of a planned outage on this Interconnect.
class InterconnectOutageNotificationResponse3 {
  /// If issue_type is IT_PARTIAL_OUTAGE, a list of the Google-side circuit IDs that will be affected.
  final List<String> affectedCircuits;

  /// A description about the purpose of the outage.
  final String description;

  /// Scheduled end time for the outage (milliseconds since Unix epoch).
  final String endTime;

  /// Form this outage is expected to take, which can take one of the following values: - OUTAGE: The Interconnect may be completely out of service for some or all of the specified window. - PARTIAL_OUTAGE: Some circuits comprising the Interconnect as a whole should remain up, but with reduced bandwidth. Note that the versions of this enum prefixed with "IT_" have been deprecated in favor of the unprefixed values.
  final String issueType;

  /// Unique identifier for this outage notification.
  final String name;

  /// The party that generated this notification, which can take the following value: - GOOGLE: this notification as generated by Google. Note that the value of NSRC_GOOGLE has been deprecated in favor of GOOGLE.
  final String source;

  /// Scheduled start time for the outage (milliseconds since Unix epoch).
  final String startTime;

  /// State of this notification, which can take one of the following values: - ACTIVE: This outage notification is active. The event could be in the past, present, or future. See start_time and end_time for scheduling. - CANCELLED: The outage associated with this notification was cancelled before the outage was due to start. - COMPLETED: The outage associated with this notification is complete. Note that the versions of this enum prefixed with "NS_" have been deprecated in favor of the unprefixed values.
  final String state;

  InterconnectOutageNotificationResponse3({
    required this.affectedCircuits,
    required this.description,
    required this.endTime,
    required this.issueType,
    required this.name,
    required this.source,
    required this.startTime,
    required this.state,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['affectedCircuits'] = affectedCircuits;
    map['description'] = description;
    map['endTime'] = endTime;
    map['issueType'] = issueType;
    map['name'] = name;
    map['source'] = source;
    map['startTime'] = startTime;
    map['state'] = state;
    return map;
  }

  factory InterconnectOutageNotificationResponse3.fromMap(
      Map<String, dynamic> map) {
    return InterconnectOutageNotificationResponse3(
      affectedCircuits: (map['affectedCircuits'] as List).cast<String>(),
      description: map['description'] as String,
      endTime: map['endTime'] as String,
      issueType: map['issueType'] as String,
      name: map['name'] as String,
      source: map['source'] as String,
      startTime: map['startTime'] as String,
      state: map['state'] as String,
    );
  }
}
