library module_dataloss_prevention_discovery_config_target_other_cloud_target_filter_collection_include_regexes_pattern;

export 'prevention_discovery_config_target_other_cloud_target_filter_collection_include_regexes_pattern/prevention_discovery_config_target_other_cloud_target_filter_collection_include_regexes_pattern.dart';
