library module_dataloss_prevention_discovery_config_target_big_query_target_filter_table_reference;

export 'prevention_discovery_config_target_big_query_target_filter_table_reference/prevention_discovery_config_target_big_query_target_filter_table_reference.dart';
