library module_dataloss_prevention_job_trigger_inspect_job_action_save_findings_output_config_table;

export 'prevention_job_trigger_inspect_job_action_save_findings_output_config_table/prevention_job_trigger_inspect_job_action_save_findings_output_config_table.dart';
