library module_dataloss_prevention_job_trigger_inspect_job_inspect_config_custom_info_type_regex;

export 'prevention_job_trigger_inspect_job_inspect_config_custom_info_type_regex/prevention_job_trigger_inspect_job_inspect_config_custom_info_type_regex.dart';
