library module_dataloss_prevention_job_trigger_inspect_job_storage_config_timespan_config_timestamp_field;

export 'prevention_job_trigger_inspect_job_storage_config_timespan_config_timestamp_field/prevention_job_trigger_inspect_job_storage_config_timespan_config_timestamp_field.dart';
