library module_dataloss_prevention_inspect_template_inspect_config_custom_info_type_regex;

export 'prevention_inspect_template_inspect_config_custom_info_type_regex/prevention_inspect_template_inspect_config_custom_info_type_regex.dart';
