library module_dataloss_prevention_job_trigger_inspect_job_inspect_config_info_type;

export 'prevention_job_trigger_inspect_job_inspect_config_info_type/prevention_job_trigger_inspect_job_inspect_config_info_type.dart';
