library module_dataloss_prevention_inspect_template_inspect_config_custom_info_type_sensitivity_score;

export 'prevention_inspect_template_inspect_config_custom_info_type_sensitivity_score/prevention_inspect_template_inspect_config_custom_info_type_sensitivity_score.dart';
