library module_dataloss_prevention_job_trigger_inspect_job_inspect_config_rule_set_rule_hotword_rule_likelihood_adjustment;

export 'prevention_job_trigger_inspect_job_inspect_config_rule_set_rule_hotword_rule_likelihood_adjustment/prevention_job_trigger_inspect_job_inspect_config_rule_set_rule_hotword_rule_likelihood_adjustment.dart';
