library module_dataloss_prevention_discovery_config_target_cloud_storage_target;

export 'prevention_discovery_config_target_cloud_storage_target/prevention_discovery_config_target_cloud_storage_target.dart';
