library module_dataloss_prevention_discovery_config_target_other_cloud_target_filter_single_resource;

export 'prevention_discovery_config_target_other_cloud_target_filter_single_resource/prevention_discovery_config_target_other_cloud_target_filter_single_resource.dart';
