library module_dataloss_prevention_discovery_config_target_big_query_target_conditions_types;

export 'prevention_discovery_config_target_big_query_target_conditions_types/prevention_discovery_config_target_big_query_target_conditions_types.dart';
