library module_dataloss_prevention_discovery_config_target_cloud_storage_target_generation_cadence;

export 'prevention_discovery_config_target_cloud_storage_target_generation_cadence/prevention_discovery_config_target_cloud_storage_target_generation_cadence.dart';
