library module_dataloss_prevention_inspect_template_inspect_config_limits_max_findings_per_info_type_info_type_sensitivity_score;

export 'prevention_inspect_template_inspect_config_limits_max_findings_per_info_type_info_type_sensitivity_score/prevention_inspect_template_inspect_config_limits_max_findings_per_info_type_info_type_sensitivity_score.dart';
