// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering SecurityGatewayApplicationIamPolicy resources.
class SecurityGatewayApplicationIamPolicyState {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? applicationId;
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;
  /// ID of the Security Gateway resource this belongs to. Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? securityGatewayId;

  /// Creates a new [SecurityGatewayApplicationIamPolicyState].
  /// [applicationId] Used to find the parent resource to bind the IAM policy to
  /// [etag] (Computed) The etag of the IAM policy.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [securityGatewayId] ID of the Security Gateway resource this belongs to. Used to find the parent resource to bind the IAM policy to
  SecurityGatewayApplicationIamPolicyState({
    pulumi.Output<String>? applicationId,
    pulumi.Output<String>? etag,
    pulumi.Output<String>? policyData,
    pulumi.Output<String>? project,
    pulumi.Output<String>? securityGatewayId,
  }) :
      applicationId = pulumi.Input.asOptionalInput<String>(applicationId),
      etag = pulumi.Input.asOptionalInput<String>(etag),
      policyData = pulumi.Input.asOptionalInput<String>(policyData),
      project = pulumi.Input.asOptionalInput<String>(project),
      securityGatewayId = pulumi.Input.asOptionalInput<String>(securityGatewayId);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'applicationId': ?applicationId,
      'etag': ?etag,
      'policyData': ?policyData,
      'project': ?project,
      'securityGatewayId': ?securityGatewayId,
    };
  }

  factory SecurityGatewayApplicationIamPolicyState.fromMap(Map<String, dynamic> map) {
    return SecurityGatewayApplicationIamPolicyState(
      applicationId: map['applicationId'] == null ? null : pulumi.Output.create<String>(map['applicationId'] as String),
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
      securityGatewayId: map['securityGatewayId'] == null ? null : pulumi.Output.create<String>(map['securityGatewayId'] as String),
    );
  }
}

