library module_wafv2_rule_group_rule_statement_rate_based_statement_scope_down_statement_or_statement;

export 'rule_group_rule_statement_rate_based_statement_scope_down_statement_or_statement/rule_group_rule_statement_rate_based_statement_scope_down_statement_or_statement.dart';
