library module_wafv2_rule_group_rule_statement_geo_match_statement_forwarded_ip_config;

export 'rule_group_rule_statement_geo_match_statement_forwarded_ip_config/rule_group_rule_statement_geo_match_statement_forwarded_ip_config.dart';
