library module_wafv2_rule_group_rule_statement_rate_based_statement_forwarded_ip_config;

export 'rule_group_rule_statement_rate_based_statement_forwarded_ip_config/rule_group_rule_statement_rate_based_statement_forwarded_ip_config.dart';
