library module_wafv2_rule_group_rule_statement_rate_based_statement_scope_down_statement_label_match_statement;

export 'rule_group_rule_statement_rate_based_statement_scope_down_statement_label_match_statement/rule_group_rule_statement_rate_based_statement_scope_down_statement_label_match_statement.dart';
