library module_wafv2_web_acl_rule_statement_rate_based_statement_scope_down_statement_regex_match_statement_field_to_match_single_query_argument;

export 'web_acl_rule_statement_rate_based_statement_scope_down_statement_regex_match_statement_field_to_match_single_query_argument/web_acl_rule_statement_rate_based_statement_scope_down_statement_regex_match_statement_field_to_match_single_query_argument.dart';
