library module_wafv2_web_acl_association_config_request_body_cognito_user_pool;

export 'web_acl_association_config_request_body_cognito_user_pool/web_acl_association_config_request_body_cognito_user_pool.dart';
