library module_wafv2_web_acl_rule_statement_managed_rule_group_statement_managed_rule_group_config;

export 'web_acl_rule_statement_managed_rule_group_statement_managed_rule_group_config/web_acl_rule_statement_managed_rule_group_statement_managed_rule_group_config.dart';
