library module_wafv2_web_acl_rule_statement_xss_match_statement_field_to_match_cookies_match_pattern;

export 'web_acl_rule_statement_xss_match_statement_field_to_match_cookies_match_pattern/web_acl_rule_statement_xss_match_statement_field_to_match_cookies_match_pattern.dart';
