library module_wafv2_web_acl_rule_statement_size_constraint_statement_text_transformation;

export 'web_acl_rule_statement_size_constraint_statement_text_transformation/web_acl_rule_statement_size_constraint_statement_text_transformation.dart';
