library module_wafv2_web_acl_rule_statement_geo_match_statement_forwarded_ip_config;

export 'web_acl_rule_statement_geo_match_statement_forwarded_ip_config/web_acl_rule_statement_geo_match_statement_forwarded_ip_config.dart';
