library module_wafv2_web_acl_rule_statement_managed_rule_group_statement_scope_down_statement_label_match_statement;

export 'web_acl_rule_statement_managed_rule_group_statement_scope_down_statement_label_match_statement/web_acl_rule_statement_managed_rule_group_statement_scope_down_statement_label_match_statement.dart';
