library module_wafv2_web_acl_rule_statement_regex_pattern_set_reference_statement_text_transformation;

export 'web_acl_rule_statement_regex_pattern_set_reference_statement_text_transformation.dart';
