name: pulumi_aws_apigateway
description: Pulumi Amazon Web Services (AWS) API Gateway Components.
version: 3.0.0
license: Apache-2.0
repository: https://github.com/pulumi/pulumi-aws-apigateway
topics:
    - pulumi
    - aws
    - apigateway
    - category-cloud
    - kind-component
publish_to: none
environment:
    sdk: ^3.10.0
resolution: workspace
dependencies:
    pulumi:
        path: /home/kingwill101/code/dart_packages/pulumi-dart/pulumi-dart
    pulumi_aws: ^7.0.0
dev_dependencies:
    lints: ^5.0.0
