name: pulumi_command
description: A Pulumi package for executing commands locally or remotely.
version: 1.0.0
resolution: workspace
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-command
topics:
  - pulumi
  - command

environment:
  sdk: ^3.10.0

dependencies:
  pulumi: 0.0.1

dev_dependencies:
  lints: ^5.0.0
