library module_appautoscaling_policy_predictive_scaling_policy_configuration_metric_specification_customized_load_metric_specification;

export 'policy_predictive_scaling_policy_configuration_metric_specification_customized_load_metric_specification.dart';
