library module_networkfirewall_tls_inspection_configuration_tls_inspection_configuration_server_certificate_configuration_scope_destination_port;

export 'tls_inspection_configuration_tls_inspection_configuration_server_certificate_configuration_scope_destination_port.dart';
