/// Ssl cipher suites enums.
enum ApplicationGatewaySslCipherSuite {
  valueTLSECDHERSAWITHAES256CBCSHA384("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"),
  valueTLSECDHERSAWITHAES128CBCSHA256("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"),
  valueTLSECDHERSAWITHAES256CBCSHA("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"),
  valueTLSECDHERSAWITHAES128CBCSHA("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"),
  valueTLSDHERSAWITHAES256GCMSHA384("TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"),
  valueTLSDHERSAWITHAES128GCMSHA256("TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"),
  valueTLSDHERSAWITHAES256CBCSHA("TLS_DHE_RSA_WITH_AES_256_CBC_SHA"),
  valueTLSDHERSAWITHAES128CBCSHA("TLS_DHE_RSA_WITH_AES_128_CBC_SHA"),
  valueTLSRSAWITHAES256GCMSHA384("TLS_RSA_WITH_AES_256_GCM_SHA384"),
  valueTLSRSAWITHAES128GCMSHA256("TLS_RSA_WITH_AES_128_GCM_SHA256"),
  valueTLSRSAWITHAES256CBCSHA256("TLS_RSA_WITH_AES_256_CBC_SHA256"),
  valueTLSRSAWITHAES128CBCSHA256("TLS_RSA_WITH_AES_128_CBC_SHA256"),
  valueTLSRSAWITHAES256CBCSHA("TLS_RSA_WITH_AES_256_CBC_SHA"),
  valueTLSRSAWITHAES128CBCSHA("TLS_RSA_WITH_AES_128_CBC_SHA"),
  valueTLSECDHEECDSAWITHAES256GCMSHA384(
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  ),
  valueTLSECDHEECDSAWITHAES128GCMSHA256(
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  ),
  valueTLSECDHEECDSAWITHAES256CBCSHA384(
    "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
  ),
  valueTLSECDHEECDSAWITHAES128CBCSHA256(
    "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
  ),
  valueTLSECDHEECDSAWITHAES256CBCSHA("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"),
  valueTLSECDHEECDSAWITHAES128CBCSHA("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"),
  valueTLSDHEDSSWITHAES256CBCSHA256("TLS_DHE_DSS_WITH_AES_256_CBC_SHA256"),
  valueTLSDHEDSSWITHAES128CBCSHA256("TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"),
  valueTLSDHEDSSWITHAES256CBCSHA("TLS_DHE_DSS_WITH_AES_256_CBC_SHA"),
  valueTLSDHEDSSWITHAES128CBCSHA("TLS_DHE_DSS_WITH_AES_128_CBC_SHA"),
  valueTLSRSAWITH3DESEDECBCSHA("TLS_RSA_WITH_3DES_EDE_CBC_SHA"),
  valueTLSDHEDSSWITH3DESEDECBCSHA("TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA"),
  valueTLSECDHERSAWITHAES128GCMSHA256("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"),
  valueTLSECDHERSAWITHAES256GCMSHA384("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");

  const ApplicationGatewaySslCipherSuite(this.wireValue);
  final String wireValue;

  static ApplicationGatewaySslCipherSuite fromValue(String value) {
    for (final item in ApplicationGatewaySslCipherSuite.values) {
      if (item.wireValue == value) {
        return item;
      }
    }
    throw ArgumentError(
      'Unknown ApplicationGatewaySslCipherSuite value: $value',
    );
  }
}
