name: aws_dart_stackreference_company
description: Pulumi stackreference company stack in Dart.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
dependencies:
  pulumi: 0.1.0
dev_dependencies:
  lints: ^6.1.0