library module_s3control_storage_lens_configuration_storage_lens_configuration_data_export_cloud_watch_metrics;

export 'storage_lens_configuration_storage_lens_configuration_data_export_cloud_watch_metrics.dart';
