library module_memorystore_get_instance_cross_instance_replication_config_primary_instance;

export 'get_instance_cross_instance_replication_config_primary_instance/get_instance_cross_instance_replication_config_primary_instance.dart';
