library module_memorystore_instance_automated_backup_config_fixed_frequency_schedule;

export 'instance_automated_backup_config_fixed_frequency_schedule/instance_automated_backup_config_fixed_frequency_schedule.dart';
