library module_memorystore_instance_cross_instance_replication_config_primary_instance;

export 'instance_cross_instance_replication_config_primary_instance/instance_cross_instance_replication_config_primary_instance.dart';
