library module_vertex_ai_feature_online_store_dedicated_serving_endpoint_private_service_connect_config;

export 'ai_feature_online_store_dedicated_serving_endpoint_private_service_connect_config.dart';
