library module_bedrock_agent_knowledge_base_storage_configuration_opensearch_serverless_configuration_field_mapping;

export 'agent_knowledge_base_storage_configuration_opensearch_serverless_configuration_field_mapping.dart';
