library module_oracledatabase_exascale_db_storage_vault_properties_exascale_db_storage_details;

export 'exascale_db_storage_vault_properties_exascale_db_storage_details/exascale_db_storage_vault_properties_exascale_db_storage_details.dart';
