// ignore_for_file: unused_element, unnecessary_cast

/// The SP's certificate data for IDP to verify the SAMLRequest generated by the SP.
class GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse {
  /// Timestamp of the cert expiration instance.
  final String expiresAt;

  /// Self-signed public certificate.
  final String x509Certificate;

  GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse({
    required this.expiresAt,
    required this.x509Certificate,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['expiresAt'] = expiresAt;
    map['x509Certificate'] = x509Certificate;
    return map;
  }

  factory GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse.fromMap(
      Map<String, dynamic> map) {
    return GoogleCloudIdentitytoolkitAdminV2SpCertificateResponse(
      expiresAt: map['expiresAt'] as String,
      x509Certificate: map['x509Certificate'] as String,
    );
  }
}
