name: pulumi_aws
description: A Pulumi package for creating and managing Amazon Web Services (AWS) cloud resources.
version: 7.20.0
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-aws
topics:
    - pulumi
    - aws
environment:
    sdk: ^3.11.0
resolution: workspace
dependencies:
    pulumi: 0.1.0
dev_dependencies:
    lints: ^6.1.0
