name: pulumi_aws
description: A Pulumi package for creating and managing Amazon Web Services (AWS) cloud resources.
version: 7.20.0
license: Apache-2.0
homepage: https://pulumi.io
repository: https://github.com/pulumi/pulumi-aws
topics:
    - pulumi
    - aws
publish_to: none
environment:
    sdk: ^3.11.0
resolution: workspace
dependencies:
    pulumi:
        path: /home/kingwill101/code/dart_packages/pulumi-dart/packages/pulumi-dart
dev_dependencies:
    lints: ^6.1.0
