library module_bedrock_agent_knowledge_base_storage_configuration_s3_vectors_configuration;

export 'agent_knowledge_base_storage_configuration_s3_vectors_configuration/agent_knowledge_base_storage_configuration_s3_vectors_configuration.dart';
