library module_bedrock_agent_flow_definition_node_configuration_prompt_source_configuration_inline_template_configuration_chat;

export 'agent_flow_definition_node_configuration_prompt_source_configuration_inline_template_configuration_chat/agent_flow_definition_node_configuration_prompt_source_configuration_inline_template_configuration_chat.dart';
