library module_bedrock_agentcore_gateway_target_target_configuration_mcp_lambda_tool_schema;

export 'agentcore_gateway_target_target_configuration_mcp_lambda_tool_schema/agentcore_gateway_target_target_configuration_mcp_lambda_tool_schema.dart';
