library module_bedrock_agent_data_source_data_source_configuration_s3_configuration;

export 'agent_data_source_data_source_configuration_s3_configuration/agent_data_source_data_source_configuration_s3_configuration.dart';
