library module_bedrock_agent_data_source_data_source_configuration_share_point_configuration;

export 'agent_data_source_data_source_configuration_share_point_configuration/agent_data_source_data_source_configuration_share_point_configuration.dart';
