library module_bedrock_agent_knowledge_base_knowledge_base_configuration_vector_knowledge_base_configuration_embedding_model_configuration;

export 'agent_knowledge_base_knowledge_base_configuration_vector_knowledge_base_configuration_embedding_model_configuration/agent_knowledge_base_knowledge_base_configuration_vector_knowledge_base_configuration_embedding_model_configuration.dart';
