library module_bedrock_agentcore_gateway_interceptor_configuration_interceptor_lambda;

export 'agentcore_gateway_interceptor_configuration_interceptor_lambda/agentcore_gateway_interceptor_configuration_interceptor_lambda.dart';
