library module_bedrock_agent_knowledge_base_knowledge_base_configuration_sql_knowledge_base_configuration;

export 'agent_knowledge_base_knowledge_base_configuration_sql_knowledge_base_configuration/agent_knowledge_base_knowledge_base_configuration_sql_knowledge_base_configuration.dart';
