library module_bedrock_agentcore_gateway_target_credential_provider_configuration_api_key;

export 'agentcore_gateway_target_credential_provider_configuration_api_key/agentcore_gateway_target_credential_provider_configuration_api_key.dart';
