library module_bedrock_guardrail_sensitive_information_policy_config_regexes_config;

export 'guardrail_sensitive_information_policy_config_regexes_config/guardrail_sensitive_information_policy_config_regexes_config.dart';
