library module_sagemaker_domain_default_space_settings_jupyter_server_app_settings_default_resource_spec;

export 'domain_default_space_settings_jupyter_server_app_settings_default_resource_spec.dart';
