name: azure_dart_stream_analytics
description: Uses an Azure Stream Analytics job to transform data in an Event Hub.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  crypto: ^3.0.6
  pulumi: 3.0.0
  pulumi_azure: 6.33.0

dev_dependencies:
  lints: ^6.1.0
