// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'file_system_lifecycle_policy.dart';
import 'file_system_protection.dart';

/// {@template pulumi_efs_file_system_file_system_args_doc}
/// The set of arguments for FileSystem.
/// {@endtemplate}
/// {@macro pulumi_efs_file_system_file_system_args_doc}
class FileSystemArgs {
  /// the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
  final pulumi.Input<String>? availabilityZoneName;

  /// A unique name (a maximum of 64 characters are allowed)
  /// used as reference when creating the Elastic File System to ensure idempotent file
  /// system creation. By default generated by this provider. See [Elastic File System]
  /// user guide for more information.
  final pulumi.Input<String>? creationToken;

  /// If true, the disk will be encrypted.
  final pulumi.Input<bool>? encrypted;

  /// The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
  final pulumi.Input<String>? kmsKeyId;

  /// A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
  final pulumi.Input<List<FileSystemLifecyclePolicy>>? lifecyclePolicies;

  /// The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
  final pulumi.Input<String>? performanceMode;

  /// A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
  final pulumi.Input<FileSystemProtection>? protection;

  /// The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
  final pulumi.Input<double>? provisionedThroughputInMibps;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;

  /// A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  final pulumi.Input<Map<String, String>>? tags;

  /// Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
  final pulumi.Input<String>? throughputMode;

  /// Creates a new [FileSystemArgs].
  /// [availabilityZoneName] the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
  /// [creationToken] A unique name (a maximum of 64 characters are allowed)
  /// [encrypted] If true, the disk will be encrypted.
  /// [kmsKeyId] The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
  /// [lifecyclePolicies] A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
  /// [performanceMode] The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
  /// [protection] A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
  /// [provisionedThroughputInMibps] The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  /// [tags] A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  /// [throughputMode] Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
  FileSystemArgs({
    String? availabilityZoneName,
    String? creationToken,
    bool? encrypted,
    String? kmsKeyId,
    List<FileSystemLifecyclePolicy>? lifecyclePolicies,
    String? performanceMode,
    FileSystemProtection? protection,
    double? provisionedThroughputInMibps,
    String? region,
    Map<String, String>? tags,
    String? throughputMode,
  }) : availabilityZoneName = pulumi.Input.asOptionalInput<String>(
         availabilityZoneName,
       ),
       creationToken = pulumi.Input.asOptionalInput<String>(creationToken),
       encrypted = pulumi.Input.asOptionalInput<bool>(encrypted),
       kmsKeyId = pulumi.Input.asOptionalInput<String>(kmsKeyId),
       lifecyclePolicies =
           pulumi.Input.asOptionalInput<List<FileSystemLifecyclePolicy>>(
             lifecyclePolicies,
           ),
       performanceMode = pulumi.Input.asOptionalInput<String>(performanceMode),
       protection = pulumi.Input.asOptionalInput<FileSystemProtection>(
         protection,
       ),
       provisionedThroughputInMibps = pulumi.Input.asOptionalInput<double>(
         provisionedThroughputInMibps,
       ),
       region = pulumi.Input.asOptionalInput<String>(region),
       tags = pulumi.Input.asOptionalInput<Map<String, String>>(tags),
       throughputMode = pulumi.Input.asOptionalInput<String>(throughputMode);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'availabilityZoneName': ?availabilityZoneName,
      'creationToken': ?creationToken,
      'encrypted': ?encrypted,
      'kmsKeyId': ?kmsKeyId,
      'lifecyclePolicies':
          ?pulumi.Input.mapOptionalInputValue<
            List<FileSystemLifecyclePolicy>,
            List<Map<String, dynamic>>
          >(
            lifecyclePolicies,
            (value) =>
                pulumi.Input.encodeList<
                  FileSystemLifecyclePolicy,
                  Map<String, dynamic>
                >(value, (value) => value.toMap()),
          ),
      'performanceMode': ?performanceMode,
      'protection':
          ?pulumi.Input.mapOptionalInputValue<
            FileSystemProtection,
            Map<String, dynamic>
          >(protection, (value) => value.toMap()),
      'provisionedThroughputInMibps': ?provisionedThroughputInMibps,
      'region': ?region,
      'tags': ?tags,
      'throughputMode': ?throughputMode,
    };
  }

  factory FileSystemArgs.fromMap(Map<String, dynamic> map) {
    return FileSystemArgs(
      availabilityZoneName: map['availabilityZoneName'] == null
          ? null
          : map['availabilityZoneName'] as String,
      creationToken: map['creationToken'] == null
          ? null
          : map['creationToken'] as String,
      encrypted: map['encrypted'] == null ? null : map['encrypted'] as bool,
      kmsKeyId: map['kmsKeyId'] == null ? null : map['kmsKeyId'] as String,
      lifecyclePolicies: map['lifecyclePolicies'] == null
          ? null
          : pulumi.Input.decodeList<FileSystemLifecyclePolicy>(
              map['lifecyclePolicies'],
              (value) => FileSystemLifecyclePolicy.fromMap(
                (value as Map).cast<String, dynamic>(),
              ),
            ),
      performanceMode: map['performanceMode'] == null
          ? null
          : map['performanceMode'] as String,
      protection: map['protection'] == null
          ? null
          : FileSystemProtection.fromMap(
              (map['protection'] as Map).cast<String, dynamic>(),
            ),
      provisionedThroughputInMibps: map['provisionedThroughputInMibps'] == null
          ? null
          : map['provisionedThroughputInMibps'] as double,
      region: map['region'] == null ? null : map['region'] as String,
      tags: map['tags'] == null
          ? null
          : (map['tags'] as Map).cast<String, String>(),
      throughputMode: map['throughputMode'] == null
          ? null
          : map['throughputMode'] as String,
    );
  }
}
