library module_observabilityadmin_centralization_rule_for_organization_rule_source_source_logs_configuration;

export 'centralization_rule_for_organization_rule_source_source_logs_configuration/centralization_rule_for_organization_rule_source_source_logs_configuration.dart';
