library module_quicksight_data_set_logical_table_map_data_transform_rename_column_operation;

export 'data_set_logical_table_map_data_transform_rename_column_operation/data_set_logical_table_map_data_transform_rename_column_operation.dart';
