library module_quicksight_data_set_row_level_permission_tag_configuration_tag_rule;

export 'data_set_row_level_permission_tag_configuration_tag_rule/data_set_row_level_permission_tag_configuration_tag_rule.dart';
