library module_s3_bucket_lifecycle_configuration_rule_abort_incomplete_multipart_upload;

export 'bucket_lifecycle_configuration_rule_abort_incomplete_multipart_upload/bucket_lifecycle_configuration_rule_abort_incomplete_multipart_upload.dart';
