library module_s3_bucket_replication_configuration_rule_source_selection_criteria;

export 'bucket_replication_configuration_rule_source_selection_criteria/bucket_replication_configuration_rule_source_selection_criteria.dart';
