library module_s3_bucket_lifecycle_configuration_rule_noncurrent_version_transition;

export 'bucket_lifecycle_configuration_rule_noncurrent_version_transition/bucket_lifecycle_configuration_rule_noncurrent_version_transition.dart';
