library module_s3_bucket_lifecycle_configuration_rule_noncurrent_version_expiration;

export 'bucket_lifecycle_configuration_rule_noncurrent_version_expiration/bucket_lifecycle_configuration_rule_noncurrent_version_expiration.dart';
