library module_s3_get_bucket_object_lock_configuration_rule_default_retention;

export 'get_bucket_object_lock_configuration_rule_default_retention/get_bucket_object_lock_configuration_rule_default_retention.dart';
