library module_s3_get_bucket_replication_configuration_rule_delete_marker_replication;

export 'get_bucket_replication_configuration_rule_delete_marker_replication/get_bucket_replication_configuration_rule_delete_marker_replication.dart';
