library module_s3_get_bucket_replication_configuration_rule_destination_metric_event_threshold;

export 'get_bucket_replication_configuration_rule_destination_metric_event_threshold/get_bucket_replication_configuration_rule_destination_metric_event_threshold.dart';
