library module_s3_get_bucket_replication_configuration_rule_source_selection_criteria_replica_modification;

export 'get_bucket_replication_configuration_rule_source_selection_criteria_replica_modification/get_bucket_replication_configuration_rule_source_selection_criteria_replica_modification.dart';
