library module_appautoscaling_policy_predictive_scaling_policy_configuration_metric_specification_customized_capacity_metric_specification_metric_data_query;

export 'policy_predictive_scaling_policy_configuration_metric_specification_customized_capacity_metric_specification_metric_data_query.dart';
