// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for ServiceIamPolicy.
class ServiceIamPolicyArgs2 {
  /// The policy data generated by
  /// a <span pulumi-lang-nodejs="`gcp.organizations.getIAMPolicy`" pulumi-lang-dotnet="`gcp.organizations.getIAMPolicy`" pulumi-lang-go="`organizations.getIAMPolicy`" pulumi-lang-python="`organizations_get_iam_policy`" pulumi-lang-yaml="`gcp.organizations.getIAMPolicy`" pulumi-lang-java="`gcp.organizations.getIAMPolicy`">`gcp.organizations.getIAMPolicy`</span> data source.
  final Input<String> policyData;

  /// Used to find the parent resource to bind the IAM policy to
  final Input<String> serviceName;

  ServiceIamPolicyArgs2({
    required this.policyData,
    required this.serviceName,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['policyData'] = policyData;
    map['serviceName'] = serviceName;
    return map;
  }

  factory ServiceIamPolicyArgs2.fromMap(Map<String, dynamic> map) {
    return ServiceIamPolicyArgs2(
      policyData: Input.asInput<String>(map['policyData']),
      serviceName: Input.asInput<String>(map['serviceName']),
    );
  }
}
