library module_dataloss_prevention_job_trigger_inspect_job_action_deidentify_transformation_details_storage_config_table;

export 'prevention_job_trigger_inspect_job_action_deidentify_transformation_details_storage_config_table.dart';
