// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'function_custom_container_config.dart';

/// {@template pulumi_fc_function_function_args_doc}
/// The set of arguments for Function.
/// {@endtemplate}
/// {@macro pulumi_fc_function_function_args_doc}
class FunctionArgs {
  /// The port that the function listen to, only valid for [custom runtime](https://www.alibabacloud.com/help/doc-detail/132044.htm) and [custom container runtime](https://www.alibabacloud.com/help/doc-detail/179368.htm).
  final pulumi.Input<int>? caPort;
  /// The checksum (crc64) of the function code.Used to trigger updates.The value can be generated by data source alicloud_file_crc64_checksum.
  /// > **NOTE:** For more information, see [Limits](https://www.alibabacloud.com/help/doc-detail/51907.htm).
  final pulumi.Input<String>? codeChecksum;
  /// The configuration for custom container runtime.See `custom_container_config` below.
  final pulumi.Input<FunctionCustomContainerConfig>? customContainerConfig;
  /// The Function Compute function description.
  final pulumi.Input<String>? description;
  /// A map that defines environment variables for the function.
  final pulumi.Input<Map<String, String>>? environmentVariables;
  /// The path to the function's deployment package within the local filesystem. It is conflict with the `oss_`-prefixed options.
  final pulumi.Input<String>? filename;
  /// The function [entry point](https://www.alibabacloud.com/help/doc-detail/157704.htm) in your code.
  final pulumi.Input<String> handler;
  /// The maximum length of time, in seconds, that the function's initialization should be run for.
  final pulumi.Input<int>? initializationTimeout;
  /// The entry point of the function's [initialization](https://www.alibabacloud.com/help/doc-detail/157704.htm).
  final pulumi.Input<String>? initializer;
  /// The maximum number of requests can be executed concurrently within the single function instance.
  final pulumi.Input<int>? instanceConcurrency;
  /// The instance type of the function.
  final pulumi.Input<String>? instanceType;
  /// The configuration for layers.
  final pulumi.Input<List<String>>? layers;
  /// Amount of memory in MB your function can use at runtime. Defaults to `128`. Limits to [128, 32768].
  final pulumi.Input<int>? memorySize;
  /// The Function Compute function name. It is the only in one service and is conflict with "name_prefix".
  final pulumi.Input<String>? name;
  /// Setting a prefix to get a only function name. It is conflict with "name".
  final pulumi.Input<String>? namePrefix;
  /// The OSS bucket location containing the function's deployment package. Conflicts with `filename`. This bucket must reside in the same Alibaba Cloud region where you are creating the function.
  final pulumi.Input<String>? ossBucket;
  /// The OSS key of an object containing the function's deployment package. Conflicts with `filename`.
  final pulumi.Input<String>? ossKey;
  /// See [Runtimes][https://www.alibabacloud.com/help/zh/function-compute/latest/manage-functions#multiTask3514] for valid values.
  final pulumi.Input<String> runtime;
  /// The Function Compute service name.
  final pulumi.Input<String> service;
  /// The amount of time your function has to run in seconds.
  final pulumi.Input<int>? timeout;

  /// Creates a new [FunctionArgs].
  /// [caPort] The port that the function listen to, only valid for [custom runtime](https://www.alibabacloud.com/help/doc-detail/132044.htm) and [custom container runtime](https://www.alibabacloud.com/help/doc-detail/179368.htm).
  /// [codeChecksum] The checksum (crc64) of the function code.Used to trigger updates.The value can be generated by data source alicloud_file_crc64_checksum.
  /// [customContainerConfig] The configuration for custom container runtime.See `custom_container_config` below.
  /// [description] The Function Compute function description.
  /// [environmentVariables] A map that defines environment variables for the function.
  /// [filename] The path to the function's deployment package within the local filesystem. It is conflict with the `oss_`-prefixed options.
  /// [handler] The function [entry point](https://www.alibabacloud.com/help/doc-detail/157704.htm) in your code.
  /// [initializationTimeout] The maximum length of time, in seconds, that the function's initialization should be run for.
  /// [initializer] The entry point of the function's [initialization](https://www.alibabacloud.com/help/doc-detail/157704.htm).
  /// [instanceConcurrency] The maximum number of requests can be executed concurrently within the single function instance.
  /// [instanceType] The instance type of the function.
  /// [layers] The configuration for layers.
  /// [memorySize] Amount of memory in MB your function can use at runtime. Defaults to `128`. Limits to [128, 32768].
  /// [name] The Function Compute function name. It is the only in one service and is conflict with "name_prefix".
  /// [namePrefix] Setting a prefix to get a only function name. It is conflict with "name".
  /// [ossBucket] The OSS bucket location containing the function's deployment package. Conflicts with `filename`. This bucket must reside in the same Alibaba Cloud region where you are creating the function.
  /// [ossKey] The OSS key of an object containing the function's deployment package. Conflicts with `filename`.
  /// [runtime] See [Runtimes][https://www.alibabacloud.com/help/zh/function-compute/latest/manage-functions#multiTask3514] for valid values.
  /// [service] The Function Compute service name.
  /// [timeout] The amount of time your function has to run in seconds.
  FunctionArgs({
    this.caPort,
    this.codeChecksum,
    this.customContainerConfig,
    this.description,
    this.environmentVariables,
    this.filename,
    required this.handler,
    this.initializationTimeout,
    this.initializer,
    this.instanceConcurrency,
    this.instanceType,
    this.layers,
    this.memorySize,
    this.name,
    this.namePrefix,
    this.ossBucket,
    this.ossKey,
    required this.runtime,
    required this.service,
    this.timeout,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'caPort': ?caPort,
      'codeChecksum': ?codeChecksum,
      'customContainerConfig': ?pulumi.Input.mapOptionalInputValue<FunctionCustomContainerConfig, Map<String, dynamic>>(customContainerConfig, (value) => value.toMap()),
      'description': ?description,
      'environmentVariables': ?environmentVariables,
      'filename': ?filename,
      'handler': handler,
      'initializationTimeout': ?initializationTimeout,
      'initializer': ?initializer,
      'instanceConcurrency': ?instanceConcurrency,
      'instanceType': ?instanceType,
      'layers': ?layers,
      'memorySize': ?memorySize,
      'name': ?name,
      'namePrefix': ?namePrefix,
      'ossBucket': ?ossBucket,
      'ossKey': ?ossKey,
      'runtime': runtime,
      'service': service,
      'timeout': ?timeout,
    };
  }

  factory FunctionArgs.fromMap(Map<String, dynamic> map) {
    return FunctionArgs(
      caPort: map['caPort'] == null ? null : (map['caPort'] as int).input(),
      codeChecksum: map['codeChecksum'] == null ? null : (map['codeChecksum'] as String).input(),
      customContainerConfig: map['customContainerConfig'] == null ? null : (FunctionCustomContainerConfig.fromMap((map['customContainerConfig'] as Map).cast<String, dynamic>())).input(),
      description: map['description'] == null ? null : (map['description'] as String).input(),
      environmentVariables: map['environmentVariables'] == null ? null : ((map['environmentVariables'] as Map).cast<String, String>()).input(),
      filename: map['filename'] == null ? null : (map['filename'] as String).input(),
      handler: (map['handler'] as String).input(),
      initializationTimeout: map['initializationTimeout'] == null ? null : (map['initializationTimeout'] as int).input(),
      initializer: map['initializer'] == null ? null : (map['initializer'] as String).input(),
      instanceConcurrency: map['instanceConcurrency'] == null ? null : (map['instanceConcurrency'] as int).input(),
      instanceType: map['instanceType'] == null ? null : (map['instanceType'] as String).input(),
      layers: map['layers'] == null ? null : ((map['layers'] as List).cast<String>()).input(),
      memorySize: map['memorySize'] == null ? null : (map['memorySize'] as int).input(),
      name: map['name'] == null ? null : (map['name'] as String).input(),
      namePrefix: map['namePrefix'] == null ? null : (map['namePrefix'] as String).input(),
      ossBucket: map['ossBucket'] == null ? null : (map['ossBucket'] as String).input(),
      ossKey: map['ossKey'] == null ? null : (map['ossKey'] as String).input(),
      runtime: (map['runtime'] as String).input(),
      service: (map['service'] as String).input(),
      timeout: map['timeout'] == null ? null : (map['timeout'] as int).input(),
    );
  }
}

