library module_autoscalingplans_scaling_plan_scaling_instruction_target_tracking_configuration_predefined_scaling_metric_specification;

export 'scaling_plan_scaling_instruction_target_tracking_configuration_predefined_scaling_metric_specification/scaling_plan_scaling_instruction_target_tracking_configuration_predefined_scaling_metric_specification.dart';
