library module_securitycenter_management_folder_security_health_analytics_custom_module_custom_config_predicate;

export 'management_folder_security_health_analytics_custom_module_custom_config_predicate.dart';
