library module_lakeformation_get_data_lake_settings_create_table_default_permission;

export 'get_data_lake_settings_create_table_default_permission/get_data_lake_settings_create_table_default_permission.dart';
