library module_licensemanager_get_received_license_consumption_configuration_borrow_configuration;

export 'get_received_license_consumption_configuration_borrow_configuration/get_received_license_consumption_configuration_borrow_configuration.dart';
