library module_verifiedpermissions_identity_source_configuration_open_id_connect_configuration_token_selection_access_token_only;

export 'identity_source_configuration_open_id_connect_configuration_token_selection_access_token_only.dart';
