library module_sesv2_configuration_set_event_destination_event_destination_kinesis_firehose_destination;

export 'configuration_set_event_destination_event_destination_kinesis_firehose_destination/configuration_set_event_destination_event_destination_kinesis_firehose_destination.dart';
