library module_sesv2_configuration_set_event_destination;

export 'configuration_set_event_destination/configuration_set_event_destination.dart';
export 'configuration_set_event_destination/configuration_set_event_destination_args.dart';
