library module_sesv2_configuration_set_event_destination_event_destination_sns_destination;

export 'configuration_set_event_destination_event_destination_sns_destination/configuration_set_event_destination_event_destination_sns_destination.dart';
