library module_sesv2_configuration_set_event_destination_event_destination_event_bridge_destination;

export 'configuration_set_event_destination_event_destination_event_bridge_destination/configuration_set_event_destination_event_destination_event_bridge_destination.dart';
