import 'package:pulumi/pulumi.dart' as pulumi;
import 'cache_node_property_response.dart';
import 'enterprise_mcc_cache_nodes_operation_args.dart';
import 'system_data_response.dart';

/// Represents the high level Nodes needed to provision cache node resources
///
/// Uses Azure REST API version 2023-05-01-preview. In version 2.x of the Azure Native provider, it used API version 2023-05-01-preview.
///
/// Other available API versions: 2024-11-30-preview. These can be accessed by generating a local SDK package using the CLI command `pulumi package add azure-native connectedcache [ApiVersion]`. See the [version guide](../../../version-guide/#accessing-any-api-version-via-local-packages) for details.
///
/// {{% examples %}}
/// ## Example Usage
/// {{% example %}}
/// ### Creates an enterpriseMccCacheNode resource - generated by [MaximumSet] rule
/// ```csharp
/// using System.Collections.Generic;
/// using System.Linq;
/// using Pulumi;
/// using AzureNative = Pulumi.AzureNative;
///
/// return await Deployment.RunAsync(() =>
/// {
///     var enterpriseMccCacheNodesOperation = new AzureNative.ConnectedCache.EnterpriseMccCacheNodesOperation("enterpriseMccCacheNodesOperation", new()
///     {
///         CacheNodeResourceName = "fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr",
///         CustomerResourceName = "nhdkvstdrrtsxxuz",
///         Location = "westus",
///         Properties = new AzureNative.ConnectedCache.Inputs.CacheNodePropertyArgs
///         {
///             AdditionalCacheNodeProperties = new AzureNative.ConnectedCache.Inputs.AdditionalCacheNodePropertiesArgs
///             {
///                 BgpConfiguration = new AzureNative.ConnectedCache.Inputs.BgpConfigurationArgs
///                 {
///                     AsnToIpAddressMapping = "fjbggfvumrn",
///                 },
///                 CacheNodePropertiesDetailsIssuesList = new[]
///                 {
///                     "ennbzfpuszgalzpawmwicaofqcwcj",
///                 },
///                 DriveConfiguration = new[]
///                 {
///                     new AzureNative.ConnectedCache.Inputs.CacheNodeDriveConfigurationArgs
///                     {
///                         CacheNumber = 11,
///                         NginxMapping = "cirlpkpuxg",
///                         PhysicalPath = "pcbkezoofhamkycot",
///                         SizeInGb = 14,
///                     },
///                 },
///                 OptionalProperty1 = "ph",
///                 OptionalProperty2 = "soqqgpgcbhb",
///                 OptionalProperty3 = "fpnycrbagptsujiotnjfuhlm",
///                 OptionalProperty4 = "gesqugrxvhxlxxyvatgrautxwlmxsf",
///                 OptionalProperty5 = "zknjgzpaqtvdqjydd",
///                 ProxyUrl = "ihkzxlzvpcywtzrogupqozkdud",
///                 ProxyUrlConfiguration = new AzureNative.ConnectedCache.Inputs.ProxyUrlConfigurationArgs
///                 {
///                     ProxyUrl = "hplstyg",
///                 },
///             },
///             CacheNode = new AzureNative.ConnectedCache.Inputs.CacheNodeEntityArgs
///             {
///                 CacheNodeId = "fmrjefyddfn",
///                 CacheNodeName = "qppvqxliajjfoalzjbgmxggr",
///                 CidrCsv = new[]
///                 {
///                     "nlqlvrthafvvljuupcbcw",
///                 },
///                 CidrSelectionType = 11,
///                 CustomerAsn = 25,
///                 CustomerIndex = "vafvezmelfgmjsrccjukrhppljvipg",
///                 CustomerName = "zsklcocjfjhkcpmzyefzkwamdzc",
///                 FullyQualifiedResourceId = "yeinlleavzbehelhsucb",
///                 IpAddress = "gbfkdhloyphnpnhemwrcrxlk",
///                 IsEnabled = true,
///                 IsEnterpriseManaged = true,
///                 MaxAllowableEgressInMbps = 27,
///                 ShouldMigrate = true,
///             },
///             StatusCode = "1",
///             StatusDetails = "lgljxmyyoakw",
///             StatusText = "Success",
///         },
///         ResourceGroupName = "rgConnectedCache",
///         Tags =
///         {
///             { "key259", "qbkixjuyjkoj" },
///         },
///     });
///
/// });
///
///
/// ```
///
/// ```go
/// package main
///
/// import (
/// 	connectedcache "github.com/pulumi/pulumi-azure-native-sdk/connectedcache/v3"
/// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
/// )
///
/// func main() {
/// 	pulumi.Run(func(ctx *pulumi.Context) error {
/// 		_, err := connectedcache.NewEnterpriseMccCacheNodesOperation(ctx, "enterpriseMccCacheNodesOperation", &connectedcache.EnterpriseMccCacheNodesOperationArgs{
/// 			CacheNodeResourceName: pulumi.String("fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr"),
/// 			CustomerResourceName:  pulumi.String("nhdkvstdrrtsxxuz"),
/// 			Location:              pulumi.String("westus"),
/// 			Properties: &connectedcache.CacheNodePropertyArgs{
/// 				AdditionalCacheNodeProperties: &connectedcache.AdditionalCacheNodePropertiesArgs{
/// 					BgpConfiguration: &connectedcache.BgpConfigurationArgs{
/// 						AsnToIpAddressMapping: pulumi.String("fjbggfvumrn"),
/// 					},
/// 					CacheNodePropertiesDetailsIssuesList: pulumi.StringArray{
/// 						pulumi.String("ennbzfpuszgalzpawmwicaofqcwcj"),
/// 					},
/// 					DriveConfiguration: connectedcache.CacheNodeDriveConfigurationArray{
/// 						&connectedcache.CacheNodeDriveConfigurationArgs{
/// 							CacheNumber:  pulumi.Int(11),
/// 							NginxMapping: pulumi.String("cirlpkpuxg"),
/// 							PhysicalPath: pulumi.String("pcbkezoofhamkycot"),
/// 							SizeInGb:     pulumi.Int(14),
/// 						},
/// 					},
/// 					OptionalProperty1: pulumi.String("ph"),
/// 					OptionalProperty2: pulumi.String("soqqgpgcbhb"),
/// 					OptionalProperty3: pulumi.String("fpnycrbagptsujiotnjfuhlm"),
/// 					OptionalProperty4: pulumi.String("gesqugrxvhxlxxyvatgrautxwlmxsf"),
/// 					OptionalProperty5: pulumi.String("zknjgzpaqtvdqjydd"),
/// 					ProxyUrl:          pulumi.String("ihkzxlzvpcywtzrogupqozkdud"),
/// 					ProxyUrlConfiguration: &connectedcache.ProxyUrlConfigurationArgs{
/// 						ProxyUrl: pulumi.String("hplstyg"),
/// 					},
/// 				},
/// 				CacheNode: &connectedcache.CacheNodeEntityArgs{
/// 					CacheNodeId:   pulumi.String("fmrjefyddfn"),
/// 					CacheNodeName: pulumi.String("qppvqxliajjfoalzjbgmxggr"),
/// 					CidrCsv: pulumi.StringArray{
/// 						pulumi.String("nlqlvrthafvvljuupcbcw"),
/// 					},
/// 					CidrSelectionType:        pulumi.Int(11),
/// 					CustomerAsn:              pulumi.Int(25),
/// 					CustomerIndex:            pulumi.String("vafvezmelfgmjsrccjukrhppljvipg"),
/// 					CustomerName:             pulumi.String("zsklcocjfjhkcpmzyefzkwamdzc"),
/// 					FullyQualifiedResourceId: pulumi.String("yeinlleavzbehelhsucb"),
/// 					IpAddress:                pulumi.String("gbfkdhloyphnpnhemwrcrxlk"),
/// 					IsEnabled:                pulumi.Bool(true),
/// 					IsEnterpriseManaged:      pulumi.Bool(true),
/// 					MaxAllowableEgressInMbps: pulumi.Int(27),
/// 					ShouldMigrate:            pulumi.Bool(true),
/// 				},
/// 				StatusCode:    pulumi.String("1"),
/// 				StatusDetails: pulumi.String("lgljxmyyoakw"),
/// 				StatusText:    pulumi.String("Success"),
/// 			},
/// 			ResourceGroupName: pulumi.String("rgConnectedCache"),
/// 			Tags: pulumi.StringMap{
/// 				"key259": pulumi.String("qbkixjuyjkoj"),
/// 			},
/// 		})
/// 		if err != nil {
/// 			return err
/// 		}
/// 		return nil
/// 	})
/// }
///
/// ```
///
/// ```java
/// package generated_program;
///
/// import com.pulumi.Context;
/// import com.pulumi.Pulumi;
/// import com.pulumi.core.Output;
/// import com.pulumi.azurenative.connectedcache.EnterpriseMccCacheNodesOperation;
/// import com.pulumi.azurenative.connectedcache.EnterpriseMccCacheNodesOperationArgs;
/// import com.pulumi.azurenative.connectedcache.inputs.CacheNodePropertyArgs;
/// import com.pulumi.azurenative.connectedcache.inputs.AdditionalCacheNodePropertiesArgs;
/// import com.pulumi.azurenative.connectedcache.inputs.BgpConfigurationArgs;
/// import com.pulumi.azurenative.connectedcache.inputs.ProxyUrlConfigurationArgs;
/// import com.pulumi.azurenative.connectedcache.inputs.CacheNodeEntityArgs;
/// import java.util.List;
/// import java.util.ArrayList;
/// import java.util.Map;
/// import java.io.File;
/// import java.nio.file.Files;
/// import java.nio.file.Paths;
///
/// public class App {
///     public static void main(String[] args) {
///         Pulumi.run(App::stack);
///     }
///
///     public static void stack(Context ctx) {
///         var enterpriseMccCacheNodesOperation = new EnterpriseMccCacheNodesOperation("enterpriseMccCacheNodesOperation", EnterpriseMccCacheNodesOperationArgs.builder()
///             .cacheNodeResourceName("fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr")
///             .customerResourceName("nhdkvstdrrtsxxuz")
///             .location("westus")
///             .properties(CacheNodePropertyArgs.builder()
///                 .additionalCacheNodeProperties(AdditionalCacheNodePropertiesArgs.builder()
///                     .bgpConfiguration(BgpConfigurationArgs.builder()
///                         .asnToIpAddressMapping("fjbggfvumrn")
///                         .build())
///                     .cacheNodePropertiesDetailsIssuesList("ennbzfpuszgalzpawmwicaofqcwcj")
///                     .driveConfiguration(CacheNodeDriveConfigurationArgs.builder()
///                         .cacheNumber(11)
///                         .nginxMapping("cirlpkpuxg")
///                         .physicalPath("pcbkezoofhamkycot")
///                         .sizeInGb(14)
///                         .build())
///                     .optionalProperty1("ph")
///                     .optionalProperty2("soqqgpgcbhb")
///                     .optionalProperty3("fpnycrbagptsujiotnjfuhlm")
///                     .optionalProperty4("gesqugrxvhxlxxyvatgrautxwlmxsf")
///                     .optionalProperty5("zknjgzpaqtvdqjydd")
///                     .proxyUrl("ihkzxlzvpcywtzrogupqozkdud")
///                     .proxyUrlConfiguration(ProxyUrlConfigurationArgs.builder()
///                         .proxyUrl("hplstyg")
///                         .build())
///                     .build())
///                 .cacheNode(CacheNodeEntityArgs.builder()
///                     .cacheNodeId("fmrjefyddfn")
///                     .cacheNodeName("qppvqxliajjfoalzjbgmxggr")
///                     .cidrCsv("nlqlvrthafvvljuupcbcw")
///                     .cidrSelectionType(11)
///                     .customerAsn(25)
///                     .customerIndex("vafvezmelfgmjsrccjukrhppljvipg")
///                     .customerName("zsklcocjfjhkcpmzyefzkwamdzc")
///                     .fullyQualifiedResourceId("yeinlleavzbehelhsucb")
///                     .ipAddress("gbfkdhloyphnpnhemwrcrxlk")
///                     .isEnabled(true)
///                     .isEnterpriseManaged(true)
///                     .maxAllowableEgressInMbps(27)
///                     .shouldMigrate(true)
///                     .build())
///                 .statusCode("1")
///                 .statusDetails("lgljxmyyoakw")
///                 .statusText("Success")
///                 .build())
///             .resourceGroupName("rgConnectedCache")
///             .tags(Map.of("key259", "qbkixjuyjkoj"))
///             .build());
///
///     }
/// }
///
/// ```
///
/// ```typescript
/// import * as pulumi from "@pulumi/pulumi";
/// import * as azure_native from "@pulumi/azure-native";
///
/// const enterpriseMccCacheNodesOperation = new azure_native.connectedcache.EnterpriseMccCacheNodesOperation("enterpriseMccCacheNodesOperation", {
///     cacheNodeResourceName: "fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr",
///     customerResourceName: "nhdkvstdrrtsxxuz",
///     location: "westus",
///     properties: {
///         additionalCacheNodeProperties: {
///             bgpConfiguration: {
///                 asnToIpAddressMapping: "fjbggfvumrn",
///             },
///             cacheNodePropertiesDetailsIssuesList: ["ennbzfpuszgalzpawmwicaofqcwcj"],
///             driveConfiguration: [{
///                 cacheNumber: 11,
///                 nginxMapping: "cirlpkpuxg",
///                 physicalPath: "pcbkezoofhamkycot",
///                 sizeInGb: 14,
///             }],
///             optionalProperty1: "ph",
///             optionalProperty2: "soqqgpgcbhb",
///             optionalProperty3: "fpnycrbagptsujiotnjfuhlm",
///             optionalProperty4: "gesqugrxvhxlxxyvatgrautxwlmxsf",
///             optionalProperty5: "zknjgzpaqtvdqjydd",
///             proxyUrl: "ihkzxlzvpcywtzrogupqozkdud",
///             proxyUrlConfiguration: {
///                 proxyUrl: "hplstyg",
///             },
///         },
///         cacheNode: {
///             cacheNodeId: "fmrjefyddfn",
///             cacheNodeName: "qppvqxliajjfoalzjbgmxggr",
///             cidrCsv: ["nlqlvrthafvvljuupcbcw"],
///             cidrSelectionType: 11,
///             customerAsn: 25,
///             customerIndex: "vafvezmelfgmjsrccjukrhppljvipg",
///             customerName: "zsklcocjfjhkcpmzyefzkwamdzc",
///             fullyQualifiedResourceId: "yeinlleavzbehelhsucb",
///             ipAddress: "gbfkdhloyphnpnhemwrcrxlk",
///             isEnabled: true,
///             isEnterpriseManaged: true,
///             maxAllowableEgressInMbps: 27,
///             shouldMigrate: true,
///         },
///         statusCode: "1",
///         statusDetails: "lgljxmyyoakw",
///         statusText: "Success",
///     },
///     resourceGroupName: "rgConnectedCache",
///     tags: {
///         key259: "qbkixjuyjkoj",
///     },
/// });
///
/// ```
///
/// ```python
/// import pulumi
/// import pulumi_azure_native as azure_native
///
/// enterprise_mcc_cache_nodes_operation = azure_native.connectedcache.EnterpriseMccCacheNodesOperation("enterpriseMccCacheNodesOperation",
///     cache_node_resource_name="fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr",
///     customer_resource_name="nhdkvstdrrtsxxuz",
///     location="westus",
///     properties={
///         "additional_cache_node_properties": {
///             "bgp_configuration": {
///                 "asn_to_ip_address_mapping": "fjbggfvumrn",
///             },
///             "cache_node_properties_details_issues_list": ["ennbzfpuszgalzpawmwicaofqcwcj"],
///             "drive_configuration": [{
///                 "cache_number": 11,
///                 "nginx_mapping": "cirlpkpuxg",
///                 "physical_path": "pcbkezoofhamkycot",
///                 "size_in_gb": 14,
///             }],
///             "optional_property1": "ph",
///             "optional_property2": "soqqgpgcbhb",
///             "optional_property3": "fpnycrbagptsujiotnjfuhlm",
///             "optional_property4": "gesqugrxvhxlxxyvatgrautxwlmxsf",
///             "optional_property5": "zknjgzpaqtvdqjydd",
///             "proxy_url": "ihkzxlzvpcywtzrogupqozkdud",
///             "proxy_url_configuration": {
///                 "proxy_url": "hplstyg",
///             },
///         },
///         "cache_node": {
///             "cache_node_id": "fmrjefyddfn",
///             "cache_node_name": "qppvqxliajjfoalzjbgmxggr",
///             "cidr_csv": ["nlqlvrthafvvljuupcbcw"],
///             "cidr_selection_type": 11,
///             "customer_asn": 25,
///             "customer_index": "vafvezmelfgmjsrccjukrhppljvipg",
///             "customer_name": "zsklcocjfjhkcpmzyefzkwamdzc",
///             "fully_qualified_resource_id": "yeinlleavzbehelhsucb",
///             "ip_address": "gbfkdhloyphnpnhemwrcrxlk",
///             "is_enabled": True,
///             "is_enterprise_managed": True,
///             "max_allowable_egress_in_mbps": 27,
///             "should_migrate": True,
///         },
///         "status_code": "1",
///         "status_details": "lgljxmyyoakw",
///         "status_text": "Success",
///     },
///     resource_group_name="rgConnectedCache",
///     tags={
///         "key259": "qbkixjuyjkoj",
///     })
///
/// ```
///
/// ```yaml
/// resources:
///   enterpriseMccCacheNodesOperation:
///     type: azure-native:connectedcache:EnterpriseMccCacheNodesOperation
///     properties:
///       cacheNodeResourceName: fgduqdovidpemlnmhelomffuafdrbgaasqznvrdkbvspfzsnrhncdtqquhijhdpwyzwleukqldpceyxqhqlftqrr
///       customerResourceName: nhdkvstdrrtsxxuz
///       location: westus
///       properties:
///         additionalCacheNodeProperties:
///           bgpConfiguration:
///             asnToIpAddressMapping: fjbggfvumrn
///           cacheNodePropertiesDetailsIssuesList:
///             - ennbzfpuszgalzpawmwicaofqcwcj
///           driveConfiguration:
///             - cacheNumber: 11
///               nginxMapping: cirlpkpuxg
///               physicalPath: pcbkezoofhamkycot
///               sizeInGb: 14
///           optionalProperty1: ph
///           optionalProperty2: soqqgpgcbhb
///           optionalProperty3: fpnycrbagptsujiotnjfuhlm
///           optionalProperty4: gesqugrxvhxlxxyvatgrautxwlmxsf
///           optionalProperty5: zknjgzpaqtvdqjydd
///           proxyUrl: ihkzxlzvpcywtzrogupqozkdud
///           proxyUrlConfiguration:
///             proxyUrl: hplstyg
///         cacheNode:
///           cacheNodeId: fmrjefyddfn
///           cacheNodeName: qppvqxliajjfoalzjbgmxggr
///           cidrCsv:
///             - nlqlvrthafvvljuupcbcw
///           cidrSelectionType: 11
///           customerAsn: 25
///           customerIndex: vafvezmelfgmjsrccjukrhppljvipg
///           customerName: zsklcocjfjhkcpmzyefzkwamdzc
///           fullyQualifiedResourceId: yeinlleavzbehelhsucb
///           ipAddress: gbfkdhloyphnpnhemwrcrxlk
///           isEnabled: true
///           isEnterpriseManaged: true
///           maxAllowableEgressInMbps: 27
///           shouldMigrate: true
///         statusCode: '1'
///         statusDetails: lgljxmyyoakw
///         statusText: Success
///       resourceGroupName: rgConnectedCache
///       tags:
///         key259: qbkixjuyjkoj
///
/// ```
///
/// {{% /example %}}
/// {{% /examples %}}
///
/// ## Import
///
/// An existing resource can be imported using its type token, name, and identifier, e.g.
///
/// ```sh
/// $ pulumi import azure-native:connectedcache:EnterpriseMccCacheNodesOperation MccRPTest1 /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedCache/enterpriseMccCustomers/{customerResourceName}/enterpriseMccCacheNodes/{cacheNodeResourceName}
/// ```
class EnterpriseMccCacheNodesOperation extends pulumi.CustomResource {
  /// The Azure API version of the resource.
  late final pulumi.Output<String> azureApiVersion;

  /// The geo-location where the resource lives
  late final pulumi.Output<String> location;

  /// The name of the resource
  late final pulumi.Output<String> name;

  /// The resource-specific properties for this resource.
  late final pulumi.Output<CacheNodePropertyResponse> properties;

  /// Azure Resource Manager metadata containing createdBy and modifiedBy information.
  late final pulumi.Output<SystemDataResponse> systemData;

  /// Resource tags.
  late final pulumi.Output<Map<String, String>?> tags;

  /// The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
  late final pulumi.Output<String> type;

  /// Creates a new [EnterpriseMccCacheNodesOperation].
  /// [name] The Pulumi resource name.
  /// [args] Arguments used to configure this [EnterpriseMccCacheNodesOperation]. {@macro pulumi_connectedcache_enterprise_mcc_cache_nodes_operation_args_doc}
  /// [options] Resource options controlling this resource's behavior.
  EnterpriseMccCacheNodesOperation(
    String name, {
    EnterpriseMccCacheNodesOperationArgs? args,
    pulumi.CustomResourceOptions? options,
  }) : super(
         'azure-native:connectedcache:EnterpriseMccCacheNodesOperation',
         name,
         pulumi.Input.mapToInputs(args?.toMap() ?? const {}),
         options ?? pulumi.CustomResourceOptions(),
       ) {
    azureApiVersion = registerOutput<String>('azureApiVersion');
    location = registerOutput<String>('location');
    this.name = registerOutput<String>('name');
    properties = registerOutput<CacheNodePropertyResponse>(
      'properties',
      decoder: (raw) {
        final guardedValue = raw;
        if (guardedValue == null) return null;
        return CacheNodePropertyResponse.fromMap(
          (guardedValue as Map).cast<String, dynamic>(),
        );
      },
    );
    systemData = registerOutput<SystemDataResponse>(
      'systemData',
      decoder: (raw) {
        final guardedValue = raw;
        if (guardedValue == null) return null;
        return SystemDataResponse.fromMap(
          (guardedValue as Map).cast<String, dynamic>(),
        );
      },
    );
    tags = registerOutput<Map<String, String>?>('tags');
    type = registerOutput<String>('type');
  }
}
