// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_dataplex_aspect_type_iam_policy_aspect_type_iam_policy_args_doc}
/// The set of arguments for AspectTypeIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_dataplex_aspect_type_iam_policy_aspect_type_iam_policy_args_doc}
class AspectTypeIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> aspectTypeId;

  /// The location where aspect type will be created in.
  /// Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? location;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Creates a new [AspectTypeIamPolicyArgs].
  /// [aspectTypeId] Used to find the parent resource to bind the IAM policy to
  /// [location] The location where aspect type will be created in.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  AspectTypeIamPolicyArgs({
    required String aspectTypeId,
    String? location,
    required String policyData,
    String? project,
  })  : aspectTypeId = pulumi.Input.asInput<String>(aspectTypeId),
        location = pulumi.Input.asOptionalInput<String>(location),
        policyData = pulumi.Input.asInput<String>(policyData),
        project = pulumi.Input.asOptionalInput<String>(project);

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['aspectTypeId'] = aspectTypeId;
    final locationValue = location;
    if (locationValue != null) {
      map['location'] = locationValue;
    }
    map['policyData'] = policyData;
    final projectValue = project;
    if (projectValue != null) {
      map['project'] = projectValue;
    }
    return map;
  }

  factory AspectTypeIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return AspectTypeIamPolicyArgs(
      aspectTypeId: map['aspectTypeId'] as String,
      location: map['location'] == null ? null : map['location'] as String,
      policyData: map['policyData'] as String,
      project: map['project'] == null ? null : map['project'] as String,
    );
  }
}
