library module_cognito_log_delivery_configuration_log_configuration_firehose_configuration;

export 'log_delivery_configuration_log_configuration_firehose_configuration/log_delivery_configuration_log_configuration_firehose_configuration.dart';
