library module_cognito_risk_configuration_account_takeover_risk_configuration_actions;

export 'risk_configuration_account_takeover_risk_configuration_actions/risk_configuration_account_takeover_risk_configuration_actions.dart';
