library module_cognito_risk_configuration_compromised_credentials_risk_configuration_actions;

export 'risk_configuration_compromised_credentials_risk_configuration_actions/risk_configuration_compromised_credentials_risk_configuration_actions.dart';
