library module_cognito_risk_configuration_account_takeover_risk_configuration_notify_configuration_block_email;

export 'risk_configuration_account_takeover_risk_configuration_notify_configuration_block_email/risk_configuration_account_takeover_risk_configuration_notify_configuration_block_email.dart';
