library module_cognito_risk_configuration_account_takeover_risk_configuration_actions_low_action;

export 'risk_configuration_account_takeover_risk_configuration_actions_low_action/risk_configuration_account_takeover_risk_configuration_actions_low_action.dart';
