library module_cognito_risk_configuration_compromised_credentials_risk_configuration;

export 'risk_configuration_compromised_credentials_risk_configuration/risk_configuration_compromised_credentials_risk_configuration.dart';
