library module_cognito_user_pool_account_recovery_setting_recovery_mechanism;

export 'user_pool_account_recovery_setting_recovery_mechanism/user_pool_account_recovery_setting_recovery_mechanism.dart';
