import 'package:pulumi/pulumi.dart';
import 'company_args.dart';
import 'company_derived_info_response.dart';

/// Creates a new company entity.
class Company extends CustomResource {
  /// Optional. The URI to employer's career site or careers page on the employer's web site, for example, "https://careers.google.com".
  late final Output<String> careerSiteUri;

  /// Derived details about the company.
  late final Output<CompanyDerivedInfoResponse> derivedInfo;

  /// The display name of the company, for example, "Google LLC".
  late final Output<String> displayName;

  /// Optional. Equal Employment Opportunity legal disclaimer text to be associated with all jobs, and typically to be displayed in all roles. The maximum number of allowed characters is 500.
  late final Output<String> eeoText;

  /// Client side company identifier, used to uniquely identify the company. The maximum number of allowed characters is 255.
  late final Output<String> externalId;

  /// Optional. The street address of the company's main headquarters, which may be different from the job location. The service attempts to geolocate the provided address, and populates a more specific location wherever possible in DerivedInfo.headquarters_location.
  late final Output<String> headquartersAddress;

  /// Optional. Set to true if it is the hiring agency that post jobs for other employers. Defaults to false if not provided.
  late final Output<bool> hiringAgency;

  /// Optional. A URI that hosts the employer's company logo.
  late final Output<String> imageUri;

  /// Optional. This field is deprecated. Please set the searchability of the custom attribute in the Job.custom_attributes going forward. A list of keys of filterable Job.custom_attributes, whose corresponding `string_values` are used in keyword search. Jobs with `string_values` under these specified field keys are returned if any of the values matches the search keyword. Custom field values with parenthesis, brackets and special symbols won't be properly searchable, and those keyword queries need to be surrounded by quotes.
  late final Output<List<String>> keywordSearchableJobCustomAttributes;

  /// Required during company update. The resource name for a company. This is generated by the service when a company is created. The format is "projects/{project_id}/companies/{company_id}", for example, "projects/api-test-project/companies/foo".
  late final Output<String> name;
  late final Output<String> project;

  /// Optional. The employer's company size.
  late final Output<String> size;

  /// Indicates whether a company is flagged to be suspended from public availability by the service when job content appears suspicious, abusive, or spammy.
  late final Output<bool> suspended;

  /// Optional. The URI representing the company's primary web site or home page, for example, "https://www.google.com". The maximum number of allowed characters is 255.
  late final Output<String> websiteUri;

  Company(
    String name, {
    CompanyArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:jobs/v3:Company',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.careerSiteUri = Output.createUnknown<String>();
    this.derivedInfo = Output.createUnknown<CompanyDerivedInfoResponse>();
    this.displayName = Output.createUnknown<String>();
    this.eeoText = Output.createUnknown<String>();
    this.externalId = Output.createUnknown<String>();
    this.headquartersAddress = Output.createUnknown<String>();
    this.hiringAgency = Output.createUnknown<bool>();
    this.imageUri = Output.createUnknown<String>();
    this.keywordSearchableJobCustomAttributes =
        Output.createUnknown<List<String>>();
    this.name = Output.createUnknown<String>();
    this.project = Output.createUnknown<String>();
    this.size = Output.createUnknown<String>();
    this.suspended = Output.createUnknown<bool>();
    this.websiteUri = Output.createUnknown<String>();
  }
}
