// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering GetHostPoolRegistrationInfo resources.
class GetHostPoolRegistrationInfoState {
  /// A valid `RFC3339Time` for the expiration of the token..
  final pulumi.Input<String?>? expirationDate;
  /// The ID of the Virtual Desktop Host Pool to link the Registration Info to. Changing this forces a new Registration Info resource to be created. Only a single virtualDesktopHostPoolRegistrationInfo resource should be associated with a given hostpool. Assigning multiple resources will produce inconsistent results.
  final pulumi.Input<String?>? hostpoolId;
  /// The registration token generated by the Virtual Desktop Host Pool for registration of session hosts.
  final pulumi.Input<String?>? token;

  /// Creates a new [GetHostPoolRegistrationInfoState].
  /// [expirationDate] A valid `RFC3339Time` for the expiration of the token..
  /// [hostpoolId] The ID of the Virtual Desktop Host Pool to link the Registration Info to. Changing this forces a new Registration Info resource to be created. Only a single virtualDesktopHostPoolRegistrationInfo resource should be associated with a given hostpool. Assigning multiple resources will produce inconsistent results.
  /// [token] The registration token generated by the Virtual Desktop Host Pool for registration of session hosts.
  const GetHostPoolRegistrationInfoState({
    this.expirationDate,
    this.hostpoolId,
    this.token,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'expirationDate': ?expirationDate,
      'hostpoolId': ?hostpoolId,
      'token': ?token,
    };
  }

  factory GetHostPoolRegistrationInfoState.fromMap(Map<String, dynamic> map) {
    return GetHostPoolRegistrationInfoState(
      expirationDate: (() { final guardedValue = map['expirationDate']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      hostpoolId: (() { final guardedValue = map['hostpoolId']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      token: (() { final guardedValue = map['token']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}
