library module_wafv2_web_acl_rule_statement_rate_based_statement_scope_down_statement_ip_set_reference_statement_ip_set_forwarded_ip_config;

export 'web_acl_rule_statement_rate_based_statement_scope_down_statement_ip_set_reference_statement_ip_set_forwarded_ip_config.dart';
