library module_bigquery_table_external_catalog_table_options_storage_descriptor_serde_info;

export 'table_external_catalog_table_options_storage_descriptor_serde_info/table_external_catalog_table_options_storage_descriptor_serde_info.dart';
