library module_emrserverless_application_monitoring_configuration_s3_monitoring_configuration;

export 'application_monitoring_configuration_s3_monitoring_configuration/application_monitoring_configuration_s3_monitoring_configuration.dart';
