library module_chimesdkmediapipelines_media_insights_pipeline_configuration_element_amazon_transcribe_call_analytics_processor_configuration;

export 'media_insights_pipeline_configuration_element_amazon_transcribe_call_analytics_processor_configuration.dart';
