// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering EventSubscription resources.
class EventSubscriptionState {
  /// The Amazon Resource Name of the DocumentDB event notification subscription
  final pulumi.Input<String>? arn;
  /// The AWS customer account associated with the DocumentDB event notification subscription
  final pulumi.Input<String>? customerAwsId;
  /// A boolean flag to enable/disable the subscription. Defaults to true.
  final pulumi.Input<bool>? enabled;
  /// A list of event categories for a SourceType that you want to subscribe to. See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_Event.html or run `aws docdb describe-event-categories`.
  final pulumi.Input<List<String>>? eventCategories;
  /// The name of the DocumentDB event subscription. By default generated by this provider.
  final pulumi.Input<String>? name;
  /// The name of the DocumentDB event subscription. Conflicts with `name`.
  final pulumi.Input<String>? namePrefix;
  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;
  final pulumi.Input<String>? snsTopicArn;
  /// A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified.
  final pulumi.Input<List<String>>? sourceIds;
  /// The type of source that will be generating the events. Valid options are `db-instance`, `db-cluster`, `db-parameter-group`, `db-security-group`,` db-cluster-snapshot`. If not set, all sources will be subscribed to.
  final pulumi.Input<String>? sourceType;
  /// A map of tags to assign to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  final pulumi.Input<Map<String, String>>? tags;
  /// A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  final pulumi.Input<Map<String, String>>? tagsAll;

  /// Creates a new [EventSubscriptionState].
  /// [arn] The Amazon Resource Name of the DocumentDB event notification subscription
  /// [customerAwsId] The AWS customer account associated with the DocumentDB event notification subscription
  /// [enabled] A boolean flag to enable/disable the subscription. Defaults to true.
  /// [eventCategories] A list of event categories for a SourceType that you want to subscribe to. See https://docs.aws.amazon.com/documentdb/latest/developerguide/API_Event.html or run `aws docdb describe-event-categories`.
  /// [name] The name of the DocumentDB event subscription. By default generated by this provider.
  /// [namePrefix] The name of the DocumentDB event subscription. Conflicts with `name`.
  /// [region] Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  /// [snsTopicArn] Optional.
  /// [sourceIds] A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified.
  /// [sourceType] The type of source that will be generating the events. Valid options are `db-instance`, `db-cluster`, `db-parameter-group`, `db-security-group`,` db-cluster-snapshot`. If not set, all sources will be subscribed to.
  /// [tags] A map of tags to assign to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
  /// [tagsAll] A map of tags assigned to the resource, including those inherited from the provider `default_tags` configuration block.
  EventSubscriptionState({
    this.arn,
    this.customerAwsId,
    this.enabled,
    this.eventCategories,
    this.name,
    this.namePrefix,
    this.region,
    this.snsTopicArn,
    this.sourceIds,
    this.sourceType,
    this.tags,
    this.tagsAll,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'arn': ?arn,
      'customerAwsId': ?customerAwsId,
      'enabled': ?enabled,
      'eventCategories': ?eventCategories,
      'name': ?name,
      'namePrefix': ?namePrefix,
      'region': ?region,
      'snsTopicArn': ?snsTopicArn,
      'sourceIds': ?sourceIds,
      'sourceType': ?sourceType,
      'tags': ?tags,
      'tagsAll': ?tagsAll,
    };
  }

  factory EventSubscriptionState.fromMap(Map<String, dynamic> map) {
    return EventSubscriptionState(
      arn: map['arn'] == null ? null : (map['arn'] as String).input(),
      customerAwsId: map['customerAwsId'] == null ? null : (map['customerAwsId'] as String).input(),
      enabled: map['enabled'] == null ? null : (map['enabled'] as bool).input(),
      eventCategories: map['eventCategories'] == null ? null : ((map['eventCategories'] as List).cast<String>()).input(),
      name: map['name'] == null ? null : (map['name'] as String).input(),
      namePrefix: map['namePrefix'] == null ? null : (map['namePrefix'] as String).input(),
      region: map['region'] == null ? null : (map['region'] as String).input(),
      snsTopicArn: map['snsTopicArn'] == null ? null : (map['snsTopicArn'] as String).input(),
      sourceIds: map['sourceIds'] == null ? null : ((map['sourceIds'] as List).cast<String>()).input(),
      sourceType: map['sourceType'] == null ? null : (map['sourceType'] as String).input(),
      tags: map['tags'] == null ? null : ((map['tags'] as Map).cast<String, String>()).input(),
      tagsAll: map['tagsAll'] == null ? null : ((map['tagsAll'] as Map).cast<String, String>()).input(),
    );
  }
}

