// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

class ConnectionIkeConfig {
  /// the authentication algorithm that is used in Phase 1 negotiations. Valid values: md5, sha1, sha2
  final pulumi.Input<String>? ikeAuthAlg;
  /// the encryption algorithm that is used in Phase 1 negotiations. Valid values: aes, aes192, aes256, des, and 3des. Default value: aes.
  final pulumi.Input<String>? ikeEncAlg;
  /// the SA lifetime as a result of Phase 1 negotiations. Unit: seconds. Valid values: 0 to 86400. Default value: 86400.
  final pulumi.Input<int>? ikeLifetime;
  /// the identifier of the VPN gateway. It can contain at most 100 characters. The default value is the IP address of the VPN gateway.
  final pulumi.Input<String>? ikeLocalId;
  /// the negotiation mode of IKE. Valid values: main and aggressive. Default value: main.
  /// - main: This mode offers higher security during negotiations.
  /// - aggressive: This mode supports faster negotiations and a higher success rate.
  final pulumi.Input<String>? ikeMode;
  /// the Diffie-Hellman key exchange algorithm that is used in Phase 1 negotiations. Valid values: group1, group2, group5, and group14. Default value: group2.
  final pulumi.Input<String>? ikePfs;
  /// the identifier of the customer gateway. It can contain at most 100 characters. The default value is the IP address of the customer gateway.
  final pulumi.Input<String>? ikeRemoteId;
  /// the version of the Internet Key Exchange (IKE) protocol. Valid values: ikev1 and ikev2. Default value: ikev1.
  /// Compared with IKEv1, IKEv2 simplifies the security association (SA) negotiation process and provides better support for scenarios with multiple CIDR blocks.
  final pulumi.Input<String>? ikeVersion;
  /// the pre-shared key that is used for identity authentication between the VPN gateway and the on-premises data center. The key must be 1 to 100 characters in length and can contain digits, letters, and the following special characters: ~!\`@#$%^&*()_-+={}[]|;:',.&lt;&gt;/? If you do not specify a pre-shared key, the system randomly generates a 16-bit string as the pre-shared key. You can call the DescribeVpnConnection operation to query the pre-shared key that is automatically generated by the system.
  final pulumi.Input<String>? psk;

  /// Creates a new [ConnectionIkeConfig].
  /// [ikeAuthAlg] the authentication algorithm that is used in Phase 1 negotiations. Valid values: md5, sha1, sha2
  /// [ikeEncAlg] the encryption algorithm that is used in Phase 1 negotiations. Valid values: aes, aes192, aes256, des, and 3des. Default value: aes.
  /// [ikeLifetime] the SA lifetime as a result of Phase 1 negotiations. Unit: seconds. Valid values: 0 to 86400. Default value: 86400.
  /// [ikeLocalId] the identifier of the VPN gateway. It can contain at most 100 characters. The default value is the IP address of the VPN gateway.
  /// [ikeMode] the negotiation mode of IKE. Valid values: main and aggressive. Default value: main.
  /// [ikePfs] the Diffie-Hellman key exchange algorithm that is used in Phase 1 negotiations. Valid values: group1, group2, group5, and group14. Default value: group2.
  /// [ikeRemoteId] the identifier of the customer gateway. It can contain at most 100 characters. The default value is the IP address of the customer gateway.
  /// [ikeVersion] the version of the Internet Key Exchange (IKE) protocol. Valid values: ikev1 and ikev2. Default value: ikev1.
  /// [psk] the pre-shared key that is used for identity authentication between the VPN gateway and the on-premises data center. The key must be 1 to 100 characters in length and can contain digits, letters, and the following special characters: ~!\`@#$%^&*()_-+={}[]|;:',.&lt;&gt;/? If you do not specify a pre-shared key, the system randomly generates a 16-bit string as the pre-shared key. You can call the DescribeVpnConnection operation to query the pre-shared key that is automatically generated by the system.
  const ConnectionIkeConfig({
    this.ikeAuthAlg,
    this.ikeEncAlg,
    this.ikeLifetime,
    this.ikeLocalId,
    this.ikeMode,
    this.ikePfs,
    this.ikeRemoteId,
    this.ikeVersion,
    this.psk,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'ikeAuthAlg': ?ikeAuthAlg,
      'ikeEncAlg': ?ikeEncAlg,
      'ikeLifetime': ?ikeLifetime,
      'ikeLocalId': ?ikeLocalId,
      'ikeMode': ?ikeMode,
      'ikePfs': ?ikePfs,
      'ikeRemoteId': ?ikeRemoteId,
      'ikeVersion': ?ikeVersion,
      'psk': ?psk,
    };
  }

  factory ConnectionIkeConfig.fromMap(Map<String, dynamic> map) {
    return ConnectionIkeConfig(
      ikeAuthAlg: (() { final guardedValue = map['ikeAuthAlg']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikeEncAlg: (() { final guardedValue = map['ikeEncAlg']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikeLifetime: (() { final guardedValue = map['ikeLifetime']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as int); })(),
      ikeLocalId: (() { final guardedValue = map['ikeLocalId']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikeMode: (() { final guardedValue = map['ikeMode']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikePfs: (() { final guardedValue = map['ikePfs']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikeRemoteId: (() { final guardedValue = map['ikeRemoteId']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      ikeVersion: (() { final guardedValue = map['ikeVersion']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
      psk: (() { final guardedValue = map['psk']; if (guardedValue == null) return null; return pulumi.Input.fromValue(guardedValue as String); })(),
    );
  }
}

