// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// The set of arguments for EventApiDestination.
class EventApiDestinationArgs {
  /// ARN of the EventBridge Connection to use for the API Destination.
  final pulumi.Input<String> connectionArn;

  /// The description of the new API Destination. Maximum of 512 characters.
  final pulumi.Input<String>? description;

  /// Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc.
  final pulumi.Input<String> httpMethod;

  /// URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "*" as path parameters wildcards to be set from the Target HttpParameters.
  final pulumi.Input<String> invocationEndpoint;

  /// Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300).
  final pulumi.Input<int>? invocationRateLimitPerSecond;

  /// The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.
  final pulumi.Input<String>? name;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  final pulumi.Input<String>? region;

  EventApiDestinationArgs({
    required this.connectionArn,
    this.description,
    required this.httpMethod,
    required this.invocationEndpoint,
    this.invocationRateLimitPerSecond,
    this.name,
    this.region,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['connectionArn'] = connectionArn;
    final descriptionValue = description;
    if (descriptionValue != null) {
      map['description'] = descriptionValue;
    }
    map['httpMethod'] = httpMethod;
    map['invocationEndpoint'] = invocationEndpoint;
    final invocationRateLimitPerSecondValue = invocationRateLimitPerSecond;
    if (invocationRateLimitPerSecondValue != null) {
      map['invocationRateLimitPerSecond'] = invocationRateLimitPerSecondValue;
    }
    final nameValue = name;
    if (nameValue != null) {
      map['name'] = nameValue;
    }
    final regionValue = region;
    if (regionValue != null) {
      map['region'] = regionValue;
    }
    return map;
  }

  factory EventApiDestinationArgs.fromMap(Map<String, dynamic> map) {
    return EventApiDestinationArgs(
      connectionArn: pulumi.Input.asInput<String>(map['connectionArn']),
      description: pulumi.Input.asOptionalInput<String>(map['description']),
      httpMethod: pulumi.Input.asInput<String>(map['httpMethod']),
      invocationEndpoint:
          pulumi.Input.asInput<String>(map['invocationEndpoint']),
      invocationRateLimitPerSecond: pulumi.Input.asOptionalInput<int>(
          map['invocationRateLimitPerSecond']),
      name: pulumi.Input.asOptionalInput<String>(map['name']),
      region: pulumi.Input.asOptionalInput<String>(map['region']),
    );
  }
}
