import 'package:pulumi/pulumi.dart';
import 'event_api_destination_args.dart';

/// Provides an EventBridge event API Destination resource.
///
/// > **Note:** EventBridge was formerly known as CloudWatch Events. The functionality is identical.
///
/// ## Example Usage
///
///
///
/// ## Import
///
/// Using `pulumi import`, import EventBridge API Destinations using the `name`. For example:
///
/// ```sh
/// $ pulumi import aws:cloudwatch/eventApiDestination:EventApiDestination test api-destination
/// ```
class EventApiDestination extends CustomResource {
  /// The Amazon Resource Name (ARN) of the event API Destination.
  late final Output<String> arn;

  /// ARN of the EventBridge Connection to use for the API Destination.
  late final Output<String> connectionArn;

  /// The description of the new API Destination. Maximum of 512 characters.
  late final Output<String?> description;

  /// Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc.
  late final Output<String> httpMethod;

  /// URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "*" as path parameters wildcards to be set from the Target HttpParameters.
  late final Output<String> invocationEndpoint;

  /// Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300).
  late final Output<int?> invocationRateLimitPerSecond;

  /// The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.
  late final Output<String> name;

  /// Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
  late final Output<String> region;

  EventApiDestination(
    String name, {
    EventApiDestinationArgs? args,
    CustomResourceOptions? options,
  }) : super(
          'aws:cloudwatch/eventApiDestination:EventApiDestination',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.arn = registerOutput<String>('arn');
    this.connectionArn = registerOutput<String>('connectionArn');
    this.description = registerOutput<String?>('description');
    this.httpMethod = registerOutput<String>('httpMethod');
    this.invocationEndpoint = registerOutput<String>('invocationEndpoint');
    this.invocationRateLimitPerSecond =
        registerOutput<int?>('invocationRateLimitPerSecond');
    this.name = registerOutput<String>('name');
    this.region = registerOutput<String>('region');
  }
}
