library module_chimesdkmediapipelines_media_insights_pipeline_configuration_element_kinesis_data_stream_sink_configuration;

export 'media_insights_pipeline_configuration_element_kinesis_data_stream_sink_configuration.dart';
