/// Techniques of the assessment
enum Techniques {
  valueAbuseElevationControlMechanism("Abuse Elevation Control Mechanism"),
  valueAccessTokenManipulation("Access Token Manipulation"),
  valueAccountDiscovery("Account Discovery"),
  valueAccountManipulation("Account Manipulation"),
  valueActiveScanning("Active Scanning"),
  valueApplicationLayerProtocol("Application Layer Protocol"),
  valueAudioCapture("Audio Capture"),
  valueBootOrLogonAutostartExecution("Boot or Logon Autostart Execution"),
  valueBootOrLogonInitializationScripts("Boot or Logon Initialization Scripts"),
  valueBruteForce("Brute Force"),
  valueCloudInfrastructureDiscovery("Cloud Infrastructure Discovery"),
  valueCloudServiceDashboard("Cloud Service Dashboard"),
  valueCloudServiceDiscovery("Cloud Service Discovery"),
  valueCommandAndScriptingInterpreter("Command and Scripting Interpreter"),
  valueCompromiseClientSoftwareBinary("Compromise Client Software Binary"),
  valueCompromiseInfrastructure("Compromise Infrastructure"),
  valueContainerAndResourceDiscovery("Container and Resource Discovery"),
  valueCreateAccount("Create Account"),
  valueCreateOrModifySystemProcess("Create or Modify System Process"),
  valueCredentialsFromPasswordStores("Credentials from Password Stores"),
  valueDataDestruction("Data Destruction"),
  valueDataEncryptedForImpact("Data Encrypted for Impact"),
  valueDataFromCloudStorageObject("Data from Cloud Storage Object"),
  valueDataFromConfigurationRepository("Data from Configuration Repository"),
  valueDataFromInformationRepositories("Data from Information Repositories"),
  valueDataFromLocalSystem("Data from Local System"),
  valueDataManipulation("Data Manipulation"),
  valueDataStaged("Data Staged"),
  valueDefacement("Defacement"),
  valueDeobfuscateDecodeFilesOrInformation(
    "Deobfuscate/Decode Files or Information",
  ),
  valueDiskWipe("Disk Wipe"),
  valueDomainTrustDiscovery("Domain Trust Discovery"),
  valueDriveByCompromise("Drive-by Compromise"),
  valueDynamicResolution("Dynamic Resolution"),
  valueEndpointDenialOfService("Endpoint Denial of Service"),
  valueEventTriggeredExecution("Event Triggered Execution"),
  valueExfiltrationOverAlternativeProtocol(
    "Exfiltration Over Alternative Protocol",
  ),
  valueExploitPublicFacingApplication("Exploit Public-Facing Application"),
  valueExploitationForClientExecution("Exploitation for Client Execution"),
  valueExploitationForCredentialAccess("Exploitation for Credential Access"),
  valueExploitationForDefenseEvasion("Exploitation for Defense Evasion"),
  valueExploitationForPrivilegeEscalation(
    "Exploitation for Privilege Escalation",
  ),
  valueExploitationOfRemoteServices("Exploitation of Remote Services"),
  valueExternalRemoteServices("External Remote Services"),
  valueFallbackChannels("Fallback Channels"),
  valueFileAndDirectoryDiscovery("File and Directory Discovery"),
  valueGatherVictimNetworkInformation("Gather Victim Network Information"),
  valueHideArtifacts("Hide Artifacts"),
  valueHijackExecutionFlow("Hijack Execution Flow"),
  valueImpairDefenses("Impair Defenses"),
  valueImplantContainerImage("Implant Container Image"),
  valueIndicatorRemovalOnHost("Indicator Removal on Host"),
  valueIndirectCommandExecution("Indirect Command Execution"),
  valueIngressToolTransfer("Ingress Tool Transfer"),
  valueInputCapture("Input Capture"),
  valueInterProcessCommunication("Inter-Process Communication"),
  valueLateralToolTransfer("Lateral Tool Transfer"),
  valueManInTheMiddle("Man-in-the-Middle"),
  valueMasquerading("Masquerading"),
  valueModifyAuthenticationProcess("Modify Authentication Process"),
  valueModifyRegistry("Modify Registry"),
  valueNetworkDenialOfService("Network Denial of Service"),
  valueNetworkServiceScanning("Network Service Scanning"),
  valueNetworkSniffing("Network Sniffing"),
  valueNonApplicationLayerProtocol("Non-Application Layer Protocol"),
  valueNonStandardPort("Non-Standard Port"),
  valueObtainCapabilities("Obtain Capabilities"),
  valueObfuscatedFilesOrInformation("Obfuscated Files or Information"),
  valueOfficeApplicationStartup("Office Application Startup"),
  valueOSCredentialDumping("OS Credential Dumping"),
  valuePermissionGroupsDiscovery("Permission Groups Discovery"),
  valuePhishing("Phishing"),
  valuePreOSBoot("Pre-OS Boot"),
  valueProcessDiscovery("Process Discovery"),
  valueProcessInjection("Process Injection"),
  valueProtocolTunneling("Protocol Tunneling"),
  valueProxy("Proxy"),
  valueQueryRegistry("Query Registry"),
  valueRemoteAccessSoftware("Remote Access Software"),
  valueRemoteServiceSessionHijacking("Remote Service Session Hijacking"),
  valueRemoteServices("Remote Services"),
  valueRemoteSystemDiscovery("Remote System Discovery"),
  valueResourceHijacking("Resource Hijacking"),
  valueScheduledTaskJob("Scheduled Task/Job"),
  valueScreenCapture("Screen Capture"),
  valueSearchVictimOwnedWebsites("Search Victim-Owned Websites"),
  valueServerSoftwareComponent("Server Software Component"),
  valueServiceStop("Service Stop"),
  valueSignedBinaryProxyExecution("Signed Binary Proxy Execution"),
  valueSoftwareDeploymentTools("Software Deployment Tools"),
  valueSQLStoredProcedures("SQL Stored Procedures"),
  valueStealOrForgeKerberosTickets("Steal or Forge Kerberos Tickets"),
  valueSubvertTrustControls("Subvert Trust Controls"),
  valueSupplyChainCompromise("Supply Chain Compromise"),
  valueSystemInformationDiscovery("System Information Discovery"),
  valueTaintSharedContent("Taint Shared Content"),
  valueTrafficSignaling("Traffic Signaling"),
  valueTransferDataToCloudAccount("Transfer Data to Cloud Account"),
  valueTrustedRelationship("Trusted Relationship"),
  valueUnsecuredCredentials("Unsecured Credentials"),
  valueUserExecution("User Execution"),
  valueValidAccounts("Valid Accounts"),
  valueWindowsManagementInstrumentation("Windows Management Instrumentation"),
  valueFileAndDirectoryPermissionsModification(
    "File and Directory Permissions Modification",
  );

  const Techniques(this.wireValue);
  final String wireValue;

  static Techniques fromValue(String value) {
    for (final item in Techniques.values) {
      if (item.wireValue == value) {
        return item;
      }
    }
    throw ArgumentError('Unknown Techniques value: $value');
  }
}
