// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart';

/// The set of arguments for ClusterIAMPolicy.
class ClusterIAMPolicyArgs {
  /// The name or relative resource id of the cluster to manage IAM policies for.
  ///
  /// For <span pulumi-lang-nodejs="`gcp.dataproc.ClusterIAMMember`" pulumi-lang-dotnet="`gcp.dataproc.ClusterIAMMember`" pulumi-lang-go="`dataproc.ClusterIAMMember`" pulumi-lang-python="`dataproc.ClusterIAMMember`" pulumi-lang-yaml="`gcp.dataproc.ClusterIAMMember`" pulumi-lang-java="`gcp.dataproc.ClusterIAMMember`">`gcp.dataproc.ClusterIAMMember`</span> or <span pulumi-lang-nodejs="`gcp.dataproc.ClusterIAMBinding`" pulumi-lang-dotnet="`gcp.dataproc.ClusterIAMBinding`" pulumi-lang-go="`dataproc.ClusterIAMBinding`" pulumi-lang-python="`dataproc.ClusterIAMBinding`" pulumi-lang-yaml="`gcp.dataproc.ClusterIAMBinding`" pulumi-lang-java="`gcp.dataproc.ClusterIAMBinding`">`gcp.dataproc.ClusterIAMBinding`</span>:
  final Input<String> cluster;

  /// The policy data generated by a <span pulumi-lang-nodejs="`gcp.organizations.getIAMPolicy`" pulumi-lang-dotnet="`gcp.organizations.getIAMPolicy`" pulumi-lang-go="`organizations.getIAMPolicy`" pulumi-lang-python="`organizations_get_iam_policy`" pulumi-lang-yaml="`gcp.organizations.getIAMPolicy`" pulumi-lang-java="`gcp.organizations.getIAMPolicy`">`gcp.organizations.getIAMPolicy`</span> data source.
  ///
  /// - - -
  final Input<String> policyData;

  /// The project in which the cluster belongs. If it
  /// is not provided, the provider will use a default.
  final Input<String>? project;

  /// The region in which the cluster belongs. If it
  /// is not provided, the provider will use a default.
  final Input<String>? region;

  ClusterIAMPolicyArgs({
    required this.cluster,
    required this.policyData,
    this.project,
    this.region,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['cluster'] = cluster;
    map['policyData'] = policyData;
    final projectValue = project;
    if (projectValue != null) {
      map['project'] = projectValue;
    }
    final regionValue = region;
    if (regionValue != null) {
      map['region'] = regionValue;
    }
    return map;
  }

  factory ClusterIAMPolicyArgs.fromMap(Map<String, dynamic> map) {
    return ClusterIAMPolicyArgs(
      cluster: Input.asInput<String>(map['cluster']),
      policyData: Input.asInput<String>(map['policyData']),
      project: Input.asOptionalInput<String>(map['project']),
      region: Input.asOptionalInput<String>(map['region']),
    );
  }
}
