// ignore_for_file: unused_element, unnecessary_cast

import 'prevention_discovery_config_target_other_cloud_target_conditions.dart';
import 'prevention_discovery_config_target_other_cloud_target_data_source_type.dart';
import 'prevention_discovery_config_target_other_cloud_target_filter.dart';
import 'prevention_discovery_config_target_other_cloud_target_generation_cadence.dart';

class PreventionDiscoveryConfigTargetOtherCloudTarget {
  /// In addition to matching the filter, these conditions must be true before a profile is generated.
  /// Structure is documented below.
  final PreventionDiscoveryConfigTargetOtherCloudTargetConditions? conditions;

  /// Required. The type of data profiles generated by this discovery target. Supported values are: aws/s3/bucket
  /// Structure is documented below.
  final PreventionDiscoveryConfigTargetOtherCloudTargetDataSourceType?
  dataSourceType;

  /// Disable profiling for resources that match this filter.
  final Map<String, dynamic>? disabled;

  /// Required. The resources that the discovery cadence applies to. The first target with a matching filter will be the one to apply to a resource.
  /// Structure is documented below.
  final PreventionDiscoveryConfigTargetOtherCloudTargetFilter filter;

  /// How often and when to update profiles. New resources that match both the filter and conditions are scanned as quickly as possible depending on system capacity.
  /// Structure is documented below.
  final PreventionDiscoveryConfigTargetOtherCloudTargetGenerationCadence?
  generationCadence;

  /// Creates a new [PreventionDiscoveryConfigTargetOtherCloudTarget].
  /// [conditions] In addition to matching the filter, these conditions must be true before a profile is generated.
  /// [dataSourceType] Required. The type of data profiles generated by this discovery target. Supported values are: aws/s3/bucket
  /// [disabled] Disable profiling for resources that match this filter.
  /// [filter] Required. The resources that the discovery cadence applies to. The first target with a matching filter will be the one to apply to a resource.
  /// [generationCadence] How often and when to update profiles. New resources that match both the filter and conditions are scanned as quickly as possible depending on system capacity.
  PreventionDiscoveryConfigTargetOtherCloudTarget({
    this.conditions,
    this.dataSourceType,
    this.disabled,
    required this.filter,
    this.generationCadence,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'conditions': ?conditions == null ? null : conditions!.toMap(),
      'dataSourceType': ?dataSourceType == null
          ? null
          : dataSourceType!.toMap(),
      'disabled': ?disabled,
      'filter': filter.toMap(),
      'generationCadence': ?generationCadence == null
          ? null
          : generationCadence!.toMap(),
    };
  }

  factory PreventionDiscoveryConfigTargetOtherCloudTarget.fromMap(
    Map<String, dynamic> map,
  ) {
    return PreventionDiscoveryConfigTargetOtherCloudTarget(
      conditions: map['conditions'] == null
          ? null
          : PreventionDiscoveryConfigTargetOtherCloudTargetConditions.fromMap(
              (map['conditions'] as Map).cast<String, dynamic>(),
            ),
      dataSourceType: map['dataSourceType'] == null
          ? null
          : PreventionDiscoveryConfigTargetOtherCloudTargetDataSourceType.fromMap(
              (map['dataSourceType'] as Map).cast<String, dynamic>(),
            ),
      disabled: map['disabled'] == null
          ? null
          : (map['disabled'] as Map).cast<String, dynamic>(),
      filter: PreventionDiscoveryConfigTargetOtherCloudTargetFilter.fromMap(
        (map['filter'] as Map).cast<String, dynamic>(),
      ),
      generationCadence: map['generationCadence'] == null
          ? null
          : PreventionDiscoveryConfigTargetOtherCloudTargetGenerationCadence.fromMap(
              (map['generationCadence'] as Map).cast<String, dynamic>(),
            ),
    );
  }
}
