// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// The set of arguments for V2OrganizationSourceIamPolicy.
class V2OrganizationSourceIamPolicyArgs {
  final pulumi.Input<String> organization;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> source;

  V2OrganizationSourceIamPolicyArgs({
    required this.organization,
    required this.policyData,
    required this.source,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['organization'] = organization;
    map['policyData'] = policyData;
    map['source'] = source;
    return map;
  }

  factory V2OrganizationSourceIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return V2OrganizationSourceIamPolicyArgs(
      organization: pulumi.Input.asInput<String>(map['organization']),
      policyData: pulumi.Input.asInput<String>(map['policyData']),
      source: pulumi.Input.asInput<String>(map['source']),
    );
  }
}
