library module_lex_v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_response_message_group_variation_plain_text_message;

export 'v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_response_message_group_variation_plain_text_message/v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_response_message_group_variation_plain_text_message.dart';
