library module_lex_v2models_intent_confirmation_setting_declination_conditional;

export 'v2models_intent_confirmation_setting_declination_conditional/v2models_intent_confirmation_setting_declination_conditional.dart';
