library module_lex_v2models_intent_confirmation_setting_declination_conditional_default_branch;

export 'v2models_intent_confirmation_setting_declination_conditional_default_branch/v2models_intent_confirmation_setting_declination_conditional_default_branch.dart';
