library module_lex_v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_next_step_intent_slot;

export 'v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_next_step_intent_slot/v2models_intent_fulfillment_code_hook_post_fulfillment_status_specification_failure_next_step_intent_slot.dart';
