library module_lex_v2models_intent_confirmation_setting_declination_response_message_group_message_image_response_card;

export 'v2models_intent_confirmation_setting_declination_response_message_group_message_image_response_card/v2models_intent_confirmation_setting_declination_response_message_group_message_image_response_card.dart';
