library module_lex_v2models_intent_confirmation_setting_prompt_specification_message_group_variation_custom_payload;

export 'v2models_intent_confirmation_setting_prompt_specification_message_group_variation_custom_payload/v2models_intent_confirmation_setting_prompt_specification_message_group_variation_custom_payload.dart';
