library module_lex_v2models_intent_fulfillment_code_hook_fulfillment_updates_specification;

export 'v2models_intent_fulfillment_code_hook_fulfillment_updates_specification/v2models_intent_fulfillment_code_hook_fulfillment_updates_specification.dart';
