library module_lex_v2models_intent_closing_setting_closing_response_message_group_message;

export 'v2models_intent_closing_setting_closing_response_message_group_message/v2models_intent_closing_setting_closing_response_message_group_message.dart';
