library module_lex_v2models_intent_confirmation_setting_confirmation_conditional_default_branch_response;

export 'v2models_intent_confirmation_setting_confirmation_conditional_default_branch_response/v2models_intent_confirmation_setting_confirmation_conditional_default_branch_response.dart';
