library module_lex_v2models_intent_closing_setting_closing_response_message_group;

export 'v2models_intent_closing_setting_closing_response_message_group/v2models_intent_closing_setting_closing_response_message_group.dart';
