library module_lex_v2models_intent_qna_intent_configuration_bedrock_model_configuration_guardrail;

export 'v2models_intent_qna_intent_configuration_bedrock_model_configuration_guardrail/v2models_intent_qna_intent_configuration_bedrock_model_configuration_guardrail.dart';
