library module_lex_v2models_intent_confirmation_setting_prompt_specification_prompt_attempts_specification;

export 'v2models_intent_confirmation_setting_prompt_specification_prompt_attempts_specification/v2models_intent_confirmation_setting_prompt_specification_prompt_attempts_specification.dart';
