library module_lex_v2models_intent_confirmation_setting_prompt_specification;

export 'v2models_intent_confirmation_setting_prompt_specification/v2models_intent_confirmation_setting_prompt_specification.dart';
