library module_lex_v2models_intent_qna_intent_configuration_data_source_configuration_kendra_configuration;

export 'v2models_intent_qna_intent_configuration_data_source_configuration_kendra_configuration/v2models_intent_qna_intent_configuration_data_source_configuration_kendra_configuration.dart';
