library module_lex_v2models_intent_confirmation_setting_code_hook_post_code_hook_specification_success_response;

export 'v2models_intent_confirmation_setting_code_hook_post_code_hook_specification_success_response/v2models_intent_confirmation_setting_code_hook_post_code_hook_specification_success_response.dart';
