library module_lex_v2models_slot_value_elicitation_setting_prompt_specification;

export 'v2models_slot_value_elicitation_setting_prompt_specification/v2models_slot_value_elicitation_setting_prompt_specification.dart';
