// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_iam_workforce_pool_iam_policy_workforce_pool_iam_policy_args_doc}
/// The set of arguments for WorkforcePoolIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_iam_workforce_pool_iam_policy_workforce_pool_iam_policy_args_doc}
class WorkforcePoolIamPolicyArgs {
  /// The location for the resource. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? location;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> workforcePoolId;

  /// Creates a new [WorkforcePoolIamPolicyArgs].
  /// [location] The location for the resource. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// [policyData] The policy data generated by
  /// [workforcePoolId] Used to find the parent resource to bind the IAM policy to
  WorkforcePoolIamPolicyArgs({
    pulumi.Output<String>? location,
    required pulumi.Output<String> policyData,
    required pulumi.Output<String> workforcePoolId,
  }) :
      location = pulumi.Input.asOptionalInput<String>(location),
      policyData = pulumi.Input.asInput<String>(policyData),
      workforcePoolId = pulumi.Input.asInput<String>(workforcePoolId);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'location': ?location,
      'policyData': policyData,
      'workforcePoolId': workforcePoolId,
    };
  }

  factory WorkforcePoolIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return WorkforcePoolIamPolicyArgs(
      location: map['location'] == null ? null : pulumi.Output.create<String>(map['location'] as String),
      policyData: pulumi.Output.create<String>(map['policyData'] as String),
      workforcePoolId: pulumi.Output.create<String>(map['workforcePoolId'] as String),
    );
  }
}

