// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering WorkloadIdentityPoolIamPolicy resources.
class WorkloadIdentityPoolIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? workloadIdentityPoolId;

  /// Creates a new [WorkloadIdentityPoolIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [workloadIdentityPoolId] Used to find the parent resource to bind the IAM policy to
  WorkloadIdentityPoolIamPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? policyData,
    pulumi.Output<String>? project,
    pulumi.Output<String>? workloadIdentityPoolId,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      policyData = pulumi.Input.asOptionalInput<String>(policyData),
      project = pulumi.Input.asOptionalInput<String>(project),
      workloadIdentityPoolId = pulumi.Input.asOptionalInput<String>(workloadIdentityPoolId);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'policyData': ?policyData,
      'project': ?project,
      'workloadIdentityPoolId': ?workloadIdentityPoolId,
    };
  }

  factory WorkloadIdentityPoolIamPolicyState.fromMap(Map<String, dynamic> map) {
    return WorkloadIdentityPoolIamPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
      workloadIdentityPoolId: map['workloadIdentityPoolId'] == null ? null : pulumi.Output.create<String>(map['workloadIdentityPoolId'] as String),
    );
  }
}

