name: pulumi_packages_workspace
environment:
  sdk: ^3.10.0
workspace:
  - alicloud
  - aws
  - aws-apigateway
  - awsx
  - azure
  - azure-native
  - azuread
  - command
  - digitalocean
  - docker
  - docker-build
  - eks
  - f5bigip
  - gcp
  - gcp-global-cloudrun
  - google-native
  - hcloud
  - kubernetes
  - libvirt
  - linode
  - mysql
  - newrelic
  - openstack
  - policy
  - postgresql
  - pulumiservice
  - random
  - terraform
  - tls
dependency_overrides:
  pulumi:
    path: ../pulumi-dart
