name: gcp_rails_postgresql
description: Pulumi Dart example for Kubernetes with Ruby on Rails and PostgreSQL on GCP.
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  pulumi: ^3.0.0
  pulumi_docker: 5.2.0+1
  pulumi_gcp: 9.35.1+1
  pulumi_kubernetes: 4.33.0+1

dev_dependencies:
  lints: ^6.1.0
