name: gcp_rails_postgresql
description: Pulumi Dart example for Kubernetes with Ruby on Rails and PostgreSQL on GCP.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  pulumi: 0.1.0
  pulumi_docker: any
  pulumi_gcp: any
  pulumi_kubernetes: any

dev_dependencies:
  lints: ^6.1.0
