library module_securitycenter_management_organization_event_threat_detection_custom_module;

export 'management_organization_event_threat_detection_custom_module/management_organization_event_threat_detection_custom_module.dart';
export 'management_organization_event_threat_detection_custom_module/management_organization_event_threat_detection_custom_module_args.dart';
