library module_securitycenter_management_organization_security_health_analytics_custom_module_custom_config_predicate;

export 'management_organization_security_health_analytics_custom_module_custom_config_predicate/management_organization_security_health_analytics_custom_module_custom_config_predicate.dart';
