library module_securitycenter_v2_organization_notification_config;

export 'v2_organization_notification_config/v2_organization_notification_config.dart';
export 'v2_organization_notification_config/v2_organization_notification_config_args.dart';
