library module_dynamodb_get_table_global_secondary_index_on_demand_throughput;

export 'get_table_global_secondary_index_on_demand_throughput/get_table_global_secondary_index_on_demand_throughput.dart';
