library module_lex_v2models_intent_confirmation_setting_confirmation_response_message_group_message_custom_payload;

export 'v2models_intent_confirmation_setting_confirmation_response_message_group_message_custom_payload.dart';
