// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_compute_disk_iam_policy_disk_iam_policy_args_doc}
/// The set of arguments for DiskIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_compute_disk_iam_policy_disk_iam_policy_args_doc}
class DiskIamPolicyArgs {
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? name;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;
  /// A reference to the zone where the disk resides. Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no zone is provided in the parent identifier and no
  /// zone is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? zone;

  /// Creates a new [DiskIamPolicyArgs].
  /// [name] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [zone] A reference to the zone where the disk resides. Used to find the parent resource to bind the IAM policy to. If not specified,
  DiskIamPolicyArgs({
    this.name,
    required this.policyData,
    this.project,
    this.zone,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'name': ?name,
      'policyData': policyData,
      'project': ?project,
      'zone': ?zone,
    };
  }

  factory DiskIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return DiskIamPolicyArgs(
      name: map['name'] == null ? null : (map['name'] as String).input(),
      policyData: (map['policyData'] as String).input(),
      project: map['project'] == null ? null : (map['project'] as String).input(),
      zone: map['zone'] == null ? null : (map['zone'] as String).input(),
    );
  }
}

