// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// Input properties used for looking up and filtering ImageIamPolicy resources.
class ImageIamPolicyState {
  /// (Computed) The etag of the IAM policy.
  final pulumi.Input<String>? etag;
  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String>? image;
  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String>? policyData;
  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Creates a new [ImageIamPolicyState].
  /// [etag] (Computed) The etag of the IAM policy.
  /// [image] Used to find the parent resource to bind the IAM policy to
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  ImageIamPolicyState({
    pulumi.Output<String>? etag,
    pulumi.Output<String>? image,
    pulumi.Output<String>? policyData,
    pulumi.Output<String>? project,
  }) :
      etag = pulumi.Input.asOptionalInput<String>(etag),
      image = pulumi.Input.asOptionalInput<String>(image),
      policyData = pulumi.Input.asOptionalInput<String>(policyData),
      project = pulumi.Input.asOptionalInput<String>(project);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'etag': ?etag,
      'image': ?image,
      'policyData': ?policyData,
      'project': ?project,
    };
  }

  factory ImageIamPolicyState.fromMap(Map<String, dynamic> map) {
    return ImageIamPolicyState(
      etag: map['etag'] == null ? null : pulumi.Output.create<String>(map['etag'] as String),
      image: map['image'] == null ? null : pulumi.Output.create<String>(map['image'] as String),
      policyData: map['policyData'] == null ? null : pulumi.Output.create<String>(map['policyData'] as String),
      project: map['project'] == null ? null : pulumi.Output.create<String>(map['project'] as String),
    );
  }
}

