// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import 'region_url_map_default_route_action_cors_policy.dart';
import 'region_url_map_default_route_action_fault_injection_policy.dart';
import 'region_url_map_default_route_action_request_mirror_policy.dart';
import 'region_url_map_default_route_action_retry_policy.dart';
import 'region_url_map_default_route_action_timeout.dart';
import 'region_url_map_default_route_action_url_rewrite.dart';
import 'region_url_map_default_route_action_weighted_backend_service.dart';

class RegionUrlMapDefaultRouteAction {
  /// The specification for allowing client side cross-origin requests. Please see
  /// [W3C Recommendation for Cross Origin Resource Sharing](https://www.w3.org/TR/cors/)
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionCorsPolicy>? corsPolicy;
  /// The specification for fault injection introduced into traffic to test the resiliency of clients to backend service failure.
  /// As part of fault injection, when clients send requests to a backend service, delays can be introduced by a load balancer on a percentage of requests before sending those requests to the backend service.
  /// Similarly requests from clients can be aborted by the load balancer for a percentage of requests.
  /// timeout and retryPolicy is ignored by clients that are configured with a faultInjectionPolicy if: 1. The traffic is generated by fault injection AND 2. The fault injection is not a delay fault injection.
  /// Fault injection is not supported with the global external HTTP(S) load balancer (classic). To see which load balancers support fault injection, see Load balancing: [Routing and traffic management features](https://cloud.google.com/load-balancing/docs/features#routing-traffic-management).
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionFaultInjectionPolicy>? faultInjectionPolicy;
  /// Specifies the policy on how requests intended for the route's backends are shadowed to a separate mirrored backend service.
  /// The load balancer does not wait for responses from the shadow service. Before sending traffic to the shadow service, the host / authority header is suffixed with -shadow.
  /// Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionRequestMirrorPolicy>? requestMirrorPolicy;
  /// Specifies the retry policy associated with this route.
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionRetryPolicy>? retryPolicy;
  /// Specifies the timeout for the selected route. Timeout is computed from the time the request has been fully processed (known as end-of-stream) up until the response has been processed. Timeout includes all retries.
  /// If not specified, this field uses the largest timeout among all backend services associated with the route.
  /// Not supported when the URL map is bound to a target gRPC proxy that has validateForProxyless field set to true.
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionTimeout>? timeout;
  /// The spec to modify the URL of the request, before forwarding the request to the matched service.
  /// urlRewrite is the only action supported in UrlMaps for external HTTP(S) load balancers.
  /// Not supported when the URL map is bound to a target gRPC proxy that has the validateForProxyless field set to true.
  /// Structure is documented below.
  final pulumi.Input<RegionUrlMapDefaultRouteActionUrlRewrite>? urlRewrite;
  /// A list of weighted backend services to send traffic to when a route match occurs. The weights determine the fraction of traffic that flows to their corresponding backend service. If all traffic needs to go to a single backend service, there must be one weightedBackendService with weight set to a non-zero number.
  /// After a backend service is identified and before forwarding the request to the backend service, advanced routing actions such as URL rewrites and header transformations are applied depending on additional settings specified in this HttpRouteAction.
  /// Structure is documented below.
  final pulumi.Input<List<RegionUrlMapDefaultRouteActionWeightedBackendService>>? weightedBackendServices;

  /// Creates a new [RegionUrlMapDefaultRouteAction].
  /// [corsPolicy] The specification for allowing client side cross-origin requests. Please see
  /// [faultInjectionPolicy] The specification for fault injection introduced into traffic to test the resiliency of clients to backend service failure.
  /// [requestMirrorPolicy] Specifies the policy on how requests intended for the route's backends are shadowed to a separate mirrored backend service.
  /// [retryPolicy] Specifies the retry policy associated with this route.
  /// [timeout] Specifies the timeout for the selected route. Timeout is computed from the time the request has been fully processed (known as end-of-stream) up until the response has been processed. Timeout includes all retries.
  /// [urlRewrite] The spec to modify the URL of the request, before forwarding the request to the matched service.
  /// [weightedBackendServices] A list of weighted backend services to send traffic to when a route match occurs. The weights determine the fraction of traffic that flows to their corresponding backend service. If all traffic needs to go to a single backend service, there must be one weightedBackendService with weight set to a non-zero number.
  RegionUrlMapDefaultRouteAction({
    this.corsPolicy,
    this.faultInjectionPolicy,
    this.requestMirrorPolicy,
    this.retryPolicy,
    this.timeout,
    this.urlRewrite,
    this.weightedBackendServices,
  });

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'corsPolicy': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionCorsPolicy, Map<String, dynamic>>(corsPolicy, (value) => value.toMap()),
      'faultInjectionPolicy': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionFaultInjectionPolicy, Map<String, dynamic>>(faultInjectionPolicy, (value) => value.toMap()),
      'requestMirrorPolicy': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionRequestMirrorPolicy, Map<String, dynamic>>(requestMirrorPolicy, (value) => value.toMap()),
      'retryPolicy': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionRetryPolicy, Map<String, dynamic>>(retryPolicy, (value) => value.toMap()),
      'timeout': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionTimeout, Map<String, dynamic>>(timeout, (value) => value.toMap()),
      'urlRewrite': ?pulumi.Input.mapOptionalInputValue<RegionUrlMapDefaultRouteActionUrlRewrite, Map<String, dynamic>>(urlRewrite, (value) => value.toMap()),
      'weightedBackendServices': ?pulumi.Input.mapOptionalInputValue<List<RegionUrlMapDefaultRouteActionWeightedBackendService>, List<Map<String, dynamic>>>(weightedBackendServices, (value) => pulumi.Input.encodeList<RegionUrlMapDefaultRouteActionWeightedBackendService, Map<String, dynamic>>(value, (value) => value.toMap())),
    };
  }

  factory RegionUrlMapDefaultRouteAction.fromMap(Map<String, dynamic> map) {
    return RegionUrlMapDefaultRouteAction(
      corsPolicy: map['corsPolicy'] == null ? null : (RegionUrlMapDefaultRouteActionCorsPolicy.fromMap((map['corsPolicy']! as Map).cast<String, dynamic>())).input(),
      faultInjectionPolicy: map['faultInjectionPolicy'] == null ? null : (RegionUrlMapDefaultRouteActionFaultInjectionPolicy.fromMap((map['faultInjectionPolicy']! as Map).cast<String, dynamic>())).input(),
      requestMirrorPolicy: map['requestMirrorPolicy'] == null ? null : (RegionUrlMapDefaultRouteActionRequestMirrorPolicy.fromMap((map['requestMirrorPolicy']! as Map).cast<String, dynamic>())).input(),
      retryPolicy: map['retryPolicy'] == null ? null : (RegionUrlMapDefaultRouteActionRetryPolicy.fromMap((map['retryPolicy']! as Map).cast<String, dynamic>())).input(),
      timeout: map['timeout'] == null ? null : (RegionUrlMapDefaultRouteActionTimeout.fromMap((map['timeout']! as Map).cast<String, dynamic>())).input(),
      urlRewrite: map['urlRewrite'] == null ? null : (RegionUrlMapDefaultRouteActionUrlRewrite.fromMap((map['urlRewrite']! as Map).cast<String, dynamic>())).input(),
      weightedBackendServices: map['weightedBackendServices'] == null ? null : (pulumi.Input.decodeList<RegionUrlMapDefaultRouteActionWeightedBackendService>(map['weightedBackendServices']!, (value) => RegionUrlMapDefaultRouteActionWeightedBackendService.fromMap((value as Map).cast<String, dynamic>()))).input(),
    );
  }
}

