import 'package:pulumi/pulumi.dart' hide Config;
import 'execution_args3.dart';
import 'execution_template_response.dart';

/// Creates a new Execution in a given project and location.
/// Auto-naming is currently not supported for this resource.
class Execution3 extends CustomResource {
  /// Time the Execution was instantiated.
  late final Output<String> createTime;

  /// A brief description of this execution.
  late final Output<String> description;

  /// Name used for UI purposes. Name can only contain alphanumeric characters and underscores '_'.
  late final Output<String> displayName;

  /// Required. User-defined unique ID of this execution.
  late final Output<String> executionId;

  /// execute metadata including name, hardware spec, region, labels, etc.
  late final Output<ExecutionTemplateResponse> executionTemplate;

  /// The URI of the external job used to execute the notebook.
  late final Output<String> jobUri;
  late final Output<String> location;

  /// The resource name of the execute. Format: `projects/{project_id}/locations/{location}/executions/{execution_id}`
  late final Output<String> name;

  /// Output notebook file generated by this execution
  late final Output<String> outputNotebookFile;
  late final Output<String> project;

  /// State of the underlying AI Platform job.
  late final Output<String> state;

  /// Time the Execution was last updated.
  late final Output<String> updateTime;

  Execution3(
    String name, {
    ExecutionArgs3? args,
    CustomResourceOptions? options,
  }) : super(
          'google-native:notebooks/v1:Execution',
          name,
          Input.mapToInputs(args?.toMap() ?? const {}),
          options ?? CustomResourceOptions(),
        ) {
    this.createTime = registerOutput<String>('createTime');
    this.description = registerOutput<String>('description');
    this.displayName = registerOutput<String>('displayName');
    this.executionId = registerOutput<String>('executionId');
    this.executionTemplate =
        registerOutput<ExecutionTemplateResponse>('executionTemplate');
    this.jobUri = registerOutput<String>('jobUri');
    this.location = registerOutput<String>('location');
    this.name = registerOutput<String>('name');
    this.outputNotebookFile = registerOutput<String>('outputNotebookFile');
    this.project = registerOutput<String>('project');
    this.state = registerOutput<String>('state');
    this.updateTime = registerOutput<String>('updateTime');
  }
}
