// ignore_for_file: non_constant_identifier_names

library pulumi_f5bigip;

import 'package:pulumi_f5bigip/cm.dart' as _cm;
import 'package:pulumi_f5bigip/fast.dart' as _fast;
import 'package:pulumi_f5bigip/index.dart' as _index;
import 'package:pulumi_f5bigip/ltm.dart' as _ltm;
import 'package:pulumi_f5bigip/net.dart' as _net;
import 'package:pulumi_f5bigip/providers.dart' as _providers;
import 'package:pulumi_f5bigip/ssl.dart' as _ssl;
import 'package:pulumi_f5bigip/sys.dart' as _sys;
import 'package:pulumi_f5bigip/vcmp.dart' as _vcmp;

final cm = _CmModuleNamespace();
final fast = _FastModuleNamespace();
final index = _IndexModuleNamespace();
final ltm = _LtmModuleNamespace();
final net = _NetModuleNamespace();
final providers = _ProvidersModuleNamespace();
final ssl = _SslModuleNamespace();
final sys = _SysModuleNamespace();
final vcmp = _VcmpModuleNamespace();

class _CmModuleNamespace {
  _CmModuleNamespace();
  final Device = _cm.Device.new;
  final DeviceArgs = _cm.DeviceArgs.new;
  final DeviceGroup = _cm.DeviceGroup.new;
  final DeviceGroupArgs = _cm.DeviceGroupArgs.new;
  final DeviceGroupDevice = _cm.DeviceGroupDevice.new;
  final DeviceGroupDeviceArgs = _cm.DeviceGroupDevice.new;
}

class _FastModuleNamespace {
  _FastModuleNamespace();
  final GetAwsServiceDiscoveryArgs = _fast.GetAwsServiceDiscoveryArgs.new;
  final GetAwsServiceDiscoveryResult = _fast.GetAwsServiceDiscoveryResult.new;
  final GetAwsServiceDiscoveryResultArgs = _fast.GetAwsServiceDiscoveryResult.new;
  final GetAzureServiceDiscoveryArgs = _fast.GetAzureServiceDiscoveryArgs.new;
  final GetAzureServiceDiscoveryResult = _fast.GetAzureServiceDiscoveryResult.new;
  final GetAzureServiceDiscoveryResultArgs = _fast.GetAzureServiceDiscoveryResult.new;
  final GetConsulServiceDiscoveryArgs = _fast.GetConsulServiceDiscoveryArgs.new;
  final GetConsulServiceDiscoveryResult = _fast.GetConsulServiceDiscoveryResult.new;
  final GetConsulServiceDiscoveryResultArgs = _fast.GetConsulServiceDiscoveryResult.new;
  final GetGceServiceDiscoveryArgs = _fast.GetGceServiceDiscoveryArgs.new;
  final GetGceServiceDiscoveryResult = _fast.GetGceServiceDiscoveryResult.new;
  final GetGceServiceDiscoveryResultArgs = _fast.GetGceServiceDiscoveryResult.new;
  final getAwsServiceDiscovery = _fast.getAwsServiceDiscovery;
  final getAzureServiceDiscovery = _fast.getAzureServiceDiscovery;
  final getConsulServiceDiscovery = _fast.getConsulServiceDiscovery;
  final getGceServiceDiscovery = _fast.getGceServiceDiscovery;
}

class _IndexModuleNamespace {
  _IndexModuleNamespace();
  final As3 = _index.As3.new;
  final As3Args = _index.As3Args.new;
  final As3DeleteApps = _index.As3DeleteApps.new;
  final As3DeleteAppsArgs = _index.As3DeleteApps.new;
  final BigIqAs3 = _index.BigIqAs3.new;
  final BigIqAs3Args = _index.BigIqAs3Args.new;
  final Command = _index.Command.new;
  final CommandArgs = _index.CommandArgs.new;
  final CommonLicenseManageBigIq = _index.CommonLicenseManageBigIq.new;
  final CommonLicenseManageBigIqArgs = _index.CommonLicenseManageBigIqArgs.new;
  final Do = _index.Do.new;
  final DoArgs = _index.DoArgs.new;
  final EventServiceDiscovery = _index.EventServiceDiscovery.new;
  final EventServiceDiscoveryArgs = _index.EventServiceDiscoveryArgs.new;
  final EventServiceDiscoveryNode = _index.EventServiceDiscoveryNode.new;
  final EventServiceDiscoveryNodeArgs = _index.EventServiceDiscoveryNode.new;
  final FastApplication = _index.FastApplication.new;
  final FastApplicationArgs = _index.FastApplicationArgs.new;
  final FastHttpApp = _index.FastHttpApp.new;
  final FastHttpAppArgs = _index.FastHttpAppArgs.new;
  final FastHttpAppMonitor = _index.FastHttpAppMonitor.new;
  final FastHttpAppMonitorArgs = _index.FastHttpAppMonitor.new;
  final FastHttpAppPoolMember = _index.FastHttpAppPoolMember.new;
  final FastHttpAppPoolMemberArgs = _index.FastHttpAppPoolMember.new;
  final FastHttpAppVirtualServer = _index.FastHttpAppVirtualServer.new;
  final FastHttpAppVirtualServerArgs = _index.FastHttpAppVirtualServer.new;
  final FastHttpAppWafSecurityPolicy = _index.FastHttpAppWafSecurityPolicy.new;
  final FastHttpAppWafSecurityPolicyArgs = _index.FastHttpAppWafSecurityPolicy.new;
  final FastHttpsApp = _index.FastHttpsApp.new;
  final FastHttpsAppArgs = _index.FastHttpsAppArgs.new;
  final FastHttpsAppMonitor = _index.FastHttpsAppMonitor.new;
  final FastHttpsAppMonitorArgs = _index.FastHttpsAppMonitor.new;
  final FastHttpsAppPoolMember = _index.FastHttpsAppPoolMember.new;
  final FastHttpsAppPoolMemberArgs = _index.FastHttpsAppPoolMember.new;
  final FastHttpsAppTlsClientProfile = _index.FastHttpsAppTlsClientProfile.new;
  final FastHttpsAppTlsClientProfileArgs = _index.FastHttpsAppTlsClientProfile.new;
  final FastHttpsAppTlsServerProfile = _index.FastHttpsAppTlsServerProfile.new;
  final FastHttpsAppTlsServerProfileArgs = _index.FastHttpsAppTlsServerProfile.new;
  final FastHttpsAppVirtualServer = _index.FastHttpsAppVirtualServer.new;
  final FastHttpsAppVirtualServerArgs = _index.FastHttpsAppVirtualServer.new;
  final FastHttpsAppWafSecurityPolicy = _index.FastHttpsAppWafSecurityPolicy.new;
  final FastHttpsAppWafSecurityPolicyArgs = _index.FastHttpsAppWafSecurityPolicy.new;
  final FastTcpApp = _index.FastTcpApp.new;
  final FastTcpAppArgs = _index.FastTcpAppArgs.new;
  final FastTcpAppMonitor = _index.FastTcpAppMonitor.new;
  final FastTcpAppMonitorArgs = _index.FastTcpAppMonitor.new;
  final FastTcpAppPoolMember = _index.FastTcpAppPoolMember.new;
  final FastTcpAppPoolMemberArgs = _index.FastTcpAppPoolMember.new;
  final FastTcpAppVirtualServer = _index.FastTcpAppVirtualServer.new;
  final FastTcpAppVirtualServerArgs = _index.FastTcpAppVirtualServer.new;
  final FastTemplate = _index.FastTemplate.new;
  final FastTemplateArgs = _index.FastTemplateArgs.new;
  final FastUdpApp = _index.FastUdpApp.new;
  final FastUdpAppArgs = _index.FastUdpAppArgs.new;
  final FastUdpAppMonitor = _index.FastUdpAppMonitor.new;
  final FastUdpAppMonitorArgs = _index.FastUdpAppMonitor.new;
  final FastUdpAppPoolMember = _index.FastUdpAppPoolMember.new;
  final FastUdpAppPoolMemberArgs = _index.FastUdpAppPoolMember.new;
  final FastUdpAppVirtualServer = _index.FastUdpAppVirtualServer.new;
  final FastUdpAppVirtualServerArgs = _index.FastUdpAppVirtualServer.new;
  final GetAs3DeviceInformationArgs = _index.GetAs3DeviceInformationArgs.new;
  final GetAs3DeviceInformationResult = _index.GetAs3DeviceInformationResult.new;
  final GetAs3DeviceInformationResultArgs = _index.GetAs3DeviceInformationResult.new;
  final IpsecPolicy = _index.IpsecPolicy.new;
  final IpsecPolicyArgs = _index.IpsecPolicyArgs.new;
  final IpsecProfile = _index.IpsecProfile.new;
  final IpsecProfileArgs = _index.IpsecProfileArgs.new;
  final NetIkePeer = _index.NetIkePeer.new;
  final NetIkePeerArgs = _index.NetIkePeerArgs.new;
  final NetTunnel = _index.NetTunnel.new;
  final NetTunnelArgs = _index.NetTunnelArgs.new;
  final Partition = _index.Partition.new;
  final PartitionArgs = _index.PartitionArgs.new;
  final SaasBotDefenseProfile = _index.SaasBotDefenseProfile.new;
  final SaasBotDefenseProfileArgs = _index.SaasBotDefenseProfileArgs.new;
  final SaasBotDefenseProfileProtectedEndpoint = _index.SaasBotDefenseProfileProtectedEndpoint.new;
  final SaasBotDefenseProfileProtectedEndpointArgs = _index.SaasBotDefenseProfileProtectedEndpoint.new;
  final SslKeyCert = _index.SslKeyCert.new;
  final SslKeyCertArgs = _index.SslKeyCertArgs.new;
  final TrafficSelector = _index.TrafficSelector.new;
  final TrafficSelectorArgs = _index.TrafficSelectorArgs.new;
  final WafPolicy = _index.WafPolicy.new;
  final WafPolicyArgs = _index.WafPolicyArgs.new;
  final WafPolicyFileType = _index.WafPolicyFileType.new;
  final WafPolicyFileTypeArgs = _index.WafPolicyFileType.new;
  final WafPolicyGraphqlProfile = _index.WafPolicyGraphqlProfile.new;
  final WafPolicyGraphqlProfileArgs = _index.WafPolicyGraphqlProfile.new;
  final WafPolicyGraphqlProfileDefenseAttribute = _index.WafPolicyGraphqlProfileDefenseAttribute.new;
  final WafPolicyGraphqlProfileDefenseAttributeArgs = _index.WafPolicyGraphqlProfileDefenseAttribute.new;
  final WafPolicyHostName = _index.WafPolicyHostName.new;
  final WafPolicyHostNameArgs = _index.WafPolicyHostName.new;
  final WafPolicyIpException = _index.WafPolicyIpException.new;
  final WafPolicyIpExceptionArgs = _index.WafPolicyIpException.new;
  final WafPolicyPolicyBuilder = _index.WafPolicyPolicyBuilder.new;
  final WafPolicyPolicyBuilderArgs = _index.WafPolicyPolicyBuilder.new;
  final WafPolicySignaturesSetting = _index.WafPolicySignaturesSetting.new;
  final WafPolicySignaturesSettingArgs = _index.WafPolicySignaturesSetting.new;
  final getAs3DeviceInformation = _index.getAs3DeviceInformation;
}

class _LtmModuleNamespace {
  _LtmModuleNamespace();
  final CipherGroup = _ltm.CipherGroup.new;
  final CipherGroupArgs = _ltm.CipherGroupArgs.new;
  final CipherRule = _ltm.CipherRule.new;
  final CipherRuleArgs = _ltm.CipherRuleArgs.new;
  final DataGroup = _ltm.DataGroup.new;
  final DataGroupArgs = _ltm.DataGroupArgs.new;
  final DataGroupRecord = _ltm.DataGroupRecord.new;
  final DataGroupRecordArgs = _ltm.DataGroupRecord.new;
  final GetDataGroupArgs = _ltm.GetDataGroupArgs.new;
  final GetDataGroupRecord = _ltm.GetDataGroupRecord.new;
  final GetDataGroupRecordArgs = _ltm.GetDataGroupRecord.new;
  final GetDataGroupResult = _ltm.GetDataGroupResult.new;
  final GetDataGroupResultArgs = _ltm.GetDataGroupResult.new;
  final GetIruleArgs = _ltm.GetIruleArgs.new;
  final GetIruleResult = _ltm.GetIruleResult.new;
  final GetIruleResultArgs = _ltm.GetIruleResult.new;
  final GetMonitorArgs = _ltm.GetMonitorArgs.new;
  final GetMonitorResult = _ltm.GetMonitorResult.new;
  final GetMonitorResultArgs = _ltm.GetMonitorResult.new;
  final GetNodeArgs = _ltm.GetNodeArgs.new;
  final GetNodeFqdn = _ltm.GetNodeFqdn.new;
  final GetNodeFqdnArgs = _ltm.GetNodeFqdn.new;
  final GetNodeResult = _ltm.GetNodeResult.new;
  final GetNodeResultArgs = _ltm.GetNodeResult.new;
  final GetPolicyArgs = _ltm.GetPolicyArgs.new;
  final GetPolicyResult = _ltm.GetPolicyResult.new;
  final GetPolicyResultArgs = _ltm.GetPolicyResult.new;
  final GetPolicyRule = _ltm.GetPolicyRule.new;
  final GetPolicyRuleAction = _ltm.GetPolicyRuleAction.new;
  final GetPolicyRuleActionArgs = _ltm.GetPolicyRuleAction.new;
  final GetPolicyRuleArgs = _ltm.GetPolicyRule.new;
  final GetPolicyRuleCondition = _ltm.GetPolicyRuleCondition.new;
  final GetPolicyRuleConditionArgs = _ltm.GetPolicyRuleCondition.new;
  final GetPoolArgs = _ltm.GetPoolArgs.new;
  final GetPoolResult = _ltm.GetPoolResult.new;
  final GetPoolResultArgs = _ltm.GetPoolResult.new;
  final IRule = _ltm.IRule.new;
  final IRuleArgs = _ltm.IRuleArgs.new;
  final Ifile = _ltm.Ifile.new;
  final IfileArgs = _ltm.IfileArgs.new;
  final Monitor = _ltm.Monitor.new;
  final MonitorArgs = _ltm.MonitorArgs.new;
  final Node = _ltm.Node.new;
  final NodeArgs = _ltm.NodeArgs.new;
  final NodeFqdn = _ltm.NodeFqdn.new;
  final NodeFqdnArgs = _ltm.NodeFqdn.new;
  final PersistenceProfileCookie = _ltm.PersistenceProfileCookie.new;
  final PersistenceProfileCookieArgs = _ltm.PersistenceProfileCookieArgs.new;
  final PersistenceProfileDstAddr = _ltm.PersistenceProfileDstAddr.new;
  final PersistenceProfileDstAddrArgs = _ltm.PersistenceProfileDstAddrArgs.new;
  final PersistenceProfileSrcAddr = _ltm.PersistenceProfileSrcAddr.new;
  final PersistenceProfileSrcAddrArgs = _ltm.PersistenceProfileSrcAddrArgs.new;
  final PersistenceProfileSsl = _ltm.PersistenceProfileSsl.new;
  final PersistenceProfileSslArgs = _ltm.PersistenceProfileSslArgs.new;
  final Policy = _ltm.Policy.new;
  final PolicyArgs = _ltm.PolicyArgs.new;
  final PolicyRule = _ltm.PolicyRule.new;
  final PolicyRuleAction = _ltm.PolicyRuleAction.new;
  final PolicyRuleActionArgs = _ltm.PolicyRuleAction.new;
  final PolicyRuleArgs = _ltm.PolicyRule.new;
  final PolicyRuleCondition = _ltm.PolicyRuleCondition.new;
  final PolicyRuleConditionArgs = _ltm.PolicyRuleCondition.new;
  final Pool = _ltm.Pool.new;
  final PoolArgs = _ltm.PoolArgs.new;
  final PoolAttachment = _ltm.PoolAttachment.new;
  final PoolAttachmentArgs = _ltm.PoolAttachmentArgs.new;
  final ProfileBotDefense = _ltm.ProfileBotDefense.new;
  final ProfileBotDefenseArgs = _ltm.ProfileBotDefenseArgs.new;
  final ProfileClientSsl = _ltm.ProfileClientSsl.new;
  final ProfileClientSslArgs = _ltm.ProfileClientSslArgs.new;
  final ProfileClientSslCertKeyChain = _ltm.ProfileClientSslCertKeyChain.new;
  final ProfileClientSslCertKeyChainArgs = _ltm.ProfileClientSslCertKeyChain.new;
  final ProfileFastHttp = _ltm.ProfileFastHttp.new;
  final ProfileFastHttpArgs = _ltm.ProfileFastHttpArgs.new;
  final ProfileFastL4 = _ltm.ProfileFastL4.new;
  final ProfileFastL4Args = _ltm.ProfileFastL4Args.new;
  final ProfileFtp = _ltm.ProfileFtp.new;
  final ProfileFtpArgs = _ltm.ProfileFtpArgs.new;
  final ProfileHttp = _ltm.ProfileHttp.new;
  final ProfileHttp2 = _ltm.ProfileHttp2.new;
  final ProfileHttp2Args = _ltm.ProfileHttp2Args.new;
  final ProfileHttpArgs = _ltm.ProfileHttpArgs.new;
  final ProfileHttpCompress = _ltm.ProfileHttpCompress.new;
  final ProfileHttpCompressArgs = _ltm.ProfileHttpCompressArgs.new;
  final ProfileHttpEnforcement = _ltm.ProfileHttpEnforcement.new;
  final ProfileHttpEnforcementArgs = _ltm.ProfileHttpEnforcement.new;
  final ProfileHttpHttpStrictTransportSecurity = _ltm.ProfileHttpHttpStrictTransportSecurity.new;
  final ProfileHttpHttpStrictTransportSecurityArgs = _ltm.ProfileHttpHttpStrictTransportSecurity.new;
  final ProfileOneConnect = _ltm.ProfileOneConnect.new;
  final ProfileOneConnectArgs = _ltm.ProfileOneConnectArgs.new;
  final ProfileRewrite = _ltm.ProfileRewrite.new;
  final ProfileRewriteArgs = _ltm.ProfileRewriteArgs.new;
  final ProfileRewriteCookieRule = _ltm.ProfileRewriteCookieRule.new;
  final ProfileRewriteCookieRuleArgs = _ltm.ProfileRewriteCookieRule.new;
  final ProfileRewriteRequest = _ltm.ProfileRewriteRequest.new;
  final ProfileRewriteRequestArgs = _ltm.ProfileRewriteRequest.new;
  final ProfileRewriteResponse = _ltm.ProfileRewriteResponse.new;
  final ProfileRewriteResponseArgs = _ltm.ProfileRewriteResponse.new;
  final ProfileRewriteUriRules = _ltm.ProfileRewriteUriRules.new;
  final ProfileRewriteUriRulesArgs = _ltm.ProfileRewriteUriRulesArgs.new;
  final ProfileRewriteUriRulesClient = _ltm.ProfileRewriteUriRulesClient.new;
  final ProfileRewriteUriRulesClientArgs = _ltm.ProfileRewriteUriRulesClient.new;
  final ProfileRewriteUriRulesServer = _ltm.ProfileRewriteUriRulesServer.new;
  final ProfileRewriteUriRulesServerArgs = _ltm.ProfileRewriteUriRulesServer.new;
  final ProfileServerSsl = _ltm.ProfileServerSsl.new;
  final ProfileServerSslArgs = _ltm.ProfileServerSslArgs.new;
  final ProfileTcp = _ltm.ProfileTcp.new;
  final ProfileTcpArgs = _ltm.ProfileTcpArgs.new;
  final ProfileWebAcceleration = _ltm.ProfileWebAcceleration.new;
  final ProfileWebAccelerationArgs = _ltm.ProfileWebAccelerationArgs.new;
  final RequestLogProfile = _ltm.RequestLogProfile.new;
  final RequestLogProfileArgs = _ltm.RequestLogProfileArgs.new;
  final Snat = _ltm.Snat.new;
  final SnatArgs = _ltm.SnatArgs.new;
  final SnatOrigin = _ltm.SnatOrigin.new;
  final SnatOriginArgs = _ltm.SnatOrigin.new;
  final SnatPool = _ltm.SnatPool.new;
  final SnatPoolArgs = _ltm.SnatPoolArgs.new;
  final VirtualAddress = _ltm.VirtualAddress.new;
  final VirtualAddressArgs = _ltm.VirtualAddressArgs.new;
  final VirtualServer = _ltm.VirtualServer.new;
  final VirtualServerArgs = _ltm.VirtualServerArgs.new;
  final getDataGroup = _ltm.getDataGroup;
  final getIrule = _ltm.getIrule;
  final getMonitor = _ltm.getMonitor;
  final getNode = _ltm.getNode;
  final getPolicy = _ltm.getPolicy;
  final getPool = _ltm.getPool;
}

class _NetModuleNamespace {
  _NetModuleNamespace();
  final Route = _net.Route.new;
  final RouteArgs = _net.RouteArgs.new;
  final SelfIp = _net.SelfIp.new;
  final SelfIpArgs = _net.SelfIpArgs.new;
  final Vlan = _net.Vlan.new;
  final VlanArgs = _net.VlanArgs.new;
  final VlanInterface = _net.VlanInterface.new;
  final VlanInterfaceArgs = _net.VlanInterface.new;
}

class _ProvidersModuleNamespace {
  _ProvidersModuleNamespace();
  final TerraformConfigArgs = _providers.TerraformConfigArgs.new;
  final TerraformConfigResult = _providers.TerraformConfigResult.new;
  final TerraformConfigResultArgs = _providers.TerraformConfigResult.new;
  final terraformConfig = _providers.terraformConfig;
}

class _SslModuleNamespace {
  _SslModuleNamespace();
  final Certificate = _ssl.Certificate.new;
  final CertificateArgs = _ssl.CertificateArgs.new;
  final GetCertificateArgs = _ssl.GetCertificateArgs.new;
  final GetCertificateResult = _ssl.GetCertificateResult.new;
  final GetCertificateResultArgs = _ssl.GetCertificateResult.new;
  final GetVWanConfigArgs = _ssl.GetVWanConfigArgs.new;
  final GetVWanConfigResult = _ssl.GetVWanConfigResult.new;
  final GetVWanConfigResultArgs = _ssl.GetVWanConfigResult.new;
  final GetWafEntityParameterArgs = _ssl.GetWafEntityParameterArgs.new;
  final GetWafEntityParameterResult = _ssl.GetWafEntityParameterResult.new;
  final GetWafEntityParameterResultArgs = _ssl.GetWafEntityParameterResult.new;
  final GetWafEntityParameterUrl = _ssl.GetWafEntityParameterUrl.new;
  final GetWafEntityParameterUrlArgs = _ssl.GetWafEntityParameterUrl.new;
  final GetWafEntityUrlArgs = _ssl.GetWafEntityUrlArgs.new;
  final GetWafEntityUrlCrossOriginRequestsEnforcement = _ssl.GetWafEntityUrlCrossOriginRequestsEnforcement.new;
  final GetWafEntityUrlCrossOriginRequestsEnforcementArgs = _ssl.GetWafEntityUrlCrossOriginRequestsEnforcement.new;
  final GetWafEntityUrlMethodOverride = _ssl.GetWafEntityUrlMethodOverride.new;
  final GetWafEntityUrlMethodOverrideArgs = _ssl.GetWafEntityUrlMethodOverride.new;
  final GetWafEntityUrlResult = _ssl.GetWafEntityUrlResult.new;
  final GetWafEntityUrlResultArgs = _ssl.GetWafEntityUrlResult.new;
  final GetWafPbSuggestionsArgs = _ssl.GetWafPbSuggestionsArgs.new;
  final GetWafPbSuggestionsResult = _ssl.GetWafPbSuggestionsResult.new;
  final GetWafPbSuggestionsResultArgs = _ssl.GetWafPbSuggestionsResult.new;
  final GetWafPolicyArgs = _ssl.GetWafPolicyArgs.new;
  final GetWafPolicyResult = _ssl.GetWafPolicyResult.new;
  final GetWafPolicyResultArgs = _ssl.GetWafPolicyResult.new;
  final GetWafSignaturesArgs = _ssl.GetWafSignaturesArgs.new;
  final GetWafSignaturesResult = _ssl.GetWafSignaturesResult.new;
  final GetWafSignaturesResultArgs = _ssl.GetWafSignaturesResult.new;
  final Key = _ssl.Key.new;
  final KeyArgs = _ssl.KeyArgs.new;
  final getCertificate = _ssl.getCertificate;
  final getVWanConfig = _ssl.getVWanConfig;
  final getWafEntityParameter = _ssl.getWafEntityParameter;
  final getWafEntityUrl = _ssl.getWafEntityUrl;
  final getWafPbSuggestions = _ssl.getWafPbSuggestions;
  final getWafPolicy = _ssl.getWafPolicy;
  final getWafSignatures = _ssl.getWafSignatures;
}

class _SysModuleNamespace {
  _SysModuleNamespace();
  final BigIpLicense = _sys.BigIpLicense.new;
  final BigIpLicenseArgs = _sys.BigIpLicenseArgs.new;
  final Dns = _sys.Dns.new;
  final DnsArgs = _sys.DnsArgs.new;
  final IApp = _sys.IApp.new;
  final IAppArgs = _sys.IAppArgs.new;
  final IAppList = _sys.IAppList.new;
  final IAppListArgs = _sys.IAppList.new;
  final IAppMetadata = _sys.IAppMetadata.new;
  final IAppMetadataArgs = _sys.IAppMetadata.new;
  final IAppTable = _sys.IAppTable.new;
  final IAppTableArgs = _sys.IAppTable.new;
  final IAppTableRow = _sys.IAppTableRow.new;
  final IAppTableRowArgs = _sys.IAppTableRow.new;
  final IAppVariable = _sys.IAppVariable.new;
  final IAppVariableArgs = _sys.IAppVariable.new;
  final Ifile = _sys.Ifile.new;
  final IfileArgs = _sys.IfileArgs.new;
  final Ntp = _sys.Ntp.new;
  final NtpArgs = _sys.NtpArgs.new;
  final Ocsp = _sys.Ocsp.new;
  final OcspArgs = _sys.OcspArgs.new;
  final Provision = _sys.Provision.new;
  final ProvisionArgs = _sys.ProvisionArgs.new;
  final Snmp = _sys.Snmp.new;
  final SnmpArgs = _sys.SnmpArgs.new;
  final SnmpTraps = _sys.SnmpTraps.new;
  final SnmpTrapsArgs = _sys.SnmpTrapsArgs.new;
}

class _VcmpModuleNamespace {
  _VcmpModuleNamespace();
  final Guest = _vcmp.Guest.new;
  final GuestArgs = _vcmp.GuestArgs.new;
}

