// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;

/// {@template pulumi_dataproc_metastore_service_iam_policy_metastore_service_iam_policy_args_doc}
/// The set of arguments for MetastoreServiceIamPolicy.
/// {@endtemplate}
/// {@macro pulumi_dataproc_metastore_service_iam_policy_metastore_service_iam_policy_args_doc}
class MetastoreServiceIamPolicyArgs {
  /// The location where the metastore service should reside.
  /// The default value is `global`.
  /// Used to find the parent resource to bind the IAM policy to. If not specified,
  /// the value will be parsed from the identifier of the parent resource. If no location is provided in the parent identifier and no
  /// location is specified, it is taken from the provider configuration.
  final pulumi.Input<String>? location;

  /// The policy data generated by
  /// a `gcp.organizations.getIAMPolicy` data source.
  final pulumi.Input<String> policyData;

  /// The ID of the project in which the resource belongs.
  /// If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
  final pulumi.Input<String>? project;

  /// Used to find the parent resource to bind the IAM policy to
  final pulumi.Input<String> serviceId;

  /// Creates a new [MetastoreServiceIamPolicyArgs].
  /// [location] The location where the metastore service should reside.
  /// [policyData] The policy data generated by
  /// [project] The ID of the project in which the resource belongs.
  /// [serviceId] Used to find the parent resource to bind the IAM policy to
  MetastoreServiceIamPolicyArgs({
    String? location,
    required String policyData,
    String? project,
    required String serviceId,
  }) : location = pulumi.Input.asOptionalInput<String>(location),
       policyData = pulumi.Input.asInput<String>(policyData),
       project = pulumi.Input.asOptionalInput<String>(project),
       serviceId = pulumi.Input.asInput<String>(serviceId);

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'location': ?location,
      'policyData': policyData,
      'project': ?project,
      'serviceId': serviceId,
    };
  }

  factory MetastoreServiceIamPolicyArgs.fromMap(Map<String, dynamic> map) {
    return MetastoreServiceIamPolicyArgs(
      location: map['location'] == null ? null : map['location'] as String,
      policyData: map['policyData'] as String,
      project: map['project'] == null ? null : map['project'] as String,
      serviceId: map['serviceId'] as String,
    );
  }
}
