// ignore_for_file: unused_element, unnecessary_cast

import 'package:pulumi/pulumi.dart' as pulumi;
import '../api_config_grpc_service_file_descriptor_set/api_config_grpc_service_file_descriptor_set.dart';
import '../api_config_grpc_service_source/api_config_grpc_service_source.dart';

class ApiConfigGrpcService {
  /// Input only. File descriptor set, generated by protoc.
  /// To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.
  /// $ protoc --include_imports --include_source_info test.proto -o out.pb
  /// Structure is documented below.
  final ApiConfigGrpcServiceFileDescriptorSet fileDescriptorSet;

  /// Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.
  /// Structure is documented below.
  final List<ApiConfigGrpcServiceSource>? sources;

  ApiConfigGrpcService({
    required this.fileDescriptorSet,
    this.sources,
  });

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['fileDescriptorSet'] = fileDescriptorSet.toMap();
    final sourcesValue = sources;
    if (sourcesValue != null) {
      map['sources'] = pulumi.Input.encodeList<ApiConfigGrpcServiceSource,
          Map<String, dynamic>>(sourcesValue, (value) => value.toMap());
    }
    return map;
  }

  factory ApiConfigGrpcService.fromMap(Map<String, dynamic> map) {
    return ApiConfigGrpcService(
      fileDescriptorSet: ApiConfigGrpcServiceFileDescriptorSet.fromMap(
          (map['fileDescriptorSet'] as Map).cast<String, dynamic>()),
      sources: map['sources'] == null
          ? null
          : pulumi.Input.decodeList<ApiConfigGrpcServiceSource>(
              map['sources'],
              (value) => ApiConfigGrpcServiceSource.fromMap(
                  (value as Map).cast<String, dynamic>())),
    );
  }
}
